# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/85")
from _lib import c, table, save

c(25, "§4.1 table (verbatim); §4.1; §4.2 5★ table (verbatim); §4.2 4★ table (verbatim); §4.2 3★ table (verbatim); §4.2 2★ table (verbatim); §4.2 1★ table (verbatim); §4.2 Reading", "data-caveat", "Distribution (verbatim): " + table("## 4.1 The distribution", 0) + " — bimodal (5★ 44.21%, 1★ 14.17%, 4★ larger than 3★ and 2★); mid-star reviews are the longest 'love it, but' (REV_CONDITIONAL 85, 57 at 3–4★). Themes by band (verbatim) — 5★: " + table("### 5★ — 1,523 reviews", 0) + " || 4★: " + table("### 4★ — 677 reviews", 0) + " || 3★: " + table("### 3★ — 457 reviews", 0) + " || 2★: " + table("### 2★ — 300 reviews", 0) + " || 1★: " + table("### 1★ — 488 reviews", 0) + " — 5★ is the game layer and outcomes; 4★ already carries crash and parity complaints at high rates (12.6% crash); 3★ and 2★ are defect reviews that still praise the concept; 1★ is crash, sign-up and server failures and where deletion is announced (CHURN_DELETE 34 of 49).", "n/a", "mixed", "5★ 1,523 (44.21%); 1★ 488 (14.17%); REV_CONDITIONAL 85; CHURN_DELETE 34 of 49 at 1★", "none", "table", "generalisable", ["1223698024"], "", "")

c(26, "§4.3", "data-caveat", "Rating-vs-text contradictions: CONTRA_RATING 46 (1.34%) — 44 are 5★ reporting a defect ('起動してすぐ落ちる' — it crashes right after launch, 5★); cn over-represented (9 of 46 vs 5.83% share) and 42 of 46 predate 2022-12, consistent with reviewers treating the star field as a contact form; a 1★ given in protest at a rating prompt; all kept and coded by text.", "n/a", "mixed", "CONTRA 46 / 1.34%; 44 5★-with-defect; cn 9", "none", "Meaningful", "generalisable", ["1939410285", "1337075973", "14351099577"], "", "")

c(27, "§5.1; §5.7", "data-caveat", "Paid populations: U_PAID 55 (1.60%, mean 3.25★: MON_SUB 47, MON_GEMS 8, MON_DONATE 2); MON_WILL_PAY 36 (1.04%, 4.06★); stated barriers 67 (1.94%); none is a conversion rate; cannot claim the share who pay, renew or cancel, whether gem gating increased or only mentions of it, or prices by storefront.", "n/a", "mixed", "U_PAID 55 / 1.60% / 3.25★; WILL_PAY 36 / 4.06★; barriers 67", "none", "Meaningful", "generalisable", ["1364073113"], "", "")

c(28, "§5.2; §5.3 table (verbatim)", "insight", "What triggers a purchase (segment rates within 55 purchasers): support for a free, open, ad-free product — MON_SUPPORT_DEV 13 of 55 (23.6%; 'I upgraded just to help support the developers'), with NOT_REQUIRED or PR_FREE 8; long use — TENURE_LONG 12 of 55 (21.8%) vs 3.86% of all; family and friends — USE_FAMILY 6, gift subscriptions for friends (3); access to gem items — one subscribed and then objected to paying again for gems. Segment rates (verbatim): " + table("## 5.3 Segment rates", 0), "optional subscription bought as support", "purchase-driver", "SUPPORT_DEV 23.6% of payers; TENURE_LONG 21.8% vs 3.86%; USE_FAMILY 6; gifts 3", "build-paid", "Meaningful", "generalisable", ["1364073113", "1348967667", "11072292659"], "", "the subscription sells as patronage, not as capability")

c(29, "§5.4 table (verbatim); §5.4; §8.4", "must-never-break", "What purchasers report (verbatim): " + table("## 5.4 What purchasers report", 0) + " — the satisfied are long-term users paying to support the project ('I don't mind contributing $5 a month to keep the app and website going'; 'I'm a subscriber now, it's not expensive'); the unhappy (15 of 55 + 2 implied) name specific failures: paid then the app would not open ('Paid for premium but can barely use it as it constantly crashes', 1★); benefits not credited ('I got a month subscription and the gems didn't credit to my account', 1★); could not cancel ('Habitica keeps charging for new subscriptions', 1★; MON_CANCEL_HARD 4); left over the 2023 changes ('I cancelled my subscription and left the place').", "n/a", "churn", "unhappy payers 15 of 55; PAID_UNHAPPY 17; BUG_IAP 9; CANCEL_HARD 4", "must-never-break", "Meaningful", "generalisable", ["3905147893", "7056447552", "8088243446", "10306026207"], "", "")

c(30, "§5.5 table (verbatim); §5.5; §8.5", "monetization", "Upgrade barriers among non-buyers (verbatim): " + table("## 5.5 Upgrade barriers", 0) + " — no free path to gems: the request is not for free gems but a slow, earned route (streak rewards, achievements, an expensive gold-for-gem exchange); challenge prize draws are the current route and 'you have to just lie and say you did it'; price level ('12 month usage cost as much as a tripple AAA vid game title', 2★; regional pricing in Russia; 'a bit expensive' in Turkey); recurring vs one-off ('I'd gladly pay $10-$15 for the full program but nickel and diming users is off-putting', 2★); donation instead of add-ons (MON_ALT_SUPPORT 5: 'then have a donate button not add ons').", "gems unearnable free; subscription only", "blocked-conversion", "GEM_GATE 47; P2W 19 / 1.84★; PRICE_HIGH 8; ALT_SUPPORT 5", "research", "Meaningful", "generalisable", ["13735335061", "4259179024", "2487999989", "11987547518"], "", "")

c(31, "§5.6", "data-caveat", "Refund and churn after purchase: only 2 reviews mention a refund; churn drivers among purchasers are the same as for everyone — 9 of 55 state churn, 5 with a defect code and 3 a governance code.", "n/a", "churn", "refund 2; purchaser churn 9 of 55", "none", "limited evidence", "generalisable", ["10306026207"], "", "")

save("a")
