# -*- coding: utf-8 -*-
"""Stage 3 merge for research document 'Feature Gating vs Quantity.md'."""
import json
P = "Tools/prd_ledger/canonical.json"
L = json.load(open(P)); C = {x["id"]: x for x in L}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text

ext("C133", " Research: Feature Gating vs Quantity.md — the external corroboration for this point, and the one place in the ledger where industry literature is the evidence rather than review corpora (sources named only in aggregate: freemium strategy guides, habit-tracker analyses, habit-formation research). Its conclusion is this rule in other words — 'capabilities not quotas': 'don't cripple the core habit/task loop in free tiers', let free users track unlimited or many habits, and monetise capability — advanced analytics, custom themes, widgets, device sync/backup. The one quantified case is a consumer project-management app that limited free users to 3 projects and locked collaboration: consumer conversion 'crashed to 0.8%'; after removing the project cap and gating storage and templates instead, conversion rose to 2.6% — more than threefold, and notably gating the team-shaped features (collaboration, analytics) did not help in a consumer market while gating optional advanced capability did. The stated causal chain is retention, not pressure: B2C freemium converts at 1-4%, users still active past the first week are 5-8x more likely to convert, and habit-formation research puts automaticity at about 66 days — so 'if a habit app slams a limit or trial around day 7-14, users quit before they've truly engaged.' A paraphrased internal study found free users who complained about task/habit caps were less likely to ever pay: 'They were likely turning off the app instead of upgrading' — the cap produces exit, not purchase. Two caveats this ledger must keep attached: the document concedes that a usage-cap ('taster') model is the general B2C pattern and feature gates the B2B one — Dropbox's 2 GB is its example — so the habit-app conclusion is an exception argued from habit-formation time, not the industry default; and it accepts capability gates work partly because users expect to buy non-essential extras 'once they've already invested time', which makes the gate's timing as load-bearing as its object ([[C137]]). The market's actual gated set is named as Apple Watch support, widget access, detailed analytics and backup/sync ([[C022]], [[C107]], [[C011]], [[C013]]).")
ext("C007", " Research: Feature Gating vs Quantity.md — the external floor for this number: a good free tracker should allow 'at least 5-10 habits on the free plan, ideally with no limit', and the caps actually shipped in this category sit below it — Habitify 3 (then locks you out), Productive 5 — which the cited HabitBox analysis reads as 'engineered to push you to Pro within a week' and as a wall someone hits 'once they try to build a routine'. The quoted user reaction is a lost buyer rather than a converted one: 'extend the habit limit for free users from 3 to 4…(or better make it unlimited) - my OCD is making me seriously consider switching apps because of this'. A paraphrased internal study found cap-complainers were less likely to ever pay.")
ext("C222", " Research: Feature Gating vs Quantity.md — the calibration window a cap has to hit if one is used at all: 'if the cap is set too low, new users hit it before forming a habit and churn; if too high, they never hit it and never pay', with the stated target that a typical engaged user meets the cap after about 30 days. Set against ~66-day habit automaticity, that window is narrow, and the 3-5 caps shipped in this category fall far below it.")
ext("C236", " Research: Feature Gating vs Quantity.md — undisclosed caps are the norm in adjacent productivity apps and are discovered as a surprise: Todoist advertises 'unlimited tasks' while limiting each project to 300, 'a restriction discovered only in user reports'; capping the core count in a habit app 'often feels like a hidden trial', and freemium design guides are cited for the test — users should never feel 'cheated if we moved it behind the paywall'.")
ext("C147", " Research: Feature Gating vs Quantity.md — the quantified version of this rule: B2C freemium converts at 1-4%, users active past the first week are 5-8x more likely to convert, and a new habit takes about 66 days to become automatic, so a limit or trial landing at day 7-14 arrives before the value it is trying to charge for exists. A consumer PM app that removed its 3-project cap and gated storage and templates instead went from 0.8% to 2.6% conversion. The free-user 'bill of rights' named is unlimited logging, streaks and reminders.")
ext("C182", " Research: Feature Gating vs Quantity.md — the retention arithmetic behind this: only 1-4% of free users convert in B2C, and surviving the first week multiplies conversion 5-8x, so a paywall placed before habit formation (~66 days) removes the cohort that would have paid. 'Only after they've built some usage habit do they become sensitive to missing extras.'")
ext("C167", " Research: Feature Gating vs Quantity.md — Habitica is the document's worked example that a fully free, unlimited core is compatible with a paid tier provided the paid tier is decoration: all core features free and unlimited, only cosmetic 'Pro' perks sold, and users 'buy the paid tier only for cosmetics'.")
ext("C137", " Research: Feature Gating vs Quantity.md — why capability gates draw less backlash than quantity gates: 'users expect to purchase non-essential extras (custom themes, widgets, advanced stats) once they've already invested time.' The expectation forms after the investment, so the same gate shown at install and shown at month two are different products.")
ext("C218", " Research: Feature Gating vs Quantity.md — quantity gating in adjacent apps is widespread and often silent: TickTick gives unlimited tasks and boards but limits the habit module, Trello allows unlimited cards but 10 boards, Todoist advertises 'unlimited tasks' against an undisclosed 300-task-per-project limit found only through user reports.")
ext("C013", " Research: Feature Gating vs Quantity.md — device sync/backup is named as one of the four capabilities habit apps conventionally gate (with Apple Watch, widgets and detailed analytics), and a Zapier review of free project managers is cited for the same split: unlimited tasks and collaboration drive free adoption while premium monetises cloud sync and reporting.")
ext("C011", " Research: Feature Gating vs Quantity.md — detailed analytics is named as one of the four capabilities habit apps conventionally gate, and 'advanced analytics' heads the document's list of what to monetise once the core loop is free.")
ext("C022", " Research: Feature Gating vs Quantity.md — Apple Watch support is named first in the set of capabilities habit apps conventionally gate.")
ext("C107", " Research: Feature Gating vs Quantity.md — widget access is named as one of the four capabilities habit apps conventionally gate, and 'widgets' appears in the document's list of non-essential extras users expect to pay for once they have invested time.")
ext("C293", " Research: Feature Gating vs Quantity.md — the quoted reviewer asks for exactly one extra slot ('extend the habit limit for free users from 3 to 4…(or better make it unlimited)') and is already considering switching apps, which is this point's mechanism in a single review: the small raise does not resolve the objection, it relocates it.")

MAP = {
 "RFG-001": [], "RFG-002": ["C133"], "RFG-003": ["C222", "C133"], "RFG-004": ["C133"],
 "RFG-005": ["C007", "C133", "C236"], "RFG-006": ["C167", "C133"], "RFG-007": ["C007", "C222", "C133"],
 "RFG-008": ["C133", "C218", "C236"], "RFG-009": ["C133", "C147"], "RFG-010": ["C007", "C222", "C293"],
 "RFG-011": ["C133", "C007"], "RFG-012": ["C133", "C137"],
 "RFG-013": ["C013", "C011", "C022", "C107", "C133"], "RFG-014": ["C147", "C182"],
 "RFG-015": ["C147", "C182", "C133"], "RFG-016": ["C133", "C007"], "RFG-017": ["C133", "C007", "C147"],
}
path = "Tools/prd_ledger/research_feature_gating/cards.jsonl"
cards = [json.loads(l) for l in open(path) if l.strip()]
for c in cards:
    c["canonical"] = MAP[c["id"]]
    for cid in MAP[c["id"]]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open(path, "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(L, open(P, "w"), ensure_ascii=False, indent=1)
print("merged", len(cards), "cards;", sum(1 for c in cards if not c["canonical"]), "left in nuance register; canonical now", len(L))
