# -*- coding: utf-8 -*-
"""Stage 3 merge for report 67 (Habio – Daily Habit Tracker, Gototop LTD)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C285", "dont", "Never charge a one-off add-on on a single tap against the authorisation just given for a trial — the add-on shows its price on the button, asks its own confirmation, defaults to 'no thanks' and ignores repeat taps",
    "Report 67 (Habio, 2,051 reviews): a $29.99 'workbook' / 'Get my PDF' button shown straight after the paid-trial payment and charged against the card just authorised with no second confirmation — MON_WORKBOOK 189 (9.22%, mean 1.01, 2023-10-15 → 2025-05-04, 41 in 2024-04 alone): 'The consent to charge text is in such a low contrast colour with the background, and such a tiny type size that it hurts my eyes to even read it!'; 'la vérification est demandé donc ils ne la redemande pas ensuite'; 'cliqué en un espacio para informarme más acerca de un pdf y directamente me cobraron 29€!' (es — 39.62% of the Spanish storefront); MON_DOUBLECHARGE 157 (7.65%) often two workbooks ('adhd_workbook' + 'habits_workbook') from a button that seemed not to respond; support answered 'we do not offer refunds for in-app purchases', which in EU storefronts collides with the 14-day withdrawal right; ADHD reviewers: 'They use lack of focus among the targeted ADHD group and trick You into in app purchase without confirming payment!'; §8.2: price on the button, separate confirmation not the trial's stored authorisation, default 'No thanks', idempotent repeat taps, refund an unopened PDF on request. Related: [[C211]] (no second separately-cancelled add-on subscription), [[C274]] (a dismiss control never starts a purchase), [[C213]].")
add("C286", "dont", "Never advertise or sell in a language the app does not ship — a localised ad, quiz or checkout for an English-only app is a refund request waiting to happen",
    "Report 67 (Habio): MKT_LANG_BAIT 86 (4.19%, mean 1.07), every one dated 2024-03-28 or later — the ad and web quiz ran in French, Spanish, German, Arabic or Japanese and the paid app turned out English-only (lookup API declares EN; listing titles localised as 'Habio: Tagesplaner. Checkliste', 'Habio: Habitude et Objectif'): 'L'ensemble des publicités ansi que les questionnaires avant l'achat sont en français, et l'application n'est dispo qu'en anglais'; France 30 of 91 reviews (32.97%), Germany 12 of 85, Chile 10 of 25; 34.9% of these reviewers ask for or are refused a refund ('nunca me contestaron para decirme si podía cambiar a español o no'); the language request itself predates the ads (6 in the free era) — 'The ads made it worse; they did not create it'; §8.5: localise, or state 'English only' in every non-English ad, quiz and checkout. Related: [[C027]] (localise early), [[C148]] (deliver what the ads show), [[C218]].")

ext("C210", " Report 67 (Habio): a web quiz funnel from Instagram / Facebook ads sold subscriptions billed off-store — MON_OFFSTORE 137 (6.68%) 'not displayed in the AppStore and the receipt comes directly from Habio'; 'even after you delete the app you will still be charged $50 every 180 days unless you redownload the app and cancel through there'; MON_WEB_FUNNEL 30 paid on the website before installing; the listing still says payment is 'charged to iTunes Account' and cancellable in Account Settings; web purchases were not linked to app accounts so buyers could not restore ('couldn't find any purchase history'); U_CANCEL_TRAP 597 (29.11%, mean 1.03); off-store complaints 13.81% of the 2023-07 → 2024-02 era.")
ext("C112", " Report 67 (Habio): MON_CANCEL 361 (17.60%, mean 1.01) and MON_CHARGED_AFTER 351 (17.11%) — an in-app cancellation confirmation screen with no persistent cancelled status, an emailed cancellation link that expires in 20 minutes, 'email not found' when cancelling, deleting the app believed to cancel (CHURN_DELETE 66); §8.1: every subscription visible in app settings with status, next charge date and amount, one-tap cancel with an on-screen and emailed confirmation, an emailed request effective at receipt.")
ext("C213", " Report 67 (Habio): ads pitching ADHD help and a 'bionic reading' tool; USE_ADHD 97 (4.73%, mean 1.25 — below even the non-seeded 1.31), 35.05% refund denied, 23.71% describe dark patterns: 'en sachant pertinemment à quel point le TDAH est difficile à vivre au quotidien notamment vis à vis de la gestion financière'; 'they're using your own ADHD against you' (UK, where ADHD is 14.47% of reviews).")
ext("C109", " Report 67 (Habio): a $1 / €1 / £1 3-day paid trial (MON_TRIAL_1DOLLAR 148) converting to $40+ plans — MON_TRIAL_CHARGE 173 (8.43%, mean 1.03): 'Factually their 3 days trial for 1,00 Euro is actually a 2 two days trial'; MON_PRICE_MISMATCH 55 charged more than shown; 'they've also never mentioned in their add that the currency is not in AUD'.")
ext("C152", " Report 67 (Habio): 'The day before my trial ended, they took the money and THEN emailed me and said my trial was up the following day'; MON_NO_RECEIPT 68 (3.32%); §8.3: a reminder 48 hours before conversion with the renewal amount in local currency and the plan length.")
ext("C215", " Report 67 (Habio): 19 reviews quote a published support response time of up to four business days against a three-day trial — 'How convenient when they offer a 3-day trial'; MON_TRIAL_SHORT 9; §8.3: make the trial longer than support's own response time; §8.6: first human reply within 24 hours.")
ext("C036", " Report 67 (Habio): U_SUPPORT_FAIL 425 (20.72%, mean 1.04) — no reply 213, slow 78, templated 59, evasive 46; 'Funny how when it's public your response is timely'; retention questions in reply to cancellation requests; 37.7% of reviewers whose money left their account report a support failure.")
ext("C189", " Report 67 (Habio): a templated public developer reply under reviews is mentioned by 19 reviewers; §8.6: no identical public replies.")
ext("C212", " Report 67 (Habio): MON_REFUND_DENIED 242 (11.80%, mean 1.01); an advertised money-back guarantee cited as not honoured by 42 (2.05%) — 'Money back policy requires that you use the product for 21 days consecutively!'; 10 invoke the EU 14-day withdrawal right; refunds granted in 10 (mean 2.80), 3 of them via the bank or PayPal rather than the developer.")
ext("C029", " Report 67 (Habio): U_BILLING_HARM 878 (42.81%, mean 1.04; 60.05% of non-seeded) — charged after cancelling 351, trial conversion 173, workbook 189, charged with no subscription 164, duplicate charges 157, amount above shown 55; U_ESCALATION 196 (9.56%): bank / card / PayPal disputes 118 and regulator / police / legal threats 94 (BBB, FTC, ACCC, state attorneys general, OCU, Sernac, Verbraucherzentrale — 'Abofalle'); a card statement under the company name the customer had to research ('Tuve que investigar que aplicaciones tenía GOTOTOP LTD').")
ext("C221", " Report 67 (Habio): the charge appeared under the company name, not the app — 'Tuve que investigar que aplicaciones tenía GOTOTOP LTD para saber que me estaban cobrando'; no receipt or reminder before the charge in 68 reviews.")
ext("C076", " Report 67 (Habio): SUS_SEED 589 (28.72%, mean 4.91, 2024-03-11 → 2025-02-18) — 94.2% on the US storefront, 33.6% Cyrillic author names vs ~1% elsewhere, 3.1% with any helpfulness vote vs 28.3% of other 4–5★, zero mentions of charges or support; a developer reply pasted into a 5★ body, one paragraph split across three accounts in the same hour, six bodies posted twice by different accounts, referral spam, praise aimed at the complaint ('Cancelled my subscription with no issues at all'), praise for frequent updates while the current build dated from 2024-05-15; they supply 545 of 668 praise codes and coincide with a 4.28 US public rating against a non-seeded mean of 1.31; genuine reviewers cite the gap as proof of fraud ('These scammers pay to have their ratings boosted'); §8.7: stop any programme that sources, incentivises or scripts reviews.")
ext("C231", " Report 67 (Habio): corpus mean 2.35 vs US public 4.28 (3,932), gb 3.68, ca 4.04, au 3.71, fr 3.05, de 2.65, mx 3.31, es 2.93; 'the complaint does not depend on the market' — non-seeded means near 1★ everywhere, only the mechanism varies (workbook gb / es, language bait fr / de, cancellation and support au / de); the US is two corpora (555 of 886 flagged; non-seeded US 1.35).")
ext("C148", " Report 67 (Habio): U_AD_MISMATCH 195 (9.51%, mean 1.08) — Instagram ads showing a 'bionic' bold-first-letter reading tool for ADHD that does not exist (22: 'What a bait and switch!!'), a quiz promising a Myers-Briggs / ADHD profile or tailored plan ('Nothing like that exists in the app', 31), and ads that did not match the product (99); §8.5: withdraw creative for features that do not ship.")
ext("C218", " Report 67 (Habio): the listing claims App Store billing, 'optional subscription', 'designed in collaboration with mental health professionals' and sharing with friends, while reviewers describe off-store billing, a hard paywall ('Optional subscription was a lie') and no sharing; an old pinned 'it has a free version' review misled later installers.")
ext("C104", " Report 67 (Habio): 'I downloaded this app based on the pinned review that stated it had a free version' — the free tier disappeared in 2022 (hard wall 17.74% of that era) while older reviews still said free.")
ext("C147", " Report 67 (Habio): the E2 objection was paying blind — 'I'd love an opportunity to try before I buy!'; MON_HARDWALL 47; the free era E1 averaged 3.03 with 53.42% praise against 1.73 once the wall arrived; §8.8: a real free tier or card-free trial, measuring chargebacks and refund requests rather than only conversion.")
ext("C061", " Report 67 (Habio): the non-seeded 5★ reviews are mostly free-era — 'Let's you have as many habits you want for free'; 'This app doesn't ask for payments which I really love'.")
ext("C182", " Report 67 (Habio): the purchase path is ad → quiz → small paid trial ('€5.49 seemed like a reasonable amount to see if the app could fulfil on the promises') → immediate add-on → auto-renewal; 995 reviewers say money left their account (mean 1.05) and only 35 describe a deliberate purchase (mean 1.23); very few buy because of the product.")
ext("C187", " Report 67 (Habio): paid Instagram / Facebook acquisition into a web quiz and a $1 auto-converting trial across 81 storefronts; volume tripled in the web-funnel era (572 reviews, mean 1.17, scam language 51.4%).")
ext("C033", " Report 67 (Habio): U_ACCESS_FAIL 97 (4.73%, mean 1.02) — cannot log in / email not found 52, paid but no premium or restore fails 43, purchased PDF not delivered 10; 'even i payed for subscription 350 kr but everything is locked'; §8.4: link web purchases to app accounts automatically.")
ext("C065", " Report 67 (Habio): 35 deliberate buyers (mean 1.23) report the same failures as everyone else plus locked premium; praise among money-left reviewers has a 0.06× lift.")
ext("C103", " Report 67 (Habio): USE_ACCESS 18 name vulnerability (disability, low income, student, mental-health crisis) and USE_MENTAL 40 — 'Shame on the developers for scamming people, like me, who are trying to work on their mental health' (the most-voted review, 16 votes).")
ext("C042", " Report 67 (Habio): the ADHD audience the ads target is the most harmed segment (97, mean 1.25) and finds the product 'way too overwhelming' for ADHD; §8.9: a short path to the first tracked habit, skippable pop-ups, the quiz after first value.")
ext("C111", " Report 67 (Habio): the quiz doubles as the sales funnel — NEG_ONBOARD_LONG 29 ('so we don't waste our time filling up a bunch of useless data in the first place'), paid on the web before installing.")
ext("C203", " Report 67 (Habio): preset routines only — 'What if I want the routine to include a workout but not meditation?'; REQ_CUSTOM_ROUTINE 18 and NEG_NO_CUSTOM_HABIT 9, 'the most consistent product request from people who got past the paywall'; forced intentions / rewards / reflections steps (7).")
ext("C116", " Report 67 (Habio): articles, courses and quotes criticised far more than praised (57 vs 12 non-seeded) — 'all the typos and language errors'; a therapist 'would never recommend for a client'; 'essentially charging 1 euro per page'; NEG_SHALLOW 102 'You literally pay to track your own habits'.")
ext("C093", " Report 67 (Habio): NEG_POPUP 19 ('I just wish it was voluntary'); a 2026 dashboard described as 'a mini Time Square Billboard showcase' of upsells.")
ext("C134", " Report 67 (Habio): what survives among non-seeded reviews is the calm, soft visual design (PR_DESIGN 39, in every era, often from complainants: 'I love the look and feel of the app, it's calming') and the reflection journal — keep them (§8.11).")
ext("C027", " Report 67 (Habio): REQ_LANG 41 (2.00%) — the only request at meaningful strength — from the free era onward ('ojalá pronto la pongan en español también'; 'Nur wie kann ich die App auf deutsch umstellen?'); France 13.19%.")
ext("C113", " Report 67 (Habio): 13 price points from $0.49 to $79.99 in the US listing, charges above the price shown (55), and currency not disclosed ('never mentioned in their add that the currency is not in AUD').")
ext("C003", " Report 67 (Habio): a $49.99 lifetime unlock is listed but no reviewer says they bought it; 'consideren una que sea de un único pago o Lifetime, anima más a los usuarios'.")
ext("C274", " Report 67 (Habio): NEG_DARKUX 163 (7.95%, mean 1.01), used by reviewers who work in UX — 'As a UX designer I should have seen the dark patterns from the start'; '환불을 어렵게 만드는 전형적인 다크 패턴'.")
ext("C002", " Report 67 (Habio): era means 3.03 (free) → 1.73 (paywall) → 1.17 (web funnel) → 2.98 (seeded wave; non-seeded 1.11) → 1.59 — the positive share is the number that moves, and it depends almost entirely on the flagged reviews; billing harm stays high-priority under every exclusion.")
ext("C059", " Report 67 (Habio): MKT_REVIEW_MISLEAD 74 (3.61%) cite other reviews, mostly as a warning to would-be buyers — 'the first several top-rated reviews were all previous users warning others not to pay'.")
ext("C172", " Report 67 (Habio): the daily reflection journal is one of the two things the corpus says to keep.")

M = {
 "R67-001":["C218","C113"], "R67-002":["C231"], "R67-003":["C231","C076"], "R67-004":["C029","C210"], "R67-005":["C210","C112","C218"],
 "R67-006":["C112","C029","C221"], "R67-007":["C109","C152","C215","C113"], "R67-008":["C285","C274","C212"], "R67-009":["C212"], "R67-010":["C029"],
 "R67-011":["C286","C148"], "R67-012":["C213","C103","C042","C285"], "R67-013":["C036","C215","C189"], "R67-014":["C076","C054"], "R67-015":["C134","C172"],
 "R67-016":["C147","C061","C003","C104"], "R67-017":["C203","C116","C111"], "R67-018":["C033","C210","C145"], "R67-019":["C027","C203"], "R67-020":["C274"],
 "R67-021":["C059","C104"], "R67-022":["C076","C061","C027"], "R67-023":["C231","C002"], "R67-024":["C182","C187","C036","C065"], "R67-025":["C065","C033"],
 "R67-026":["C231"], "R67-027":["C076","C231"], "R67-028":["C213","C285"], "R67-029":["C286","C027"], "R67-030":["C112","C212"],
 "R67-031":["C112","C036","C113"], "R67-032":["C212"], "R67-033":["C285","C029"], "R67-034":["C231","C076"], "R67-035":["C002","C104","C187"],
 "R67-036":["C285","C286","C076"], "R67-037":["C002","C027"], "R67-038":["C231"], "R67-039":["C218","C286","C210"], "R67-040":["C109","C285"],
 "R67-041":["C093","C111","C207"], "R67-042":["C029","C112","C285","C152","C215","C076"],
}
cards = [json.loads(l) for l in open("Tools/prd_ledger/67/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/67/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 67" in x["statement"] and not any(k.startswith("R67-") for k in x["cards"])])
