# -*- coding: utf-8 -*-
"""Stage 3 merge for report 83 (Roubit : Fun Routine Planner, Roubit Inc.)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C301", "must-never-break", "The support form and account deletion must not live behind the surface most likely to break — a tab outage must never take the reporting and exit paths down with it",
    "Report 83 (Roubit, 500 reviews): in two waves (2025-11-06 → 11-10 and 2026-05-16 → 06-09) the Diary and Settings tabs opened a white screen — BUG_DIARY_SETTINGS_BLANK 40 (8.00%), 14 of the 15 reviews in the first window and 26 of 37 in the second; Settings holds the in-app support form and account deletion, so the bug cut off the way to report it and the way to leave: SUPPORT_UNREACHABLE_INAPP 6 — '設定にもいけないから不具合報告が出来なくてやむなくこちらに書かせて頂きました' (I can't reach Settings to report the bug, so I had no choice but to write here, 4★); '設定画面に入れないので何もできない' (I can't get into Settings, so I can't do anything — about deleting the account, 1★); reviews became the support desk (SUPPORT_QUESTION 43, 8.60%) and 19 of the 40 blank-screen reports were filed at four or five stars by loyal users. §8.1: 'Move the support form and account deletion somewhere that does not depend on Settings loading'; a release gate on Diary and Settings opening, staged rollout with blank-screen telemetry, a fallback read-only diary view, diary export. Related: [[C036]] (a support channel reachable outside the app), [[C249]] (account deletion completes in one step), [[C235]] (a first-run failure escape hatch), [[C188]] (the app must open offline).")

ext("C036", " Report 83 (Roubit): the in-app support form sits inside the Settings tab that blanked in two bug waves, so the corpus became the support desk (SUPPORT_QUESTION 43, 8.60%; 31 of 33 rating/text contradictions are high-star bug reports); support_negative 15 (3.00%, 2.53★): unanswered email ('I emailed the person in charge twice with no reply'), unread KakaoTalk, a promised same-day fix then three days of silence, 'it's starting to feel like the app is being neglected'; where support worked it raised ratings ('The support helped me fix the ad issue by using the Restore Subscription button' → 5★; 'sorted within 24 hours').")
ext("C249", " Report 83 (Roubit): account deletion lives in a Settings tab that would not open — 'I can't get into Settings, so I can't do anything' (1★, trying to delete the account); ACCOUNT_DELETE 4.")
ext("C034", " Report 83 (Roubit): the diary holds years of personal writing and was unreachable for weeks in two waves — DATA_LOSS 11 (2.20%, 2.91★): 'this app holds two years of my memories' (5★); 'I'd at least like to see the diary I wrote for a year, but I can't'; 'after updating, all my diary entries disappeared' (1★); 'It lost all my fragments. I had dozens.'; §8.1 treat the diary as irreplaceable data — release gate, fallback read-only view, export.")
ext("C020", " Report 83 (Roubit): no export or backup request appears in 500 reviews — until the diary tab blanked; §8.1 offer diary export as the fallback for a multi-year personal record.")
ext("C175", " Report 83 (Roubit): 'new bugs seem to appear with every update, so I'm thinking of switching apps' (3★); two blank-screen waves coinciding with releases (6.1.24 'Dreaming Idol' theme; 6.4.50 ad-rewards) — timing not proven cause; BUG_UPDATE_LOOP 7 — a forced update that cannot be installed (2022, Feb–Mar 2025, Mar–Apr 2026); widget removed in July 2025 for a paying user; U:defect_any 14.7% (E1) → 73.5% (E4); 'the product broke under paying users' — 14 of 27 payers report a defect.")
ext("C188", " Report 83 (Roubit): BUG_LAUNCH_LOAD 26 (5.20%, 2.85★; US 11.5%: 'i have never been able to use it because it does not load'; 'it just infinitely loads. Unusable.'); BUG_UPDATE_LOOP 7 — §8.2 instrument install → home screen (room loading, routine fetch, forced-update check) and fail open: show routines when the room or store cannot load; 'never block the app on an update that the App Store does not yet offer'.")
ext("C235", " Report 83 (Roubit): a white screen on launch with yesterday's routines visible and an ad required to complete them (jp 3★); §8.2 fail open — show routines when the room or store cannot load.")
ext("C031", " Report 83 (Roubit): U:cant_use_app 88 (17.60%, 3.23★) — blank tabs 40, launch/load 26, login/sign-up 16 (Google and Facebook login, lost items), crash 11, update loop 7; 46 of 62 one- and two-star reviews describe a defect or being blocked; an earlier launch cluster March–April 2023 ('it breaks every like 3-4 days').")
ext("C162", " Report 83 (Roubit): the AI 'support letter' that replies to diary entries receives crisis-level disclosures — '제가 죽고싶었을때가 있는데 이거 덕분에 지금 제가 여기있었어요' (there was a time I wanted to die; thanks to this I'm here now, 5★); 'No es una exageración decir que esta aplicación me salvó la vida'; USE_MENTAL_HEALTH 16 (depression, anxiety, ADHD, autism, crisis); one reviewer values that the letters keep 'recommending seeking a professional'; Dr. Eddy (AI counsellor chat) answered a factual question wrongly and is used by a minor for homework; 13 reviews are from students or children behind a 14+ sign-up gate on a 4+ app; §8.3 document and test how the AI responds to self-harm, crisis and minor users, always surface crisis resources, label the letter as AI — 'the question is not frequency but handling'.")
ext("C263", " Report 83 (Roubit): the AI reply is both the emotional core and the paid hook — PRAISE_SUPPORT_LETTER 70 (14.00%, 4.69★; 21.7% of the era it launched in: 'the diary replies are better than talking with my friends'; 'when I read the letter I felt those feelings slowly drift away'), known to be AI and valued anyway ('Even if it's ai, they've always been really well done'); OUT_EMOTIONAL_SUPPORT 64 (4.84★); PAID_FOR_LETTERS 3 ('so I subscribed; the money isn't wasted at all'); the allowance is undisclosed and moves (2 replies, 2 a week, 'second day you have to pay', ads to unlock; unlimited on the KR yearly plan) — PAYWALL_LETTERS_AI 8 (2★: 'it's sad I only get replies twice a week'; 'the app didn't warn you and it just stops'); BUG_LETTER_AI 9; AI_CONTENT_DISLIKE 1 ('very cliche answers'); §8.6 state the allowance before the user writes and test 2/week vs 1/day.")
ext("C103", " Report 83 (Roubit): U:mental_health_any 68 (13.60%, mean 4.84★) — the highest-rated cohort; two suicidal-crisis disclosures credited to the app; a diary sent to an AI with an advertising-and-analytics privacy label and no review asking where the text goes; minors present (SEG_STUDENT_MINOR 13).")
ext("C042", " Report 83 (Roubit): ADHD 4, autism 1 ('I am autistic and find it very hard to manage routines', 5★), depression 2, anxiety 2 — USE_MENTAL_HEALTH 16 at 4.75★; 3 of 27 payers name a condition.")
ext("C117", " Report 83 (Roubit): the mascot is the retention engine — U:character_game 192 (38.40%), PRAISE_CUTE 157 (31.40%), PRAISE_GAMIFICATION 76 (4.68★): 'I go in to decorate the room and end up doing all my tasks automatically'; a reviewer who installed five top apps: 'the only one that survived was Roubit'; 'my bunny passed away recently and I kind of enjoy taking care of the rabbit in the app'; SEG_TRIED_MANY 23 at 4.91★; REQ_CUSTOMISE_CHARACTER 14 at 5.00★; a minority is repelled (FEATURE_BLOAT 3: 'I've decided to leave the bunny behind'; a 1★ 'feels too much like a game').")
ext("C237", " Report 83 (Roubit): carrots → coins → fragments → gems spent on furniture, themes and outfits partly through a gacha; REWARD_ECONOMY_SLOW 7 ('It is so hard to get the coins'); PAYWALL_COSMETICS 4 ('A bit greedy' — fragments cannot buy Ultimate items); BUG_REWARDS 15 (2.80★); requests for more outfits, poses, rooms and seasonal themes (14, 5.00★) — the content runway is the ask.")
ext("C167", " Report 83 (Roubit): 'Ultimate' yearly plan adds exclusive themes and outfits; Gold Carrots sold as consumables ($0.99–$9.99); PAYWALL_COSMETICS 4 (0.80%, 'A bit greedy') vs REQ_CUSTOMISE_CHARACTER 14 at 5.00★ — cosmetics are wanted and lightly resented as a paid layer.")
ext("C024", " Report 83 (Roubit): gamification at its most effective in the series — 'habit app × gacha game' called 'excellent' even by a user uninstalling; PRAISE_GAMIFICATION 76 (15.20%, 4.68★); META_CALLS_IT_GAME 6; Duolingo named both as a nag to avoid ('it's not gonna harass you like Duolingo') and as a widget model.")
ext("C207", " Report 83 (Roubit): 'I wish I could hide the room-decorating tab' (FEATURE_BLOAT 3); one user left for a more minimal app — 'I've decided to leave the bunny behind'; ONBOARDING_LONG 1 ('endless questions and promotions').")
ext("C157", " Report 83 (Roubit): a 1★ from someone for whom the app 'feels too much like a game to use'; the game layer is default-on and not hideable.")
ext("C262", " Report 83 (Roubit): checking off yesterday's routine requires watching an ad (ADS_FOR_PAST_CHECK 4, since 2022: 'making me watch an ad for each record just to check off the previous day is very inconvenient'); when the ad would not load for a month, past tasks could not be completed and the user uninstalled (jp 3★); §8.4 'let yesterday's routine be completed without an ad; if an ad cannot load, complete anyway. Keep rewards, not records, ad-gated.'")
ext("C275", " Report 83 (Roubit): an ad that fails to load blocks the recovery action it gates — a month of unloadable past-day ads ended in an uninstall; 'even after watching them I can't get into Roubit at all' (1★, a user of several years).")
ext("C246", " Report 83 (Roubit): ads moved into the core loop in 2026 — 'ads now play when opening the app and when writing the diary' (jp 1★); 'as long as ads don't appear, I'll keep using it' (2023); U:ads_any 16 (3.20%), 3 of 13 stated churns cite ads; release notes 2026-04-29 'watch ads and earn additional rewards', 2026-06-09 'Premium users can now receive rewards without waiting for ads'.")
ext("C082", " Report 83 (Roubit): a free tier with ads that reviewers praise as generous (PRAISE_FREE_GENEROUS 14: 'literally gives you supportive letters every day FOR FREE'; PRAISE_NO_ADS 6) until 2026 put ads on open, on diary write and on past-day check-off — then ads became a stated churn reason; no reviewer says they paid to remove ads.")
ext("C231", " Report 83 (Roubit, 500 reviews): the positively selected case — public 4.658★ vs corpus 4.156★ (+0.502), small in Korea and the US, +1.13★ in Japan where the text turned during bug waves while the cumulative rating still read 4.48★ — 'the text reviews are the more negative signal, and they lead it'; 31 of 33 rating/text contradictions are four- or five-star bug reports and 19 of 40 blank-screen reports are 4–5★ — 'star ratings understate dissatisfaction during bug waves'; reviews used as a support desk (SUPPORT_QUESTION 43); 145 reviews (29.00%) under 60 characters; 17 of 31 voted reviews are Japanese, 10 of them bug reports; seven solicited or invite-code reviews, all 5★.")
ext("C300", " Report 83 (Roubit): the counter-case — here the written reviews lead the public rating downward during a bug wave (Japan text 3.36★ vs public 4.48★) because loyal users file bug reports at five stars and the cumulative star base lags; §8.10 'don't read cumulative 4.66★ as current satisfaction'.")
ext("C002", " Report 83 (Roubit): E1 4.69★ → E4 3.52★ with praise 88.2% → 53.0% and defects 14.7% → 73.5% — the fall is reliability, not the offer: paywall friction is lower in E4 (6.0%) than E3 (14.8%) and none of PRICE_TOO_HIGH / WANT_ONE_TIME / PAYWALL_LETTERS appears in E4.")
ext("C054", " Report 83 (Roubit): four reviews from January–March 2022 were written during a developer survey or for an in-app 'review-writing mission', and three post invite codes for in-app rewards — U:solicited_signal 7 (1.40%), all 5.00★; kept at the star given.")
ext("C094", " Report 83 (Roubit): an in-app 'review-writing mission' and invite-code reviews produced seven 5★ reviews with little product content (1.40%).")
ext("C003", " Report 83 (Roubit): WANT_ONE_TIME_PURCHASE 6 (1.20%: 'a subscription feels like slavery', kr; 'どうしても買い切りが欲しい', jp); Korean users anchor a routine-app subscription against a one-time game — 'Animal Crossing is ₩50,000 for life; a routine app is ₩55,000 a year… the first app where I'm upset that I can't bring myself to pay' (5★); §8.5 test a lifetime or long-term plan and a student price against the yearly ₩55,000.")
ext("C004", " Report 83 (Roubit): PRICE_TOO_HIGH 10 (2.00%), eight in Korea, anchored on the yearly price (₩39,000 in 2023, ₩55,000 from 2024) and against one-time games; PRICE_FAIR 2 ('honestly isn't that bad at 7.99'); 'about $60/yr' while an ad still plays on every task completion (4★).")
ext("C064", " Report 83 (Roubit): monetisation friction is mild (U:paywall_friction 61, 12.20%, 3.85★) and the free tier is praised more than attacked; the objection is format and the yearly anchor, 'not the value of the character or the letters'; WOULD_PAY_INTENT 11 of 246 in Korea vs 1 of 254 elsewhere; one Korean 3★ payer mainly uses Todo Mate, 'cheaper and works with Apple Watch'.")
ext("C005", " Report 83 (Roubit): COMP_NAMED_APP 8 — Todo Mate (cheaper, Apple Watch), me+, Study Bunny, Finch, Duolingo (as nag and as widget model), Animal Crossing (as a price anchor), iPhone's built-in apps ('no better than iPhone's built-in apps', a regretful payer).")
ext("C111", " Report 83 (Roubit): PRICE_OPAQUE 8 (1.60%) — 'services that don't show the price clearly aren't very trustworthy' (jp 3★); an elementary-schooler asking whether it keeps charging; §8.5 show price and renewal terms before the trial.")
ext("C109", " Report 83 (Roubit): BILL_UNEXPECTED_CHARGE 2 — 'I started a 7-day free trial and was charged ₩4,400'; 'suddenly ₩55,000 for a year was charged' (5★, refund requested); TRIAL_USER 4; a trial-ad problem fixed via Restore Subscription.")
ext("C191", " Report 83 (Roubit): the free cap has been moved repeatedly — a 150-record cap in 2021 ('it's like don't use it unless you pay'), 8 routines for most of the window, 9 in 2023-02, 4 in 2025-02 — each move a separate grievance (FREE_LIMIT_ROUTINES 12, a 1★ 'I'll just use another app').")
ext("C007", " Report 83 (Roubit): an 8-routine free cap with a praised free tier (FREE_GENEROUS 14 vs FREE_LIMIT_ROUTINES 12); PAID_FOR_ROUTINES 3 ('the unlimited routines really make all the difference') — the cap converts a few and is tolerated by most; its value has been changed at least four times.")
ext("C236", " Report 83 (Roubit): the letter allowance is undisclosed and moves — 'you have to pay for the AI letter, but the app didn't warn you and it just stops' (2★); 'I'm not sure though' about the rule; §8.6 state the allowance before the user writes.")
ext("C033", " Report 83 (Roubit): PAID_NOT_UNLOCKED 4 — 'I was stuck with only 8 even after paying' with no support reply (us 1★); 'despite paying for the ¥6,000 annual plan, none of the paid features applied… 詐欺に近い対応です' (jp 1★, refund requested); membership 'sometimes drops'; one fixed by support via Restore Subscription; SCAM_LANGUAGE is otherwise absent (2 in 500).")
ext("C139", " Report 83 (Roubit): a Restore Subscription button resolved an entitlement/ad problem for a paying user who then moved to 5★; membership that 'sometimes drops' is the same class.")
ext("C065", " Report 83 (Roubit): PAID_EXPLICIT 27 (5.40%, 3.67★) — 44.4% satisfied, 51.9% report a defect (one who paid for the letters then lost the diary: 'if it seems fixed after a while I'll subscribe again', 2★), 4 regret ('abandoned a year's subscription as clunky'), 3 not unlocked, 4 churned — 'the product broke under paying users'.")
ext("C040", " Report 83 (Roubit): BUG_WIDGET 15 (3.00%; KR 4.9%) — routine order reversed in the widget (developer promised a fix for October 2024); in July 2025 'with this update the iPhone widget seems to be unsupported' for a paying user; REQ_WIDGET 9.")
ext("C155", " Report 83 (Roubit): the iPhone widget disappeared in a July 2025 update (a paying user, 3★); Dr. Eddy (AI counsellor) is praised 2023-08 → 2024-10 and then asked about as removed (FEATURE_REMOVED 6: 'is it gone or premium-only?').")
ext("C141", " Report 83 (Roubit): REQ_IPAD_WATCH_MAC 15 (3.00%), every one from Korea — 'I want to buy premium but hesitate because I use my iPad a lot'; a paying Korean 3★ mainly uses Todo Mate for Apple Watch; §8.8 an iPad layout for Korea.")
ext("C022", " Report 83 (Roubit): Apple Watch requested only from Korea (within REQ_IPAD_WATCH_MAC 15); a paying user defected to a rival 'cheaper and works with Apple Watch'.")
ext("C043", " Report 83 (Roubit): REQ_FLEX_SCHEDULE 10 (2.00%) — every N days, weekly counts, reps ('if it's 10 planks a day'), recurring deadlines, a pomodoro timer.")
ext("C170", " Report 83 (Roubit): 'not getting carrots for tasks done after midnight kills motivation' (kr) — a later day boundary requested.")
ext("C143", " Report 83 (Roubit): '하루에 프랭크 10회 하기라면' (if it's 10 planks a day) — count-based routines requested (REQ_FLEX_SCHEDULE 10).")
ext("C066", " Report 83 (Roubit): 'a pomodoro timer and the ability to set recurring deadlines' requested (5★).")
ext("C255", " Report 83 (Roubit): the app spread internationally before it spoke other languages — English speakers arrived via Twitter in 2022 to a Korean-only app while the listing already claimed English ('inside the app you can only use korean'; 'tried my best to translate each part but its tiring'); LANG_REQUEST 11 (18.4% of E2); LOCALIZATION_INCOMPLETE 5 in 2023–2026 (Korean in the gacha and store: 'ハングルで読めない'; 'me aparecen letras coreanas'; no am/pm format); §8.7 string-coverage checks per release per shipped language.")
ext("C027", " Report 83 (Roubit): 247 of 500 reviews (49.40%) are non-Korean for an app shipping only English and Korean; Portuguese (26) and Spanish (22) reviews are among the warmest (4.08★, 4.41★) with neither language shipped; Chinese (3) and Vietnamese (1) requests open; §8.7 decide from install data.")
ext("C286", " Report 83 (Roubit): the listing claimed English in 2022 while the app was Korean-only — 'in developer the language said it was on korean and english but inside the app you can only use korean' (4★).")
ext("C130", " Report 83 (Roubit): Korea (home market, 246 reviews, 4.37★) is where the buyers, would-be buyers, price objections, platform requests and widget bugs concentrate (PAID 6.9%, WOULD_PAY 4.5%, IPAD_WATCH 6.1%, BUG_WIDGET 4.9%); other markets report reliability (Japan blank-diary 32.1%, US launch failure 11.5%).")
ext("C062", " Report 83 (Roubit): the defined high-spend list (US-dominated) is more positive and less broken (defects 28.2% vs 38.0%) but excludes Korea and Japan, the two largest storefronts; outside Korea reliability is the bigger issue (cant_use_app 22.8%, 3.904★).")
ext("C184", " Report 83 (Roubit): 'the gender field has an undecided option besides female and male; I found that thoughtful' (kr 5★) — PRAISE_INCLUSIVE 2.")
ext("C238", " Report 83 (Roubit): a student segment (SEG_STUDENT_MINOR 13; a high-schooler 'it has helped me cope'; an elementary-schooler asking whether it keeps charging) and, from 2026-04-29, 'a new option to watch ads and earn additional rewards'; §8.5 test a student price.")
ext("C068", " Report 83 (Roubit): 13 reviews from students or children on a 4+ app with a 14+ sign-up gate — '앱이4세 이상인데 14세이상 가입이니 조금 당황스러워요' (5★); §8.3 asks whether minors reach the AI letter despite the gate.")
ext("C059", " Report 83 (Roubit): a developer reply promising a widget-order fix for October 2024; support that worked raised two ratings; but 2026 brought unanswered email, unread KakaoTalk, a promised same-day fix followed by silence and 'it's starting to feel like the app is being neglected' (NEGLECT_PERCEIVED 7).")
ext("C202", " Report 83 (Roubit): REQ_SOCIAL 5 ('please add the ability to msg your friends and give them gifts'); a friend feature shipped in January 2026; SOCIAL_WITH_FRIENDS 10; REFERRAL_CODE 3.")
ext("C172", " Report 83 (Roubit): a diary with mood logging is the emotional core (PRAISE_DIARY 24); REQ_DIARY_FEATURES 10 — photos, more moods, memos, more than one entry a day ('I pay so letters are unlimited, which is good, but I can only write one a day').")
ext("C208", " Report 83 (Roubit): photos in the diary requested (REQ_DIARY_FEATURES 10).")
ext("C258", " Report 83 (Roubit): 'alarms that repeat until done' are a shipped feature — PRAISE_REMINDERS 9, NOTIF_TOO_PERSISTENT 3, BUG_REMINDERS 6.")
ext("C046", " Report 83 (Roubit): NFC tag check-ins (Korea) — PRAISE_NFC 2; a user paid for the plan and bought stickers and the tag did not work; stickers out of stock.")
ext("C185", " Report 83 (Roubit): PRAISE_CUTE 157 (31.40%, 4.50★) and PRAISE_DESIGN_UI 43 — cuteness converts on day one ('paid for premium immediately and don't regret it at all'; paid 'after one day') and is what remains when the app breaks (19 of 40 blank-screen reports at 4–5★).")
ext("C085", " Report 83 (Roubit): one tracking objection in 500 ('the app tracks you', 5★); the privacy label lists advertising and analytics uses and precise location; the diary — with crisis content — is sent to an AI and no review asks where it goes.")
ext("C267", " Report 83 (Roubit): AI-written letters are accepted and loved ('Even if it's ai, they've always been really well done'); AI_CONTENT_DISLIKE 1 ('very cliche answers that don't resonate with me'); Dr. Eddy hallucinated an author's work.")
ext("C012", " Report 83 (Roubit): statistics and weekly reports ship; PRAISE_ALL_IN_ONE 23 — one user deleted separate to-do, goal and diary apps.")
ext("C144", " Report 83 (Roubit): routines, to-dos, goals, D-day, diary with mood, quotes and an AI letter in one app — PRAISE_ALL_IN_ONE 23 (4.60%): 'deleted separate to-do, goal and diary apps'; the cost is FEATURE_BLOAT 3 and a long onboarding.")
ext("C226", " Report 83 (Roubit): 'alarms that repeat until done' — NOTIF_TOO_PERSISTENT 3 against PRAISE_REMINDERS 9.")
ext("C123", " Report 83 (Roubit): NOTIF_TOO_PERSISTENT 3 for alarms that repeat until done; BUG_REMINDERS 6.")

M = {
 "R83-001":["C117","C144","C263","C012"], "R83-002":["C231"], "R83-003":["C231","C300"], "R83-004":["C117","C024","C263","C185"], "R83-005":["C301","C034","C036","C249","C175"],
 "R83-006":["C162","C103","C042","C263"], "R83-007":["C031","C188","C235"], "R83-008":["C064","C003","C004","C007"], "R83-009":["C262","C275","C246","C082"], "R83-010":["C255","C027","C286"],
 "R83-011":["C036","C231","C059"], "R83-012":["C085","C020","C141"], "R83-013":["C191","C263","C167","C246","C109","C046"], "R83-014":["C231"], "R83-015":["C117","C185","C144","C184","C082"],
 "R83-016":["C263","C267","C155","C162"], "R83-017":["C042","C103","C068","C238","C005"], "R83-018":["C175","C031","C040","C034","C207","C157","C155"], "R83-019":["C191","C004","C003","C111","C237","C167"], "R83-020":["C065","C109"],
 "R83-021":["C255","C027"], "R83-022":["C141","C022","C043","C170","C143","C066","C237","C172","C208","C202"], "R83-023":["C036","C059","C005","C024"], "R83-024":["C162","C103","C068","C085"], "R83-025":["C231"],
 "R83-026":["C231","C065","C157"], "R83-027":["C231","C300"], "R83-028":["C065","C231"], "R83-029":["C007","C263","C185","C046","C042"], "R83-030":["C033","C139","C065","C175"],
 "R83-031":["C064","C003","C111","C141","C109","C004"], "R83-032":["C231"], "R83-033":["C130","C141","C064"], "R83-034":["C188","C062"], "R83-035":["C301","C300","C231"],
 "R83-036":["C062","C130"], "R83-037":["C027","C255"], "R83-038":["C300","C231"], "R83-039":["C002","C231"], "R83-040":["C002","C263","C175"],
 "R83-041":["C301","C175","C034"], "R83-042":["C301","C034","C020","C036","C249"], "R83-043":["C188","C235","C031"], "R83-044":["C162","C103","C068","C267"], "R83-045":["C262","C275","C246"],
 "R83-046":["C003","C004","C111","C238"], "R83-047":["C263","C236"], "R83-048":["C255","C141","C043","C117","C040"], "R83-049":["C117","C263","C007","C301","C262","C162","C300"], "R83-050":["C054","C094"],
 "R83-051":["C207","C157","C117","C024"], "R83-052":["C059","C036","C139"], "R83-053":["C191","C007","C111","C236"],
}
M["R83-016"] += ["C172"]; M["R83-018"] += ["C226","C123","C258"]; M["R83-012"] += ["C022"]
cards = [json.loads(l) for l in open("Tools/prd_ledger/83/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/83/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 83" in x["statement"] and not any(k.startswith("R83-") for k in x["cards"])])
