# -*- coding: utf-8 -*-
"""Stage 3 merge for report 90 (Quit Bad Habits & Addiction, SHPAVDA TOO)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C306", "must-never-break", "Third-party ad code never sits on the launch path — the core surface renders first and any ad failure fails open",
    "Report 90 (Quit Bad Habits & Addiction, 614 reviews, mean 4.40★): release 1.2.0 (2026-07-15) put an ad banner in the launch path and the app became unusable for a week — BUG_CRASH 65 (10.59%, mean 2.23★), 64 of them in the seven days 2026-07-16 → 07-22, 64 of the 69 reviews posted that week, mean 2.41★, 58.0% one- or two-star, and 40 of the corpus's 62 one- and two-star reviews for all time. Reviewers diagnosed it themselves: BUG_CRASH_AD_LOAD 14 ('After recent update the app constantly crashes after the advertisement screen tries to load!'; 'the ad tries to load as soon as I open the app, and it crashes at once') and CRASH_OFFLINE_WORKAROUND 3 ('airplane mode helps'; 'with the internet off it runs stably'); BUG_AFTER_UPDATE 21. For a counter app the crash is not an inconvenience — 'if a relapse happens I won't be able to log it'; one reviewer thought years of statistics and notes were lost; another switched to a competitor. The same crash hit the developer's other app, so the defect travelled with the shared ad integration. §8.1: initialise the ad SDK after the core surface renders, catch and fail open on every ad load error, test release builds with the network on and ads live, stage the rollout and watch crash rates by build for 48 hours. The recovery is the other half of the lesson: 1.2.1 shipped six days later and the wave stopped dead — the 30 reviews after 2026-07-22 contain no crash report and average 4.70★, and the cumulative public rating (4.913★ over 14,806 ratings) barely moved. Related: [[C031]] (crashes and launch failures), [[C188]] (the app must open offline), [[C275]] (an ad that fails to load must never block the core action), [[C156]] (a release needs a crash gate).")

add("C307", "dont", "In a recovery or addiction app, exclude gambling, alcohol, tobacco and vaping ad categories — and verify the exclusion per storefront",
    "Report 90 (Quit Bad Habits & Addiction): the app is used to quit gambling, alcohol, smoking, drugs and self-harm (U:safety_sensitive 23, 3.75%; U:substance_any 31, 5.05%) and served betting and casino ads to exactly those users — ADS_HARMFUL_CONTENT 2 (2025-05-09 and 2025-09-23), promoted above its frequency band on safety grounds: 'it advertises betting and casinos to them … why not add alcohol and cigarette ads too?' (ru, 3★); 'ads for gambling, one of the addictions' (ru, 1★, titled 'Развод' — scam). The complaint carries the corpus's scam language, and the ad stream is otherwise a slow-building grievance (U:ads_negative 20, mean 2.65★, 6 of whom deleted the app). §8.2: enforce category exclusions (gambling, alcohol, tobacco and vaping, dating) at the ad network, verify them per storefront, and keep ads out of the relapse flow entirely — 'two reports clear no frequency threshold; the harm case does'. Related: [[C103]] (vulnerable users are a sensitive surface), [[C114]] (ads must match the app), [[C246]] (no ads in a personal habit tracker), [[C162]] (safety-filtered content for at-risk users).")

add("C308", "must-have", "Logging a lapse must not be the same action as destroying the count — a quit-tracker needs a way to record a slip, and non-judgemental wording around it",
    "Report 90 (Quit Bad Habits & Addiction): the product's whole mechanism is loss aversion on a big number — 'breaking big numbers hurts far more than the urge to smoke'; 'one reason not to relapse was that all the days would reset' — and reviewers then route around the reset rather than take it: a Ukrainian user logged a slip as a note instead of resetting ('I didn't want one day's slip to wipe two weeks, so I just noted the day'), PRAISE_NOTES_LOG 21 (3.42%, mean 4.90★) is the relapse note with its reason and date ('the ability to write and save the reason when you relapse is wonderful', jp), REQ_RELAPSE_OPTIONS 4 ask for a pause that keeps progress ('you can't pause and keep your progress'), and REQ_MOTIVATION_CONTENT 14 ask for supportive wording — 'show a line saying how many days you could have been clean'; 'a button for почти сорвался (almost relapsed)'. The vocabulary itself is noticed: 'the words refusal, bad habits, relapse are so-so' (REQ_POSITIVE_HABITS 3). This matters most where the audience is at risk — USE_SELF_HARM 13 (mean 4.92★), USE_DRUGS 8, USE_TREATMENT_CONTEXT 3, one keeping the log for a psychiatrist. §8.4 and §8.7: a growth visual that does not wither on relapse, an 'almost relapsed' record, crisis and support resources in the relapse flow for every shipped language, and no ads in that flow. Related: [[C216]] (a forgiving long-run measure beside streaks), [[C157]] (every guilt mechanic optional), [[C016]] (pause without losing history), [[C103]], [[C262]] (recovery actions stay free).")

ext("C031", " Report 90 (Quit Bad Habits & Addiction): the sharpest single-release regression in the series — BUG_CRASH 65 (10.59%), 64 of them in the seven days after 1.2.0, 92.8% of that week's reviews, taking the era mean to 2.41★ against 4.62–4.70★ in every other era; devices named include iPhone 13, 14 and 14 Pro Max on iOS 26.5.2 and iPhone 17 Pro, and reinstalling did not help; the fix (1.2.1, six days later) ended it completely — 30 later reviews, no crash report, 4.70★ ([[C306]]).")
ext("C188", " Report 90 (Quit Bad Habits & Addiction): the inverse case — the app only worked *offline* during the July 2026 crash week, because the ad load on launch was what crashed it ('airplane mode helps'; 'with the internet off it runs stably'); the listing promises 'works offline', and a network-dependent ad banner quietly broke that promise ([[C306]]).")
ext("C156", " Report 90 (Quit Bad Habits & Addiction): 1.2.0 shipped 'The app has been translated into more languages.' with an ad banner on the launch path and no staged rollout — 64 crash reports in six days across RU 44, US 15, KZ 3, CA 1, TJ 1, and the same crash in the developer's other app; §8.1 stage rollouts and watch crash rates by build for the first 48 hours.")
ext("C275", " Report 90 (Quit Bad Habits & Addiction): the ad load did not merely block an action — it crashed the app on launch for a week (BUG_CRASH_AD_LOAD 14), so the free tier's ad path took down the counter itself; ADS_TOO_MANY 18 describe a long unskippable ad after every action ('a long ad after every action; deleting'; 'the ads are long and can't be skipped'; 'to close it you have to exit completely').")
ext("C246", " Report 90 (Quit Bad Habits & Addiction): a free counter praised for having no ads at launch (PRAISE_NO_FEW_ADS 19 from day one, 'great that there are no ads') became an ad-carrying app — first complaint 2024-06-12, U:ads_negative 20 (3.26%, mean 2.65★), 6 of the 20 deleted the app and 7 of the 20 carry a lost-user signal against 5 of the 536 reviews with no money code: 'reviews that criticise ads are the churn segment'; some tolerate it ('far too many ads in the free version, but it's pointless complaining'; 'the ads are fully justified'), and two ask for ads instead of payment.")
ext("C082", " Report 90 (Quit Bad Habits & Addiction): ads are the app's only revenue apart from two ad-removal subscriptions, and the corpus prices that trade-off — U:money_any 36 (5.86%), 20 of them ad complaints; FUTURE_MONETISATION_WORRY 3 wrote before the ads arrived ('just don't ruin it with ads'), and they were right: the ad rollout produced the churn segment and, in July 2026, the crash ([[C306]]).")
ext("C103", " Report 90 (Quit Bad Habits & Addiction): U:safety_sensitive 23 (3.75%, mean 4.96★) — USE_SELF_HARM 13 ('with this app I haven't harmed myself for a month'; 'with it I stopped crying and cutting', ua; 12 of the 13 describe holding back), USE_DRUGS 8 (cocaine, injected drugs, Lyrica, weed), USE_TREATMENT_CONTEXT 3 (two rehabs, a relapse log kept for a psychiatrist); the listing describes smoking, alcohol, gambling and nail-biting and never mentions self-harm, the app is rated 9+, and it served gambling ads ([[C307]]) — 'the app is already used for self-harm recovery by reviewers who are likely young; its content, relapse copy and any ads shown to them are a safety question'.")
ext("C162", " Report 90 (Quit Bad Habits & Addiction): §8.7 — when a habit is self-harm or a drug, show crisis and support resources in the articles and the relapse flow for each supported language, and keep ads out of that flow; the corpus has 13 self-harm and 8 drug users and no crisis surface at all.")
ext("C019", " Report 90 (Quit Bad Habits & Addiction, 614 reviews, 4.40★): a pure quit-tracker — time since quitting to the second, unlimited habits, a personal record, an attempts counter, a relapse button with a dated note — earns U:praise_any 476 (77.52%) and U:outcome_any 118 (19.22%, mean 4.92★: 'not smoking for 2 years'; 'quit smoking and drugs with the app'); what is quit: smoking or vaping 17, self-harm 13, alcohol 10, drugs 8, food or weight 8, sexual 3, plus phone addiction, face picking, nail and lip biting, swearing and a habit that caused stuttering; the mechanism is the number itself ([[C308]]).")
ext("C024", " Report 90 (Quit Bad Habits & Addiction): the counter *is* the gamification — 'breaking big numbers hurts far more than the urge to smoke'; 'seeing the numbers clearly calms me more than a pile of praise' — and the app has no streak badges, levels or rewards at all; the requests are for a growth visual and milestones (U:motivation_layer_request 49, 7.98%), not for points.")
ext("C273", " Report 90 (Quit Bad Habits & Addiction): the home screen shows a tree inside a filling circle that never grows — REQ_TREE_GROWTH 28 (4.56%), 27 of them Russian, including the corpus's most-voted review (109 votes, 'why not add tree growth?') and 'the tree doesn't change, only the circle slowly closes … it doesn't motivate me much' (12 votes); by 2025 it reads as neglect — 'in all these years the developers haven't managed to add tree growth' (2★); §8.4 a tree that grows with the current streak and does not wither on relapse. A reward visual that implies growth and never delivers it generates the same complaint as one that stalls.")
ext("C101", " Report 90 (Quit Bad Habits & Addiction): REQ_MOTIVATION_CONTENT 14 (2.28%) — achievements, quotes and congratulation at milestones; 'no daily motivation, notifications or congratulations … after three days I forgot it existed' (2★); against a counter-signal — one reviewer finds plain numbers calmer than praise — so §8.4 makes milestone notifications optional and off by default.")
ext("C009", " Report 90 (Quit Bad Habits & Addiction): REQ_WIDGET 86 (14.01%, mean 4.53★) is the single most-requested thing in every era from 2023-02-06 to 2026-08-25 in an app that has no widget at all; 30 of the 87 four-star reviews ask for one and say it is the missing star ('without a widget the app is pointless', 3★; 'no home-screen widgets … deleting', kz); the reason is the mechanism — 'without one you can forget the app is even installed' — so §8.3 ships the counter widget free and tests premium *styles* inside the ad-free subscription: 'gate styling, not the number'.")
ext("C107", " Report 90 (Quit Bad Habits & Addiction): the one conditional purchase intent in 614 reviews is a widget — 'ready to buy a subscription, but please add widgets' (2023, 5★) — and §5.6 refuses to call it a result: 'no finding that a widget would sell subscriptions… an experiment to run'.")
ext("C023", " Report 90 (Quit Bad Habits & Addiction): the widget requests are for visibility of the count on the lock and home screen (second- and third-most-voted reviews in the corpus, 33 and 32 votes), not for interaction; one 2026 request asks to mark progress from it.")
ext("C217", " Report 90 (Quit Bad Habits & Addiction): the goal ladder advances by itself and is not explained — U:goal_setting 25 (4.07%, mean 4.12★) from people who otherwise like the app: GOAL_HOWTO_QUESTION 13 ('tapped everything, can't see where to change the goal'; 'spent the first day trying to understand why my goal is one day and where to change it') and GOAL_STEPS_RIGID 15 (7 then 30 days is too far for a strong habit; 'a 100-year goal is somewhat unrealistic', de; a 13-year-sober reviewer wants 15 years, not 100; 'it sets a month automatically, I need a year'); one reviewer says custom goals used to work and were removed; §8.5 show on first run that goals advance automatically, allow a custom next milestone, and use a gentler ladder (1, 3, 7, 14, 30, 60, 90 days, then yearly) — and one reviewer likes the automation, so it stays the default.")
ext("C108", " Report 90 (Quit Bad Habits & Addiction): goals are free and automatic here, and the complaint is the opposite of a paywall — users cannot edit the target at all (GOAL_STEPS_RIGID 15, GOAL_HOWTO_QUESTION 13).")
ext("C038", " Report 90 (Quit Bad Habits & Addiction): BUG_COUNTER_ATTEMPTS 5 — the count follows the device clock ('changing the phone's date changes the count'), an attempt was not recorded, a deleted relapse still counts, and a wrong day count appeared after the update; DATA_LOSS 3 includes a 1000-day count reset after a week away and a habit that 'deleted itself' — in a sobriety counter the number is the product, so a wrong number is a total failure.")
ext("C047", " Report 90 (Quit Bad Habits & Addiction): REQ_COUNTER_DISPLAY 5 — 'annoying that there's no day count for the current attempt'; REQ_BENEFITS_STATS 3 want cigarettes or drinks not consumed; REQ_CALENDAR 4 want relapses as dots on a calendar.")
ext("C100", " Report 90 (Quit Bad Habits & Addiction): REQ_BENEFITS_STATS 3 (0.49%) — 'bad that it doesn't show cigarettes or drinks not consumed'; the corpus asks for the avoided-quantity counter but not for money.")
ext("C123", " Report 90 (Quit Bad Habits & Addiction): the app has no notifications at all and REQ_NOTIFICATIONS 11 (1.79%) ask for them — 'Only downside is no notifications'; 'the app is forgotten very quickly'; 'no daily motivation, notifications or congratulations … after three days I forgot it existed' — while §8.4 still specifies them as optional and off by default. Zero notifications is also why no review in 614 complains of notification spam.")
ext("C006", " Report 90 (Quit Bad Habits & Addiction): minimalism is not a style here but an accessibility requirement — 'the interface doesn't trigger — important for people with addictions, where an extra detail can set you off'; PRAISE_SIMPLE_EASY 132 (21.50%, 4.91★), PRAISE_DESIGN 39, 'counter, reset and a comment to analyse a slip. Nothing else is needed'; the counter-pressure is FEATURE_THIN 12 ('just a timer: start, stop').")
ext("C178", " Report 90 (Quit Bad Habits & Addiction): a quiet counter with no account, no social layer, no streak badges and no notifications carries a 4.40★ corpus and 77.52% praise; 'no subscriptions and no extra buttons'; the tree icon is praised as calm ('the idea of the tree as the main icon is simply beautiful').")
ext("C061", " Report 90 (Quit Bad Habits & Addiction): with every feature free, one of the three would-pay statements is pure patronage — 'I see the ad-free subscription as a plus; thinking of using it to support you' (kz) — and the two actual buyers bought ad removal and stayed satisfied: 'paid at once — you can't start a tracker like this by watching smelly ads'.")
ext("C003", " Report 90 (Quit Bad Habits & Addiction): ad removal is sold only as a monthly ($0.99 / 99 ₽) or yearly ($9.99 / 699 ₽) subscription, and the objection is the format — 'sad you can't switch ads off for life' (kz); 'you should add a lifetime purchase; I want to buy' (vn, 5★); §8.6 add a one-time 'remove ads forever' purchase beside the plans and measure the purchase rate and one-star 'paid app' reviews in Russia.")
ext("C110", " Report 90 (Quit Bad Habits & Addiction): every feature is free and six Russian reviewers still believe the app is paid — PAYWALL_PERCEIVED 6 (0.98%, all RU): 'you can't even see the interface; a fully paid app' (1★); 'nothing but ads, and everything only for a month' (1★); 'the app is good, pity it's paid' (5★); the report cannot establish whether they saw an onboarding ad-removal offer, a trial screen or another app — §8.6 states on the purchase screen that every feature stays free.")
ext("C218", " Report 90 (Quit Bad Habits & Addiction): the listing says Free with in-app purchases and 'works offline'; a Turkish reviewer read it as 'tamamen ücretsiz' (completely free), was charged and asked for a refund (2023); the store language field says English only while the description claims 70+ languages; and 'works offline' sat beside an ad banner that crashed the app whenever the network was on.")
ext("C109", " Report 90 (Quit Bad Habits & Addiction): TRIAL_USER 1 — 'even though I deleted it and cancelled, they still try to charge me for the free subscription' (ru, 2025-12, 1★); the listing shows no trial, so what the reviewer saw could not be confirmed.")
ext("C036", " Report 90 (Quit Bad Habits & Addiction): no developer response appears on either captured listing and no reviewer reports contacting support or getting a reply; SUPPORT_QUESTION 15 (2.44%), 14 of them Russian, ask in the review how to set the goal, how to set the start date, whether progress transfers to a new phone and how to fix the crash — the review page is the only support channel the app appears to have.")
ext("C085", " Report 90 (Quit Bad Habits & Addiction): the privacy label declares Data Used to Track You (location, identifiers, usage data, diagnostics) and third-party advertising and analytics, in an app where reviewers log self-harm, cocaine, injected drugs and masturbation — and not one of 614 reviews raises privacy, tracking or data use; §8.8 asks how backup or transfer (REQ_BACKUP_SYNC 4) squares with a 'works offline' promise and a tracking label for sensitive habits.")
ext("C034", " Report 90 (Quit Bad Habits & Addiction): REQ_BACKUP_SYNC 4 (0.65%) — 'if I change iPhone, will my progress be saved?' — with no account and no sync; DATA_LOSS 3 (a habit that deleted itself, a 1000-day count reset after a week, and the crash-week fear of losing 'lots of statistics and notes').")
ext("C300", " Report 90 (Quit Bad Habits & Addiction): the counter-example — corpus 4.397★ vs 4.913★ over 14,806 public ratings is only +0.515★, and before the crash week the corpus averages 4.647★; 'text reviews and public ratings agree that the app is liked; the difference is the crash week, whose one-star reviews barely move a cumulative public mean'; the largest per-storefront gaps (RU +0.58, US +0.70) are the storefronts that carried the crash.")
ext("C231", " Report 90 (Quit Bad Habits & Addiction, 614 reviews, 37 storefronts): a Russian-language corpus — 516 reviews (84.04%) in Russian across 23 storefronts, including 41 of the 56 US-storefront reviews, so 'the US findings describe mostly Russian speakers using US App Store accounts'; only RU (407) and US (56) reach 50 and 17 storefronts hold one review; the request pattern is Russian-speaking (REQ_WIDGET 16.7% in RU vs 8.7% elsewhere; 27 of 28 tree-growth requests; SUPPORT_QUESTION 3.4% vs 0.5%; all six perceived-paywall reviews) while the crash concentrated in the high-spend group (19.3% vs 9.2%, driven by the US); 'language, not storefront, organises this corpus'.")
ext("C130", " Report 90 (Quit Bad Habits & Addiction): Russia is both the volume (66.29%) and the specification — 27 of the corpus's 28 tree-growth requests, 68 of 86 widget requests, 14 of 15 support questions and every perceived-paywall review come from the RU storefront, and the most-voted review in the corpus (109 votes) is a Russian feature request that later reviews cite back ('I'll voice everyone's request: PLEASE ADD TREE GROWTH').")
ext("C027", " Report 90 (Quit Bad Habits & Addiction): the store language field says English only while the description claims 70+ languages and 1.2.0's note was 'The app has been translated into more languages'; PRAISE_LOCALISATION 3, including 'Ukrainian is available'; the Ukrainian storefront splits 17 Russian / 13 Ukrainian reviews.")
ext("C094", " Report 90 (Quit Bad Habits & Addiction): no review in 614 mentions a rating prompt, a reward, a survey or a referral code, and the only bursts are crash reports — 'nothing here looks like coordinated positive reviewing. The corpus's weakness is short text, not manipulation' — against 45.77% of reviews under 60 characters and a public mean only 0.515★ above the corpus.")
ext("C240", " Report 90 (Quit Bad Habits & Addiction): ADS_TOO_MANY 18 (2.93%, mean 2.72★) describe an unskippable ad after every action in an app whose action is logging abstinence — '15 mandatory seconds of ads every time you use the app' (co); 'a long ad after every action. Deleting'; 'to close it you have to exit completely'.")
ext("C134", " Report 90 (Quit Bad Habits & Addiction): what the listing sells (smoking, alcohol, gambling, nail-biting) is narrower than what reviewers use it for — self-harm 13, drugs 8, phone addiction, face picking, swearing, a habit that caused stuttering — and the most-praised quality, a non-triggering minimal counter, is not what the description leads with.")
ext("C214", " Report 90 (Quit Bad Habits & Addiction): FEATURE_THIN 12 (1.95%, mean 3.33★) — 'just a timer: start, stop'; 'no more complex than a timer' — the same comparison-to-a-free-primitive objection, here aimed at a free app, which is why it costs three stars instead of a refund.")
ext("C016", " Report 90 (Quit Bad Habits & Addiction): REQ_RELAPSE_OPTIONS 4 — 'you can't pause and keep your progress'; users instead log a slip as a note to avoid zeroing two weeks ([[C308]]).")
ext("C294", " Report 90 (Quit Bad Habits & Addiction): the opposite constraint — with no archived listing history (the Wayback Machine was not queried, §9.E) the corpus is the only record of the app's past pricing and ad behaviour, and it disagrees with itself: one 2023 review already says 'only ads' while ad complaints as a pattern start in June 2024 and two 2026 reviewers describe ads as newly added. When the reviews are the only history, 'when did this change' cannot be answered at all.")
ext("C261", " Report 90 (Quit Bad Habits & Addiction): REQ_COLOURS_THEMES 7 (1.14%) — a colour per habit exists and reviewers want a different palette ('the colours are too toxic'), plus a dark theme that is already praised.")
ext("C060", " Report 90 (Quit Bad Habits & Addiction): DEV_OTHER_APPS 5 (0.81%) — one buyer downloaded 'all your apps', another wants widgets 'across the whole trilogy'; the same July 2026 ad crash hit the developer's good-habits app, so the family shares its defects as well as its goodwill.")
ext("C102", " Report 90 (Quit Bad Habits & Addiction): the pure abstinence direction — the number counts up from the last relapse and a relapse zeroes it; REQ_POSITIVE_HABITS 3 ask for the same product in positive wording ('the words refusal, bad habits, relapse are so-so'), which is the same counter with the sign flipped.")
ext("C062", " Report 90 (Quit Bad Habits & Addiction): the high-spend list holds 83 of 614 reviews and 56 of them are the US storefront written mostly in Russian — the group is a language cohort, not a market; it carries the crash (19.3% vs 9.2%) and almost none of the feature requests.")
ext("C114", " Report 90 (Quit Bad Habits & Addiction): the mismatch is inside the ad slot rather than the ad creative — betting and casino ads served in an addiction-recovery app ([[C307]]).")
ext("C300", " Report 90 (sensitivity): dropping the one crash week lifts the corpus to 4.650★ — within 0.26★ of the 4.913★ public mean — so this app's written-vs-public gap is almost entirely one release, not a rating mechanism.")
ext("C216", " Report 90 (Quit Bad Habits & Addiction): a relapse zeroes a counter that reviewers describe as their whole motivation, and they work around it — logging a slip as a dated note rather than resetting two weeks — while REQ_RELAPSE_OPTIONS 4 ask for a pause that keeps progress ([[C308]]).")

M = {
 "R90-001":["C019","C218","C231","C006","C134"], "R90-002":["C231"], "R90-003":["C300","C231"], "R90-004":["C019","C308","C006","C178","C024"], "R90-005":["C306","C031","C188","C156"],
 "R90-006":["C009","C023","C107"], "R90-007":["C273","C101","C217","C123"], "R90-008":["C103","C162","C308"], "R90-009":["C246","C307","C082","C240","C275"], "R90-010":["C003","C110","C061"],
 "R90-011":["C085","C034","C094"], "R90-012":["C110","C218","C109","C085","C003"], "R90-013":["C019","C231"], "R90-014":["C006","C178","C308","C024","C261"], "R90-015":["C019","C103"],
 "R90-016":["C103","C019","C102","C060"], "R90-017":["C031","C306","C038","C034","C214"], "R90-018":["C246","C082","C110","C003","C307"], "R90-019":["C217","C108"], "R90-020":["C009","C273","C101","C123","C047","C100","C016","C034","C308","C261","C216"],
 "R90-021":["C036","C130","C246"], "R90-022":["C109","C003","C218"], "R90-023":["C103","C162","C085","C307"], "R90-024":["C300","C231"], "R90-025":["C009","C031","C217","C214"],
 "R90-026":["C300","C231"], "R90-027":["C003","C246","C082","C061"], "R90-028":["C061","C003","C009"], "R90-029":["C110","C003","C218"], "R90-030":["C231","C300"],
 "R90-031":["C231","C130","C110"], "R90-032":["C231","C306","C062"], "R90-033":["C231","C062"], "R90-034":["C027","C231"], "R90-035":["C231","C246"],
 "R90-036":["C009","C246","C019","C103"], "R90-037":["C306","C031","C156","C094"], "R90-038":["C306","C031","C188"], "R90-039":["C307","C103","C114"], "R90-040":["C009","C107","C023"],
 "R90-041":["C273","C101","C308","C123"], "R90-042":["C217","C108"], "R90-043":["C003","C110","C218"], "R90-044":["C103","C162","C308","C085","C034"], "R90-045":["C019","C006","C307","C306","C009","C217"],
 "R90-046":["C036","C130"], "R90-047":["C231","C300"], "R90-048":["C085","C034","C094","C023"], "R90-049":["C231","C246"], "R90-050":["C231","C294"],
}
cards = [json.loads(l) for l in open("Tools/prd_ledger/90/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/90/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 90" in x["statement"] and not any(k.startswith("R90-") for k in x["cards"])])
