# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/79")
from _lib import c, table, save

c(54, "§7.1 boundary table (verbatim); §7.1 era table (verbatim); §7.1 quarter table (verbatim); §7.1 union table (verbatim); §7.1", "timeline", "Three eras at externally verifiable releases (verbatim): " + table("## 7.1 Method", 0) + " || " + table("## 7.1 Method", 1) + " || quarterly (verbatim): " + table("## 7.1 Method", 2) + " || unions by era (verbatim): " + table("## 7.1 Method", 3) + " — E2 has only 21 reviews, so E1→E3 comparisons are the reliable ones; 2025 Q2 is the peak (22 reviews, 5.00★), 2026 Q3 the trough (3.71★).", "n/a", "mixed", "E1 110 / 4.89★; E2 21 / 4.19★; E3 41 / 4.02★; 2025 Q2 5.00 → 2026 Q3 3.71", "none", "table", "app-specific", ["13836767975", "13767244783"], "", "")

c(55, "§7.2", "timeline", "T1 ratings fell monotonically across every boundary — the strongest trend: mean 4.89 → 4.19 → 4.02; 5★ 95.5% → 71.4% → 56.1%; negative_any 4.5% → 23.8% → 41.5%; first 50 reviews 4.88★ / last 50 3.98★; 2 1★ in the first 15 months, 9 in the last 11. What it is not: a collapse in how people regard the product — craft_praise still 58.5% in E3, COMP_BEST still awarded in the final review, 23 of 41 E3 reviews 5★: 'the decline is additive — the same praise, now with something attached to it'.", "n/a", "1★-burst", "4.89 → 4.02; 5★ 95.5% → 56.1%", "none", "High-priority", "app-specific", ["14501661045", "13836767975"], "", "")

c(56, "§7.3", "timeline", "T2 monetization complaints appeared and stayed — money_negative 2.7% (1.67★) → 19.0% → 17.1% (2.29★); not one complaint about the paywall's shape in the first 15 months (paywall_shape 0/110 in E1, then 9.5%, 9.8%); the positive side thinned then partly recovered (ONETIME_PRAISE 9 → 1 → 2; PRICE_FAIR 6 → 0 → 4 — four still call it fair after it rose): 'this is not a market rejecting a price. It is a market that was sold a specific promise — one payment, no subscription — encountering a different one, with no listing text to mediate the change.'", "n/a", "mixed", "money_negative 2.7% → 17.1%; paywall_shape 0 → 9.8%; PRICE_FAIR 6 → 0 → 4", "product-rule", "High-priority", "generalisable", ["11570370725", "11921754194", "14501661045", "13681657252"], "", "")

c(57, "§7.4; §8.2.1 table (verbatim); §8.2.1; §8.2.2", "must-never-break", "T3 defects went from zero to a fifth of the corpus — 8 of 9 after v2.1.0 (2026-02-11), whose notes warn widgets and shortcuts must be re-created, followed within four days by v2.1.1/2.1.2 adding a 'Deduplicate data' tool 'as some people reported duplicated boards and check-ins'; sub-classes traceable: crash fixed by name 11 days later; UI bugs one month after the overhaul; notifications — two complaints five and six weeks after v2.2.0 shipped multiple reminders ('a feature three reviewers asked for in 2024 shipped and then generated two reliability complaints'); data loss ×3, the last matching v2.6.2's stability fix for year-old builds; causation not claimed, coincidence tight and corroborated. Priority queue (verbatim): " + table("## 8.2 Do next", 0) + " — §8.2.2 give a recovery path for lost boards and say so publicly ('Is there anyway I can get them back? I had a nice streak going', 4★); an archive/restore feature shipped in v2.3.0 and nothing suggests users know it exists.", "major internal overhaul shipped with a migration side-effect", "1★-burst", "defect_any 0.9% → 19.5% (2.50★); data loss 3; notifications 2 post-reminders", "must-never-break", "High-priority", "generalisable", ["13767244783", "13836767975", "13929651995", "13962890919", "14173657564", "14293610339", "14397430419", "14501661045"], "a newly shipped requested feature (reminders) generated its own defect class", "")

c(58, "§7.5", "timeline", "T4 the paywall tightened in the second half — every paywall_shape review (6) falls after 2025-10-25; the free-tier sequence brackets the change between 2025-07-16 (free tier 'without huge limitations') and 2025-10-25 (can't place a widget) — a 101-day window in which the free tier's most-praised component moved behind the wall; counter-evidence kept in view: 'súper útil con analíticas y todo' on the free tier (2026-08-28) is consistent with v2.4.0 de-gating advanced analytics — 'the paywall moved in both directions during E3'.", "widgets gated ~Aug–Oct 2025; analytics ungated Apr 2026", "mixed", "paywall_shape 6, all after 2025-10-25; bracket 101 days", "none", "Very strong", "app-specific", ["12899474787", "13311025859", "14482128335"], "", "")

c(59, "§7.6; §8.4.4", "timeline", "T5 developer equity thinned — 26.4% → 9.5% → 12.2%; PRAISE_INDIE none after 2025-02-28 (nine in the first seven months, zero in the following eighteen); CH_YOUTUBE none after 2025-11-25; PRAISE_DEV holds (last 2026-06-09 'Appreciate the updates. Keeps improving') — 'not a story about support getting worse… the early corpus is full of people who followed a developer; the recent corpus is full of people who found an app'; §8.4.4 rebuild the acquisition story or accept a harsher audience — E1 rated 4.89★ partly because it arrived predisposed; whatever replaces that channel will not be.", "creator-channel launch cohort aging out", "mixed", "developer_equity 26.4% → 12.2%; INDIE 9 → 0; YOUTUBE 5 → 0", "do", "moderate", "generalisable", ["14162555466", "11622746398", "13439873787"], "", "")

c(60, "§7.7; §7.7 table (verbatim)", "insight", "T6 requests stayed constant (16.4% → 19.0% → 19.5%) and got structurally harder (verbatim): " + table("## 7.7 T6", 0) + " — E1 asks (notes, reminders, smaller widgets, start-of-day, multi-board view) were incremental and all shipped, with two reviewers returning to acknowledge it; E3 asks (Watch, iPad, import, categories/search, photos) are structural and none shipped — 'the request pipeline works; the backlog that remains is the part a point release cannot clear'.", "n/a", "mixed", "request_any flat ~17–20%; incremental shipped, structural open", "none", "Meaningful", "generalisable", ["14118758406", "14162555466"], "", "")

c(61, "§7.8; §7.9", "data-caveat", "Persisted across 770 days: craft praise in every quarter; COMP_BEST 2024-09 → 2026-09; widgets 27 at 5.00★ (2024-08 → 2026-06); zero complaints about ads, privacy, battery, accessibility or forced accounts; the three-board cap never moved. Cannot say: the date of the pricing change (bracketed only); which single cause drove the rating decline (pricing, widget gating, the v2.1.0 regression and the review prompt are all live in the same window); whether a composition shift explains it (E1 arrived from YouTube/Reddit; a drop from 4.89 to 4.02 is consistent with a harsher audience as well as a worse experience); volume trend.", "n/a", "mixed", "5 persistences; 4 unanswerables", "none", "limited evidence", "generalisable", ["14501661045"], "", "")

c(62, "§8.1.1; §8.8 #1; part 8 #1", "must-never-break", "§8.1.1 make the purchase work and make restore work — 4 of 11 1★, mean 1.00★, 33.3% of stated payers, 2024-11 → 2026-06 (a recurring class, not one build): entitlement not applied after payment, restore failing, a paid entitlement unusable on a second device; the v2.7.0 note confirms the class ('Ripples+ features would sometimes become locked while the device was offline'); add an in-app 'my purchases' state showing what is owned and when it was verified, an offline grace period for verified entitlements, and a visible support path from the failure screen; 'Developer doesn't respond' in a public 1★ is the worst outcome available.", "entitlement lock offline; no multi-device; restore broken", "1★-burst", "4 / 1.00★ / 33.3% of payers", "must-never-break", "High-priority", "generalisable", ["11921754194", "13582314702", "14192253561", "12352054623"], "", "")

c(63, "§8.1.2; §8.1.3; §8.8 #2; part 8 #2", "must-have", "§8.1.2 write the monetization paragraph the description does not have — four sentences: what the free tier includes, that the board limit is three, what Plus adds, and that both a subscription and a one-time option exist — 'the cheapest high-value change in the report'; §8.1.3 a billing period on every SKU and collapse three product names to one — 'A customer who cannot tell whether they are buying a subscription cannot consent to buying one.'", "no monetization text; 5 SKUs / 3 names / no periods", "blocked-conversion", "paywall_shape 6 (all after Oct 2025); UNEXPECTED 2; 6 names in 9 reviews", "must-have", "Very strong", "generalisable", ["14422900213", "14483046633", "11575210211", "12104500362"], "", "")

c(64, "§8.1.4; §8.6 #3; part 8 #3", "dont", "§8.1.4 turn the review prompt down — two 1★ (mean 1.00★, 18.2% of the worst ratings) from people who say the app is good; 'i already rated this highly, but now I keep getting the review prompt after every check in. Lowering to 1 stars until fixed'; cap it: once per user, never after a check-in, never after a user has already rated — effect immediate and measurable in the rating stream.", "prompt after every check-in", "1★-burst", "UX_NAG_REVIEW 2 / 1.00★; 2 of 11 1★", "dont", "Meaningful", "generalisable", ["13728350332", "14173657564"], "", "")

c(65, "§8.3 table (verbatim); §8.3; part 8 #5", "feature", "§8.3 the backlog that repeats (verbatim): " + table("## 8.3 Do next", 0) + " — Watch: 'quasi unentbehrlich' for fast capture, 'the app's whole value is low-friction check-in and the Watch is where that friction is lowest'; weekly scheduling: 'a gym habit done 3×/week can never build a streak, so the app's core feedback loop breaks for non-daily habits'; negative boards: both German, 17 months apart, same design (smoking; unfulfilled days as the streak) — opens the quit-habit use case; two asks carry a pre-committed 5★, the only rating-elasticity evidence, pointing at Watch and weekly scheduling.", "iPhone-only, daily-only, positive-only boards", "complaint", "Watch 3; weekly 3; iPad 2; import 2; negative 2; 2 pre-committed stars", "must-have", "Meaningful", "generalisable", ["12110523017", "13628057308", "14162555466", "11859903290", "13910121511", "14272948959", "14089348287", "14264852300", "13619259448", "12537644066", "14501661045"], "", "")

c(66, "§8.4.1; §8.6 #1; §8.8 #3; part 8 #4", "product-rule", "§8.4.1 reconsider gating the widget — 27 reviews at 5.00★ with zero negative mentions, the only feature with a perfect record; two complain it is now paid, one in the app's angriest review; a third proposes the compromise — 'make 2 widgets available in free version, one the bigger one and one the minimalist one'; 'A widget on a home screen is a daily impression of the product; removing it from the free tier removes the strongest retention and word-of-mouth surface the app has, in exchange for pressure on a cap that was already working' (the one explicit upgrade was for more boards, not widgets); §8.6 E1: free tier with widgets + 3-board cap vs current, measuring trial→paid and D30 retention.", "widget moved behind the wall ~Oct 2025", "complaint", "PRAISE_WIDGET 27 / 5.00★; WIDGET_GATED 2; cap upgrade 1", "build-free", "High-priority", "generalisable", ["13311025859", "14373214557", "14201744091", "12712143678"], "", "")

c(67, "§8.4.2; §8.6 #5; part 8 #6", "product-rule", "§8.4.2 decide whether this is a subscription product, then say so plainly — 12 reviews (6.98%, 4.67★) chose it because it was not, including the only 'used to be great' review which lists the absent subscription among what it lost; if the subscription stays, the Lifetime SKU must be prominent enough that the original promise is visibly honoured; if it goes, say so; 'the current state — five SKUs, three names, no periods, no description text — is the worst of both'; §8.6 E5 lifetime-forward paywall: show Lifetime first, subscription second, measure whether the 'no subscription' audience converts higher.", "subscription added beside lifetime, undeclared", "churn", "ONETIME_PRAISE 12 / 4.67★; SUB_OBJECTION 2", "product-rule", "High-priority", "generalisable", ["13836767975", "13681657252", "14483046633", "13106720476"], "", "")

c(68, "§8.4.3; part 8 #7", "monetization", "§8.4.3 price level is not the barrier — do not lead with a discount: ten volunteer the price is good (5.00★), four after the increase, against five objectors who are Italian, Slovak, German, German and Czech — not a low-income-market pattern; 'the elasticity evidence points at what you get and whether you knew, not at how much. A price cut would buy less than four sentences of disclosure.'", "€23 lifetime", "mixed", "PRICE_FAIR 10 / 5.00★ vs price_objection 5 / 3.20★", "dont", "High-priority", "generalisable", ["14501661045", "13854797898", "13311025859"], "", "")

c(69, "§8.5; part 8 #8", "dont", "§8.5 do not: add gamification, streak pressure, social feeds or AI ('Minimal incentive to follow some arbitrary set of rules'; 'no extra gamification, no ads, no BS'; anti_bloat 38.37% at 4.98★; zero ask for social or AI) — 'the product's position IS restraint'; add ads (five praise their absence, zero ask for an ad tier); weaken privacy (three cite it as a reason to choose); rewrite the UI (68.02% craft praise; the 'unusable' review blames overhaul bugs, not design); treat the 4.599★ corpus mean as the app's rating (public 4.781★).", "restraint as position", "praise", "anti_bloat 66 / 38.37% / 4.98★; NO_ADS 5; NO_TRACKING 3", "dont", "High-priority", "generalisable", ["11832349033", "13882115210", "11832301736", "12160259550"], "", "")

c(70, "§8.6 #2, #4; §8.7", "insight", "§8.6 experiments: disclosure A/B on the listing measuring the 1★ rate; weekly-target boards (are non-daily habits a niche or a large unserved segment). §8.7 research questions: what share of users ever hit the three-board cap; how many of the 765 silent raters are on the free tier; were one-time buyers grandfathered when the subscription arrived (one 1★ consistent with a migration failure); is the rating decline an experience change or an audience change; why France produced 57 ratings and 2 text reviews; does the Watch app actually convert or is it a stated preference.", "n/a", "mixed", "report gives none", "research", "limited evidence", "generalisable", ["13582314702", "13628057308"], "", "")

c(71, "§0.1 (competitive win); §3.3 P4; §8.5", "insight", "Restraint beats cute in a crowded category: 'Others are way too expensive or overly animated and cute. This one strikes a great balance'; 'no extra gamification, no ads, no BS'; the GitHub-contribution-graph metaphor is the identity (7 mentions at 5.00★, developers self-identify: 'As a SWE'; 'I'm a developer so I can definitely understand the GitHub feel').", "GitHub-grid, no gamification", "praise", "GITHUB_GRID 7 / 5.00★; NO_GAMIFICATION 2; anti_bloat 66", "do", "Very strong", "generalisable", ["14214708913", "13882115210", "11622746398", "14122073599"], "", "developer / engineer audience")

c(72, "§0.6; §8.1.1 (multi-device)", "must-never-break", "A paid entitlement must work on every device the buyer owns: 'Estafa — Pagué por la versión premium pero no puedo usarla en mis dos celulares' (1★); a Family SKU exists yet no review mentions Family Sharing.", "entitlement not usable on a second device", "1★-burst", "n=1, 1★", "must-never-break", "Emerging", "generalisable", ["14192253561"], "", "")

c(73, "§0.6 (promo); §1.6.10", "tactic", "A giveaway promo that could not be redeemed: an AppAdvice free-lifetime promotion on 2025-02-25 — 'today we are supposed to be able to get the lifetime version free through…' — produced a 1★ (MON_PROMO_FAIL) from a user who also could not find directions; a second giveaway (a competition win, disclosed unprompted, 'trotzdem urteile ich neutral') produced a 5★.", "promo codes via third-party giveaways", "mixed", "CH_GIVEAWAY 2 (3.00★): 1★ + 5★", "dont", "Emerging", "generalisable", ["12352054623", "14185235911"], "", "a promo that fails is worse than no promo")

save("a")
