# -*- coding: utf-8 -*-
"""Stage 3 merge for report 89 (Check Calendar - Habit Tracker, Naoki Otsu)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C305", "do", "Say 'one-time, not a subscription' wherever a one-time price appears — a buyer who mistakes it for a subscription reviews it as one",
    "Report 89 (Check Calendar, 253 reviews, mean 3.33★): the app sells a single SKU, 'Premium (Pay Once)' $4.99 / ¥780, and no subscription exists — yet PAY_SUBSCRIPTION_BELIEF 5 (1.98%) describe one ('$4/month'; 'Unless you purchase a subscription'; 'pagar una subscripción'; 'Scammed out of current subscription') and rate the app 2.20★ against 4.60★ for the 20 reviewers who understood the price as one-time and small ('it's one-time $4, people! A cup of coffee!'); the developer had to reply on the listing that Premium 'is a one-time payment, not a monthly fee'. The trial wall makes the confusion likely: a free period that ends in a demand for money reads as a subscription to anyone who has not read the SKU name. §8.1: say 'one-time, not a subscription' wherever the price appears — the store description, the trial countdown and the paywall. Related: [[C003]] (lead with a one-time purchase), [[C177]] (every plan states its period), [[C181]] (a trial-gated app says so up front).")

ext("C181", " Report 89 (Check Calendar, Naoki Otsu — the same developer as report 74, with the same omission): a free download whose checking stops after 4 days to a month, with no mention of a trial, Premium or a price in the store description captured 2026-09-13 nor in the archived 2024 and 2025 descriptions — PAY_TRIAL_WALL 73 (28.85%), PAY_UNDISCLOSED 27 (10.67%; 26 of them also describe the wall), U:paywall_any 107 (42.29%) explaining 64 of 71 one-star reviews; 'It was very cleanly, organized and easy to use. However, it says nothing about a trial'; 'NOT A SINLGE WORD was said about the need to pay'; 'Secretly paid app' (2026-08); reviewers write the fix themselves — 'If the app was upfront and said in the future, I'd have to pay I would have because I really like the app, but the dishonesty has made me delete the app'; 'if I had been told at the start, I would have paid right away' (jp, 5★); §8.1 put the trial length and the one-time price in the first lines of the description and on the first screen after install, with a visible countdown from day one and a reminder the day before it ends.")
ext("C236", " Report 89 (Check Calendar): the wall arrives after the reviewer has invested — install, log for days, then lose the ability to tick a box ('Works great the first weeK. After the free trial ends, even the basic function of checking off 1 day is behind a paywall'; 'it says you have to pay 6 dollars after I already did a lot of stuff with the app'); the durations reviewers name disagree (7 days, 4 days, two weeks, a month), which is itself evidence that nothing in the product announced the period; 'it is a disclosure and lock-out problem more than a price problem' — U:trust_breach 42 (16.60%) outnumbers U:value_objection 33 (13.04%), and 30 of the 107 paywall reviews also praise the app.")
ext("C193", " Report 89 (Check Calendar): after the trial, previously entered checks and notes cannot be viewed or copied out — PAY_DATA_LOCKED 8 (3.16%, 1.75★): 'when it ends, you're basically unable to do ANYTHING without paying. I can't even copy the notes I had written down'; 'Holds your data hostage for money'; 'now I can't even see the information I entered in those 7 days; it's blocked' (br); 'it's sad that I can't even see the notes I've entered without paying' (jp, 2026-03) — 'this matters more for a medication tracker than for a to-do list' (USE_HEALTH 14); one reviewer said a January 2025 update made old records visible again and a March 2026 reviewer still could not read notes; §8.2 keep history readable and CSV export available (the export already exists) even if new checks require Premium.")
ext("C204", " Report 89 (Check Calendar): locked records are one of the seven upgrade barriers named and the one that removes the clean exit — 'Records locked, so no way to leave cleanly' (PAY_DATA_LOCKED 8); the same records are what converted two reluctant buyers (PURCHASE_LOCKIN: 'didn't want to pay, but had already entered records, so bought').")
ext("C176", " Report 89 (Check Calendar): PURCHASE_LOCKIN 2 — 'didn't want to pay, but had already entered records, so bought' (jp); two others bought specifically so their records would be safe ('so they store my data and i don't loose it'; 'para ter o backup automático') and both then lost their data on a new phone — 'two of the stated reasons to buy — keeping data safe and not losing records already entered — are the same things that failed for other buyers and that the trial wall threatens for non-buyers'.")
ext("C104", " Report 89 (Check Calendar): the trial wall was applied to existing free users, not only new installs — the first trial-wall review (2024-01-06) came from someone who had used the app about two months ('2ヶ月ほど使っていましたが'); 2024-Q1 holds 21 reviews, 11 describing the wall, with three reviews on each of 01-06, 01-10 and 01-13 across jp, br and us; mean fell 3.78★ → 2.91★ and paywall share 11.1% → 56.7% between eras; PAY_FEATURE_REVERSAL 7 includes long-time users newly locked out ('Used this app around last year and it worked great, the premium features makes sense like more tabs… But recently… now you need to pay for the WHOLE features'); before 2024 the same app's complaints were freemium-shaped (two calendars free, dark mode moved to paid in 2022).")
ext("C186", " Report 89 (Check Calendar): a freemium tier (two calendars free, ads, dark mode paid) replaced by a trial wall in January 2024 caught users who had chosen the app on the earlier terms — PAY_FEATURE_REVERSAL 7 (2.77%), 'previous free features into paid ones'; the two-calendar-limit complaint disappears after 2024-01-20, 'consistent with the free tier being replaced by the trial'.")
ext("C001", " Report 89 (Check Calendar): dark mode moved behind payment in 2022 ('previous free features into paid ones', 1★), then in 2024 the whole core tick moved behind a trial — PAY_FEATURE_REVERSAL 7.")
ext("C214", " Report 89 (Check Calendar): PAY_NOT_WORTH 28 (11.07%, 1.71★) — the argument is almost always that ticking a calendar should not cost money, not that $4.99 is a lot: 'Why would using a calendar cost money? You can do this for free on your iPhone'; 'Not paying any amount of money to put check marks on a calendar'; 'who pays for a calendar?' (jp); 'too simple to pay 90 pesos' (mx); only one reviewer in 253 names a lower number they would pay; COMP_FREE_ALTERNATIVE 9 (1.11★) name a physical calendar, the phone's calendar, Google Calendar, a paper diary — and, in July 2026, an AI assistant ('Uninstalled this and created my own in 10 mins with Claude'); 'the simplicity that earns the praise is also the paywall's biggest obstacle'; §8.9 country-specific pricing will not help because 'price objections are about paying at all, not the amount'.")
ext("C147", " Report 89 (Check Calendar): PAY_CONDITIONAL_WILLING 6 — the conditions are disclosure (4), a widget (1) and paid extras rather than a paid base (1, from 2021: 'even as a paid option'); U:would_pay_signal 25 (9.88%); §8.4 experiment an ongoing free tier (one or two calendars, or ads) against the wall — before 2024 the app was freemium and paywall complaints were 11.1% of reviews, against 42.0–56.7% in each year since; 'the corpus cannot say which converts better; it says which one reviewers resent'.")
ext("C110", " Report 89 (Check Calendar): an ad-supported free option that reviewers say exists but cannot be selected — PAY_FREE_OPTION_BLOCKED 2 ('The whole app is basically useless without premium', 4★ 2026-06), FREE_TIER_OK 3, PAY_PREFER_ADS 2 ('You could just show ads so that we can use it freely'), MODEL_FREE_CLAIM 2 — 'the corpus cannot tell whether a working ad-supported tier exists'; the free/paid boundary is illegible enough that reviewers disagree about whether a free tier exists at all.")
ext("C200", " Report 89 (Check Calendar): after the trial 'even the basic function of checking off 1 day is behind a paywall' — the completion action itself is what the wall meters, and §8.5 proposes the inverse: basic ticking free, Premium sold on backup/sync, unlimited calendars, per-emoji reports and widgets.")
ext("C296", " Report 89 (Check Calendar): §8.5 sell Premium on what buyers name — the one-time price (PAY_ONCE_PRAISE 10), keeping records safe, unlimited calendars, per-emoji reports and widgets (a stated purchase condition) — with basic ticking free; paid-extra willingness predates the wall (2021: reminders, icons, colours 'even as a paid option').")
ext("C003", " Report 89 (Check Calendar): a single 'Premium (Pay Once)' SKU at $4.99 / ¥780 — PAY_ONCE_PRAISE 10 (4.60★: 'really great that payment is one-time'; 'an ad-free version for a few bucks without subscription!'), PRICE_FAIR 14 ('it's one-time $4, people! A cup of coffee!'; 'by far the cheapest'); buyers name the one-time model as the reason ('it's a one-time purchase, so I bought the paid version'; 'buying outright felt better'); 15 of the 20 price-positive reviews are five-star — 'the one-time price is part of what earns the top rating'; §8.9 do not add a subscription — believers already rate it 2.20★ ([[C305]]).")
ext("C177", " Report 89 (Check Calendar): one SKU, clearly named 'Premium (Pay Once)', and still five reviewers describe a subscription — the period must be stated where the price is seen, not only in the SKU list ([[C305]]).")
ext("C064", " Report 89 (Check Calendar): $3.99 → $4.99 and 600円 → 800円 (¥780 listed) between July 2025 and mid-2026, inferred from reviewer-quoted prices because the listing does not date it; no reviewer compares before and after — 'no price elasticity'; the only lower-price ask in 253 reviews is 'a couple of hundred roubles'.")
ext("C294", " Report 89 (Check Calendar): reviewers keep quoting 600円 through 2026-03 and $3.99 while the listing shows ¥780 / $4.99 — 'Prices quoted by reviewers are what they saw at the time, in their currency'; a 2026-05 reviewer records the change ('it used to be 600 yen, now 800').")
ext("C033", " Report 89 (Check Calendar): DEF_RESTORE_PURCHASE 9 (3.56%), all buyers — the failure point is the device change: 'I have the premium version but had to change devices… it's asking me to pay again' (br); 'I already PAID and now it wants me to pay again???' (ca); the restore button 'does nothing' on a new iPhone; a buyer cannot use Premium on their iPad; three buyers used the review to ask how to restore; 15 of 31 buyers (48.4%) report a post-purchase problem; none reported in 2026 (5 buyers) — §8.3 treat the silence as unconfirmed, test iPhone → iPhone and iPhone → iPad restore of both purchase and records, and make Restore purchase and backup status visible in settings.")
ext("C034", " Report 89 (Check Calendar): DEF_DATA_LOSS 6 (2.37%), 5 of them buyers — 'i took the premium version of the app for 1 reason: so they store my data and i don't loose it, i changed my phone and lost evrything' (1★); 'bought premium for automatic backup; it failed; notes lost' (br, 5★ with negative text); 'stopped working after 2 years of tracking and wouldnt open' then a reinstall lost data and the purchase; U:device_change_fail 12 (4.74%) consistent 2022 → 2025; last report 2025-09-04 while the listing now advertises backup and restore 'even across different devices' — 'whether that fixed it is not established'.")
ext("C030", " Report 89 (Check Calendar): 'No login required' and 'stored only on your device' beside a backup that restores across devices — the developer replied in February 2025 that automatic sync between devices is being 'actively' looked into; REQ_SYNC_MULTI_DEVICE 3; every buyer problem in the corpus is a device change.")
ext("C035", " Report 89 (Check Calendar): the no-account design is the reason every buyer failure is a device change — purchase not recognised, records empty, 'how to use that account on my ipad?' — and the reason 'Unable to backup on new phone since it is not allowing me to login' is written as a 5★ review with no other channel.")
ext("C065", " Report 89 (Check Calendar): PAID_EXPLICIT 31 (12.25%, 3.48★) — 15 of 31 (48.4%) report a post-purchase problem (restore 9, data loss 5, ads after paying 2, refund request 1, disputed charge 1) against 0.5% of non-buyers; four of the seven one-star reviews without a paywall code are paid users — 'outside the paywall, what earns one star is losing, miscounting or being re-charged for records the user paid to keep'; three-star is the paid-user band (8 of 26 buyers, 7 problems).")
ext("C127", " Report 89 (Check Calendar): PAID_ADS_AFTER_PURCHASE 2 — 'why are you showing ads in an application I paid for' (2022); 'premium purchased, but ads started appearing' (jp, 2023).")
ext("C036", " Report 89 (Check Calendar): SUPPORT_UNRESPONSIVE 2 ('no way to contact support'; 'Lodged a support ticket- no answer') and SUPPORT_QUESTION 5 — three paid users asking in a review how to restore their purchase on another device; §8.3 'give support a reachable path'.")
ext("C059", " Report 89 (Check Calendar): DEV_IMPROVEMENT_NOTICED 3 — 'I sent feedback to the developer to ask for one change: to be able to adjust the period displayed in the graph. And today I looked at the update, and it's done!' (5★); PRAISE_DEV_THANKS 19 (7.51%, 4.58★: 'Thank you to the developer for opting for simplicity!'); widget and notification requests (5 each) stop the moment both appear in the listing — no request for either after 2025-08-23.")
ext("C298", " Report 89 (Check Calendar): the inverse case — a public promise that was not kept. The developer replied on the Japanese listing on 2024-12-18 (pricing 'caused misunderstanding'; UI to be improved 'in an update') and 2025-02-10 ('hard to understand'; considering showing which features are paid before paying); after the second reply 15 of 139 reviews still report non-disclosure and 37 the wall, the listing still does not mention a trial, and DEV_PROMISE_UNKEPT 3 name the gap — 'tells other reviews it will improve, then does nothing' (jp); all three are on the storefront where the promise was made.")
ext("C189", " Report 89 (Check Calendar): seven public replies — a design rationale, two apologies for the pricing mechanism, a correction that Premium is 'a one-time payment, not a monthly fee', two feature acknowledgements and one confirmation of a shipped request; the apologies were specific and polite and still became evidence against the developer because the listing did not change ([[C298]]) — a reply that promises a fix is only as good as the fix's ship date.")
ext("C300", " Report 89 (Check Calendar): corpus 3.332★ vs 4.676★ over 7,065 public ratings (+1.344★); the gap tracks the paywall share by storefront (Canada +2.82, Vietnam +2.78, Brazil +1.65, Japan +1.47, US +1.38 vs India +0.55, UK +0.19); seven five-star reviews carry negative text ('(1 STAR RATING) DO NOT INSTALL THIS' at 5★); very short reviews rose to 44.9% of 2026 reviews as the US rating base grew 258 → 868 → 1,492; one complaint of a review request every day — §8.7 find how often the prompt fires and at what point in the trial: 'if it fires before the trial ends, the public rating mostly reflects the pre-wall experience'.")
ext("C094", " Report 89 (Check Calendar): REVIEW_PROMPT_EXCESS 1 — 'a review request every day, very excessive' (br, 1★, 2026-09); the rating–text contradictions (7 five-star reviews with negative text) are 'consistent with' a prompt that captures the star before the complaint is written.")
ext("C150", " Report 89 (Check Calendar): a review prompt that may fire inside the trial produces a 4.676★ public rating for an app whose written reviews are 42% paywall complaints — §8.7 research whether it fires before the wall.")
ext("C264", " Report 89 (Check Calendar): the whole proposition is one tap — 'typical apps often need at least 2 taps to record… in this app, tapping the date on the calendar completes the record… it became stress-free' (jp, 5★); PRAISE_ONE_TAP 7, U:calendar_core 25 (9.88%, 4.72★), U:simplicity 81 (32.02%, 4.42★) framed against other apps' clutter ('It's perfect because it's simple. All the other apps have a bunch of functions and distractions'); the developer's reply: 'we designed it so you reach your goal in as few actions as possible'; FRICTION_CHECK_INPUT 3 are the only logging-path complaints (a mis-tap confirmation that appears too often; a future date checked by accident; a check that cannot be erased).")
ext("C006", " Report 89 (Check Calendar): 'among apps with lots of unnecessary features, this one is very simple and easy to use' (jp); 'simple and not cluttered with too many options'; §8.9 no more features for their own sake — simplicity is the praise (U:simplicity 81, 32.02%).")
ext("C178", " Report 89 (Check Calendar): a calendar you tick, no streaks, no login, no social — zero streak, Apple Health or Family Sharing mentions in 253 reviews and no social request; PRAISE_NEED_FIT 31 ('Finally a calendar app where you can check off days'; 'I wanted a basic calendar with yes or no to track gym attendance this does exactly what I wanted').")
ext("C012", " Report 89 (Check Calendar): PRAISE_MONTH_VIEW 11 (4.91★) — 'see the whole month of the glance'; 'having a visual where I can see how often I accomplish my goals in a given month is helpful'; one monthly calendar per habit, several as tabs (PRAISE_MULTI_CALENDAR 11, 5.00★).")
ext("C254", " Report 89 (Check Calendar): the one-calendar-per-habit design is praised (11 reviews at 5.00★) and its cost appears as REQ_MULTI_HABIT_VIEW 2 and a request to tick several habits from the widget (2026-07) — the same tension report 74 recorded for the sibling app.")
ext("C261", " Report 89 (Check Calendar): PRAISE_CUSTOMISE 10 — emojis above all ('I made it a cute emoji I like, got motivated and kept at it every day', jp); REQ_CUSTOMISATION 9: tab colours, background colour, all emojis, per-date emoji, cell line thickness, filled cells, hiding last month's faded checks.")
ext("C069", " Report 89 (Check Calendar): 'I fell addicted to the little haptic click every time i would click off another day clean' — written in a 2★ review that ends 'it's a shame i have to get rid of the app now' because of the trial wall.")
ext("C172", " Report 89 (Check Calendar): PRAISE_NOTES 4 ('I use the short note for listing my weight'); DEF_NOTES_ERROR 2 on consecutive days in January 2024 ('10.1.0でメモが書けない'; 'Something went wrong'); notes are what the trial wall locks ('I can't even copy the notes I had written down').")
ext("C256", " Report 89 (Check Calendar): REPORT_ALL_MARKS_COUNTED 4 (1.58%) — reports count a ❌ day as done: 'I went to the gym 5 times this week… But I will also put 2 times the x… when I see the report, it shows 7 counts' (5★); one buyer gave 1★ for it and another wonders whether paying 600円 was a mistake; §8.6 count per emoji/mark in reports — 'for a record-keeping app these defects undermine the reason to pay'.")
ext("C038", " Report 89 (Check Calendar): DEF_COUNT_WRONG 2 ('some checked days aren't counted in the total'; monthly cumulative and this-month totals 'often don't match'), DEF_DATE_STALE 1 ('date doesn't become today unless the app is closed'), DEF_CHECK_LOST 1 ('checks sometimes vanish on reopening') — all Japanese, 2024–2026; U:record_integrity 20 (7.91%, 2.60★) once locked and lost records are included.")
ext("C047", " Report 89 (Check Calendar): PRAISE_REPORTS 4 ('Even though I have a smart watch it doesn't provide such reporting as this app'), REQ_REPORT_OPTIONS 5 (all-time or three-year ranges, y-axis from zero, percentages, per-emoji totals) — and DEF_COUNT_WRONG 2 where the totals do not match the calendar.")
ext("C271", " Report 89 (Check Calendar): PLATFORM_PRICE_GAP 2, both January 2026 — 'Why is the iPhone app paid? And only gives you a week-long trial, while it's free on Android?'; a Uruguayan reviewer paid on iPhone after using it free on Android and still gave five stars — the gap is a complaint on one platform and a purchase on the other.")
ext("C085", " Report 89 (Check Calendar): the listing says 'Your data is stored only on your device. It is never sent to third parties' while the privacy label declares 'Data Used to Track You: Diagnostics', the policy says edited information is sent 'to the analysis service', and the app advertises backup and restore across devices — one reviewer notices ('the description mentions security being top priority… Yet the backup/restore option uses the privacy-invading cloud', 4★, asking for non-cloud export); §8.8 reconcile the statements — 'the risk is to a positioning a reviewer already questions'.")
ext("C218", " Report 89 (Check Calendar): the description lists widgets, notifications, backup 'even across different devices' and 'No login required' and says nothing about a trial, Premium or a price — in the 2026 capture and the archived 2024 and 2025 captures — while the app stops after 4–30 days; the developer apologised twice for the confusion and the listing text did not change.")
ext("C231", " Report 89 (Check Calendar, 253 reviews, 40 storefronts): only the US (61) and Japan (60) reach 50; corpus 3.58% of 7,065 ratings and 1.34★ below them; half the corpus is non-English (Japanese 59); Japan carries the highest paywall share (50.0%) with the least fraud language (3.3%) and the most precise, polite descriptions, the most buyers (18.3%), the most specific praise (51.7%), all the record-integrity defects and all three unkept-promise reviews, and 17 of the 21 voted reviews; the US is 'the same paywall share but more accusatory' (non-disclosure 18.0%, scam language 11.5%, both double the rest) and says 'does what I need' more than 'simple'; storefronts with ≥10 reviews carry the paywall problem (46.5% vs 33.3%) and the public-rating gap tracks it by storefront.")
ext("C062", " Report 89 (Check Calendar): high-spend storefronts (11 present, US 61 of 99) buy less (8.1% explicit buyers vs 14.9% outside — Japan 18.3% and Brazil are outside the list) and object to price at the same rate (13.1% vs 13.0%); Japan is the largest buyer market and the one where the developer replies in writing.")
ext("C027", " Report 89 (Check Calendar): 24 listing languages and 12 review languages; the one Arabic request is written in English on the US storefront because Arabic is not shipped; DEF_LOCALISATION 1 — 'app name is in strange japanese characters' (br, 1★, 2022).")
ext("C042", " Report 89 (Check Calendar): USE_HEALTH 14 (5.53%, 4.57★) — medication, insulin, supplements, diet — 7 of 14 Japanese; the developer's site says the app began as a way to remember medication; 'with the app I don't forget my pills' (mx); and the trial wall lands on exactly these uses — 'I installed it so I wouldn't forget my supplements, but it was usable for only 7 days' (jp, 3★); §8.2 locked records 'matter more for a medication tracker than for a to-do list'.")
ext("C067", " Report 89 (Check Calendar): USE_FITNESS 18 (7.11%) — gym attendance, swimming, stretching, strength training; 'I wanted a basic calendar with yes or no to track gym attendance this does exactly what I wanted'; a Japanese buyer paid for a diet habit, reached the goal, and came back for exercise.")
ext("C140", " Report 89 (Check Calendar): USE_OTHER_PURPOSE 4 — work attendance (2), homestay bookings, piano practice ('I bought this app to track my piano practice'); a yes/no calendar generalises beyond habits.")
ext("C023", " Report 89 (Check Calendar): REQ_WIDGET 5 (2022-01 → 2025-01) stopped once widgets appeared in the listing — and not one of 253 reviews praises the widget; the one 2026 widget request asks to tick several habits from it (REQ_WIDGET_MULTI); §8.9 widgets are not a priority.")
ext("C142", " Report 89 (Check Calendar): widgets and notifications are both in the listing and neither is praised in 253 reviews — five requests each stopped after they shipped, but no review says they were found; a widget shipped and never mentioned is a widget users may not know exists.")
ext("C008", " Report 89 (Check Calendar): REQ_NOTIFICATIONS 5 (2021-08 → 2025-08: 'Notifications are missing.'), none after the listing added them; no notification failure in the corpus.")
ext("C020", " Report 89 (Check Calendar): CSV export is in the listing and §8.2 relies on it — keep it available after the trial so locked history can leave; REQ_LOCAL_EXPORT 1 asks for a non-cloud export on privacy grounds.")
ext("C080", " Report 89 (Check Calendar): dark mode was moved behind payment in 2022 (PAY_FEATURE_REVERSAL, 1★) and is praised when present (PRAISE_DARK_MODE 3: 'I love the OLED black color'); DEF_DARK_FLASH 1 — 'dark mode flashes on every open' (cn, 2021).")
ext("C010", " Report 89 (Check Calendar): PRAISE_BACKFILL 1 (5★) — editing past days is part of U:calendar_core (4.72★).")
ext("C246", " Report 89 (Check Calendar): ADS_COMPLAINT 5 (1.98%), all 2022-05 → 2024-10, two from buyers who still saw ads; two reviewers ask for ads instead of the wall (PAY_PREFER_ADS) — ads are the lesser resentment beside a silent trial.")
ext("C082", " Report 89 (Check Calendar): the free-with-ads option is 'offered but not selectable' for one reviewer (2024-07), used with a top banner by another (2024-10), 'useless without premium' for a third (2026-06) — the corpus cannot establish whether the ad tier works; PAY_PREFER_ADS 2 would take it over the wall.")
ext("C060", " Report 89 (Check Calendar): the same individual developer ships two habit apps (Habit Check Calendar, report 74, and Check Calendar) with the same undisclosed trial — 23.84% and 28.85% trial grievances — and reviewers notice the family (COMP_SAME_DEV_APP 2; REQ_MERGE_APPS 1 asks to merge them); a family repeats its flaw as readily as its trust.")
ext("C103", " Report 89 (Check Calendar): USE_HEALTH 14 includes insulin, medication and supplements — and PAY_DATA_LOCKED locks exactly those records; a reviewer tracking days 'clean' (2★) lost the app to the wall.")
ext("C141", " Report 89 (Check Calendar): REQ_IPAD_LANDSCAPE 1 (2021); a buyer could not use Premium on their iPad ('how to use that account on my ipad?', 2★).")
ext("C045", " Report 89 (Check Calendar): REQ_GROUPS 1 — calendar folders (paid user, 5★).")
ext("C048", " Report 89 (Check Calendar): REQ_QUANTITY 1 — numeric values per day (5★).")
ext("C099", " Report 89 (Check Calendar): REQ_REPEAT_TEXT 1 — repeat an entry across days; the developer replied that automatic daily repeat is under consideration (2025-02).")
ext("C051", " Report 89 (Check Calendar): the Android version is free per two reviewers while iOS is trial-gated at $4.99 (PLATFORM_PRICE_GAP); one Huawei request (REQ_OTHER_PLATFORM).")
ext("C031", " Report 89 (Check Calendar): zero crash or freeze reports in 253 reviews over five years; one 'wouldn't open' after two years of tracking (DEF_WONT_OPEN, whose reinstall then lost data and purchase); §8.9 no stability overhaul.")
ext("C133", " Report 89 (Check Calendar): before 2024 the free cap was two calendars (PAY_CALENDAR_LIMIT 3: a third required payment) — a quantity gate replaced in 2024 by a time gate on the core tick, which drew five times the complaint share (11.1% → 56.7%).")
ext("C297", " Report 89 (Check Calendar): the same two-calendar cap read as acceptable freemium in 2022–2023 (paywall complaints 11.1% of E1 reviews, 'the premium features makes sense like more tabs, and more customization') and its replacement by a trial on the core tick read as a wall (42–57% in every year since).")
ext("C043", " Report 89 (Check Calendar): FRICTION_CHECK_INPUT — touching a future date checks it by accident (jp, 4★); a yes/no calendar without a schedule has no non-scheduled days, so every mis-tap is a record.")
ext("C223", " Report 89 (Check Calendar): 'can't erase a check once entered' (jp, 4★, 2023) and a mis-tap confirmation dialog that 'appears too often' (jp, 4★, 2025) — undo must exist and must not become a modal on every tap.")
ext("C002", " Report 89 (Check Calendar): the 146 reviews without a paywall code average 4.438★ against 1.82★ for the 107 with one; the bands 'differ in kind' — paywall share 5% of five-star → 90% of one-star, specific praise 60% → 3%.")
ext("C070", " Report 89 (Check Calendar): reviewers reach for the calendar metaphor itself — 'Finally a calendar app where you can check off days'; the listing's name says what it is (Check Calendar) and the praise repeats it.")

M = {
 "R89-001":["C181","C218","C003","C231"], "R89-002":["C231"], "R89-003":["C300","C231"], "R89-004":["C181","C193","C236","C002"], "R89-005":["C236","C181","C147"],
 "R89-006":["C298","C189","C060"], "R89-007":["C033","C034","C065","C035"], "R89-008":["C264","C178","C214","C006"], "R89-009":["C256","C038","C023","C008"], "R89-010":["C031","C142","C178"],
 "R89-011":["C305","C110","C082","C133","C001","C271","C294"], "R89-012":["C085","C218"], "R89-013":["C002","C236"], "R89-014":["C236","C193","C181","C104"], "R89-015":["C214","C186","C001","C133"],
 "R89-016":["C003","C305","C147","C246","C082","C271","C051","C177"], "R89-017":["C264","C012","C261","C069","C006","C178","C010","C070"], "R89-018":["C042","C067","C140","C103"], "R89-019":["C059","C298","C036"], "R89-020":["C261","C023","C008","C047","C256","C030","C254","C045","C048","C099","C141","C027","C020"],
 "R89-021":["C038","C172","C223","C094","C080","C085","C031","C043"], "R89-022":["C002","C231"], "R89-023":["C059","C065","C300"], "R89-024":["C300","C094"], "R89-025":["C065","C003","C231","C127"],
 "R89-026":["C065"], "R89-027":["C176","C034","C033","C204"], "R89-028":["C214","C193","C305","C147"], "R89-029":["C231","C300"], "R89-030":["C231","C062"],
 "R89-031":["C231","C062","C298"], "R89-032":["C062","C231"], "R89-033":["C231","C027"], "R89-034":["C104","C186","C231"], "R89-035":["C033","C034","C298","C218","C023"],
 "R89-036":["C064","C294","C271","C300","C038"], "R89-037":["C181","C305","C236"], "R89-038":["C193","C204","C020","C042"], "R89-039":["C033","C034","C036","C035"], "R89-040":["C147","C110","C297","C082"],
 "R89-041":["C296","C200","C003"], "R89-042":["C256","C038","C047"], "R89-043":["C300","C150","C085"], "R89-044":["C023","C142","C031","C006","C003","C214"], "R89-045":["C189","C298","C059","C305"],
}
cards = [json.loads(l) for l in open("Tools/prd_ledger/89/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/89/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 89" in x["statement"] and not any(k.startswith("R89-") for k in x["cards"])])
