C = {
0:"NR",1:("LIKE","使用touchID和faceID来保护您的习惯隐私"),2:("LIKE","有应用锁这个功能很贴心"),3:"NR",4:"NR",5:"NR",6:"NR",7:"NR",8:"NR",9:"NR",10:"NR",11:"NR",12:"NR",13:"NR",14:"NR",15:"NR",16:"NR",
17:("BROKEN","now it even stucks on Face ID"),18:("BROKEN","卡在启动界面准备验证faceid"),19:("BROKEN","it shows face id symbol but doesn’t actually do anything"),
20:("BROKEN","指纹提醒不见了"),21:("BROKEN","it did nothing for several tries now I can’t get in"),22:("BROKEN","Total lock on the face ID page"),
23:"NR",24:"NR",25:("LIKE FREE","even lock the app"),26:"NR",27:"NR",28:("LIKE","set a passcode for the app"),29:"NR",30:"NR",31:"NR",32:"NR",33:"NR",34:"NR",35:"NR",36:"NR",37:"NR",38:"NR",39:"NR",
40:("WANT","Custom Lock Screen Passcode"),41:("BROKEN","antes de fazer a senha ou depois de fazer ela"),42:"NR",43:("LIKE","Face ID locking"),44:"NR",45:"NR",46:"NR",47:"NR",48:"NR",49:"NR",50:"NR",51:"NR",
52:("WANT","app內也無法設定密碼"),53:"NR",54:"NR",55:"NR",56:"NR",57:"NR",
58:("LEAK_NOTIF WHY_OTHERS","I don't someone see my private habits on my lock screen"),
59:("PEEK","when you open it next time it will momentarily peek inside"),
60:("BROKEN","приложение при входе вылетает"),61:"LIKE",62:("LIKE WHY_SENS","helps my mental health"),63:("LIKE WHY_SENS","sorta personal"),64:("LIKE FREE","touch id lock"),
65:("LIKE WHY_SENS WHY_OTHERS","so nobody can snoop into my habits"),66:"NR",67:("LIKE WHY_OTHERS","so people can’t see your bad habits unless they enter the code"),68:"LIKE",69:"LIKE",70:"LIKE",
71:("DISCREET WHY_SENS","very discreet when using it for self harm"),72:("LIKE WHY_SENS WHY_OTHERS","scared of people knowing"),73:("LIKE RELOCK","the app locks when you leave it open for privacy"),
74:"DISCREET",75:"LIKE",76:"LIKE",77:("LIKE DISCREET","change the app icon and use face id/passcode for privacy purposes"),78:("LIKE WHY_OTHERS","lucky snoopers who caught your phone turned on and unlocked"),
79:("LIKE ACCIDENT","security against accidental resets"),80:"LIKE",81:("LIKE WHY_OTHERS","allow people to do things on my phone"),82:("LIKE DISCREET","change the icon and have face id"),83:"LIKE",84:"LIKE",
85:("LIKE WHY_OTHERS","so no one else can see it"),86:("LIKE DISCREET WHY_OTHERS","no one can access it without my permission"),87:("LIKE FALLBACK","either password or face"),
88:("LEAK_WIDGET WHY_OTHERS","The data is still available through the widget"),89:"DISCREET",90:"LIKE",91:"LIKE",92:"LIKE",93:"LIKE",94:"LIKE",
95:("LIKE DISCREET WHY_OTHERS","discreet if people go through your phone"),96:("LIKE DISCREET WHY_OTHERS","keep nosy people not getting the hint"),97:"NR",98:("LIKE FREE","Something which is also paid in other apps"),
99:"LIKE",100:"NR",101:("LIKE WHY_OTHERS","even if your phone is unlocked"),102:"LIKE",103:"LIKE",104:"LIKE",105:"LIKE",106:"LIKE",107:("LIKE WHY_OTHERS","stuff on there that you don’t want people to see"),
108:("LIKE WHY_SENS","lees embarrass"),109:"LIKE",110:"LIKE",111:("LIKE DISCREET WHY_SENS","discreet app icon"),112:"LIKE",113:"LIKE",114:"DISCREET",
115:("LIKE WIDGET_DISCREET","widget of the time with out putting what the days are"),116:"DISCREET",117:"LIKE",118:"LIKE",119:("LIKE WHY_OTHERS","no one can just hack into ur counter"),
120:("LIKE SYSTEMCODE WHY_SENS","lock it with your phone passcode"),121:"NR",122:("LIKE FREE","paid feature on many similar apps"),123:"NR",124:"DISCREET",125:"NR",126:"LIKE",127:"DISCREET",128:("LIKE","behind a passcode"),129:("LIKE WHY_OTHERS","if you don’t want others to know"),
}
