# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/88")
from _lib import c, table, save

c(1, "header lines 1-6; §2.1; §2.1 table (verbatim); §2.2 table (verbatim); §2.5", "positioning", "GetHabit - Easy Habit Tracker (App Store ID 1541469491, fl.productivity.app; terms name it 'GetHabit: Motivation & Planner') by Fire Arc Technologies Ltd (FireArc Ltd., Herzliya, Israel), released 2020-11-24, current 1.3.1 (2024-03-26, 'Bug fixes'), called HabitBox in 2020–2021 reviews, 5 languages, listed Free ('Our app is free to use') with Premium Access IAPs at $7.99–$39.99 and printables at $9.99, privacy label 'Data Used to Track You' — in 2020–21 an onboarding that asks for a name and goals, preset 7–30-day challenges (cleaning, mental health, minimalism), custom habits with reminders, task lists, 'just 5 articles', statistics, printable PDF checklists sold separately, ads in the free version, a review prompt tied to content. Feature table (verbatim): " + table("## 2.1 What the product is", 0) + " || listing (verbatim): " + table("## 2.2 What the store listing says", 0) + " — not establishable: conversion/refund/chargeback rates, the 2021 web checkout, whether 'PersonalityPath' is a related entity, when the rename happened, whether the review gate / countdown / paid trial still exist, why the description's prices differ from the IAP list.", "hard paywall after onboarding; weekly/monthly/lifetime; paid trial; web checkout from mid-2021", "1★-burst", "490 reviews, 63 storefronts, 10 languages, 2020-11-25 → 2025-06-14 (98.16% in 2020–21), mean 1.714★; 90 codes; 2,376 assignments; 64 checks", "none", "header", "app-specific", ["6756282701", "6832389139"], "", "a 2020–21 corpus about a product mostly sold under another name")

c(2, "How to read this; Nine warnings 2, 3, 4, 5, 6, 7, 8, 9; §1.1 table (verbatim); §1.2 table (verbatim); §1.3 table (verbatim); §1.4; §1.5 table (verbatim); §1.6", "data-caveat", "Method and limits: every one of 490 reviews read in date order in the original language (es 17, de 13, it 7, pt 6, fr 3, four singletons), 90 codes in 13 families (86 hand, 4 mechanical), 23 unions, 2,376 assignments, 64 checks (36 tie codes to text; two real errors caught), 20 absence tests; no duplicates, no repeat authors; only the US (203) and UK (52) reach 50; a 2020–2021 corpus (481 of 490) — nothing describes the current build; no version field, no release history, no Wayback capture; purchases self-reported and some charge complaints may be the reviewer's own mistake ('my own fault'); prices mix plans, currencies and channels; 82 reviews (16.73%) under 60 characters and 132 (26.94%) carry helpful votes in a pattern that is itself a finding; 13 say the app made them rate it before unlocking content. Bands (verbatim): " + table("## 1.5 Signal thresholds", 0), "n/a", "mixed", "490/490 read; 90 codes; 64 checks; 20 absence tests; low-info 82", "none", "method", "generalisable", ["6756282701"], "", "")

c(3, "Warning 1; §6.8", "data-caveat", "Text reviewers are a negatively selected minority — and here the rating base is itself doubtful: 20,597 public ratings across the same 63 storefronts average 4.355★ vs the corpus 1.714★, a gap of +2.641★, the corpus 2.38% of the base; in the US 1★ is 6.76% of public ratings but 76.85% of text reviews; 'this corpus describes what made people write, not how the rating base scores the app — and §0.7 gives reasons to doubt the rating base itself'.", "n/a", "mixed", "gap +2.641★; 20,597 ratings vs 490 text (2.38%); US 1★ 6.76% public vs 76.85% text", "none", "High-priority", "generalisable", ["6756282701"], "", "")

c(4, "§0.1; §0.1 table (verbatim)", "monetization", "Money is the subject of nearly half the corpus: U:money_taken 227 (46.33%, CI 42.0–50.8%, mean 1.15★) — PAID_EXPLICIT 182 (37.14%) chose to pay, CHARGED_NOT_CHOSEN 45 (9.18%) say money was taken without their choosing (verbatim): " + table("## 0.1 Money is the subject", 0) + " — it explains the one-star band: 290 of 355 1★ (81.69%) describe paying before they could see the app, or money taken; of 182 who chose to pay, mean 1.18★ and 161 gave one star; 'It was an additional fee! I'm out $60 and there are 16 challenges... total'; 'it wants more money for every little thing it is worthless'; 'the first thing I chose, they want $9.99 to unlock the PDFs'.", "pay-first funnel with stacked extra-paid content", "1★-burst", "money_taken 227 / 46.33% / 1.15★; paywall_any 236; trust_breach 197 (40.20%); pre_use_wall 132; paid_problem 107; SCAM 105 (21.43%); unwanted_charge 93; buyers 1.18★, 161 of 182 at 1★", "product-rule", "High-priority", "generalisable", ["6832389139", "7185140969", "7200379204"], "", "")

c(5, "§0.2; §3.3; §8.1", "anti-pattern", "The purchase flow charges people twice: BILL_DOUBLE_CHARGE 26 (5.31%, CI 3.6–7.7%), 13 of them also describing the discounted lifetime offer that appears during or straight after a purchase; PAY_COUNTDOWN_OFFER 46 (9.39%) — a half-price lifetime offer on a timer; BILL_WRONG_PLAN 15 (3.06%) — bought lifetime or yearly, billed weekly or monthly; the sequence is consistent: buy a plan, see a half-price offer with a countdown, accept it believing it replaces the first, and pay both — 'a pop-up showed that I get a 50%off for this deal if I subscribe within one hour. So I did'; 'Right after I clicked purchase, a pop up comes up claiming to be offering it to you for half off, so $19.99… It was simply a double charge'; 'my subscription says weekly for 7.99 still'.", "post-purchase countdown upsell that stacks on the first purchase", "1★-burst", "DOUBLE_CHARGE 26 / 5.31%; COUNTDOWN_OFFER 46 / 9.39%; WRONG_PLAN 15 / 3.06%", "dont", "High-priority", "generalisable", ["6778267872", "7029621975", "6893430322"], "", "")

c(6, "§0.3; §3.2; §8.2", "product-rule", "People had to pay before they could see what they were buying: U:pre_use_wall 132 (26.94%, CI 23.2–31.0%, 1.17★) — PAY_HARD_WALL 96 (19.59%), PAY_NO_FREE_TRIAL 58 (11.84%), PAY_FREE_LABEL_MISLEADING 33 (6.73%); 97 of the 132 did not pay — lost installs, not refund cases; PAY_PREMIUM_INCOMPLETE 38 (7.76%) — having paid, content was still locked or cost more (PDFs, checklists, challenges); 'Free to download and the only thing you can do is write your name before purchasing a hefty $8 per week membership plan'; 'immediately when opening it and putting in a user name it asked you to pay $39.99'; the current description still says 'Our app is free to use' and lists $4.99 / $9.99 / $19.99 while the IAP list shows $7.99–$39.99; two reviewers said in-app prices were double the listing's.", "hard wall after the name screen; listing says free", "blocked-conversion", "pre_use_wall 132 / 26.94% / 1.17★; HARD_WALL 96; NO_FREE_TRIAL 58; FREE_LABEL_MISLEADING 33; PREMIUM_INCOMPLETE 38; non-payers 97", "product-rule", "High-priority", "generalisable", ["6810306576", "7082241504", "6832829686", "6934056192"], "", "")

c(7, "§0.4; §3.5; §8.6", "anti-pattern", "The ad was not the app: U:ad_mismatch 104 (21.22%, CI 17.8–25.1%) — ADS_MISLEADING 72 (14.69%) say the app is not what the ad showed, the rest object to the 'free' label; ACQ_SOCIAL_AD 53 (10.82%) came from Facebook, Instagram, TikTok or tumblr; 52 of the 72 misleading-ad reviewers paid — 'the ad did its job; the product did not match it'; USE_CLEANING 12 wanted the cleaning checklist they had seen advertised (11 in the US): 'the ad showed this super detailed all inclusive checklist for cleaning… Then I go looking for the checklist that was advertised on fb and can't find it anywhere'; 'The Instagram add suggested that it had something to do with personality types' (jp).", "social ads showing content the app does not have", "1★-burst", "ad_mismatch 104 / 21.22%; ADS_MISLEADING 72; SOCIAL_AD 53; misleading-ad payers 52 of 72; USE_CLEANING 12", "dont", "High-priority", "generalisable", ["7084713878", "6715202713"], "", "")

c(8, "§0.5; §0.5 table (verbatim); §3.3; §8.3", "timeline", "In mid-2021 the complaint moved from the paywall to the card statement — from June 2021 reviewers describe buying or trialling through a website reached from Instagram or Facebook, then being billed outside the App Store (verbatim): " + table("## 0.5 In mid-2021", 0) + " — BILL_WEB_CHECKOUT first appears 2021-06-03; BILL_OTHER_MERCHANT_NAME 4, all August 2021 ('with the name PersonalityPath (they impersonate this company)', tr; 'using another companys name on bank statements', gb); 'purchased the free trial week via their website… cannot use the premium offer, it's asking me to pay again' (gb).", "web checkout outside the App Store from June 2021", "1★-burst", "E3: unwanted_charge 47.7%; CHARGED_NOT_CHOSEN 39.8%; WEB_CHECKOUT 20.5%; CANT_CANCEL 25.0%; OTHER_MERCHANT 4", "product-rule", "High-priority", "generalisable", ["7692398130", "7674187696", "7621555490"], "", "")

c(9, "§0.6; §3.8; §8.4", "must-have", "Support did not answer, and refunds were rare: SUPPORT_UNRESPONSIVE 59 (12.04%), U:support_negative 70 (14.29%); BILL_REFUND_REQUEST 64 (13.06%) vs BILL_REFUND_RECEIVED 4 (0.82%) and BILL_REFUND_REFUSED 7; 61 of the 227 money-taken reviewers (26.9%) also report a support failure; a support reply quoted by a reviewer: 'we are unable to monitor every double-subscription case since there is a huge number of such mistakes'; two Spanish reviewers were refunded quickly.", "unresponsive support; refunds 4 of 64 requests", "1★-burst", "UNRESPONSIVE 59 / 12.04%; REFUND_REQUEST 64; RECEIVED 4; REFUSED 7; money-taken with support failure 26.9%", "must-have", "High-priority", "generalisable", ["7932137213", "7879858284", "8036849766"], "", "")

c(10, "§0.7; §3.5 (review gate); §4.7; §8.5", "data-caveat", "The public rating does not look like the reviews, and the corpus shows why it might not: a review gate — REVIEW_GATE 13 (2.65%) say the app made them rate it before unlocking a challenge, 8 of 13 had not yet used the app ('The app makes you rate it before unlocking a challenge', 3★); helpful votes run backwards — 27 of 54 five-star reviews (50%) carry votes vs 80 of 355 one-star (23%), five-star averaging 2.74 votes vs 0.37, and 11 five-star US reviews under 60 characters carry five or more votes ('Cool', 9 votes; 'Great app', 12 votes); two allege fake reviews ('Identical reviews with two different usernames'), REVIEWS_DISTRUST 11, though the corpus contains no repeated body; 'none of this proves manipulation. It is enough that the 4.355★ public rating should not be used as evidence of satisfaction for this app'.", "rating prompt gating content; vote pattern inverted", "mixed", "REVIEW_GATE 13 / 2.65% (8 pre-use); 5★ votes 50% vs 1★ 23%; 5★ 2.74 votes vs 0.37; REVIEWS_DISTRUST 11", "dont", "Meaningful", "generalisable", ["6824431033", "6794221347", "6804556598", "7261488968"], "", "")

c(11, "§0.8; §3.10", "insight", "What anyone liked: U:praise_any 90 (18.37%), praise_specific 33 (6.73%), OUT_BENEFIT 20 (4.08%); only 53 (10.82%) praise without any complaint (4.77★), 35 of 54 five-star reviews under 60 characters; of 182 buyers one is satisfied (PAID_SATISFIED, 3★: 'I purchased the app and it has helped with daily/weekly/monthly habits and to-do lists'); the idea is liked more than the app — PRAISE_CONCEPT 15 (1.53★): 'the concept is amazing but of course you have to buy everything for it to work'.", "n/a", "mixed", "praise_any 90 / 18.37%; praise-only 53 / 10.82%; PAID_SATISFIED 1 of 182; PRAISE_CONCEPT 15 / 1.53★", "none", "High-priority", "generalisable", ["7391062590", "7067923282"], "", "")

c(12, "§0.9; §2.4; §3.12", "data-caveat", "Absent: no Apple Watch, battery, Family Sharing, sleep or AI mention; one crash, one broken widget, one Apple Health mention; no developer reply quoted except one seen months later. Privacy: the label says Data Used to Track You and Data Linked to You for advertising; no review raises tracking — but PRIV_PAYMENT_DETAILS 8 (1.63%) object to handing over card details to try the app ('It's not actually free trial when you force ppl to put their credit card data!!'; 'Don't use their trial with your card details. This is a trap!'); the 2022 terms describe cancellation through Apple or Google only, but 2021 web buyers say that route did not exist for them.", "card-gated trial; tracking label", "complaint", "PRIV_PAYMENT_DETAILS 8; crash 1; widget 1; dev reply 1", "none", "absence test", "generalisable", ["7142966385", "7672761451", "8034491173"], "", "")

c(13, "§2.3 table (verbatim); §2.3", "monetization", "Free / paid / trial / unclear, prices as quoted 2020–21 (verbatim): " + table("## 2.3 Free / paid / trial", 0) + " — using the app at all was paid per most reviewers (a purchase screen after the name; five got past it: 'if you wait 5 or so seconds an X pops up'); a paid or card-gated trial ($0.49 first week, three days free with card, a '$1 verification of funds' / €0.01 / $0.99 on the web); weekly $7.99 / £7.99 / 69 kr; monthly $9.99; $30 per three months; $40 per year; lifetime $39.99 offered at $19.99 with a countdown; extra-paid content inside a paid plan (PDFs $9.99, a 'Full-Time-Pass' 10,99€, 'an additional $16 per month'); web checkout ~$31.96 not visible in Apple's subscription list; ad-promised trial length unclear (a week / 28 days / a month, then a charge within days — BILL_TRIAL_SHORTER 8).", "hard wall; paid trial; weekly plan; countdown lifetime; extra-paid content; web checkout", "blocked-conversion", "HARD_WALL 96; PAID_TRIAL 29; WEEKLY_PLAN 20; COUNTDOWN 46; PREMIUM_INCOMPLETE 38; WEB_CHECKOUT 19; CANT_CANCEL 34; TRIAL_SHORTER 8; FREE_TIER_OK 5", "undecided", "table", "app-specific", ["6930069664", "7637881316", "7974564520", "7611454280", "7199743576", "7188581081", "6894642285"], "", "")

save("w")
