# -*- coding: utf-8 -*-
"""Stage 3 merge for report 88 (GetHabit / HabitBox, Fire Arc Technologies Ltd)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C304", "product-rule", "A discounted offer shown during or after a purchase must replace and refund the first purchase, visibly — never stack a timed second offer on a completed one",
    "Report 88 (GetHabit / HabitBox, 490 reviews, mean 1.71★): the purchase flow charged people twice — BILL_DOUBLE_CHARGE 26 (5.31%), 13 of them describing the discounted lifetime offer that appears during or straight after a purchase; PAY_COUNTDOWN_OFFER 46 (9.39%), a half-price lifetime offer on a timer that 40 of the 46 who mention it accepted; BILL_WRONG_PLAN 15 (bought lifetime or yearly, billed weekly); the sequence is consistent — buy a plan, see a half-price offer with a countdown, accept it believing it replaces the first, and pay both: 'a pop-up showed that I get a 50%off for this deal if I subscribe within one hour. So I did' (vn 1★); 'Right after I clicked purchase, a pop up comes up claiming to be offering it to you for half off, so $19.99… It was simply a double charge' (us 1★); 'I also fell for the £19.99 offer… it is NOT telling me I have a lifetime membership but a WEEK membership' (gb); 24 of the 182 buyers (13.2%) report a double charge, and a support reply quoted in the corpus says 'we are unable to monitor every double-subscription case since there is a huge number of such mistakes'. §8.1: if a discounted plan is shown after a purchase it must replace and refund the first; remove timers from purchase screens; show the plan and renewal period on the confirmation screen and in settings. Related: [[C180]] (no exit discounts or countdown timers on the paywall), [[C285]] (a paid add-on is never bought on a single tap), [[C113]] (one stable disclosed price), [[C285]].")

ext("C180", " Report 88 (GetHabit): PAY_COUNTDOWN_OFFER 46 (9.39%) — a half-price lifetime offer on a one-hour timer shown before or right after another purchase; 40 of 46 accepted it and 13 were charged twice ([[C304]]); PAY_UPSELL_NAGS 36 — 'I've seen 4 attempted at making me buy upgrades in the first 1 minute'.")
ext("C285", " Report 88 (GetHabit): PAY_PREMIUM_INCOMPLETE 38 (7.76%), 30 of them buyers — having paid, PDFs, checklists and challenges cost more ('the first thing I chose, they want $9.99 to unlock the PDFs'; 'Not worth 3 different life time membership fees I had to pay'; a 'Full-Time-Pass' 10,99€ on top; 'an additional $16 per month to access further content'); the listing still sells 'Access to all printable items' separately; §8.7 include printables in any lifetime or yearly plan.")
ext("C211", " Report 88 (GetHabit): content packs sold on top of a paid plan — PDFs $9.99, a 'Full-Time-Pass', 'an additional $16 per month' — drove PAY_PREMIUM_INCOMPLETE 38, 30 of them from buyers; 'I'm out $60 and there are 16 challenges... total'.")
ext("C182", " Report 88 (GetHabit): the hardest pre-use wall in the series — U:pre_use_wall 132 (26.94%, 1.17★): PAY_HARD_WALL 96 ('It asks for your name, then tries to sell you a subscription'; 'you can't get past the subscription page without making a selection. There is no free version'), PAY_NO_FREE_TRIAL 58, PAY_FREE_LABEL_MISLEADING 33 ('listing it as Free in the store seems bad faith'); 97 of the 132 did not pay — lost installs; those who paid to see it found little (CONTENT_THIN 54; 'the concept is amazing but of course you have to buy everything for it to work'); of 182 buyers one is satisfied; 'the barrier is the order of events, not the price alone'.")
ext("C147", " Report 88 (GetHabit): 'you have to pay to even access the app. Whatever, did that' — and 51.1% of buyers then hit a problem, 35.7% regret; PAY_CONDITIONAL_WILLING 8 name a real trial as their condition ('A successful 30 day trial and I probably would have paid the subscription'; 'If I had a 14 or even 7 day trial I would have actually given it ago'); §8.2 a usable free core (a few habits and one challenge) before any purchase screen.")
ext("C296", " Report 88 (GetHabit): five reviewers got past the wall only by waiting for an X to appear ('if you wait 5 or so seconds an X pops up'); the free tier showed a name field and nothing else.")
ext("C109", " Report 88 (GetHabit): a paid or card-gated trial — $0.49 / £0.49 / 0,49€ for the first week, three days free with card details, a '$1 verification of funds' / €0.01 / $0.99 on the web (PAY_PAID_TRIAL 29: 'Was met with a $0.49 charge to even enter the app'); ad-promised trial lengths (a week, 28 days, a month) then a charge within days — BILL_TRIAL_SHORTER 8, BILL_TRIAL_CONVERSION 35 ('they offer you a 3 day subscription but charge you $31 immediately'; 'the trial that said ONE MONTH… automatically charged 20€'); PRIV_PAYMENT_DETAILS 8 object to card details for a 'free' trial ('Don't use their trial with your card details. This is a trap!').")
ext("C190", " Report 88 (GetHabit): PAY_WEEKLY_PLAN 20 (4.08%) — 'charge EIGHT DOLLARS A WEEK'; '3 days for free, then they'll charge 69 kroners (about 10$) per WEEK!!'; BILL_WRONG_PLAN 15 bought lifetime or yearly and were billed weekly; 'my subscription says weekly for 7.99 still'; the UK over-indexes on the weekly plan ('£8 per week after').")
ext("C210", " Report 88 (GetHabit): from June 2021 purchases and trials moved to a website reached from Instagram or Facebook ads, billed by card or PayPal outside the App Store (BILL_WEB_CHECKOUT 19, first 2021-06-03) — in that era unwanted charges 47.7%, charged without choosing 39.8%, could not cancel 25.0%; 'checked Apple's subscriptions to be safe — it wasn't there; still a 30 € PayPal debit' (de); 'the only way to cancel your subscription is through mail' (fr); 8 of 19 web buyers could not get the purchase into the app ('cannot use the premium offer, it's asking me to pay again'); §8.3 if web checkout is used, link it to an account that unlocks the app, bill under the app's own name, put a self-serve cancel link in every receipt.")
ext("C221", " Report 88 (GetHabit): BILL_OTHER_MERCHANT_NAME 4, all August 2021 — 'with the name PersonalityPath (they impersonate this company)' (tr); 'using another companys name on bank statements' (gb); BILL_PRICE_MISMATCH 10 ('Said it was charging me 39.99. I was charged 75 freaking dollars'); §8.3 bill under the app's own name and put a cancel link in every receipt.")
ext("C112", " Report 88 (GetHabit): BILL_CANT_CANCEL 34 (6.94%; 25.0% of the web-checkout era, 44.4% of the tail), BILL_CHARGED_AFTER_CANCEL 21 ('I sent three emails asking to cancel that night and one the following day'; 'they've been charging me for months', 2022; 'the payment still running in my credit card', 2024); the 2022 terms describe cancellation through Apple or Google only while 2021 web buyers say that route did not exist for them.")
ext("C212", " Report 88 (GetHabit): BILL_REFUND_REQUEST 64 (13.06%) vs BILL_REFUND_RECEIVED 4 and REFUSED 7 — 'tried to request a refund TWICE from Apple and was denied'; 'I was told I had to pruebe I used the app at least during 7 days'; the terms call fees 'non-refundable'; the two refunded quickly changed their tone ('they issued a full refund in under 24 hours'; 'que ladrones no son', 3★) — §8.4 a no-questions refund for double charges and charges after cancellation.")
ext("C287", " Report 88 (GetHabit): 'they told me we don't do refunds'; a support reply excusing double charges — 'we are unable to monitor every double-subscription case since there is a huge number of such mistakes'; BANK_ACTION 8 went to their bank or blocked their card.")
ext("C036", " Report 88 (GetHabit): SUPPORT_UNRESPONSIVE 59 (12.04%, 1.22★) — emails unanswered, 'Failed to send email', no contact details; 61 of 227 money-taken reviewers (26.9%) report a support failure; SUPPORT_QUESTION 13 used the review to ask how to cancel; 'seeing as the creator isn't responding to these reviews, I don't hold much hope'.")
ext("C148", " Report 88 (GetHabit): U:ad_mismatch 104 (21.22%) — ADS_MISLEADING 72 (1.14★) say the app is not what the Facebook, Instagram, TikTok or tumblr ad showed (personality types, cleaning checklists, templates, challenges); 52 of the 72 paid — 'the ad did its job; the product did not match it'; USE_CLEANING 12 wanted the advertised cleaning checklist ('Then I go looking for the checklist that was advertised on fb and can't find it anywhere'); §8.6 run creatives that show real screens and measure refund requests and one-star reviews per purchase, or ship the content the ads promised.")
ext("C281", " Report 88 (GetHabit): ACQ_SOCIAL_AD 53 (10.82%) — Facebook, Instagram, TikTok, tumblr — into an app labelled Free whose first screen after the name is a purchase wall ('Nothing like the Facebook adds. Was so excited to purchase but left sorely disappointed'); from June 2021 the ad led to a web checkout under another merchant's name.")
ext("C218", " Report 88 (GetHabit): the listing said 'free' while the app could not be used without paying (PAY_FREE_LABEL_MISLEADING 33, 1.06★); the description today still says 'Our app is free to use' and lists $4.99 / $9.99 / $19.99 while the IAP list shows $7.99–$39.99; two reviewers said in-app prices were double the listing's; QUALITY_SPELLING 12 ('Makr a list of short term goals').")
ext("C111", " Report 88 (GetHabit): a purchase screen after the name field with no price shown before install — 'immediately when opening it and putting in a user name it asked you to pay $39.99'; the trial's cost ($0.49) and the weekly renewal were the surprise.")
ext("C054", " Report 88 (GetHabit): REVIEW_GATE 13 (2.65%) — the app made users rate it before unlocking a challenge, 8 of 13 before they had used it ('it forced me to leave a review to unlock the first habit tracker'; 'writing a review in exchange for trying the app'; 'Just needed to rate to unlock'); the helpful-vote pattern runs backwards (5★ 2.74 votes vs 1★ 0.37; 11 one-line US 5★ with five or more votes); REVIEWS_DISTRUST 11 ('I'm assuming those are paid reviews'; 'I was a fool for trusting the 4.4 star rating'); §8.5 ask for ratings only after a completed streak, never as a condition — 'none of this proves manipulation. It is enough that the 4.355★ public rating should not be used as evidence of satisfaction'.")
ext("C094", " Report 88 (GetHabit): rating requests gating content produced five-star reviews from people who had not used the app ('Excited to try this in the new year!'; 5 five-star, 2 four-star and 4 three-star not-yet-used) and a buyer who gave 5★ so the warning would be seen ('the reviews tend to show to 5 star reviews first so that's why I gave it 5 stars. don't download this app').")
ext("C300", " Report 88 (GetHabit): the largest gap in the series — corpus 1.714★ vs 20,597 public ratings at 4.355★ (+2.641★), at least +2.3★ in every storefront with ten or more reviews; US 1★ is 6.76% of public ratings but 76.85% of text; the corpus shows two mechanisms — a rate-to-unlock gate and five-star texts written before use — plus a vote pattern in which one-line 5★ reviews carry the most votes; 'it is enough that the 4.355★ public rating should not be used as evidence of satisfaction for this app'.")
ext("C231", " Report 88 (GetHabit, 490 reviews): a 2020–21 corpus (98.16%) about a product sold under another name (HabitBox), 87.55% negative, 72.45% one-star; text 2.38% of the rating base and 2.64★ below it; the review gate, pre-use five-stars and inverted vote pattern make the public rating itself suspect; volume collapsed from 92 reviews in April 2021 to 6 in May, so the disappearance of the in-app dark patterns after May 2021 is 'weak evidence that they were removed'; some charge complaints may be the reviewer's own mistake and several say so ('my own fault').")
ext("C065", " Report 88 (GetHabit): of 182 who chose to pay, mean 1.18★ and 161 gave one star; 51.1% hit a post-purchase problem (unwanted charge 28.0%, content still locked 16.5%, no access 13.7%, support failure 23.6%), 35.7% regret, 27.5% asked for a refund, one is satisfied; PAID_NO_ACCESS 28 ('Despite that I cannot access app: Error. There was a problem with App Store'); 'buyers rate lower than everyone' — the public 4.355★ is not produced by its paying customers.")
ext("C002", " Report 88 (GetHabit): the extreme case — 290 of 355 one-star reviews (81.69%) describe paying before seeing the app or money taken; the product is barely evaluated (request_any 3.47%: 'requests are few because most reviewers never reached the product'); praise_any 18.37% and PRAISE_CONCEPT 15 at 1.53★ — 'the idea is liked more than the app'.")
ext("C133", " Report 88 (GetHabit): PAY_PRICE_TOO_HIGH 54 (11.02%, 1.52★) 'usually against how little the app contained, not against a competitor's price'; COMP_FREE_ALTERNATIVE 33 — the phone's reminders and notes, a journal, Pinterest, Google lists; 'the barrier is the order of events, not the price alone'.")
ext("C214", " Report 88 (GetHabit): U:value_content 105 (21.43%, 1.33★) — 'There are like 5 challenges and they are laughable'; 'the cleaning list is like Day 1 do the dishes, day 2 make the bed'; 'just 5 articles'; COMP_FREE_ALTERNATIVE 33 name the phone's own reminders and notes; at $7.99 a week the comparison to paper is fatal.")
ext("C283", " Report 88 (GetHabit): an onboarding that asks 'What do you want to work on? Reading? Drinking water? DO SPORT????' and then presents a purchase wall; ads promising personality-type content; a countdown offer on a timer; 'pay to see the app at all'.")
ext("C275", " Report 88 (GetHabit): ADS_IN_APP 21 (4.29%, all before 2021-04-07) — 'Impossible to use because of enormous number of long video ads' — inside an app that also charged $7.99 a week.")
ext("C246", " Report 88 (GetHabit): video ads in the free tier (ADS_IN_APP 21, 1.14★) on top of a hard paywall — the worst of both; the ads disappear from the corpus after April 2021.")
ext("C039", " Report 88 (GetHabit): DEF_REMINDERS 18 (3.67%) — 'the habit notifications are sent at the complete wrong time'; 'it goes back to the default time so the reminders don't work properly'; §8.8 'reminders that fire at the set time… are table stakes in the category'.")
ext("C073", " Report 88 (GetHabit): FUNC_LIMITED 13 — 'you can't change the name of a habit, you can't add more habit categories, you cant change the order of habits within a category' (mx); §8.8 editable habits as table stakes.")
ext("C143", " Report 88 (GetHabit): counting habits ('8 glasses of water') cannot be tracked (FUNC_LIMITED); §8.8 count-based habits as table stakes.")
ext("C264", " Report 88 (GetHabit): DEF_CANT_TRACK 7 — 'unable to mark my habits done'; 'it wants more money for every little thing' on each tap.")
ext("C031", " Report 88 (GetHabit): DEF_BUG_UI 28 (5.71%) — layout broken on iPhone SE, stuck set-up, black or blank screens; one crash report in 490; a lifetime buyer's app 'has just an freeze screen' by 2022.")
ext("C209", " Report 88 (GetHabit): no account or sync (NO_ACCOUNT_SYNC 9) — 'cannot login without having to pay full payment again' (sg); web buyers could not link their purchase to the app; one would pay for 'cross device syncing'.")
ext("C035", " Report 88 (GetHabit): the absence of an account meant a web purchase could not unlock the app (8 of 19 web buyers) and a reinstall required paying again — §8.3 'link it to an account that unlocks the app'.")
ext("C059", " Report 88 (GetHabit): no developer reply to a review is quoted except one seen months later; the two reviewers refunded within 24 hours revised their tone upward — the only responsiveness signal in 490 reviews.")
ext("C062", " Report 88 (GetHabit): the paywall and ad complaints are a large-market pattern (high-spend paywall 52.4% vs 34.7%, ad mismatch 24.7% vs 10.2% — the cleaning-checklist ad ran in the US) while billing harm is uniform (unwanted charges ~19% everywhere) and web checkout more common in small storefronts (6.5% vs 2.7%); German reviews average 1.00★ ('Abzocke'), Spanish 1.18★; non-English reviews rose to 22.7% in the web-checkout era — 'the web-checkout complaints came from more countries'.")
ext("C286", " Report 88 (GetHabit): sold in 63 storefronts with five UI languages — LANG_NOT_AVAILABLE 6 ('bought the app and it's all in German', pt); two ask for Spanish.")
ext("C278", " Report 88 (GetHabit): renamed from HabitBox to GetHabit at an unknown date in 2021 after the launch wave; seven reviews name the old app; a billing descriptor under a third name ('PersonalityPath') — three names on one product.")
ext("C099", " Report 88 (GetHabit): a 30-day-challenge format (7–30-day preset checklists) is the content model; CONTENT_THIN 54 and REQ_MORE_CHALLENGES 7.")
ext("C118", " Report 88 (GetHabit): preset challenges (cleaning, mental health, minimalism — 7 to 30 days) as the paid layer: PRAISE_CHALLENGES 7 vs CONTENT_THIN 54 and CONTENT_LOW_QUALITY 19 ('Minimalism challenge. Day 1 Purge your wardrobe'); CONTENT_NOT_PERSONAL 13 ('aimed females and/or those in a relationship').")
ext("C116", " Report 88 (GetHabit): printable PDF checklists and challenge packs sold on top of premium — the content library as the paid layer, at $9.99 a pack, on a product whose challenges were 'laughable'.")
ext("C103", " Report 88 (GetHabit): USE_MENTAL_NEURO 5 — ADHD, OCD, brain injury, addiction recovery — reached a product that charged $7.99 a week before showing anything.")
ext("C042", " Report 88 (GetHabit): 'I have ADHD and need help organizing my life' — two ADHD reviewers among the handful who reached the product.")
ext("C067", " Report 88 (GetHabit): a cleaning-checklist ad drew USE_CLEANING 12 (11 in the US) — the advertised use case the app did not contain.")

M = {
 "R88-001":["C182","C218","C278","C118"], "R88-002":["C231"], "R88-003":["C300","C231"], "R88-004":["C065","C002","C182","C285"], "R88-005":["C304","C180","C190"],
 "R88-006":["C182","C147","C218","C285","C296"], "R88-007":["C148","C281","C067"], "R88-008":["C210","C221","C112"], "R88-009":["C036","C212","C287"], "R88-010":["C054","C094","C300"],
 "R88-011":["C002","C065","C214"], "R88-012":["C109","C112","C059"], "R88-013":["C182","C109","C190","C304","C285","C210","C296"], "R88-014":["C231","C002"], "R88-015":["C182","C218","C109","C190","C285","C180","C133","C147","C111"],
 "R88-016":["C304","C221","C190","C109","C112","C210","C212","C287"], "R88-017":["C065","C209"], "R88-018":["C148","C275","C246","C054","C094","C281"], "R88-019":["C214","C118","C073","C143","C133","C099"], "R88-020":["C031","C039","C264","C218","C286","C209"],
 "R88-021":["C036","C212","C287"], "R88-022":["C065","C231"], "R88-023":["C103","C042","C067","C002"], "R88-024":["C002","C109"], "R88-025":["C231","C300"],
 "R88-026":["C231","C094","C054"], "R88-027":["C231","C094"], "R88-028":["C065","C231"], "R88-029":["C304","C148","C147","C109","C180","C283"], "R88-030":["C065","C304","C112","C036"],
 "R88-031":["C182","C147","C133","C109"], "R88-032":["C300","C231"], "R88-033":["C062","C148","C054"], "R88-034":["C062","C190"], "R88-035":["C062"],
 "R88-036":["C062","C286","C210"], "R88-037":["C231","C002"], "R88-038":["C210","C112","C054","C275","C231"], "R88-039":["C112","C278","C031","C231"], "R88-040":["C304","C180"],
 "R88-041":["C182","C147","C218","C109"], "R88-042":["C210","C221","C112","C035"], "R88-043":["C036","C212"], "R88-044":["C054","C094"], "R88-045":["C148","C285","C211","C116"],
 "R88-046":["C039","C073","C143","C264","C031"], "R88-047":["C300","C182","C304","C210","C054"], "R88-048":["C103","C042","C067"], "R88-049":["C065","C300"], "R88-050":["C212","C059"],
 "R88-051":["C281","C148","C304","C210","C278","C283"],
}
cards = [json.loads(l) for l in open("Tools/prd_ledger/88/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/88/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 88" in x["statement"] and not any(k.startswith("R88-") for k in x["cards"])])
