# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/89")
from _lib import c, table, save

c(1, "header lines 1-6; §2.1; §2.1 table (verbatim); §2.2 table (verbatim); §2.5", "positioning", "Check Calendar - Habit Tracker (App Store ID 1563837295, com.checkcalendar) by Naoki Otsu, an individual developer, released 2021-04-27, current 14.47.0 (2026-07-24), Free with advertising and a single IAP 'Premium (Pay Once)' $4.99 / ¥780 ($3.99 in 2024–2025 archives), 24 languages, iPhone/iPad/Mac/Vision — a monthly calendar per habit ticked with one tap, emojis or icons instead of a tick, short notes, reports/counts, several calendars as tabs, dark mode, backfill, backup/restore, widgets, notifications, CSV export, Face ID, 'No login required', offline; used mostly for exercise and medication. Feature table (verbatim): " + table("## 2.1 What the product is", 0) + " || listing (verbatim): " + table("## 2.2 What the store listing says", 0) + " — not establishable: downloads, conversion, revenue, refunds; when the trial wall shipped and whether existing free users were hit; whether records are readable after the trial today; whether the ad-supported option exists; whether restore now works for paid users; Android pricing.", "one-time Premium behind an undisclosed trial wall", "mixed", "253 reviews, 40 storefronts, 12 languages, 2021-06-18 → 2026-09-05, mean 3.332★; 95 codes; 1,073 assignments; 43 checks", "none", "header", "app-specific", ["10139655335", "11171003334", "7973712003"], "", "a one-tap calendar tracker from a solo developer whose trial is not in the listing")

c(2, "How to read this; Nine warnings 2, 3, 4, 5, 6, 7, 8, 9; §1.1 table (verbatim); §1.2 table (verbatim); §1.3 table (verbatim); §1.4; §1.5 table (verbatim); §1.6", "data-caveat", "Method and limits: every one of 253 reviews read in date order in the original language (126 non-English: Japanese 59, Spanish 23, Portuguese 19, Russian 8, Chinese 7, Vietnamese/Italian/French/Korean 2 each, German and Catalan 1), 95 codes in 10 families (92 hand, 3 mechanical), 24 unions, 1,073 assignments, 43 checks (19 tie codes to text; first run caught two real errors and one wrong direction), 20 absence tests; no duplicates, no repeat authors, one edited review; only the US (61) and Japan (60) reach 50; the trial wall is not externally dated (first review 2024-01-06 is a lower bound; version history shows only 25 boilerplate releases since 2026-05); no version field — timing, not proven cause; purchases are explicit statements only (31; 15 who praise the price without saying they bought are not counted); prices are what reviewers saw in their currency; 79 reviews (31.23%) under 60 characters; ten rating-vs-text contradictions kept at the star given; the app was not tested; translations are the analyst's own. Bands (verbatim): " + table("## 1.5 Signal thresholds", 0) + " — at n=253 one review is 0.40%, three are 1.19% (Meaningful), thirteen 5.14% (High-priority); in the US and Japan one review is already 1.6–1.7%.", "n/a", "mixed", "253/253 read; 95 codes; 43 checks; 20 absence tests; low-info 79", "none", "method", "generalisable", ["12598179708"], "", "")

c(3, "Warning 1; §6.6", "data-caveat", "Text reviewers are a negatively selected minority: 7,065 public ratings across the same 40 storefronts average 4.676★ vs the corpus 3.332★ (+1.344★), the corpus 3.58% of the base; in the US 1★ is 3.28% of public ratings but 27.87% of text reviews, in Japan 4.13% vs 30.00% — 'this corpus describes what makes people write, not how the user base rates the app'.", "n/a", "mixed", "gap +1.344★; 7,065 ratings vs 253 text (3.58%); US 1★ 3.28% public vs 27.87% text; JP 4.13% vs 30.00%", "none", "High-priority", "generalisable", ["10882459680"], "", "")

c(4, "§0.1; §0.1 table (verbatim)", "monetization", "The paywall is the single largest subject: U:paywall_any 107 (42.29%, CI 36.4–48.5%, mean 1.82★) — must pay, stops working after a free period, locks records, reversed free features, limits free calendars, or not worth charging for (verbatim): " + table("## 0.1 The paywall is the single largest subject", 0) + " — it explains the low ratings almost entirely: 64 of 71 one-star (90.14%) and 80 of 91 at one or two stars (87.91%) carry a paywall code; the 146 without one average 4.438★; the complaint is specific — people start logging, the app works, and after a period it stops: 'It was very cleanly, organized and easy to use. However, it says nothing about a trial'; 'when it ends, you're basically unable to do ANYTHING without paying. I can't even copy the notes I had written down'; 'Holds your data hostage for money'; 'there is no mention of a trial period, yet it became unusable after 7 days. It's like a fraud app' (jp, translated); the store listing still does not mention a trial — the description captured 2026-09-13 and archived 2024/2025 descriptions say nothing about a trial, Premium, a price or any paid feature.", "silent trial wall then one-time Premium", "1★-burst", "paywall_any 107 / 42.29% / 1.82★; MUST_PAY 102; TRIAL_WALL 73; NOT_WORTH 28; UNDISCLOSED 27; SCAM 18; DATA_LOCKED 8; 1★ with paywall 90.14%", "product-rule", "High-priority", "generalisable", ["10882459680", "11513669707", "12179154565", "13715567301"], "", "")

c(5, "§0.2", "product-rule", "It is a disclosure and lock-out problem more than a price problem: U:trust_breach 42 (16.60%, CI 12.5–21.7%) object to non-disclosure, deception, a free option that cannot be selected, or free use withdrawn; U:value_objection 33 (13.04%, CI 9.4–17.8%) object to the price itself or name a free substitute; 30 of the 107 paywall reviews (28.04%; 11.86% of 253) also praise the app; U:would_pay_signal 25 (9.88%) say the price is fair, praise the one-time model, or would pay under a condition; reviewers write the fix themselves — 'If the app was upfront and said in the future, I'd have to pay I would have because I really like the app, but the dishonesty has made me delete the app'; 'if I had been told at the start, I would have paid right away… I do think 600 yen one-time is cheap' (jp, 5★, translated); 'It's not expensive, but it's pretty shady and dishonest to spring this on your users'; 'if it were announced, I think many people would buy it willingly' (jp, translated).", "undisclosed trial; price itself accepted", "blocked-conversion", "trust_breach 42 / 16.60%; value_objection 33 / 13.04%; paywall+praise 30; would_pay 25 / 9.88%", "product-rule", "High-priority", "generalisable", ["10882459680", "11511386286", "13086753669", "12775365144"], "", "a disclosed trial converts the same people the silent one loses")

c(6, "§0.3", "anti-pattern", "The developer acknowledged the problem in writing and the reports continued: on the Japanese listing the developer replied 2024-12-18 (apologised that pricing 'caused misunderstanding', UI to be improved 'in an update') and 2025-02-10 (apologised the pay-after-free-period mechanism is 'hard to understand', considering showing which features are paid before paying) [external]; after 2025-02-10, 15 of 139 reviews still report non-disclosure and 37 of 139 still describe the trial wall, the latest titled 'Secretly paid app' (2026-08-04); DEV_PROMISE_UNKEPT 3 (1.19%) name the gap — 'tells other reviews it will improve, then does nothing' (jp, translated); the same developer's other habit app (Habit Check Calendar, app 74 in this repository) shows the same pattern — one-time Premium, trial not mentioned in the listing, trial grievances in 23.84% of its reviews — with the wall reported about a year earlier here (2024-01-06 vs 2025-01-04).", "public apology without the fix", "complaint", "post-2025-02-10 UNDISCLOSED 15 of 139; TRIAL_WALL 37 of 139; DEV_PROMISE_UNKEPT 3 / 1.19%; sibling app 23.84%", "dont", "Meaningful", "generalisable", ["14385347572", "13293180955", "13864528351", "12775365144"], "an unkept written promise becomes its own complaint code", "")

c(7, "§0.4", "must-never-break", "Paid users mostly praise the product and half of them hit a problem: PAID_EXPLICIT 31 (12.25%, CI 8.8–16.9%, mean 3.48★); 15 of 31 (48.4%) report a post-purchase problem — purchase not recognised after a device change or reinstall (DEF_RESTORE_PURCHASE 9, all paid), records lost (DEF_DATA_LOSS 5 of 6), ads after paying (2), a refund request (1), a disputed card charge (1); the failure point is the device change — 'I have the premium version but had to change devices… it's asking me to pay again' (br, translated); 'i took the premium version of the app for 1 reason: so they store my data and i don't loose it, i changed my phone and lost evrything'; not reported in 2026 (last restore failure 2025-04-29, last data loss 2025-09-04; U:paid_problem 0 of 69 in 2026) while the listing now advertises backup and restore 'even across different devices' — whether that fixed it is not established; what buyers value is simplicity and the one-time price ('it's a one-time purchase, so I bought the paid version'; title 'worth paying for', jp, translated).", "no account; purchase and records tied to the device", "churn", "PAID 31 / 12.25% / 3.48★; paid_problem 15 of 31 (48.4%); RESTORE 9; DATA_LOSS 5 of 6; 2026 paid_problem 0 of 69", "must-never-break", "High-priority", "generalisable", ["10789194783", "11804387968", "10498260582", "14195716095"], "", "")

c(8, "§0.5", "feature", "What people value is a calendar they can tick in one tap: U:simplicity 81 (32.02%, CI 26.6–38.0%, mean 4.42★) — PRAISE_SIMPLE 54, PRAISE_EASE 49, PRAISE_ONE_TAP 7; PRAISE_NEED_FIT 31 (12.25%) 'exactly what I needed'; U:calendar_core 25 (9.88%, mean 4.72★) — one-tap checking, one calendar per habit, the month at a glance, editing past days; U:use_case_any 32 (12.65%) — fitness 18, health and medication 14, other 4; the developer's site says the app began as a way to remember medication; 'typical apps often need at least 2 taps to record… in this app, tapping the date on the calendar completes the record… it became stress-free' (jp, translated); 'I wanted a basic calendar with yes or no to track gym attendance this does exactly what I wanted'; the simplicity that earns the praise is also the paywall's biggest obstacle — PAY_NOT_WORTH 28 say an app this basic should not cost money: 'Not paying any amount of money to put check marks on a calendar'; 'who pays for a calendar?' (jp, translated).", "one tap on the calendar date completes the record", "praise", "simplicity 81 / 32.02% / 4.42★; NEED_FIT 31; calendar_core 25 / 4.72★; use_case 32; NOT_WORTH 28", "must-have", "High-priority", "generalisable", ["11171003334", "13635728301", "11478965968", "13981173021"], "the simpler the product looks, the harder any price is to justify", "")

c(9, "§0.6", "must-never-break", "Product problems outside the paywall are few and most concern the record itself: U:defect_non_payment 14 (5.53%), 9 in Japan; U:record_integrity 20 (7.91%, mean 2.60★) — checks not counted in totals (2), checks vanishing (1), notes failing to save (2), date not rolling over (1), records lost on a device change (6), records locked after the trial (8); REPORT_ALL_MARKS_COUNTED 4 (1.58%) — reports count a ❌ day as done ('I went to the gym 5 times this week… But I will also put 2 times the x… when I see the report, it shows 7 counts'); requests are small and mostly already shipped — U:request_any 39 (15.42%); widgets (REQ_WIDGET 5) and notifications (REQ_NOTIFICATIONS 5) are both in today's listing, no request for either dated after 2025-08-23.", "reports count every mark type as done", "complaint", "defect_non_payment 14 / 5.53%; record_integrity 20 / 7.91% / 2.60★; ALL_MARKS_COUNTED 4; request_any 39", "must-never-break", "High-priority", "generalisable", ["12787415461"], "", "")

c(10, "§0.7", "data-caveat", "What is absent across 253 reviews (multilingual patterns, every hit read): no crash or freeze report; no Face ID, accessibility, battery, streak, Apple Health or Family Sharing mention; not one review praises a widget although widgets are in the listing and five reviewers asked for them; no notification failure — all six notification hits are requests or the paywall notice.", "n/a", "mixed", "crash 0; streak 0; widget praise 0; notification failure 0", "none", "Weak", "generalisable", ["8267086303", "8670254714"], "", "")

c(11, "§2.3 table (verbatim); §2.3", "monetization", "Free / paid / trial / unclear (verbatim): " + table("## 2.3 Free / paid / trial", 0) + " — Premium is a one-time purchase ($4.99 / ¥780 now, $3.99 in archives, 600円 quoted through 2026-03 then '600円… 今は800円' in 2026-05, PAY_PRICE_NAMED 20); checking days after the free period is trial-gated and undisclosed, durations named as 7 days, 4 days, two weeks or a month; reading one's own records after the trial blocked per 8 reviewers, with one saying an update made old records visible again (2025-01-15) and another still unable to see notes (2026-03-19) — unclear; free use with ads unclear (offered but not selectable; used with a top banner; 'useless without premium'); before 2024 two calendars free and a third paid (PAY_CALENDAR_LIMIT 3) and dark mode moved to paid in 2022 (PAY_FEATURE_REVERSAL 7); no subscription exists though 5 reviewers believe one does (PAY_SUBSCRIPTION_BELIEF) and the developer replied that Premium 'is a one-time payment, not a monthly fee'; Android free per 2 reviewers (PLATFORM_PRICE_GAP 2).", "one SKU; trial length inconsistent (4 days to a month)", "mixed", "PRICE_NAMED 20; TRIAL_WALL 73; DATA_LOCKED 8; FREE_TIER_OK 3; FREE_OPTION_BLOCKED 2; CALENDAR_LIMIT 3; FEATURE_REVERSAL 7; SUBSCRIPTION_BELIEF 5; PLATFORM_PRICE_GAP 2", "none", "table", "generalisable", ["11298738611", "13864708147", "13353478605", "13617077608", "10815980713", "12645311783", "13027614714", "12186143823", "13864528351", "11511386286", "11784032175", "14112073954", "14218270943", "10381711732", "10842810215", "8746219852", "13584852727", "13689050772"], "", "")

c(12, "§2.4 table (verbatim); §2.4", "contradiction", "Data and privacy statements (verbatim): " + table("## 2.4 Data and privacy statements", 0) + " — 'stored only on your device' sits awkwardly beside a backup that restores across devices and a privacy label declaring tracking diagnostics, and a policy that says edited information is sent to an analysis service; one reviewer raises it (PRIV_CLOUD_CONCERN, 4★): 'the description mentions security being top priority and that data is not sent to third parties Yet the backup/restore option uses the privacy-invading cloud'; nobody else mentions privacy.", "local-only claim vs cross-device backup and tracking label", "mixed", "PRIV_CLOUD_CONCERN 1 / 0.40%", "none", "Weak", "generalisable", ["11449760821"], "", "")

save("w")
