# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/82")
from _lib import c, table, save

c(1, "header lines 1-6; §2.1; §2.1 table (verbatim); §2.2 table (verbatim); §2.2", "positioning", "Lasting Change: Habit Builder (App Store ID 6456888481, com.thelastingchange.app) by MEDICAL SCORE UAB ('Medical Score', Lithuania), released 2023-08-18, current 2.4.2 (2026-08-21, notes 'Minor Bug Fixes'), English only, Health & Fitness, US public 4.1★ from 446 ratings, listed Free with no In-App Purchases — a three-part bundle: a personalised printed/digital book ordered from a website after a questionnaire (the thing people set out to buy), a companion habit / mental-wellness app (habit tracking, mood and stress check-ins, reminders, guided audio, meditations, lessons, challenges, sleep and nutrition logs), and a recurring subscription to the app billed off-store; the description never mentions the book. Feature inventory (verbatim): " + table("## 2.1 What the product is", 0) + " || listing (verbatim): " + table("## 2.2 What the store listing says", 0), "book-funnel bundle; off-store subscription; no free tier", "complaint", "175 reviews, 26 storefronts, 2023-09-02 → 2026-08-17 (1080 days), mean 1.880★; 96 codes / 16 families; 925 assignments", "none", "header", "app-specific", ["10326285569", "12822274987"], "", "the app is the billing vehicle for a book purchase")

c(2, "How to read this; Ten warnings 2, 3, 6, 7, 9; §1.1 table (verbatim); §1.2 table (verbatim); §1.3 table (verbatim); §1.4; §1.5 table (verbatim); §1.6", "data-caveat", "Method and limits: every one of 175 reviews read in date order in the original language (17 non-English: es 8, de 4, fr 2, pl, nl, it), 96 hand codes all used, 925 assignments, 43 checks (21 re-derive codes from text; five real errors caught), 21 absence tests; no duplicates, no repeat authors, 5 edited; only the US (75) reaches 50; no version history could be retrieved so eras are calendar thirds and nothing is attributed to a release; nothing is a conversion, churn or refund rate (people who were charged and noticed are exactly the people who write); allegations reported as allegations ('scam' counted as a word, not adjudicated); the positive base is thin (35 at 4–5★, 14 under 60 chars, 8 non-English one-liners); one review is 0.57% so Wilson CIs accompany every headline. Signal bands (verbatim): " + table("## 1.5 Signal thresholds", 0), "n/a", "mixed", "175/175 read; 96 codes; 43 checks; 21 absence tests", "none", "method", "generalisable", ["10326285569"], "", "")

c(3, "Warning 1; §1.3 selection bias table (verbatim); §0.7; §0.7 table (verbatim); §8.8", "data-caveat", "The public 4.1★ and the corpus 1.88★ describe the same app: corpus mean 1.880★ vs ratings-weighted public 3.838★ across the same 26 storefronts (848 ratings) — a 1.958-star gap, far larger than in comparable corpora; the text corpus is 20.64% of the base, 673 raters left no text (verbatim): " + table("### Selection bias, quantified", 0) + " || " + table("## 0.7 The public 4.1", 0) + " — US 75 reviews at 2.00★ vs 446 ratings at 4.10★; UK 23 at 1.09★ vs 93 at 3.27★; two readings, not chosen between: text-writers are a negatively selected minority, or star-only ratings are being collected in a context text reviews are not; 'the App Store's headline 4.1★ does not reflect the content of the reviews underneath it'; §8.8 research question.", "n/a", "mixed", "gap +1.958★; 848 ratings vs 175 text; US 4.10 vs 2.00; UK 3.27 vs 1.09", "research", "High-priority", "generalisable", ["10326285569"], "", "a star-only rating stream can sit two stars above what the written reviews say")

c(4, "§0.1; §0.1 metadata block; §0.1 table (verbatim)", "timeline", "The finding that reframes everything: this subscription is not sold through Apple — the listing's offer metadata reads hasInAppPurchases: false, hasExternalPurchases: false, isFree: true (all five sibling apps by the same developer carry true), yet the description says 'Payment is charged to your App Store account'; the corpus says which is true — a reviewer quotes the seller's own terms: 'subscriptions will not appear on apple or google if purchased through the website'; 13 (7.43%, CI 4.4–12.3%) independently report the subscription does not appear in Apple subscriptions, 4 more that it is website-only (verbatim): " + table("## 0.1 The finding that reframes", 0) + " — consequences: it cannot be cancelled in iOS Settings (CANCEL_NO_PATH 27, 15.43%); Apple cannot refund it (36 refused, zero Apple refunds); it does not appear in an auditable purchase history (17 discovered the charge from a bank statement); it is invisible to the App Store's review context where the app shows 4.1★.", "subscription billed via the developer's website, outside Apple", "1★-burst", "RAIL_NOT_IN_APPLE 13 / 7.43% / 1.15★; RAIL_WEB_ONLY 4; RAIL_CARD_DIRECT 27 / 15.43% / 1.15★; RAIL_BLOCKED_CARD 7 / 4.00%", "product-rule", "High-priority", "generalisable", ["12822274987", "12320369125", "11162929567", "13649792129"], "", "")

c(5, "§0.2; §2.1 (bundle)", "anti-pattern", "The product that gets sold is a book; the app is what gets billed: BILL_TIED_TO_BOOK 43 (24.57%, CI 18.8–31.5%, mean 1.05★) — a subscription attached to a book or journal purchase, the largest non-rhetorical code: 'I had only intended to purchase the Lasting Change book and ended up with a subscription to this app'; 'When purchasing the e-book they add on 3 Months subscription to the app without being too clear about it'; 'Had I known I would have to have the app, I would not have purchased the book'; 'I purchased the book for $50.99 which was fine. Along with that purchase is an undisclosed subscription that is $30.99'; 'a $131 purchase has turned into an ongoing financial commitment of $55 per month'; BOOK_IS_THE_PRODUCT 13 (7.43%); the book itself is not the complaint — BOOK_PRAISE 14 (8.00%) vs BOOK_CRITIC 8: 'Love the book, don't fall for the scam'; 'The book is GREAT. The app and company itself is terrible.'", "app subscription bundled into a book checkout", "1★-burst", "BILL_TIED_TO_BOOK 43 / 24.57% / 1.05★; BOOK_IS_THE_PRODUCT 13; BOOK_PRAISE 14 vs CRITIC 8", "dont", "High-priority", "generalisable", ["10559324757", "11101438874", "12265926193", "12329827913", "14437712673", "10822728831", "12822274987", "13158666353"], "a liked physical product cannot rescue the app that bills for it", "")

c(6, "§0.3; §8.3", "product-rule", "Consent, not price, is the complaint: U:consent_failure 56 (32.00%, CI 25.5–39.2%, mean 1.11★) — the recurring charge was never knowingly agreed to — against PRICE_TOO_HIGH 4 (2.29%); the strongest evidence is an edited 1★ whose author re-ran the checkout to test the company's claim: 'I explicitly unselected the app option because I was interested in the physical book only. Several weeks later, I was charged $30.99… Customer Service… repeatedly lied that the subscription details are set forth during checkout (so I went back and ran through the process again; they are not)… the app is not offered as an opt-in during checkout, you are automatically subscribed to it with a purchase of the physical book… they did add a disclaimer… in response to my email back-and-forth — and then proceeded to lie to me that it had been there all along when I have screenshots' (BILL_DESELECTED 1, a direct test of the seller's position); BILL_FREE_CLAIMED 7 (4.00%): 'Said the app came free… I am getting charged 30.99 a month'; 'offers what appears to be a free month of membership, but they hide the fact that they will begin charging you monthly many months afterward'; 'it costs $30.99 / month after the trial period, which i didnt see mentioned anywhere'.", "auto-subscribed with a book purchase; opt-out not honoured", "1★-burst", "consent_failure 56 / 32.00% / 1.11★; PRICE_TOO_HIGH 4 / 2.29%; BILL_DESELECTED 1; BILL_FREE_CLAIMED 7", "product-rule", "High-priority", "generalisable", ["13710163306", "12320369125", "13711624416", "13738145254", "13535238064"], "", "")

c(7, "§0.4; §2.2 (support address); §8.1", "must-have", "The App Store listing prints a support address at a domain that does not exist: 'contact us at hello@lastingchange.app' — nslookup NXDOMAIN, no MX, curl cannot resolve; the working domain is thelastingchange.com and the same listing page links its Developer Website and Privacy Policy buttons there; the real support addresses (help@ / hello@thelastingchange.com) are printed nowhere in the listing; a reviewer hit it: 'I tried to email hello@ and was told this was invalid despite it being given my your information' (gb 1★, 2024-06); email is the only cancellation route the corpus describes (CANCEL_EMAIL_ONLY 12, 6.86%; zero describe a working in-app cancel control) — 'a cancellation path that runs exclusively through a support address, published at a non-existent domain, is a structural failure'; the counter-example: the one unambiguously satisfied paying customer used the working address — 'I contacted help@ in order to cancel my subscription… got a friendly reply, confirming the cancellation within a quarter of an hour' (ch 5★).", "support address dead; email-only cancellation", "blocked-conversion", "CANCEL_EMAIL_ONLY 12 / 6.86%; dead-domain hit 1; working-address cancel 1 (15 min)", "must-have", "High-priority", "generalisable", ["11375486586", "11605113507"], "", "")

c(8, "§0.5; §0.5 table (verbatim); §3.3; §8.5", "must-never-break", "What happens to people who try to stop paying (verbatim): " + table("## 0.5 What happens to people", 0) + " — three successful cancellations and one successful refund against 36 refusals and 12 charges that continued after cancelling; 5 charged after deleting the account/app; 7 had to block the card or close the account; 16 (9.14%) escalated to a chargeback, FTC, FCC, BBB, trading standards or a class action; 'the corpus contains a detailed, repeated, cross-storefront account of a cancellation path that does not reliably terminate billing'.", "cancellation does not reliably stop billing; refunds refused citing T&Cs", "1★-burst", "refused refund 36 / 20.57%; charged after cancelling 12 / 6.86%; escalated 16 / 9.14%; cancel honoured 3; refund obtained 1", "must-never-break", "High-priority", "generalisable", ["10644767233", "11095665755", "10984508995", "11149347868", "11736211586", "11162929567", "10326285569", "11605113507", "12822274987", "13630518203", "11445847376"], "", "")

c(9, "§0.6; §0.6 table (verbatim); §3.6", "insight", "The app itself is a small part of the story but not blameless (verbatim): " + table("## 0.6 The app itself", 0) + " — 83 (47.43%) report money harm and never evaluate the product; APP_UNUSED 14 (8.00%) never used, activated or downloaded the app they were billed for; where judged: too much work (APP_COMPLEX 10, 5.71%), too thin for the money (APP_SHALLOW 13, 7.43%; APP_NO_VALUE_FOR_PRICE 14, 8.00%), unattractive (APP_UGLY 9, 5.14%); the one reliability theme is login — DEF_LOGIN 14 (8.00%), present in the very first review 15 days after release: 'I still can't log in, or reset my password, support is incredibly hard to find, didn't get back to me until I requested refund via PayPal'.", "subscription-gated app; login failures", "complaint", "money_harm 115 / 65.71% / 1.13★; app_quality_neg 46 / 26.29%; app-only complaints 14 / 8.00%; defect_any 19 / 10.86%; praise_any 34 / 19.43% / 4.65★; APP_UNUSED 14; DEF_LOGIN 14", "must-never-break", "High-priority", "generalisable", ["10326285569", "10481123302", "12810825147"], "", "")

c(10, "§0.8; §9.F reference", "data-caveat", "Six things the corpus proves are absent (20 of 21 claims tested absent): no review describes a working in-app cancel control in 1080 days; no review describes Apple refunding anything; no review mentions a free tier or free-habit limit; no review reports a price increase (the two regimes are different billing periods); no review mentions the app crashing or freezing — the reliability complaint is login and account state; no review mentions ads, battery, accessibility, iPad, widgets, Siri, dark mode, export, Family Sharing or Android — read as evidence that almost nobody used the app long enough to form a view of it.", "n/a", "mixed", "20 of 21 absent", "none", "absence test", "generalisable", ["10326285569"], "", "")

c(11, "§2.3 table (verbatim); §2.7", "monetization", "Free / paid / trial / unclear (verbatim): " + table("## 2.3 Free / paid / trial", 0) + " — the last two rows (billed off-store to card/PayPal/bank; cancelled by email only) are the most consequential and neither is disclosed on the listing; a lifetime purchase exists (£74.69) and all three reviews mentioning it are complaints about being charged for one unintentionally; cannot be established: any SKU list price, whether a trial exists and its length, what the checkout displays, whether the two billing regimes co-existed (dates overlap, consistent with both running concurrently), any conversion/renewal/refund/churn rate.", "no free tier; monthly ~$30.99; quarterly ~$42–56; annual; lifetime £74.69; off-store; email cancel", "blocked-conversion", "monthly 20 reviews; quarterly 9; annual 4; lifetime 3 (all accidental)", "undecided", "table", "app-specific", ["12542916281", "10372163041", "13599501333"], "", "")

c(12, "§2.4; §2.4 table (verbatim); §8.1", "dont", "The listing has a pricing section with no prices — verbatim the entire monetisation disclosure: 'SUBSCRIPTION PRICING & TERMS — Lasting Change offers flexible auto-renewing plans. PAYMENT & RENEWAL — You can download and use the app for free. Continued access to all features requires a subscription. Payment is charged to your App Store account… You can manage or cancel your subscription anytime in account settings.' Four checkable defects, each corroborated (verbatim): " + table("## 2.4 The listing has a pricing", 0) + " — a reviewer in February 2025 ('App does not show there is a payment plan anywhere in description') independently identified the defect this report found from page metadata nineteen months later.", "pricing heading with no amount, period, trial or SKU; wrong rail; wrong cancel path; dead address", "blocked-conversion", "4 listing defects; CANCEL_NO_PATH 27; RAIL_NOT_IN_APPLE 13", "dont", "High-priority", "generalisable", ["12320369125", "12822274987", "11375486586"], "", "")

c(13, "§2.5; Warning 10; §8.4", "must-never-break", "The developer sells six apps and the charge does not always say 'Lasting Change': BILL_UNKNOWN_DESCRIPTOR 5 (2.86%, 1.40★) — 'I was charged by Effecto and had to google search their customer support email to figure out why'; 'it isn't charged under Lasting Change — you'll get charged by medical score or Effecto App'; a Lasting Change review titled 'Walking Yoga a scam'; 'I checked Direct debits, apple subscriptions etc but nothing matched'; 'impossible to find until I had to call the bank'; a reconciliation failure — a buyer who wants to stop a charge must first identify it, and five report failing at that step; attribution caveat: some reviews may describe charges from a sibling product's funnel; one reviewer identified the corporate entity unaided ('this Lithuanian-based company'; UAB = Lithuanian private limited company).", "billing descriptor shows a sibling app or the corporate name", "1★-burst", "BILL_UNKNOWN_DESCRIPTOR 5 / 2.86% / 1.40★", "must-never-break", "Meaningful", "generalisable", ["11025658129", "13630518203", "13688126203", "12822274987", "12865205440", "13711624416"], "", "")

c(14, "§2.6; §2.6 Regime A table (verbatim); §2.6 Regime B table (verbatim); §2.6 bundle table (verbatim); Warning 5", "monetization", "Price evidence — the corpus is the only record (PRICE_STATED 40, 22.86%); two billing regimes that are different periods, not a rise — Regime A quarterly ~$42–56 dominant 2024–early 2025 (verbatim): " + table("## 2.6 Price evidence", 0) + " || Regime B monthly $30.99, the single most-repeated figure, from February 2025 (verbatim): " + table("## 2.6 Price evidence", 1) + " || bundle and one-off amounts (verbatim): " + table("## 2.6 Price evidence", 2) + " — book $25 (called worth it) / $50.99 / £60 (never arrived) / £62.99; lifetime upsell £74.69; journal $131 + $55/month; accumulated totals $106, $100, $200, €120.", "monthly $30.99; quarterly $42–56; book $25–£63; lifetime £74.69", "complaint", "PRICE_STATED 40 / 22.86%; monthly $30.99 ×8+6; quarterly 8", "none", "table", "app-specific", ["10912613365", "10953424710", "12329827913", "12865205440", "13535238064", "11811397305", "13599501333", "14437712673"], "", "")

c(15, "§2.6 (checkout account); §8.3", "anti-pattern", "An upsell page where a standalone price is positioned so it reads as an upgrade delta: 'I intended to purchase only a book for £62.99. After clicking pay, I was taken to another page that suggested adding a lifelong subscription priced at £74.69. The way this was presented made it appear as though this amount was simply the difference between the original price and the higher total — not an additional £74.69 charge. There was no clear price breakdown… no explicit confirmation step showing the full amount being charged… I only realised what had happened after receiving two separate receipt emails' (gb 1★); BILL_CHECKOUT_TRICK 5: 'Chose the cheapest option and they charged me for a lifetime app which was not even an option'; 'I accidentally pressed one wrong button and got immediately charged a further £80'; ordered twice in 30 minutes via PayPal and charged for '2 books and 2 annual app subscriptions'; 'automatically tried to charge me for speeding service, something I never selected'.", "post-pay upsell page without a full-amount confirmation", "1★-burst", "BILL_CHECKOUT_TRICK 5 / 2.86%; lifetime £74.69 / £80 accidental", "dont", "Meaningful", "generalisable", ["13599501333", "10416143678", "11472417650", "10909508179", "11445847376"], "", "")

save("w")
