# -*- coding: utf-8 -*-
"""Stage 3 merge for report 82 (Lasting Change: Habit Builder, MEDICAL SCORE UAB)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C299", "product-rule", "Never attach an app subscription to another product's checkout by default — the subscription is its own opt-in line with its own amount, period, renewal date and final-total confirmation, and a 'book only' choice must never produce a recurring charge",
    "Report 82 (Lasting Change, 175 reviews, mean 1.88★): the product people set out to buy is a personalised book from the developer's website; the app subscription arrives attached to that purchase — BILL_TIED_TO_BOOK 43 (24.57%, mean 1.05★), the largest non-rhetorical code ('I had only intended to purchase the Lasting Change book and ended up with a subscription to this app'; 'I purchased the book for $50.99 which was fine. Along with that purchase is an undisclosed subscription that is $30.99'; 'a $131 purchase has turned into an ongoing financial commitment of $55 per month'); U:consent_failure 56 (32.00%, 1.11★) and BILL_NO_CONSENT 36 with a perfect 1.00★ mean; one reviewer explicitly unselected the app at checkout, was billed anyway, re-ran the checkout to test the seller's claim and found no opt-in ('you are automatically subscribed to it with a purchase of the physical book'); a post-pay upsell page positioned a £74.69 lifetime price so it read as an upgrade delta with 'no explicit confirmation step showing the full amount'; the bundle is priced below the book alone so the subscription is effectively forced; 'Not one review in 175 describes choosing to subscribe to this app because of something the app does.' The book itself is liked (BOOK_PRAISE 14 vs BOOK_CRITIC 8: 'Love the book, don't fall for the scam') — a liked physical product cannot rescue the app that bills for it. §8.3: separate lines, subscription default off, full total before charging, recurring terms in the confirmation email. Related: [[C285]] (a paid add-on is never bought on a single tap), [[C210]] (bill App Store users through the App Store), [[C111]] (show the price up front), [[C283]] (never sell by manipulation).")

add("C300", "research", "A headline star rating that sits far above its own written reviews is a signal to audit, not a satisfaction figure — find where and when star-only ratings are collected before trusting them",
    "Report 82 (Lasting Change): the text corpus averages 1.880★ while the ratings-weighted public mean across the same 26 storefronts is 3.838★ (848 ratings, 673 star-only) — a 1.958-star gap, and more than two full stars in every one of the four high-volume storefronts (us 2.00 vs 4.10, gb 1.09 vs 3.27, ca 1.31 vs 3.72, au 1.29 vs 3.55); 72.00% of text reviews are one-star, at least one 5★ is a fraud warning, and the public 4.1★ 'does not reflect the content of the reviews underneath it'; two readings the report does not choose between — text-writers are a negatively selected minority, or star-only ratings are collected in a context text reviews are not — and §8.8 asks where in the lifecycle and from whom the stars are gathered. In ordinary corpora the gap is a few tenths (report 79: +0.18; report 77: +0.27; report 76: up to +0.38 per storefront); a two-star gap across every major market is the signature of a rating stream and a review stream describing different populations. Related: [[C231]] (written reviews are a complaint channel — audit the funnel), [[C094]] (ask for reviews well), [[C076]] (never seed the launch rating).")

ext("C210", " Report 82 (Lasting Change): the subscription is sold on the developer's website and charged to card / PayPal / bank — the listing's own metadata reads hasInAppPurchases: false while its description says 'Payment is charged to your App Store account'; a reviewer quotes the seller's terms: 'subscriptions will not appear on apple or google if purchased through the website'; consequences — it cannot be cancelled in iOS Settings (CANCEL_NO_PATH 27, 15.43%), Apple cannot refund it (36 refusals, zero Apple refunds), 17 discovered the charge from a bank statement, 7 blocked their card or closed the account, 16 escalated to a chargeback, FTC, FCC, BBB or trading standards; 'Apple thankfully denied all three of their attempts'.")
ext("C112", " Report 82 (Lasting Change): zero reviews in 1080 days describe a working in-app or web cancel control; CANCEL_NO_PATH 27 (15.43%: 'not… via your App Store account, their website or from within the app itself'), CANCEL_EMAIL_ONLY 12, CANCEL_DARK_PATTERN 2 ('You will forget.'); charged again after cancelling 12, after deleting the account 5 ('They confirmed cancellation and a month later they were charging me again'); cancellation honoured 3 of 175; §8.2 a self-service Cancel control in the account screen and on the web with on-screen and email confirmation — 'the only change that deals with all of the top five 1★ drivers'.")
ext("C287", " Report 82 (Lasting Change): 'I have contacted this company FOUR times to cancel my subscription and not once have they replied' (SUP_NO_REPLY 14, 1.00★); CANCEL_IGNORED 8; where the correct address is found, cancellation is confirmed in fifteen minutes — the failure is routing, not staffing.")
ext("C212", " Report 82 (Lasting Change): REFUND_REFUSED 36 (20.57%, every one 1★), 12 shielded by pointing at the T&Cs or asserting the service was delivered ('no refunds as we delivered the service — which is simply not true'; 'they don't issue out refunds unless it's their fault directly'); several asked for a refund on the same day as the charge and were refused; one refund obtained 'after insisting' — and that reviewer was then charged 50€ months later; §8.5 experiment: refund any charge disputed shortly after renewal or after a documented cancellation, and measure the 1★ rate — 'the current policy produces the most-repeated public warning'.")
ext("C036", " Report 82 (Lasting Change): the App Store listing prints a support address at a domain that does not exist — hello@lastingchange.app returns NXDOMAIN with no MX record, while the same page links the working domain thelastingchange.com; a reviewer hit it ('I tried to email hello@ and was told this was invalid'); email is the only cancellation route, so a dead address is a structural failure; the one satisfied payer used the working help@ address and was confirmed within a quarter of an hour; SUP_UNFINDABLE 5, SUP_CANNED 8 ('Your feedback has been taken into consideration…'), SUP_RESPONSE_FACADE 4.")
ext("C221", " Report 82 (Lasting Change): BILL_NO_NOTICE 11 ('I do not even have an email stating this would occur'), BILL_SURPRISE_CHARGE 17 discovered from a bank statement ('if it wasn't for my bank I probably never would have known'); BILL_UNKNOWN_DESCRIPTOR 5 — the card descriptor reads a sibling app (Effecto, Walking Yoga) or the legal entity (Medical Score), so buyers 'had to google search their customer support email to figure out why I was being charged' or call the bank; §8.4 a pre-renewal email naming product, amount and a one-click cancel link, and a descriptor that reads the app's name; the order confirmation email must carry the recurring terms — 'It's such a small change to your email template'.")
ext("C077", " Report 82 (Lasting Change): DEF_LOGIN 14 (8.00%, all but one 1★) — people who paid on the web and could not get into the app: 'we recognise your email adress but the account registration is not complete — you took all the fee in öne min'; 'it says my account doesn't exist'; no create-account option on the sign-in screen; 'my email is not even registered. Then why was I even charged'; present in the first review of the corpus (15 days after release) and still in the last year; §8.7 every successful web payment must end in a usable app account linked by the purchase email.")
ext("C249", " Report 82 (Lasting Change): BILL_AFTER_DELETE 5 — 'I deleted my account and the data during my first 3 month subscription but that didn't keep them of billing me through Paypal'; DEF_LOCKOUT 2 — 'the option to delete all personal data locks you out of the app even though you have paid for the 3 months'; §8.2 account deletion must end billing, and deleting data must not lock out a paid period.")
ext("C065", " Report 82 (Lasting Change): U:paid_evidence 125 (71.43%) averages 1.224★ — 116 × 1★, 0 × 4★ — 92.8% of everyone with purchase evidence rated one star; BILL_NO_CONSENT, REFUND_REFUSED, TRUST_ESCALATED and SUP_NO_REPLY occur only in one-star reviews ('a person who is charged without consent and refused a refund gives one star, without exception, in 1080 days across 26 storefronts'); U:trust_collapse 97 (55.43%): TRUST_SCAM_WORD 65 across seven languages, TRUST_WARN_OTHERS 67 — the largest code — written to warn the next buyer.")
ext("C231", " Report 82 (Lasting Change, 175 reviews): corpus 1.880★ vs public 3.838★ — a 1.958★ gap, over two stars in every high-volume storefront ([[C300]]); 72.00% one-star; the Anglophone UK+AU+CA block is the most negative population (mean 1.20★, 94.0% 1★, praise 2%, trust_collapse 84%) with a plausible mechanism — they can read the English listing, T&Cs and warning reviews and have consumer-protection routes they use; 90.9% of the corpus comes from high-spend markets, consistent with a $50–$131 funnel targeting high-ARPU geographies; a rising era mean (1.69 → 2.41) is a measurement artefact — nine of fifteen late positives are under 60 characters while money harm hit its highest share; the developer's home market (Lithuania) is the only storefront perfect on both measures; no rating elasticity ('they are asking for their money back'), no rating recovery, no defence of the company by any user.")
ext("C002", " Report 82 (Lasting Change): the extreme case — the offer is the whole story: U:money_harm 115 (65.71%, 1.13★) vs app-quality complaints 46 (26.29%) and only 14 (8.00%) that criticise the app with no money problem; 83 reviews (47.43%) report money harm and never evaluate the product; APP_UNUSED 14 never opened the app they were billed for; ten reported outcomes against 115 reports of money harm.")
ext("C133", " Report 82 (Lasting Change): consent objections outnumber price objections 56 to 4 (14:1) — PRICE_TOO_HIGH 4 (2.29%) vs U:consent_failure 56 (32.00%); §8.9 do not lower the price; the only clean pricing signal is a 4★ who likes the app and finds it 'too steep… especially for retirees or disabled people'.")
ext("C064", " Report 82 (Lasting Change): ~$30.99/month or ~$42–56/quarter for a companion app, billed off-store — the amount is objected to by 4 of 175 and called fair by 2; the entire objection is consent and structure.")
ext("C111", " Report 82 (Lasting Change): a quiz funnel that never mentions a payment plan (ACQ_QUIZ_FUNNEL 2: 'No where during the process does it mention payment plan'), descending-price urgency (ACQ_PRESSURE 4: 'they continually advertise and offer at lower and lower prices until you bite'; 'fake questions, artificial delays, pseudo customization, pseudo last time offers'), and a listing whose 'SUBSCRIPTION PRICING & TERMS' heading contains no price, period, trial length or SKU ('App does not show there is a payment plan anywhere in description').")
ext("C218", " Report 82 (Lasting Change): the listing states four checkable falsehoods — a payment rail it does not use ('charged to your App Store account' while hasInAppPurchases is false), a cancel path that does not exist ('manage or cancel anytime in account settings' vs 27 CANCEL_NO_PATH), a pricing heading with no prices, and a support address at a non-existent domain; it never mentions the book that 43 reviewers actually bought; §8.1 repair the listing is 'the cheapest item… with the most direct evidence'.")
ext("C236", " Report 82 (Lasting Change): BILL_UNDISCLOSED 26 (14.86%) — disclosed only in the T&Cs: 'Why can't you write it loud and clear in the sales order and not hide it in the T&C fine print if you are transparent'; 'hidden in the small print rather than being clearly and prominently disclosed'; BILL_FREE_CLAIMED 7 — presented as free or a trial ('Said the app came free… I am getting charged 30.99 a month'; '$30.99 / month after the trial period, which i didnt see mentioned anywhere'); REQ_DISCLOSURE 4, all from people harmed.")
ext("C283", " Report 82 (Lasting Change): 'fake questions, artificial delays, pseudo customization, pseudo last time offers' — the quiz feeds a 'personalised' book of which 'all they customize is the name on the cover… Pure psycho trick to make you feel invested' (BOOK_PERSONALISATION_FAKE 2); 'put a LC book in your cart and see how low they will reduce the price if you don't buy right away'.")
ext("C180", " Report 82 (Lasting Change): descending-price urgency in the web funnel — ACQ_PRESSURE 4 ('offer at lower and lower prices until you bite'; 'pseudo last time offers').")
ext("C285", " Report 82 (Lasting Change): BILL_CHECKOUT_TRICK 5 — a post-pay upsell page where a standalone £74.69 lifetime price 'made it appear as though this amount was simply the difference between the original price and the higher total… no explicit confirmation step showing the full amount being charged… I only realised after receiving two separate receipt emails'; 'I accidentally pressed one wrong button and got immediately charged a further £80'; 'Chose the cheapest option and they charged me for a lifetime app which was not even an option'; 'automatically tried to charge me for speeding service, something I never selected'; all three lifetime-purchase mentions in the corpus are complaints about being charged for one unintentionally.")
ext("C281", " Report 82 (Lasting Change): acquisition via Instagram ads and paid influencers (ACQ_SOCIAL_AD 3, ACQ_INFLUENCER 1: 'Had instagram adverts for this app so I presumed it was safe'; 'ich werde nie wieder auf entsprechende Angebote auf Instagram & co. hereinfallen') into a checkout that hides the recurring charge — the channel lends trust the checkout then spends.")
ext("C058", " Report 82 (Lasting Change): the funnel is Instagram → quiz → personalised-book checkout with a forced app bundle; every documented path to payment runs through the book, none through the app; U:acquisition_any 12 (6.86%, 1.33★).")
ext("C189", " Report 82 (Lasting Change): public developer replies on reviews are read as PR — SUP_RESPONSE_FACADE 4: 'The responses on each of these reviews from the company is a facade, and for public appeal only… I have no doubt you will paste it below to seem as though you care'; 'Addendum to developer response: they're full of it… they've ignored my emails'; four reviewers who received a reply edited their review, all hostile, none more positive; the one documented remediation (a disclaimer added beneath the terms consent after an email exchange) came with a denial that it was ever missing, contradicted by the reviewer's screenshots.")
ext("C247", " Report 82 (Lasting Change): a six-app developer whose charges arrive under a sibling app's name — 'I was charged by Effecto'; 'you'll get charged by medical score or Effecto App'; a Lasting Change review titled 'Walking Yoga a scam' — a reconciliation failure and an attribution problem: some reviews on this listing may describe a sibling product's checkout.")
ext("C060", " Report 82 (Lasting Change): the counter-case — six sibling apps under one seller share a billing entity, and a charge that shows a sibling's name spends the family's trust: 'Walking Yoga a scam' in a review of a different app.")
ext("C286", " Report 82 (Lasting Change): an English-only app and English-only T&Cs sold into at least six language markets — 17 non-English reviews (es 8, de 4, fr 2, pl, nl, it) and six of them report being charged without understanding they had agreed to anything ('yo no he autorizado ningún cobro'; 'Abofalle'); 'a disclosure problem before it is a localisation problem'; the German book translation 'hat eine KI besorgt'.")
ext("C267", " Report 82 (Lasting Change): the German edition of the paid 'personalised' book reads as machine-translated — 'Die Übersetzung aus dem Englischen hat eine KI besorgt' — and 'all they customize is the name on the cover'.")
ext("C147", " Report 82 (Lasting Change): no free tier exists in the corpus (zero mentions of a free tier or habit limit); 'Continued access to all features requires a subscription'; APP_UNUSED 14 were billed for an app they never opened; the only deliberate buyer converted 'just in case' on fear of a later price, 'not on value', then preferred a paper bullet journal.")
ext("C182", " Report 82 (Lasting Change): a subscription-gated app whose purchase happens on a website before the app is ever opened — 'Not one review in 175 describes choosing to subscribe to this app because of something the app does'; 14 reviewers never used, activated or downloaded it.")
ext("C268", " Report 82 (Lasting Change): APP_COMPLEX 10 (5.71%, all US) — 'so overwhelming how much information it gives you to fill in yourself… it would be great to have the app break it down throughout the day and ask you questions… i definitely suffer from choice paralysis'; 'I don't need a full blown psych ward evaluation every single day'; 'Too many questions'; §8.6 a guided time-of-day check-in flow vs the current logging screen, measured on 7-day retention — 'fewer inputs, not more features'.")
ext("C214", " Report 82 (Lasting Change): APP_SHALLOW 13 and APP_NO_VALUE_FOR_PRICE 14 at ~$30.99/month — the recurring comparison is paper: 'Nothing you couldn't do yourself with a piece of paper and pen'; 'You can use a paper checklist for the same results'; 'the to-do lists I make on my notes are better than this app'; 'the app itself is well designed, but it's basically a glorified tracker and not at all worth the monthly cost' (2★).")
ext("C006", " Report 82 (Lasting Change): the counter-case of a data-hungry tracker — daily long-form self-assessment ('a full blown psych ward evaluation every single day') drives APP_COMPLEX 10 and OUT_ABANDONED 5 within days; the two threads in the only pure product feedback both argue for fewer inputs.")
ext("C203", " Report 82 (Lasting Change): 'The ads made it seem like you could track whatever habits you wanted, but you in fact can not add your own habits to the daily activities' (APP_NOT_AS_ADVERTISED 3; REQ_OWN_HABITS 1) — while four other reviewers praise custom trackers, so the capability is either gated or undiscoverable.")
ext("C148", " Report 82 (Lasting Change): APP_NOT_AS_ADVERTISED 3 — the ads showed free-form habit tracking the app does not deliver; 'Won't let me post photos or upload a profile picture'; notes and photos 'give me an unsupported notification'; 'Experiments don't work and reset daily'.")
ext("C185", " Report 82 (Lasting Change): APP_UGLY 9 ('Very old and simple tracking app design'; 'Very weridly design app, very messy') alongside 'the app itself is well designed' — craft is contested and irrelevant next to consent.")
ext("C209", " Report 82 (Lasting Change): the web purchase and the app account are two systems that disagree about who the customer is (DEF_LOGIN 14) — an account is required and it is the reliability failure.")
ext("C035", " Report 82 (Lasting Change): the account system is the product's one reliability defect class — DEF_LOGIN 14 (8.00%), no crash reports at all; a paid web account must be linked to the app login by the purchase email with creation and recovery paths on the sign-in screen.")
ext("C031", " Report 82 (Lasting Change): zero crash or freeze reports in 175 reviews — the reliability complaint is login and account state; §8.9 do not prioritise stability work.")
ext("C025", " Report 82 (Lasting Change): 'The only drawback is the price, especially for retirees or disabled people. It is just too steep' (4★) — the one accessibility-framed price objection.")
ext("C103", " Report 82 (Lasting Change): a mental-wellness-framed product (mood and stress check-ins, meditations, 'Contains Health or Wellness Topics', 'Data Linked to You: Health & Fitness') whose users report sobriety and productivity outcomes (OUT_WELLBEING 7 at 4.71★; 'haven't had alcohol for over 60 days') and whose billing is the most-complained-about in the series; one PRIV_CONCERN.")
ext("C255", " Report 82 (Lasting Change): the app ships English only; 17 reviews (9.71%) are in other languages and the substantive ones are about billing consent, not language — §8.9 do not prioritise localisation.")
ext("C062", " Report 82 (Lasting Change): 90.9% of the corpus originates in 16 high-spend storefronts; the Anglophone UK+AU+CA block is the most negative (1.20★, 94% 1★) and escalates to trading standards, FTC, FCC and BBB; no price differentiation by market — amounts cluster by billing period.")
ext("C089", " Report 82 (Lasting Change): 'you have the option to buy either the personalized book only… or, at a marginally higher [price], the book plus a 3-month-subscription' — a bundle priced so the subscription is effectively forced (ACQ_BOOK_PRICE_GATE 3: 'they hiked the price of the book if you don't buy a subscription'); a 'free month of membership' that 'will begin charging you monthly many months afterward'.")
ext("C109", " Report 82 (Lasting Change): BILL_FREE_CLAIMED 7 (4.00%, 1.57★) — an app presented as free or as a trial that then bills: 'offers what appears to be a free month of membership, but they hide the fact that they will begin charging you monthly many months afterward'; 'I really thought I was going to get a 7 day trial. But, instead it wanted me to pay'; whether a trial exists or its length could not be established from any source.")
ext("C152", " Report 82 (Lasting Change): BILL_NO_NOTICE 11 (1.00★) — no renewal notice before any charge; 17 learned of the charge from their bank.")
ext("C059", " Report 82 (Lasting Change): the counter-example in the series — where a request or fix is visibly acknowledged, reviewers edit upward elsewhere; here all five edited reviews stayed negative or became more so, and the four reviewers who received a public developer reply all edited their review to be more hostile.")
ext("C094", " Report 82 (Lasting Change): the star-only rating stream (673 raters, 3.838★) sits two stars above the written reviews in every major market and includes at least one 5★ that is a fraud warning — where and when stars are being asked for is the open question ([[C300]]).")

M = {
 "R82-001":["C299","C182","C218"], "R82-002":["C231"], "R82-003":["C300","C231","C094"], "R82-004":["C210","C112","C212","C300"], "R82-005":["C299","C089","C182"],
 "R82-006":["C299","C285","C236","C133"], "R82-007":["C036","C112","C218"], "R82-008":["C212","C112","C287","C249","C210"], "R82-009":["C002","C077","C268","C214","C147"], "R82-010":["C031","C147","C112","C212"],
 "R82-011":["C299","C109","C210","C285","C112"], "R82-012":["C218","C111","C236","C036"], "R82-013":["C221","C247","C060"], "R82-014":["C064","C133"], "R82-015":["C285","C299"],
 "R82-016":["C002","C231"], "R82-017":["C299","C236","C221","C112","C152"], "R82-018":["C112","C287","C212","C036","C189"], "R82-019":["C210","C065"], "R82-020":["C065","C231","C189"],
 "R82-021":["C268","C214","C185","C148","C203","C006"], "R82-022":["C077","C249","C035","C209","C031"], "R82-023":["C203","C148","C185"], "R82-024":["C103","C002"], "R82-025":["C111","C283","C180","C281","C058","C089","C267"],
 "R82-026":["C231","C002"], "R82-027":["C065","C231"], "R82-028":["C268","C148","C203"], "R82-029":["C231","C300"], "R82-030":["C231","C300","C189","C059"],
 "R82-031":["C065","C231"], "R82-032":["C299","C182","C147","C089"], "R82-033":["C133","C064","C025"], "R82-034":["C212","C112","C065"], "R82-035":["C231"],
 "R82-036":["C268","C062"], "R82-037":["C062","C231"], "R82-038":["C062"], "R82-039":["C286","C255"], "R82-040":["C300","C231"],
 "R82-041":["C231"], "R82-042":["C299","C002","C147"], "R82-043":["C300","C231"], "R82-044":["C189","C059","C299"], "R82-045":["C218","C036","C210","C111"],
 "R82-046":["C112","C249"], "R82-047":["C299","C285","C221","C236"], "R82-048":["C221","C152","C247"], "R82-049":["C212"], "R82-050":["C268","C214","C006","C203"],
 "R82-051":["C077","C035","C209"], "R82-052":["C133","C031","C255"], "R82-053":["C210","C065","C300"], "R82-054":["C036","C287"], "R82-055":["C231","C300"],
 "R82-056":["C025","C103"],
}
cards = [json.loads(l) for l in open("Tools/prd_ledger/82/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/82/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 82" in x["statement"] and not any(k.startswith("R82-") for k in x["cards"])])
