# Paraphrased gist per cited review index (my wording, not quotes). Used by build_appendix.py.
G = {
240: "Setting habits to a time of day is what sets this app apart.",
380: "Morning / afternoon / evening / all-day split is simple and matches how a day feels.",
1513: "Likes tasks split into morning, afternoon, night because rigid time-blocking does not work for them.",
1614: "Great for morning, afternoon and evening routines; full-screen start prompt is hard to ignore.",
1389: "Has a morning block and an evening block and checks how well each went at day's end.",
3: "Would be better with morning / afternoon / night categories; uses another app for that.",
122: "Wants daily goals divided into morning, day and evening to build routines.",
2176: "Wishes for partitions in the habit list, e.g. morning, noon, evening.",
1912: "Wants separators, e.g. which medicines are taken in the morning vs evening.",
62: "Asks for a small heading bar per part of day inside the All view.",
292: "Wants the default page to be All rather than the morning/afternoon/evening pages.",
295: "View defaults to time of day so all-day habits are not seen; habits disappearing.",
897: "When shown by time of day, unfinished items hide once the next period starts.",
327: "New design shows only the morning part instead of the whole day; paid a lot for this.",
109: "A goal done twice a day cannot be put in two different times of day.",
589: "Would buy if one habit could occur several times a day (teeth AM/PM, meds 3x).",
484: "Likes setting one habit for several times of day (water, spending).",
10: "Only three fixed periods; wants to define more, e.g. 4-hour blocks for shift work.",
73: "Time-period setting forces mornings to start at midnight; night owl needs 9 am.",
556: "Night owl: day rolls over before evening routine is done; wants to set the switch time.",
578: "Cannot change the day's start time; 1 am night routine counts as the next day.",
302: "Only vague morning/afternoon/evening slots, no specific reminder time; worst purchase.",
600: "Does not allow picking a specific time of day for habits.",
584: "Likes vague time-of-day labels but wants to reorder habits within each period.",
946: "Pointless to have morning/night routines if their order cannot be kept.",
552: "Wants routines ordered by time slot or manually reorderable.",
939: "After update every task says 'any time of day'; wants the day parts back or will use Reminders.",
984: "Update removed morning/night/afternoon routines; now only specific times.",
2010: "Cannot divide the day into morning/afternoon/evening or list meds 3x a day; waste of money.",
1078: "Free tier allows two routines; needs weekday/weekend morning and night variants.",
1745: "Routines fit school days but not weekends; wants more than one routine per part of day.",
2304: "Shift nurse: routine modes are a lifesaver, but switching one day switches all following days.",
1664: "Only 4 habits per morning / afternoon / night on free tier.",
921: "Needs the day at a glance; only chunks of time shown; per-chunk limit even with premium.",
1636: "Limits habits to three per time of day unless you pay; pushes premium.",
1658: "Forced to choose a time of day for each habit; does not work for variable schedules.",
571: "Having to pick morning/afternoon/evening is very inconvenient; shift workers exist.",
787: "Cannot turn off the afternoon routine they do not need; gets pointless notifications.",
388: "Changing a habit's time of day warned it would delete all history.",
436: "Changing a habit's time of day creates a new entry and loses history.",
7434: "ADHD user: wants tabs or collapsible categories; one long list is overwhelming.",
6254: "No way to group habits by type; must scroll through big blocks to find one.",
7320: "Seeing everything on one page first thing in the morning is overwhelming; wants categories.",
5479: "Wants goals categorised into folders instead of one big list.",
6748: "Organises habits and tasks into categories and can create new ones.",
7777: "Categorising by life area looks good and reduces clutter (premium user).",
7778: "Uses folders to see morning and night routines at a glance; habit stacking works.",
6012: "Tags let you zoom in with a filter on what is relevant right now.",
6736: "Made custom filters (self care, chores, tasks) to separate the day.",
6593: "Praises easy category filtering and search.",
7306: "Wants a label bar at the top to switch categories and see only those habits.",
7661: "Wants tabs or pages per category; colour alone is not enough.",
6626: "Wants habits of the same routine grouped together in the list, not just as a filter.",
7115: "Asks to display tags under routines instead of filtering by tags.",
5297: "Uses colours to group while still seeing all habits; filtering feels burdensome.",
6286: "Asks for collapsible groups on the front page to view one category at a time.",
7473: "Wants habits grouped in a dropdown that can be expanded or hidden from its heading.",
1165: "Only one classification dimension exists; wants time period plus a separate tag dimension.",
1173: "Wants categories and time periods separated so category grouping and time order coexist.",
1825: "Can only split by morning/lunch/evening; wants categories like work, study as well.",
5331: "No grouping except by time of day, and time-of-day intervals glitch; money wasted.",
7950: "Wants more than one tag per task.",
7924: "Asks to allow three or more tags on several tasks.",
6677: "Wants category-level progress, e.g. 1 of 2 workout habits = 50%.",
7042: "Wants completion % per category per month (work 85%, home 100%).",
7652: "Wants named groups with summary reports and charts per group.",
348: "Wants time spent by morning/day/evening and by group.",
7925: "Tags cannot be edited or deleted; a misnamed tag is stuck forever.",
7864: "Cannot edit or delete tags; a mistake stays forever.",
7260: "Just wants to name a goal and tick dates, but has to fight category pickers.",
7248: "Must pick a category for every habit, only from presets; will install another app.",
7831: "Too many sub-categories to click through; deleting the app.",
8178: "Only 2 categories without premium; will look for another app.",
7794: "Tasks added without a tag cannot be found.",
7968: "Tapping All does not show all tasks; some tags do not appear on the main screen.",
5241: "Loves being able to track anything without being forced to categorise or sort.",
7493: "Sometimes people do not need categories; simplicity is the point.",
1079: "Uses the routine feature; can skip, run over or finish early, so easy to start.",
1544: "Loves the timer for morning and evening routines; helps with mild ADD.",
2073: "Lays out morning and evening routines with timed steps inside each.",
2560: "Custom timers let them move to the next action without thinking; sleeps and wakes earlier.",
2463: "ADHD: timers are essential, but the habit timer stops when the phone sleeps.",
1065: "ADHD: finally maintains morning, evening and end-of-work routines thanks to the timer.",
2630: "Likes that you can either run the timer or check tasks off yourself.",
2349: "Everything wanted in a routine builder, including a choice of timed or not timed.",
2581: "Wants to mark a routine step done instead of running a timer.",
2607: "Suggests a simple done indicator instead of a timer auto-starting for each habit.",
2661: "Would love the option to run routines without a timer.",
3139: "Wishes they could tick each item off instead of starting a timed routine.",
3232: "Becomes just a stopwatch; wants to mark tasks complete without it being so rigid.",
3066: "Wants plan A/B/C for semester, vacation, holidays and a checklist beside routines; timers rush them.",
2124: "Timing of each task once started is very stressful; red overtime colour feels bad.",
3109: "Timer gave anxiety at first but is what makes it more productive than a checklist.",
2650: "Must stay on screen to run; routine includes other apps so it breaks.",
3231: "Stopwatch stops when you leave the app, so it is useless.",
2610: "Persistent start alarms were removed; they were the point of the app.",
3286: "Start notifications are too subtle to notice; wants a full-screen alarm option.",
1122: "Wants to run routine timers from the watch without opening the phone.",
2606: "Watch app ends a running routine; hoped to stay off the phone; shopping around.",
1075: "Free tier allows only two routines; needs about five (study, skincare, going out).",
2034: "Only one routine free; wants morning and night separately.",
1123: "Hit the routine limit and was asked to pay $30 a year to add one more.",
2138: "Wants three free routines, e.g. morning, afternoon, night.",
2044: "Free plan allows one routine; wants a morning AND an evening routine.",
3213: "Too rigid: must complete in order; skipped items cannot be checked later; parents need flexibility.",
3155: "Wants more of a checklist so a parent can do things in a different order and still count.",
2078: "Wishes steps could be moved around after the routine has started.",
2542: "Wishes a routine did not have to be tied to a specific time; plans change.",
2641: "Works nights with small kids; a fixed start time does not fit.",
2086: "Praises being able to start routines whenever, unlike apps that fix a time of day.",
7338: "Suggests habit groups like 'morning' that can be ticked in one press or item by item.",
7463: "Cannot create a morning-routine group of habits; gives 3 stars for that.",
6737: "Lists can only take whole categories, not individual habits for a morning routine.",
938: "Asks for separate morning and night routine lists.",
7137: "Wants routine folders for seasons or events (winter, wedding countdown, exam).",
8007: "Would love to organise routines in folders or tags and auto-advance to the next step.",
6761: "Loves categorised recurring habits with checklists and custom reminders.",
6835: "Checklist feature finally groups tasks and saves screen space.",
3460: "Handles habits with sub-steps as well as to-do projects; very flexible.",
1914: "Asks for folders (morning, evening routine) and sub-habits inside a habit (exercise -> 10 push-ups).",
1964: "Wants mini sub-points, e.g. brush teeth with morning and evening items.",
2212: "Wants sub-tasks for habits to hold a step-by-step guide.",
5969: "Wants a checkbox habit, e.g. Morning routine with water, wash face, teeth, mobility.",
6794: "Checklist habit counts as not done unless every item is ticked; wants partial state.",
7568: "Wants sub-categories so a habit completes when all its parts are done.",
3387: "Wants sub-goals that mark partial completion of a larger daily goal.",
7376: "Wants a 'vitamins' group that expands and gets its own check when all inside are done.",
2959: "Wants a timer or stopwatch on each checklist sub-item.",
6726: "Wants minutes set per checklist item inside an exercise habit.",
3408: "Wants sub-points that each get their own reminder.",
6976: "Wants statistics for individual sub-categories inside a multiple habit.",
7592: "Wants a gym habit with sub-categories (chest, back, shoulders) holding exercises.",
3411: "Checklist inside a habit is behind the paywall; not really free.",
3483: "Sub-items auto-expand on every launch and look cluttered; wants to choose.",
3421: "Wants to move sub-tasks by tapping instead of deleting and re-adding.",
3454: "Completing sub-tasks does not change the parent's progress (0%).",
3372: "Loves that there is no clutter of sub-tasks, just did-you-do-it-or-not.",
3847: "Has the essentials without complex sub-sub-sub lists.",
4100: "Easy, not overflowing with buttons that open multiple subtasks.",
}
