# Paraphrased gists for the N-references of the explanation report (my wording, not quotes).
G = {
7: "Wants one habit ticked in both the morning and evening lists, and absent from the afternoon list.",
1218: "One habit can only sit in one section; showing it in two sections means creating a second copy.",
1155: "Wants several check-ins in different sections, all counted in the same habit's history.",
891: "Likes splitting one habit into AM / PM / night with separate alerts, but the watch marks both done at once.",
454: "Praises scheduling one habit for several times of day instead of creating it three times.",
1383: "After the morning tick, wants the habit to move to the evening slot rather than stay under morning.",
1210: "With several reminders a day, wants a separate check-in record for each time period.",
638: "A planner check needed morning, afternoon and evening; wants all three required before the day counts.",
2011: "Teeth three times as part of routines: cannot tick it until all three times are done.",
170: "A twice-daily habit gets one reminder; must create duplicate goals to be reminded twice.",
1923: "One habit = one notification; doing something morning and evening means two habits, two graphs.",
595: "Wants teeth morning/evening in one habit, half-filled after the first tap.",
5652: "Wants 7 glasses a day to fill in 1/7 steps per tap.",
1471: "Wants 8 glasses split into morning, day and evening sub-targets that add up to the daily goal.",
1775: "Praises adding 10 minutes of meditation three times a day towards a 30-minute daily target.",
474: "Wants a habit every 2 hours through the day, not only once per section.",
592: "Wants 5 push-ups every hour between set times; deleting the app because it cannot.",
1247: "Wants one habit done three times in different sections instead of naming copies 'XX1, XX2'.",
3014: "Twice-daily meds need two separate habits and two reminders, which ruins the statistics.",
360: "Cannot give a routine a clock slot such as 8:30 to 9:15; cannot use the app.",
1444: "Wants one habit at an exact hour inside the morning without moving the rest of the morning.",
1428: "Suggests sections become time ranges that contain habits with exact times.",
461: "Reminders are only per morning/afternoon/evening; must set specific times elsewhere.",
392: "Wants each habit's time shown in the list and the list auto-sorted chronologically.",
6232: "Asks how to sort habits by time inside their section (9:25 should come before 9:30).",
382: "Wants a timed schedule view of the whole day in addition to day parts.",
1033: "Wants a daily planner view showing habits as time slots.",
1178: "Wants each section to carry specific clock times.",
269: "Student and night owl: wants to set when the three periods end so habits are not 'overdue'.",
1350: "Fixed morning/day/evening times are a good idea, but must be editable; their morning starts at noon.",
1900: "Night owl: wants the day to roll over at 2 am.",
1891: "Wants the app to ask before starting a new day, in case yesterday was not logged.",
466: "Takes meds four times a day; only three slots; wants wake-up, lunch, dinner, bedtime slots.",
268: "Wants a separate 'before bed' routine so the evening section stays uncluttered.",
894: "Wants to reorder categories and to add own time bands such as commute or lunch break.",
1586: "Likes that the default morning/afternoon/evening groups can be renamed.",
1171: "Wants section names changed to morning, forenoon, noon, afternoon, evening, before bed.",
172: "Shift worker: day counting and bedtimes misalign; wants to set morning/afternoon/evening/night times.",
1829: "Night-shift worker: day starts at night; wants to set wake-up and bed times.",
1946: "Night-shift: wants morning to be 14:00 to 16:00.",
877: "Switched apps because each period's time can be adjusted.",
1483: "Praises sections calculated from the user's own wake-up and bedtime.",
2051: "Praises core daily routines plus different routines for specific weekdays.",
1553: "Wants two saved sets of morning/afternoon/evening: one for weekdays, one for weekends.",
4123: "Wants days-of-the-week on individual steps inside a routine.",
1113: "Wants conditions per task inside a routine, e.g. only on Mondays.",
7145: "Shift nurse: wants to switch the whole day's set of routines per shift in one step.",
2975: "Uses five routine modes for shifts; the chosen mode resets to mode 1 the next day.",
4490: "Wants habit groups that can be switched on and off, e.g. a holidays group.",
2980: "Asked for a separate exam-period routine set; thanks devs for adding routine modes.",
6764: "Wants to pause a group of habits, e.g. work-day routines while on holiday.",
446: "Wants a mode for trips to snooze or skip all tasks for a period.",
2049: "Keeps a shorter version of a routine for days with less time.",
2307: "Routine mode must be switchable from Home, not buried in settings.",
312: "Cannot see the whole day in one place; only morning, afternoon, night separately.",
333: "No single overview; keeps swiping between morning and afternoon pages.",
296: "After update opens on the empty morning list; must scroll sideways to all-day habits.",
404: "App auto-focuses the current time of day and shows nothing; must swipe to all-day.",
462: "Unfinished morning habits vanish when the afternoon window starts.",
391: "Asks for an option to remove morning/afternoon/evening entirely.",
1948: "Wants to disable morning/noon/evening times altogether.",
377: "Wants Today to remember the last chosen view, e.g. All Day.",
4826: "Wants the full day list, grouped, to be the main screen.",
959: "Wants the default view divided into morning, afternoon, evening parts.",
881: "Loves seeing either the habits due now or the whole day.",
853: "Likes allocating to a time of day while still viewing the whole list together.",
925: "Loves switching the view between all and time of day.",
1472: "A-few-times-a-week habits show in every section; wants a separate section for them.",
734: "Wants tasks that can be completed any time of day, not tied to a period.",
385: "Habits do not stay in the order set within morning/afternoon/evening; they move daily.",
368: "Wants to reorder habits inside each time block because the sequence matters.",
1035: "Does things in a set order even without set times; cannot reorder; keeps abandoning the app.",
954: "Task order gets jumbled and has to be reorganised every day.",
1249: "Widget shows sections in a confusing order; wants morning-to-night order.",
3316: "Wants to drag habits freely, e.g. put brushing teeth before stretching.",
4415: "Wants the overall stats page to select a group, e.g. see only the medicine group report.",
6674: "Only one category per habit; lists should allow AND/OR of categories.",
6033: "Wants filtering by several tags at once, e.g. free-time tasks on a chosen weekday.",
2947: "Wants the app to remember the selected filter instead of resetting to All.",
5291: "Tags and a category filter exist, but wants all goals visible at once, grouped by category.",
4491: "A tag filter exists, but wants a grouped view with dividers showing all tasks by tag.",
5734: "Many categories make scrolling long; wants groups that fold and unfold.",
1905: "Wants separators or tabs by time of day and by periodicity.",
50: "Wants a coloured header per life area or time of day on Home; filters each time are annoying.",
5610: "One field is used both for time of day and for category, so both cannot be done at once.",
5389: "Wants several tags: stretching is both morning routine and health/fitness.",
3312: "Praises one habit linked to several categories: a morning stack and an overall purpose.",
4252: "Wants a ring per category instead of one overall ring.",
8397: "Wants a tiled view showing n/x completed per category for the day.",
5322: "Wants the progress screen filtered to one area/category.",
7008: "Wants category percentages in charts to see which areas get most focus.",
5609: "Missing summary charts and category breakdowns.",
7141: "Wants monthly/yearly completion counts per routine, per group and in total.",
7721: "Wants an overall percentage across all tasks and one per category.",
6596: "Wants an overview of all habits together, regardless of category.",
5968: "Wants a category target: at least 5 times a week any of three sports.",
8387: "Wants a fitness category to count as done on any day yoga, lifting or running is done.",
1220: "Wants check-in statistics by time period.",
1225: "Wants a count of habits per time period.",
7559: "Wants a group like 'morning routine' with its daily completion percentage.",
883: "Watch progress complications for the current time of day and for an area were removed.",
82: "Sorts routine tasks by morning/afternoon/evening and sees the percentage still to do.",
7095: "Wants overall statistics, not only per habit, plus hours spent by category.",
4225: "Leaving to find an app with category status percentages on the home screen.",
4635: "Category totals ('Journeys') were removed; ADHD user feels unheard.",
3474: "Per-routine time report (planned vs actual per step) is a godsend for time blindness.",
3223: "Praises the time report at the end of each routine for adjusting durations.",
4230: "Shows how long each task took and suggests adjustments; stats per routine over time.",
3222: "Wants a weekly summary of time per task and which items were skipped.",
874: "Time of day does not matter for their habits; the time-of-day statistics take space and should be hideable.",
1707: "Tasks are split into three undeletable sections, with one calendar per ritual; wants one combined calendar.",
238: "Changing a habit's time of day or frequency resets its stats.",
6702: "Has 20+ categories on premium and wants a full colour picker.",
6109: "Created a routine group, but the group and its routines do not appear.",
7258: "Must choose from preset categories, as if everyone were the same.",
6911: "Lists only accept whole categories; cannot build a 'Morning routine' list from single habits.",
2522: "Wants to combine habits into routines with routine-level stats and widgets.",
2111: "Loves performing a series of habits in a row on autopilot, told what comes next.",
3170: "Wants to link habits so they stay together when reordering.",
3140: "Loves adding triggers to stack new habits onto existing tasks.",
2482: "Habit stacking does not remind after the previous habit is done, even on premium.",
2476: "Habit timer stops when the phone sleeps or the app is left.",
2298: "Timer exists but records nothing; wants time totals and statistics.",
2123: "Uses routines for morning, evening, self-care, study and work.",
2141: "Routine resets itself mid-way and records the wrong start time.",
2645: "Routine starts from the middle or end every time; looking for another app.",
2614: "Start-routine notifications would not stop; deleted the app once.",
1533: "Mostly ads for other apps; a checklist in Notes works better.",
1093: "Routines only show as groups; wants the whole day at once and ticking without the timer.",
395: "After the update, weekly habits do not show under any section.",
399: "Habits exist in the list but appear in no part of the day, so they cannot be completed.",
760: "Home is so cluttered that the morning and evening routines are hard to reach.",
1638: "Needs an alarm per habit, not one per routine section.",
858: "Custom groups disappeared; tasks can only be sorted by time of day.",
1681: "Only three sections, so only three alarms; prefers a calendar with exact hours.",
1414: "Just a list added to the day; wants categories like cleaning or health.",
57: "When a habit repeats several times a day, cannot say which part of the day each belongs to.",
3746: "Wants an overall daily % that counts tasks and sub-tasks, shown under the dates.",
3802: "Sub-habits have no statistics for which option was done how often.",
}
