# -*- coding: utf-8 -*-
"""Stage 3 merge for report 77 (Habit Tracker: Streak-Free / Momentumly, Beaucode Ventures UG)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C296", "product-rule", "The free tier must let the differentiator be experienced — a cap that hides the product's own thesis converts on nothing the user has felt",
    "Report 77 (Habit Tracker: Streak-Free / Momentumly, 71 reviews): the product's thesis — forgiving, multi-habit momentum instead of streaks — is the best-supported finding in the corpus (19 of 71, 26.76%, mean 4.89★, zero below 4★), yet the free tier is one habit, so 'the product's own differentiator (forgiving multi-habit momentum) is not experienceable free'; 'a habit tracker with one habit is a demo'; the four who hit the cap rate it 2.50★ ('you can't really explore the app'), MON_PAYWALL_BLOCKS 7 (9.86%, 2.86★) is the largest negative code, and the three reviewers who did convert converted on comparative value against trackers they had already tried — 'an informed judgement they could only make after using it'; §8.4.1 the paywall does not lead with the concept although the listing and title do; §8.4.3 a trial or an unambiguous free window is the mechanism that lets the cap be tested without changing it. The report does not recommend raising the cap (no conversion data) — it establishes that at one habit the thing being sold cannot be felt. Related: [[C147]] (let people use the product before they pay), [[C182]] (a pre-use hard paywall makes every purchase non-evidence-based), [[C133]] (gate on capability not quantity), [[C007]] (generous fixed cap), [[C063]] (free trial before purchase).")

ext("C236", " Report 77 (Streak-Free / Momentumly): the free tier is one habit and the App Store description states no habit-count limit anywhere ('helps you build your new habit' — singular); three reviewers on three storefronts across ten months independently state the number (mean 2.33★), two say in as many words the boundary surprised them (MON_UNEXPECTED 2, mean 1.50★: 'What's the point of making a free app if it's unfunctional unless you buy a premium plan'; 'Ich hatte erwartet, dass mehrere Gewohnheiten frei sind'); 'A one-habit free tier is a defensible business decision. Not disclosing it is a separate, cheaper-to-fix problem, and it is the one the corpus actually punishes'; §8.1.1 one sentence in the description is 'the highest ratio of impact to effort available here' — it removes the surprise, which is what the 1★ and 2★ text objects to.")
ext("C177", " Report 77 (Streak-Free / Momentumly): 10 IAP SKUs from $2.99 to $29.99 under three product names ('Momentumly Plus', 'Premium Habit Tracking', 'Premium'), none showing a billing period, beside a description whose only money paragraph is auto-renewal boilerplate with no price, tier, trial or one-time option — three reviews over 12 months hold three different beliefs about whether a lifetime purchase exists ('I've subscribed for the lifetime version', 2★; 'there is no possibility to get a lifetime version', 2★ — the entire review; 'The one time purchase rather than a subscription model is also a lovely thing', 5★); reviewers name the paid tier five different ways; 'a user who cannot tell what is being sold does not buy'; §8.1.2 show periods and cut the SKU count; §8.7 Q1 'does a lifetime SKU currently exist' is answerable in one minute in App Store Connect.")
ext("C218", " Report 77 (Streak-Free / Momentumly): the description states the concept well ('The first habit tracker without streaks') but never states the one-habit limit, names no price / tier / trial / one-time option, and omits widgets, Apple Health, the calendar, badges, the Habit Forest and iCloud — six capabilities reviewers discuss, two of which (widgets, Health) generated complaints from users who did not know what tier they were in; §8.1.4 name the features.")
ext("C003", " Report 77 (Streak-Free / Momentumly): a lifetime SKU is the only monetization attribute anyone in the corpus praises by name ('The one time purchase rather than a subscription model is also a lovely thing', 5★, who intends to buy 'the moment I can afford it'); a 2★ whose entire text is 'there is no possibility to get a lifetime version of subscription'; MON_SUB_FATIGUE 2 at 1.50★ ('This subscription fanaticism is getting out of hand'); §8.1.3 'if a lifetime SKU exists, say so'.")
ext("C133", " Report 77 (Streak-Free / Momentumly): money-negative reviews object to structure 12 of 14 (85.7%) vs price level 2 of 14 (14.3%); 'the corpus says the price is broadly acceptable and the boundary is not' — a structure problem, not a pricing problem; MON_PAYWALL_BLOCKS 7 (9.86%, 2.86★: 'only a tiny bit of the app's uses are free'; 'most features require the pro subscription') vs MONP_VALUE 3 at 5.00★ ('the price is just right'); no reviewer names a specific feature as the thing they paid for.")
ext("C064", " Report 77 (Streak-Free / Momentumly): price level is the smallest of eight upgrade barriers — MON_PRICE_LEVEL 2 (2.82%, mean 3.00★: 'just wastage of funds', 1★; 'a little bit pricey, basic function still worth using it', 5★) against 3 who volunteer the price is right ('really affordable compared to others'); the inference (n=3) is that the app converts against a reference price the user has already formed elsewhere, not against zero; one affordability barrier at 5★ ('the moment I can afford it').")
ext("C007", " Report 77 (Streak-Free / Momentumly): a one-habit free cap — cap objections 4 of 71 (5.63%, mean 2.50★), all in the second half of the corpus (zero in the first 42 reviews, 4 in the last 29; the corpus cannot say whether the cap tightened or merely became visible); 'add one habit, then be interrupted repeatedly'; the report does not recommend raising the cap because converters are invisible, but notes the differentiator cannot be experienced at one habit ([[C296]]); E2 in §8.6: held-out cohort at cap=3.")
ext("C222", " Report 77 (Streak-Free / Momentumly): at one habit the cap is 'an aggressive but coherent strategy' whose cost side is precise (2.50★ from those who hit it) and whose conversion effect is unmeasured; the decision should be made 'on strategy grounds, not on review grounds'.")
ext("C147", " Report 77 (Streak-Free / Momentumly): 'you can't really explore the app' (bg 4★) — 'a habit tracker with one habit is a demo'; the three who converted did so on comparative value after using it; zero of 71 mention a trial and the description offers none; §8.4.3 a trial or an unambiguous free window.")
ext("C063", " Report 77 (Streak-Free / Momentumly): MON_NO_TRIAL 1 (4★: 'there should be somewhat of a free trial because you can't really explore the app'); zero reviewers mention using a trial; §8.6 E3: a 7-day trial arm vs the 1-habit cap arm.")
ext("C093", " Report 77 (Streak-Free / Momentumly): MON_PROMPT_NAG 1 (1★, title 'annoying'): 'can only add 1 habit then after that this subscription keeps popping up 😑'; §8.4.4 fix the prompt frequency — 'invisible in aggregate metrics until it shows up as churn'.")
ext("C137", " Report 77 (Streak-Free / Momentumly): the subscription prompt fires repeatedly after the first habit is added — the moment of need becomes the moment of nagging when the cap is one.")
ext("C216", " Report 77 (Streak-Free / Momentumly): a momentum score that decays instead of resetting is the whole product — 'the first habit tracker without streaks'; 19 of 71 (26.76%, mean 4.89★, zero below 4★) praise it by name: 'I used to drop habits the second I missed a day — all because of streak pressure'; 'removes all the frustration of having to start over from zero. It takes the 2-day rule even further'; 'motivates me to get things done but without the feeling of punishment when life gets in the way'; the streak is still visible alongside; 11 outcome reviews (15.49%) all 5★; PRAISE_MOTIVATING 11 all 5★, described as 'positive reinforcement', 'nudges that feel thoughtful, not annoying', 'without making me feel anxious'.")
ext("C157", " Report 77 (Streak-Free / Momentumly): the counter-case — an app whose entire thesis is no streak pressure drew zero negative reactions to that thesis across 71 reviews, 28 storefronts and six languages; CONCEPT_FORGIVING 11 (4.82★): 'if you miss a day it isn't all for nothing; it reflects a healthy relationship with habits'.")
ext("C178", " Report 77 (Streak-Free / Momentumly): 'Momentum based habit tracking feels way more realistic and helpful… than the streak focus that is everywhere else'; COMP_TRIED_MANY 4 and COMP_BEST 3, all 5.00★ — the highest-intent reviews; 'It doesn't feel stressful, like other apps'.")
ext("C217", " Report 77 (Streak-Free / Momentumly): the momentum number is unexplained in-product — 'I can't really tell on what basis momentum arises, or why it's good that it's displayed' (kr 3★) vs 'At first I had some trouble following the points logic, but now that I've grasped it, I'm thrilled' (de 5★) — 'same obstacle, two outcomes… the gap between those two reviews is the whole opportunity'; §8.3.1 a one-tap explanation where the number is displayed; U:comprehension 4 (5.63%, 3.00★).")
ext("C256", " Report 77 (Streak-Free / Momentumly): 'removing the streak also removed the obvious scoreboard, and a minority cannot find the replacement' — no tick-mark ('Daily habits, tick mark not available', a 1★ in a habit app over the core action), no achievement feeling ('lacks to give you the feeling of achievement for completing the tasks'), an unexplained momentum number and no monthly view of hits and misses ('difficult for you to know which days you have missed… from a monthly perspective') are four versions of one complaint (U:ux_friction 7, 9.86%, mean 2.57★ — the lowest mean of any union); §8.3.3 'a filled month is the achievement feedback the streak used to provide'.")
ext("C223", " Report 77 (Streak-Free / Momentumly): UX_NO_TICK — 'Daily habits, tick mark not available' (in, 1★): whether the tick is missing or merely hard to find, 'the outcome was a one-star review in a habit app over the core action'; §8.3.2 make the completion gesture unmissable.")
ext("C012", " Report 77 (Streak-Free / Momentumly): a calendar exists but does not show hits and misses — U:calendar_gap 3 (4.23%, 3.33★): 'my habit in a calendar graphic'; 'the calendar part doesn't operate well' (kr); a monthly hit-and-miss view is what replaces the streak's achievement feedback.")
ext("C043", " Report 77 (Streak-Free / Momentumly): 'x times per week' scheduling is the only feature requested twice by otherwise-happy 4★ users, 11 months apart ('3 veces a la semana o 2 veces al mes'; ''x-mal pro Woche' zu definieren anstatt 'a Tag x und y'… Mich verwundert, dass es das nicht gibt'); scheduling is weekday-only; the use case is 'go to the gym three times a week, any three days'; 'an app built on missing a day is fine still forces users to name the days' — a scheduling-model gap that contradicts the product's own thesis; §8.8 one of the three things to do.")
ext("C009", " Report 77 (Streak-Free / Momentumly): the widget arc — requested by the very first review (2025-01-10), shipped and praised 33 days later ('Great widget too for each habit'), then reported behind the paywall ('You have to pay for widgets', pt 1★, the whole review, single-source) and found too narrow (one habit per widget); U:widget_gap 5 (7.04%, 3.80★); §8.2.2 'a widget is the cheapest daily-retention surface a habit tracker has, and this one is gated and limited to a single habit at the same time as the free tier is limited to a single habit'; §8.6 E7 ungating the widget.")
ext("C107", " Report 77 (Streak-Free / Momentumly): widgets reportedly paid (n=1, a 1★ whose whole text is 'You have to pay for widgets'); the paid layer is the widget itself, not a variant — and it shows one habit only.")
ext("C254", " Report 77 (Streak-Free / Momentumly): a multi-habit widget is the second repeated request — 'only able to select 1 habit to track at a time. So, I have to open the app to check which habits I have yet to complete' (5★); 'a widget what would show all Habbits at once' (4★); REQ_WIDGET_MULTI 2 (4.50★).")
ext("C231", " Report 77 (Streak-Free / Momentumly, 71 reviews): (1) one review is 1.41% so the spec's bands cannot discriminate — every headline carries a Wilson CI, 'where a band and an interval disagree, trust the interval'; (2) 14 of 71 (19.72%) are content-free 5★ and 3 more 5★ are complaints — 17 of 50 five-star reviews (34%) evidence no satisfaction; excluding low-info makes both the strongest positive and the strongest negative larger; (3) money complaints changed register, not volume — 7 at 1.57★ before v3.0, 7 at 3.86★ since, so 'the recent ratings no longer carry the monetization problem' (2026 Q3: 5 of 9 money-negative at 4.44★); (4) 18 of 28 storefronts contributed exactly one review, averaging 3.33★, and five of six 1★ come from them — where almost nobody writes, the one who does is the annoyed one; (5) 71 text reviews on 339 public ratings, 4.31★ vs 4.58★, the US public base has zero 1★/2★ across 37; (6) zero refund / cancellation / renewal mentions is 'a genuine blank, not a clean bill of health'.")
ext("C002", " Report 77 (Streak-Free / Momentumly): 5 of 6 one-star reviews are monetization and nothing else; zero 1★ report a crash or data problem; the product thesis drew zero negative reactions while the free/paid boundary drew every one-star — 'the product thesis is validated and the reliability is fine; everything that costs this app ratings happens at the free/paid boundary'.")
ext("C065", " Report 77 (Streak-Free / Momentumly): the four stated payers average 3.75★ (0.56 below the corpus) — a lifetime purchaser whose app crashes on every launch and whose Apple Health connection does not work ('maximum spend, zero delivery — the worst outcome in the corpus'), a premium buyer who uninstalled after 20 days over missing feedback loops, and two satisfied 5★; PAID_ENTITLEMENT_FAIL 1 ('Leider werden mir die Optionen nicht angezeigt', a 5★ titled 'Problem Premium').")
ext("C031", " Report 77 (Streak-Free / Momentumly): DEF_CRASH_LAUNCH 2 (1.50★) — one a lifetime buyer, one 'the new update, where the app can't even open without crashing' that opened the 70-day one-star window; the last defect report is 2025-08-26 and the 37 reviews since contain none.")
ext("C021", " Report 77 (Streak-Free / Momentumly): Apple Health integration exists and is the only subsystem with more than one failure — the connection 'has not worked' for a lifetime buyer (2★) and 'the app crashes when adding Active Energy' (inside a 5★) — while a third asks for more of it (REQ_HEALTHKIT 2, 5.00★): wanted and, at least twice, broken; no reviewer says which tier it needs.")
ext("C175", " Report 77 (Streak-Free / Momentumly): 'now we have reached a point with the new update, where the app can't even open without crashing' (dk 1★, 2025-08-26) — the only reliability regression, and it opened the 70-day window holding all six of the corpus's one-star reviews; defects then fell to zero for 37 consecutive reviews.")
ext("C059", " Report 77 (Streak-Free / Momentumly): PRAISE_DEV 3 (5.00★: 'Developer is also very responsive and takes feedbacks very positively'; 'dev actually listens to feedback'; 'the dev updates fairly frequently') all inside the first 90 days and none in the 61 reviews since — 'an early-community signal that is cheap to lose and expensive to rebuild'; three requests visibly shipped (Chinese localisation, more gamification, a widget within 33 days of a day-one request).")
ext("C027", " Report 77 (Streak-Free / Momentumly): one request — '希望能增加中文' (cn 5★, 2025-03-02) — and ZH-Hans + ZH-Hant now ship; zero localisation complaints in six languages; 10 localisations ship but Japan, Australia and Taiwan produced no review at all despite a shipped Japanese localisation.")
ext("C255", " Report 77 (Streak-Free / Momentumly): 10 localisations, 6 languages in the corpus, zero complaints about translation, missing languages or formatting.")
ext("C185", " Report 77 (Streak-Free / Momentumly): PRAISE_DESIGN 17 (23.94%) — 'cute' across four languages — carries a mean of 4.65★, below the concept theme's 4.89★, because two low-rated reviewers praise the design while complaining about something else: 'design praise is not a satisfaction proxy'.")
ext("C006", " Report 77 (Streak-Free / Momentumly): PRAISE_SIMPLICITY 14 (19.72%, 4.57★) and UX_TOO_MINIMAL 4 (5.63%, 2.25★: 'Maybe too simple'; 'This app lacks the punch'; 'beyond minimal, it feels bare') — 'minimalism is simultaneously the third-largest praise and the joint-largest non-monetary complaint'; two of the four also praise the design in the same review; the emptiness complaint never resolved across 603 days.")
ext("C214", " Report 77 (Streak-Free / Momentumly): 'nothing special.. just wastage of funds' (pk 1★, spend implied) — the too-minimal reading at the paywall.")
ext("C024", " Report 77 (Streak-Free / Momentumly): gamification — acorns, a squirrel, foxes, achievements, Badges (v2.6.4) and a purchasable Habit Forest (v3.0) — PRAISE_GAMIFY 5 (4.60★), REQ_MORE_GAMIFY 1; a Korean 3★ questions why the squirrel/acorns and the Focus tab exist; Badges are mentioned by no reviewer and the Forest by exactly one, eight months after shipping — 'two headline features, one mention between them'.")
ext("C167", " Report 77 (Streak-Free / Momentumly): PAID_INAPP_CONTENT 1 — 'Love the bonus of buying and planting a forest' (5★): cosmetic content bought in-app rather than a tier; the only purchase in the corpus tied to a named thing.")
ext("C101", " Report 77 (Streak-Free / Momentumly): Badges & Achievements shipped 2025-09-29 → 2025-11-02 and no reviewer mentions them; UX_NO_ACHIEVEMENT_FEEL 1 ('lacks to give you the feeling of achievement for completing the tasks') predates them.")
ext("C013", " Report 77 (Streak-Free / Momentumly): REQ_ICLOUD 2 (4.50★) — iCloud sync / backup / an account; the only account mention in 71 reviews is a request for one; 'I totally recommend it' from the 4★ who wants sync between devices.")
ext("C022", " Report 77 (Streak-Free / Momentumly): REQ_WATCH 1 (5★).")
ext("C080", " Report 77 (Streak-Free / Momentumly): REQ_DARKMODE 1 (5★).")
ext("C073", " Report 77 (Streak-Free / Momentumly): REQ_SORT 1 (5★) — sort or organise habits.")
ext("C011", " Report 77 (Streak-Free / Momentumly): REQ_MORE_STATS 1, REQ_MULTI_GRAPH 1 (compare several habits in one graph), PRAISE_STATS 5 (4.40★: 'good line graph view').")
ext("C202", " Report 77 (Streak-Free / Momentumly): REQ_SOCIAL 1 (3★) — to see other people's progress.")
ext("C056", " Report 77 (Streak-Free / Momentumly): REQ_AI 1 (kr 3★) raises AI features as an expectation — single voice.")
ext("C082", " Report 77 (Streak-Free / Momentumly): no ads; the only ad mention asks for them as a paywall alternative — 'would like to have more freebies or maybe ads instead of the payment wall' (5★).")
ext("C238", " Report 77 (Streak-Free / Momentumly): MON_WANT_ADS 1 — a 5★ user who cannot afford the wall proposes ads instead; MONP_AFFORD_BARRIER 1 ('the moment I can afford it').")
ext("C110", " Report 77 (Streak-Free / Momentumly): 'What's the point of making a free app if it's unfunctional unless you buy a premium plan' (1★) — the free/paid boundary is illegible at install and at the wall.")
ext("C209", " Report 77 (Streak-Free / Momentumly): no account, no login wall — zero complaints and one request for an account (as a sync/backup path).")
ext("C085", " Report 77 (Streak-Free / Momentumly): zero privacy or data-sharing mentions in 71 reviews across six languages.")
ext("C036", " Report 77 (Streak-Free / Momentumly): zero customer-support-failure mentions in 71 reviews; the schema has no developer-reply field.")
ext("C005", " Report 77 (Streak-Free / Momentumly): COMP_TRIED_MANY 4 and COMP_BEST 3, all 5.00★, all praising the no-streak concept — the comparison set is 'the streak focus that is everywhere else'.")
ext("C134", " Report 77 (Streak-Free / Momentumly): the title and description already lead with the concept ('The first habit tracker without streaks') — the only thing with no detractors — and it is the paywall that does not; §8.4.1.")
ext("C062", " Report 77 (Streak-Free / Momentumly): the high-spend group (US, CN, GB, DE, KR, FR, CA) supplies 34 of 71 at 4.62★ with 17.6% money-negative vs 4.03★ / 21.6% elsewhere — direction consistent with higher price tolerance in high-spend markets, not separable from noise; Japan, Australia and Taiwan produced no review at all; Germany (home market, 17 reviews, 4.76★) holds all three named-behaviour-change reviews, the only stated subscriber and the only entitlement failure.")
ext("C130", " Report 77 (Streak-Free / Momentumly): the developer's home market (Germany) is the largest and strongest storefront — 17 of 71 at 4.76★, 9 written in German and 8 in English.")
ext("C025", " Report 77 (Streak-Free / Momentumly): 'looking forward to buying it the moment I can afford it' (mx 5★) — an affordability barrier from a user sold on the concept and the one-time model.")
ext("C212", " Report 77 (Streak-Free / Momentumly): zero refund and zero cancellation mentions in six languages — 'read as unobserved, not absent'.")
ext("C104", " Report 77 (Streak-Free / Momentumly): no reviewer claims the app used to be free and became paid — the complaint is that the free tier is too thin, not that something was taken away; no paywall-introduction event is visible.")
ext("C278", " Report 77 (Streak-Free / Momentumly): the product reaches users under many names — Store title 'Habit Tracker: Streak-Free', bundle and reviewer usage 'Momentumly', a subscriber calling it 'Streak Free', and the paid tier under five names while the listing sells under three — a search and support liability.")
ext("C094", " Report 77 (Streak-Free / Momentumly): no burst or solicitation pattern detectable (largest day 2 reviews), though at n=71 'a detectable pattern is not the same as none existing'.")
ext("C075", " Report 77 (Streak-Free / Momentumly): UX_LEARNING_CURVE 1 — 'At first I had some trouble following the points logic, but now that I've grasped it, I'm thrilled' (5★); PRAISE_ONBOARDING 1.")
ext("C226", " Report 77 (Streak-Free / Momentumly): a Focus tab exists and one reviewer questions why (UX_FOCUS_TAB_POINTLESS 1, kr 3★).")
ext("C066", " Report 77 (Streak-Free / Momentumly): a Focus tab ships; the only mention is a Korean 3★ asking why it exists.")
ext("C207", " Report 77 (Streak-Free / Momentumly): UX_FOCUS_TAB_POINTLESS 1 — a tab the reviewer does not use and cannot hide.")

M = {
 "R77-001":["C278","C134"], "R77-002":["C231"], "R77-003":["C231"], "R77-004":["C216","C157","C178","C296"], "R77-005":["C216"],
 "R77-006":["C002","C133","C065"], "R77-007":["C236","C007","C296"], "R77-008":["C177","C003","C218"], "R77-009":["C175","C031","C231"], "R77-010":["C231","C002"],
 "R77-011":["C031","C021","C175","C065"], "R77-012":["C217","C256","C223"], "R77-013":["C043"], "R77-014":["C009","C254","C107"], "R77-015":["C085","C036","C212","C209","C082"],
 "R77-016":["C236","C177","C043","C009","C217","C231"], "R77-017":["C094","C231"], "R77-018":["C013","C080","C022","C043","C254","C073","C011","C012","C202"], "R77-019":["C278","C177"], "R77-020":["C218","C024"],
 "R77-021":["C236","C177","C063","C082","C104"], "R77-022":["C024","C167"], "R77-023":["C231"], "R77-024":["C216","C157","C178"], "R77-025":["C185"],
 "R77-026":["C006","C214"], "R77-027":["C216","C157"], "R77-028":["C216"], "R77-029":["C005","C178"], "R77-030":["C059"],
 "R77-031":["C133","C064","C003"], "R77-032":["C133","C110","C296"], "R77-033":["C007","C222"], "R77-034":["C236"], "R77-035":["C003","C177"],
 "R77-036":["C093","C137"], "R77-037":["C256","C217","C223"], "R77-038":["C031","C021"], "R77-039":["C059","C011","C013"], "R77-040":["C009","C107","C254"],
 "R77-041":["C059","C027"], "R77-042":["C021"], "R77-043":["C013","C012","C209"], "R77-044":["C056","C080","C011","C202","C073","C022"], "R77-045":["C212","C025"],
 "R77-046":["C231"], "R77-047":["C231"], "R77-048":["C043","C013"], "R77-049":["C065","C177","C236"], "R77-050":["C231"],
 "R77-051":["C065","C003"], "R77-052":["C003","C064","C167","C025"], "R77-053":["C133","C236","C177","C064"], "R77-054":["C007","C222","C296","C147"], "R77-055":["C212","C231"],
 "R77-056":["C133","C231"], "R77-057":["C231","C062"], "R77-058":["C062","C130"], "R77-059":["C062"], "R77-060":["C231"],
 "R77-061":["C027","C255","C062"], "R77-062":["C231","C002"], "R77-063":["C175","C002"], "R77-064":["C231"], "R77-065":["C031"],
 "R77-066":["C007"], "R77-067":["C059"], "R77-068":["C216","C006"], "R77-069":["C024","C101"], "R77-070":["C236","C002"],
 "R77-071":["C177","C003"], "R77-072":["C218"], "R77-073":["C043"], "R77-074":["C009","C254","C107"], "R77-075":["C217","C223","C256","C012"],
 "R77-076":["C134","C296"], "R77-077":["C296","C007","C222","C147","C063"], "R77-078":["C063","C147","C093","C137"], "R77-079":["C231","C059"], "R77-080":["C177","C231","C024","C065"],
 "R77-081":["C216","C157"], "R77-082":["C177","C003"], "R77-083":["C009","C107","C296"],
 "R77-018b":[],
}
M.pop("R77-018b")
# leftover ext() targets need a card each
for k,v in {"R77-075":["C075"],"R77-044":["C226","C066","C207"],"R77-015":["C238"]}.items(): M[k]+=v
cards = [json.loads(l) for l in open("Tools/prd_ledger/77/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/77/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 77" in x["statement"] and not any(k.startswith("R77-") for k in x["cards"])])
