"""Cards for report 29 — Part 3 (global findings)."""
import json, re
R = 29
rep = open("App Store Reports/29. Habit Tracker - Daily Goals - Motivation & Accountability (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(24, "§3.1 Master table (verbatim), 55 themes", "data-caveat", "Master theme table, denominator 366", "n/a", "mixed", table("## 3.1 Master table"), "none", "corpus-level fact", "app-specific", [])
T = [
 (25,"#1 Zero cost cited as a reason for satisfaction","monetization","Zero cost cited as a reason for satisfaction","172 (46.99%, HIGH), mean 4.83","product-rule","praise"),
 (26,"#2 — of which: praises 'free'","monetization","Praises 'free'","121 (33.06%, HIGH), mean 4.78","product-rule","praise"),
 (27,"#3 Simplicity / clean UI / ease of use","insight","Simplicity / clean UI / ease of use","119 (32.51%, HIGH), mean 4.80","product-rule","praise"),
 (28,"#4 — of which: praises absence of ads","monetization","Praises absence of ads","60 (16.39%, HIGH), mean 4.90","product-rule","praise"),
 (29,"#5 Any feature request","feature","Any feature request","60 (16.39%, HIGH), mean 4.35","none","complaint"),
 (30,"#6 Arrived after rejecting other trackers","positioning","Arrived after rejecting other trackers","52 (14.21%, HIGH), mean 4.83","do","praise"),
 (31,"#7 Any functional defect","must-never-break","Any functional defect","46 (12.57%, HIGH), mean 2.89","must-never-break","complaint"),
 (32,"#8 UI / visual design praised","feature","UI / visual design praised","45 (12.30%, HIGH), mean 4.64","do","praise"),
 (33,"#9 — of which: praises absence of subscription/IAP","monetization","Praises absence of subscription/IAP — the highest mean of any theme of size","44 (12.02%, HIGH), mean 4.98","product-rule","praise"),
 (34,"#10 Concrete behaviour change reported","insight","Concrete behaviour change reported","38 (10.38%, HIGH), mean 4.87","none","praise"),
 (35,"#11 Calendar / date engine defect","must-never-break","Calendar / date engine defect","37 (10.11%, HIGH), mean 2.95","must-never-break","1★-burst"),
 (36,"#12 Explicit recommendation to others","insight","Explicit recommendation to others","27 (7.38%, HIGH), mean 4.81","none","praise"),
 (37,"#13 Home Screen widget requested","feature","Home Screen widget requested","16 (4.37%, very strong), mean 4.19","must-have","complaint"),
 (38,"#14 Dark mode requested","feature","Dark mode requested","15 (4.10%, very strong), mean 4.67","must-have","complaint"),
 (39,"#15 Flexible frequency requested","feature","Flexible frequency requested","14 (3.83%, very strong), mean 4.14","must-have","complaint"),
 (40,"#16 No habit-count cap praised","monetization","No habit-count cap praised","12 (3.28%, very strong), mean 4.92","product-rule","praise"),
 (41,"#17 Statistics / charts praised","feature","Statistics / charts praised","10 (2.73%, meaningful), mean 4.60","build-free","praise"),
 (42,"#18 Data / history loss","must-never-break","Data / history loss — the lowest-rated theme of any size","9 (2.46%, meaningful), mean 2.11","must-never-break","churn"),
 (43,"#19 Notification / reminder defect","must-never-break","Notification / reminder defect","6 (1.64%, meaningful), mean 3.17","must-never-break","complaint"),
 (44,"#20 Support unreachable or unanswered","must-have","Support unreachable or unanswered","5 (1.37%, meaningful), mean 2.00","must-have","complaint"),
 (45,"#21 Cannot edit a habit after creation","must-never-break","Cannot edit a habit after creation (2024 only)","4 (1.09%, meaningful), mean 2.00","must-never-break","complaint"),
 (46,"#22 Cannot reorder / sort habits","feature","Cannot reorder / sort habits","4 (1.09%, meaningful), mean 4.00","free","complaint"),
 (47,"#23 More colours / customisation requested","feature","More colours / customisation requested","4 (1.09%, meaningful), mean 4.75","free","complaint"),
 (48,"#24 Quantity / unit tracking requested","feature","Quantity / unit tracking requested","4 (1.09%, meaningful), mean 4.50","undecided","complaint"),
 (49,"#25 End-date / no-end-date control requested","feature","End-date / no-end-date control requested","4 (1.09%, meaningful), mean 4.00","undecided","complaint"),
 (50,"#26 Anxiety that the app will stop being free","insight","Anxiety that the app will stop being free","4 (1.09%, meaningful), mean 5.00","product-rule","mixed"),
 (51,"#27 Student / child / budget context","audience","Student / child / budget context","4 (1.09%, meaningful), mean 5.00","do","praise"),
 (52,"#28 Stop reminders after completion (request)","feature","Stop reminders after completion (request)","3 (0.82%, emerging), mean 5.00","must-have","complaint"),
 (53,"#29 Rating prompt fires too early","dont","Rating prompt fires too early","3 (0.82%, emerging), mean 4.00","dont","complaint"),
 (54,"#30 'Web indexing' opt-in rejected","must-never-break","'Web indexing' opt-in rejected — 100% 1★","3 (0.82%, emerging), mean 1.00","dont","1★-burst"),
 (55,"#31 Too basic vs competitors","contradiction","Too basic vs competitors — the mirror image of the largest positive theme","3 (0.82%, emerging), mean 3.00","none","complaint"),
 (56,"#32 iCloud sync / account / backup requested","feature","iCloud sync / account / backup requested","3 (0.82%, emerging), mean 4.67","must-have","complaint"),
 (57,"#33 Richer statistics views requested","feature","Richer statistics views requested","3 (0.82%, emerging), mean 4.00","undecided","complaint"),
 (58,"#34 Mental-health / recovery context","audience","Mental-health / recovery context","3 (0.82%, emerging), mean 4.67","do","praise"),
 (59,"#35 ADHD / neurodivergence context","audience","ADHD / neurodivergence context","3 (0.82%, emerging), mean 4.33","do","mixed"),
 (60,"#36 Notes per habit requested; #37 time ordering / timestamps requested; #38 explicitly willing to pay or donate","feature","Notes per habit (2), time ordering / timestamps (2), explicitly willing to pay or donate (2)","2 / 2 / 2 (0.55%, emerging)","research","mixed"),
]
for seq, w, kind, claim, mag, d, react in T:
    c(seq, f"§3.1 Master table {w}", kind, claim, "see §3.1", react, mag, d, "theme-table signal", "yes", [])
c(61, "§3.1 Master table #39–#55 weak rows (1 each) — app will not launch (1★); completion sound cannot be muted (1★); could not add more than one habit (3★); asks whether data is the hidden price; believes a premium tier exists; no account / no email praised; per-habit streaks; stats export; shared habits; in-app rewards (2★); emoji on habits; bad-habit mode; cannot change app language; back-dating habits; daily mood rating; font disliked; public plea for support", "data-caveat",
  "Single-record rows: app will not launch (1★); completion sound cannot be muted (1★); could not add more than one habit (3★); asks whether data is the hidden price (5★); believes a premium tier exists (5★); no account / no email praised (5★); per-habit streaks requested; stats export requested (4★); shared habits for accountability; in-app rewards (2★); emoji on habits; bad-habit / quit mode; cannot change app language (5★); back-dating habits; daily mood / wellbeing rating; font disliked (5★); public plea for support to respond (4★)", "see §3.1", "mixed", "17 single-record rows", "none", "weak (anecdotes)", "yes", [])
c(62, "§3.2 P1 — zero cost: three overlapping sub-themes ('free' 121, no ads 60 at mean 4.90, no subscription/IAP 44 at mean 4.98 — the highest mean of any theme of size); the framing is relief and disbelief ('I feel like they're losing money…'; 'too goood to be true'; 'this app has not gone the way of capitalism and sold out'; 'Thank the Lord for this app') — a brand promise, not a feature list", "insight",
  "Zero cost is the defining theme, in three overlapping sub-themes — the word 'free' (121, 33.06%), the absence of ads (60, 16.39%, mean 4.90), the absence of a subscription/IAP/paywall (44, 12.02%, mean 4.98 — the highest mean of any theme of size) — framed as relief and disbelief rather than satisfaction: 'Yes it really is free!'; 'I'm just here to say this app is so perfect and free, I feel like they're losing money…'; 'too goood to be true'; 'Can't believe it's free'; 'this app has not gone the way of capitalism and sold out'; 'Thank the Lord for this app'; 'Kostenlos und voll umfänglich' — a brand promise, not a feature list", "free", "praise", "172 (46.99%); no-sub sub-theme mean 4.98", "product-rule", "high-priority", "yes",
  ["11668806995","13478561515","13719409474","13628332072","11813083900","13664505292","11402735091","11444836560","12174401255","12266898528","12354816211","12569356304","12829927902","12965689848","13044013224","13415167873","13490562375","13595921255","13613572970","13706027522","13838754294","13908186370","13962928441","14041958995","14253731512","14302347258","14349454186","14412953614","14432719449","14471259071","14497877998"])
c(63, "§3.2 P2 — simplicity is framed as the absence of things users were subjected to elsewhere ('doesn't bombard you with stupid questions and a billion pop ups'; 'No BS app'; 'for us folks who get overwhelmed with too many customization options'; 'Everything that you need, nothing that you don't'); one 4★ reads the same trait as a limitation ('It's VERY basic'); simplicity and zero cost are the same story — 'this app is not trying to extract something from me' — so any added complexity carries reputational cost beyond UX cost", "insight",
  "Simplicity (119, 32.51%, mean 4.80) is consistently framed as the absence of things reviewers have been subjected to elsewhere — onboarding quizzes, upsell screens, feature bloat: 'I finally found a habit tracker app which doesn't bombard you with stupid questions and a billion pop ups' (AU); 'No BS app without too many unnecessary complications'; 'simple to use for us folks who get overwhelmed with too many customization options'; 'Everything that you need, nothing that you don't'; 'no bells and whistles'; one 4★ reads the same trait as a limitation ('It's VERY basic, so if you're looking for more options in an app, it's not for you'); simplicity and zero cost are the same story told twice — both read as 'this app is not trying to extract something from me' — so any added complexity carries reputational cost beyond its UX cost",
  "no quiz, no upsell, no bloat", "praise", "119 (32.51%), mean 4.80", "product-rule", "high-priority", "yes",
  ["13246295251","13627010760","13631120155","13390452161","11624371093","11922911236","11581883661","12337158790","12856070826","12930469783","12972332540","13236988214","13513275431","13595335326","13877425702","14181244719"])
c(64, "§3.2 P4 — behaviour change: checkable outcomes ('in only 3 months I had a great basketball body… I never forget anymore'; 'I remember scrambling day to day, unfocused, & ungrounded'; 'Without this game I was always late to work'; 'less than a week and I see a change forming'); deliberately inclusive pattern, magnitude not precision", "insight",
  "Behaviour change (38, 10.38%, mean 4.87): checkable outcomes rather than generic satisfaction — 'Kept me motivated and in only 3 months I had a great basketball body… I never forget anymore'; 'It has truly changed my life. I remember scrambling day to day, unfocused, & ungrounded'; 'helped me rebuild my good habits while breaking my bad ones'; 'I actually stick to my routines more, which is a miracle tbh'; 'Without this game I was always late to work'; 'It's been less than a week and I see a change forming'; the pattern is deliberately inclusive, for magnitude not precision", "n/a", "praise", "38 (10.38%), mean 4.87", "none", "high (context)", "yes",
  ["13724677117","12079225449","13435869648","13933385748","11765500247","12097192081","11492021762","11568840222","11628196381","11931278202","12269619388","12361078445","12481241464","13153646941","13279086279","13505454774","13664505292","13731135008","13832226279","14162234071","14368828196"])
c(65, "§3.2 P6 — statistics: the one 'advanced' surface users praise unprompted ('bar graphs, pie chart the individual and total analysis sooo damn perfect'; 'Completed days rings are great') and ask to be extended (all-time records, monthly/yearly grid, a graph widget) — the safest place to add depth without violating the simplicity promise", "feature",
  "Statistics (10, 2.73%, mean 4.60) is the one 'advanced' surface users praise unprompted — 'the bar graphs, pie chart the individual and total analysis sooo damn perfect' (IN); 'its statical measure of my progress is also easy to interpret' (UG); 'Completed days rings are great' (AU); 'even shows stats!' — and three separate reviewers want more of it (all-time records, a monthly/yearly grid, a graph widget); the safest place to add depth without violating the simplicity promise",
  "free stats: bar, pie, rings, weekly", "praise", "10 (2.73%), mean 4.60; 3 want more", "build-free", "meaningful", "yes",
  ["13143629702","12308098235","13628332072","12430964746","12089896129","12204928662","12528474609","12604107314","13922902193","13970235286","13460543209","14297251498","13764364876"])
c(66, "§3.3 N3 — notification lifecycle: three faults in one subsystem — reminders never fire ('Defeats the purpose. Completed waste of time', 1★); deleted reminders keep firing ('Deleting the habit and remaking it doesn't fix this'; survives delete/reinstall); changed times don't take ('continue to ping at the original time after I've changed it'); plus 3 requests to stop reminding after completion — the schedule is written once and never reconciled against the habit's state; two faults surviving reinstall points at scheduled local notifications not being cancelled", "must-never-break",
  "Notification/reminder lifecycle (6, 1.64%, meaningful, mean 3.17): three distinct faults in one subsystem — reminders never fire ('Notification will not go off even though they are turned on in my phone setting and app. Defeats the purpose. Completed waste of time', 1★; 'I set the reminder but app doesn't remind me'); deleted reminders keep firing ('I deleted a reminder time… I still get a notification then. Deleting the habit and remaking it doesn't fix this'; 'Have tried delete/reinstall but it still keeps sending notifications for tasks no longer on my list'); changed times don't take ('the notifications continue to ping at the original time after I've changed it, then turned them off'; 'So painful'); a further 3 (0.82%, mean 5.00) ask to stop reminding about a habit already marked done; these nine records describe one coherent problem — the notification schedule is written once and never reconciled against the habit's current state — and two faults surviving a delete-and-reinstall point at scheduled local notifications not being cancelled",
  "notification schedule not reconciled with habit state", "complaint", "6 (1.64%), mean 3.17 + 3 requests (mean 5.00)", "must-never-break", "meaningful", "yes",
  ["12615584327","12735108537","13684390333","13853485546","13599829482","14164366682","11725303303","12945403197","14072264089"])
c(67, "§3.3 N5 — cannot edit a habit after creation: 4 reviews, all between 14 Jul and 7 Nov 2024 ('once you add a habit you can't edit it anymore'; 'You can't even edit the name of a habit after you create it'), two of them 1★; a May 2025 reviewer says the opposite — a real 2024 gap that was fixed, retained because it cost four early ratings and shows the pattern: a fix ships, but the reviews it caused remain on the store page forever", "must-never-break",
  "Cannot edit a habit after creation (4, 1.09%, mean 2.00): 'Useless app, once you add a habit you can't edit it anymore or set the end of challenge or even find it in the app' (GB, 1★); 'You can't even edit the name of a habit after you create it' (US, 1★); 'the lack of habit editing' (2★); 'I just wish I could edit the habits I already entered' (4★); all four dated 14 July → 7 November 2024, and a May 2025 reviewer says the opposite ('easy to navigate and easy to edit each habit/task') — a real 2024 gap that appears fixed, retained because it cost four early ratings, two of them 1★, and shows the pattern the app repeats: a fix ships, but the reviews it caused remain on the store page forever",
  "editing missing at launch, later added", "1★-burst", "4 (1.09%), mean 2.00; Jul–Nov 2024", "must-never-break", "meaningful (historical)", "yes",
  ["11782815253","11673002290","11490852349","11922911236","12622290066"])
c(68, "§3.3 N6 — cannot reorder or sort: 'This could be my perfect habit tracker if I could only reorder the list of tasks. How could something so simple be overlooked? Without it the app is virtually useless' (2★); two of four ask specifically for time ordering ('arrange the habits based on time') — sorting a day's list by reminder time satisfies three of four and needs no new data model", "feature",
  "Cannot reorder or sort (4, 1.09%, mean 4.00): 'This could be my perfect habit tracker if I could only reorder the list of tasks. How could something so simple be overlooked? Without it the app is virtually useless' (US, 2★); 'Would it be possible to re-shuffle the habits once we've written them down?' (5★); 'the habits aren't arranged with respect to time. Give an option to arrange the habits based on time' (IN, 5★); 'Add sort by feature' (IN, 4★); two of the four ask specifically for time ordering, not drag-and-drop — sorting a day's list by reminder time would satisfy three of these four and needs no new data model",
  "no reorder, no sort", "complaint", "4 (1.09%), mean 4.00", "free", "meaningful", "yes",
  ["14052990828","12587757164","12072423999","13987910930"])
c(69, "§3.3 N9 — 'too basic': 3 reviews (mean 3.00) want rewards, a multi-part task, 'more'; a 5★ frames it as a caveat ('could be a turn off for people who want something more, but for me it's perfect'); the smallest negative theme and the direct mirror of the largest positive one — three want more, 119 are here because there is less: the clearest 'do not fix' signal in the report", "contradiction",
  "'Too basic vs competitors' (3, 0.82%, mean 3.00): 'the app needs more features that other trackers have such as the ability to get rewards' (2★); 'It's VERY basic' (4★); 'It's built like a check list so you can't make a multi part task' (3★); a fourth frames it as a caveat while giving 5★ ('the simpleness of the app could be a turn off for people who want something more, but for me it's perfect'); the smallest negative theme in the corpus and the direct mirror image of the largest positive one — three people want more; 119 are here because there is less; the clearest 'do not fix' signal in the report",
  "minimal by design", "mixed", "3 (mean 3.00) vs 119 (mean 4.80)", "product-rule", "emerging", "yes",
  ["11490852349","11922911236","13848623635","13513275431"])
c(70, "§3.4 Unmet needs table (verbatim) — widget 16 (small/medium today's list; one wants a graph widget); dark mode 15 (system-following); flexible frequency 14; more colours 4 (custom colours); quantity/unit tracking 4 (steps, litres, reps); end-date control 4 ('no end date', change later); stop reminding after completion 3; iCloud sync/backup/sign-in 3 (trades against no-account praise); richer stats 3; notes per habit 2; time ordering 2; 1-each: per-habit streaks, stats export, shared habits, rewards, emoji, bad-habit mode, language switch, back-dating, mood rating", "data-caveat",
  "Unmet needs ranked, with the cheapest satisfying change: Home Screen widget 16 (4.37%, mean 4.19 — a small/medium widget showing today's list; one wants a graph widget); dark mode 15 (4.10%, 4.67 — system-following); flexible frequency 14 (3.83%, 4.14 — x/week untethered from weekdays, every-other-n, monthly, multiple completions per day); more colours / customisation 4 (custom colours); quantity/unit tracking 4 (numeric targets: steps, litres, reps); end-date control 4 ('no end date' option, changeable later); stop reminding after completion 3 (cancel the day's remaining reminders on check-off); iCloud sync/backup/sign-in 3 (optional iCloud backup — trades against praise for no account); richer stats views 3 (all-time records; monthly/yearly grid); notes per habit 2; time ordering/timestamps 2 (sort the day by reminder time); one each: per-habit streaks, stats export, shared/social habits, in-app rewards, emoji icons, bad-habit mode, app language switch, back-dating, daily mood rating",
  "n/a", "complaint", table("## 3.4 Unmet needs — ranked"), "none", "corpus-level fact", "yes", ["13764364876","12141452926"])
c(71, "§3.4 The widget has the lowest mean of any request (4.19) and the only 2★, from a user on a competitor ('Check Me') precisely because it has a widget, waiting to switch — the only absent feature with demonstrated substitution behaviour attached", "feature",
  "The widget request has the lowest mean of any request theme (4.19) and is the only one that produced a 2★ — from a user who uses a competitor, 'Check Me', precisely because it has a widget and is waiting ('I don't use this app right now, but it has the potential to get me switch from check me. I will wait for sometime for the widget to arrive'); two more withhold stars for it; the widget is the only absent feature in this corpus with demonstrated substitution behaviour attached — a user naming a competitor they are using instead", "no widget", "churn", "16; one 2★; 2 withhold stars", "must-have", "very strong", "yes",
  ["12043735920","12204928662","13628525201"])

with open("Tools/prd_ledger/29/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
