"""Cards for report 29 — Part 7 (country), Part 8 (trends), Part 9 (implications)."""
import json, re
R = 29
rep = open("App Store Reports/29. Habit Tracker - Daily Goals - Motivation & Accountability (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(90, "§7.1 Distribution (verbatim table) — US 201 (4.443), IN 57 (4.895) eligible; GB 26, CA 19, AU 13, BR 9 (3.778), DE 6, KE 3, seven with 2, eighteen with 1; 33 storefronts, only two clear 50", "market",
  "Storefront distribution: US 201 (54.9%, mean 4.443) and India 57 (15.6%, 4.895) are the only two ≥50; GB 26 (4.577), CA 19 (4.526), AU 13 (4.769), BR 9 (3.778), DE 6 (4.167), KE 3 (4.667); CL, CN, MX, NG, PH, RU, VN 2 each; AE, AR, AT, CH, EG, ES, FR, IL, IT, JP, KR, MN, PT, SA, UA, UG, UZ, ZA 1 each — 33 storefronts", "n/a", "mixed", table("## 7.1 Distribution"), "none", "corpus-level fact", "app-specific", [])
c(91, "§7.2 United States (verbatim table) — n=201, mean 4.443 (lowest eligible); zero-cost 48.26%; comparison shopping 17.41%; any bug 17.41%; calendar bug 14.43% — 29 of 37 global reports (78.4%) vs a 54.9% corpus share; median body 123 chars; the over-index is most plausibly reporting behaviour, not a US-specific defect (date arithmetic is locale-independent; Brazil and Chile reported it too)", "market",
  "United States (n=201, 54.9%, mean 4.443): zero-cost praise 48.26% (≈ global), simplicity 33.83%, comparison shopping 17.41% (above 14.21%), any bug 17.41% (above 12.57%), calendar bug 14.43% (above 10.11%), behaviour change 13.43%, UI praise 12.94%, requests 13.43% (below 16.39%), widget 4.48%, habit-cap praise 4.48%, data loss 2.49%, dark mode 2.99% (below); the US carries 29 of 37 calendar-bug reports (78.4%) against a 54.9% corpus share and has the longest median body (123 characters); the over-index is most plausibly reporting behaviour rather than a US-specific defect — the bug is locale-independent date arithmetic and Brazil and Chile reported it too; the US mean is the lowest of any large storefront as a direct arithmetic consequence of carrying 29 calendar-bug reviews at 2.95",
  "n/a", "mixed", table("## 7.2 United States"), "none", "very strong", "app-specific", ["12225388457","12493412514","13337918653","13594048622"])
c(92, "§7.3 India (verbatim table) — n=57, mean 4.895, 89.5% 5★, median 71 chars, 93% post-2024; zero bugs; dark mode 8.77% (2.9× global), flexible frequency 7.02%; gratitude framed around access ('Salute to the developer'; 'this masterpiece'); the single most detailed feature request (dark mode/themes, stats export to PNG/PDF/Sheets, sort-by, social sign-in); India's zero bugs should not be read as no bugs — not comparable as satisfaction, but its dark-mode rate is the single strongest country-level feature signal", "market",
  "India (n=57, 15.6%, mean 4.895, 89.5% 5★ vs 73.6% US; median body 71 vs 123 characters; 53 of 57 post-2024): zero-cost praise 47.37%, simplicity 29.82%, requests 21.05% (above 16.39%), UI praise 15.79%, dark mode 8.77% (2.9× global), flexible frequency 7.02% (1.8×), comparison shopping 5.26% (below), stats praise 5.26%, any bug 0.00%, calendar bug 0.00%; the voice is gratitude framed around access ('Thank you for making it free! You're doing a great service to students who cannot afford to spend on applications'; 'this good deed of urs for humanity is outstanding'; 'Salute to the developer'; 'thank you to developers for creating this masterpiece'); the single most detailed feature request in the corpus is Indian — dark mode/themes, stats export to PNG/PDF/Sheets, sort-by, and social sign-in; India's zero bug reports should not be read as India experiencing no bugs (shorter, post-fix-era reviews; no mechanism by which date arithmetic spares one storefront), so 4.895 is not comparable to the US 4.443 as satisfaction — but India is comparable as a demand signal, and its dark-mode rate is the single strongest country-level feature signal in the report",
  "n/a", "praise", table("## 7.3 India"), "do", "meaningful", "app-specific",
  ["12133935681","13143629702","13490562375","13922902193","13788344889","13897083789","13681701955","12568250547","12461644084","11723366610","12548926052","12919657449","13987910930","14254134741","12204928662","12699325873","13480035328","13624270960"])
c(93, "§7.4 High-spend group (US, GB, CA, AU, DE, JP, FR, KR, CH, AT, IT, ES, IL, SA, AE; a priori) n=275 (75.1%), mean 4.484, any bug 15.3%, zero-cost 48.0% vs rest n=91, mean 4.758, bug 4.4%, zero-cost 44.0% — high-spend markets rate 0.27 lower and report bugs 3.5× more while praising zero cost at a nearly identical rate: the zero-cost appeal is not a low-income-market phenomenon, it is uniform", "market",
  "High-spend markets (defined a priori from conventional high-ARPU storefronts — US, GB, CA, AU, DE, JP, FR, KR, CH, AT, IT, ES, IL, SA, AE; not derived from the data): n=275 (75.1%), mean 4.484, any bug 15.3%, zero-cost praise 48.0%, requests 14.9% vs all other markets n=91 (24.9%), mean 4.758, bug 4.4%, zero-cost 44.0%, requests 20.9% — high-spend markets rate the app 0.27 stars lower and report bugs 3.5× more often while praising the zero-cost model at a nearly identical rate; the zero-cost appeal is not a low-income-market phenomenon, it is uniform — what differs is the willingness to file a detailed complaint; for a product whose commercial question is 'can anything be sold here', the uniformity across income bands is the more consequential half",
  "n/a", "mixed", table("## 7.4 High-spend market group"), "product-rule", "group-level", "yes", [])
c(94, "§7.5 High-review-volume group (verbatim table) — top five US, IN, GB, CA, AU = 316 (86.3%, a disclosed proxy, not downloads); GB highest simplicity 42.3%; CA data loss 10.5% (2 of 19); AU zero-cost 69.2% and comparison shopping 53.8%; the zero-cost theme is 42–69% in every one of the top five — the most consistent finding in the report", "market",
  "Top five storefronts by review count (a disclosed proxy for market presence, not downloads): US 201 (4.443, bug 17.4%, zero-cost 48.3%, requests 13.4% — carries 78.4% of calendar-bug reports); IN 57 (4.895, 0.0%, 47.4%, 21.1% — dark mode 8.77%); GB 26 (4.577, 3.8%, 46.2%, 19.2% — highest simplicity rate 42.3%); CA 19 (4.526, 15.8%, 42.1%, 15.8% — data loss 10.5%, 2 of 19); AU 13 (4.769, 15.4%, 69.2%, 15.4% — comparison shopping 53.8%, 7 of 13) = 316 (86.3%); the zero-cost theme is present at 42–69% in every one of the top five — the most consistent finding in the report, holding across every income level, language and review-length profile",
  "n/a", "praise", table("## 7.5 High-review-volume market group"), "product-rule", "very strong", "app-specific", [])
c(95, "§7.6 Sub-50 limited evidence — Brazil (n=9) lowest-rated storefront at 3.778 with 3 of 9 calendar-bug reports and 2 total data losses, Portuguese is supported so not localisation; Australia (n=13) comparison shopping 53.8% and zero-cost 69.2%, all post-2025 — possibly winning an active search market", "market",
  "Limited evidence: Brazil (n=9) is the lowest-rated storefront of any size at 3.778, with 3 of its 9 reviews reporting the calendar bug and 2 total data loss (one signs off '(Brasil)' as if flagging a regional problem, one asks support to act) — Portuguese is supported per the listing so this is not a localisation failure, and n=9 could be chance; Australia (n=13) shows the corpus's highest comparison-shopping rate (53.8%, 7 of 13) alongside the highest zero-cost praise (69.2%), every review post-dating 2025 — if real, the app is winning an active search market there; n=13 cannot establish it",
  "n/a", "mixed", "br n=9, 3.778, 3 calendar, 2 data loss; au n=13, 53.8% comparison, 69.2% free", "research", "limited evidence", "app-specific",
  ["12225388457","12493412514","13337918653","12205032693","13172589582","13246295251","13628332072","13980761590","14001397712","14381720374"])
c(96, "§7.6 Language coverage (limited evidence) — the store lists 8 languages and excludes Spanish, Russian, Hindi, Arabic, Korean, Vietnamese; 8 Spanish-language reviews (UZ, CL, MX, AR, ES, US) against zero Spanish localisation, one blocked ('No puedo cambiar la lengua, ayuden me por favor'); Russian twice, both 5★ — the cheapest defensible localisation case, made from 8 records", "market",
  "Language coverage (limited evidence, n=1 each): the store lists 8 languages and excludes Spanish, Russian, Hindi, Arabic, Korean and Vietnamese; a reviewer on the Uzbekistan storefront writing in Spanish asks 'No puedo cambiar la lengua, ayuden me por favor' (5★); Spanish-language reviews also come from CL, MX, AR, ES and even the US storefront — 8 Spanish-language reviews in total against zero Spanish localisation; Russian appears twice, both 5★ — the cheapest defensible localisation case in the report, made from 8 records",
  "no Spanish/Russian localisation", "blocked-conversion", "8 Spanish-language reviews; 2 Russian; 1 blocked", "do", "limited evidence", "yes",
  ["14030455237","13463203990","13594048622","13962928441","14370833112","14305710033","14024707633","13883547720","11597240211","13688018749"])
c(97, "§7.7 Global comparison summary (verbatim table) — zero cost universal (46.99 / 48.26 / 47.37); simplicity none; any bug 12.57 / 17.41 / 0.00 (reporting behaviour, not incidence); requests India asks more; dark mode India 2.9×; widget a US/UK/AU concern (IN 1.75%); comparison shopping Anglophone (IN 5.26%)", "market",
  "Global vs US vs India: zero cost 46.99% / 48.26% / 47.37% — universal; simplicity 32.51 / 33.83 / 29.82 — no divergence; any bug 12.57 / 17.41 / 0.00 — reporting behaviour, not incidence; requests 16.39 / 13.43 / 21.05 — India asks for more; dark mode 4.10 / 2.99 / 8.77 — India 2.9× global; widget 4.37 / 4.48 / 1.75 — a US/UK/AU concern; comparison shopping 14.21 / 17.41 / 5.26 — Anglophone markets", "n/a", "mixed", table("## 7.7 Global comparison summary"), "none", "corpus-level fact", "yes", [])
# Part 8
c(98, "Part 8 method; §8.1 headline half-year series (verbatim table) — 2024H2 53 / 4.45 / calendar 9.4 / bug 11.3 / zero-cost 47.2 / requests 26.4; 2025H1 94 / 4.39 / 20.2 / 22.3 / 44.7 / 14.9; 2025H2 64 / 4.62 / 14.1 / 14.1 / 42.2 / 14.1; 2026H1 122 / 4.66 / 2.5 / 6.6 / 46.7 / 13.1; 2026H2 31 / 4.61 / 3.2 / 6.5 / 61.3 / 22.6", "timeline",
  "Headline half-year series: 2024H2 n=53, mean 4.45, 5★ 75.5%, calendar bug 9.4%, any bug 11.3%, zero-cost 47.2%, requests 26.4%; 2025H1 94, 4.39, 70.2%, 20.2%, 22.3%, 44.7%, 14.9%; 2025H2 64, 4.62, 82.8%, 14.1%, 14.1%, 42.2%, 14.1%; 2026H1 122, 4.66, 80.3%, 2.5%, 6.6%, 46.7%, 13.1%; 2026H2 31, 4.61, 80.6%, 3.2%, 6.5%, 61.3%, 22.6%; 2024H1 (n=2) never used", "n/a", "mixed", table("## 8.1 The headline series"), "none", "corpus-level fact", "app-specific", [])
c(99, "§8.2 Trend 1 — the calendar bug peaked in 2025H1 and was substantially fixed by 2026H1 (improving, high confidence): 20.2 → 14.1 → 2.5%, ~8×; mean 4.39 → 4.62 → 4.66; two residual 2026 reports are the weekday-offset face — a partial fix", "timeline",
  "Trend 1 (improving, high confidence): the calendar bug peaked in 2025H1 and was substantially fixed by 2026H1 — 20.2% → 14.1% → 2.5%, an ~8× reduction, with the corpus mean rising in step 4.39 → 4.62 → 4.66; four residual reports survive in 2026, two of them the weekday-offset face rather than the rollover face — a partial rather than complete fix; medium confidence on attributing it to a specific release", "partial date-bug fix", "praise", "20.2% → 2.5%", "must-never-break", "high", "app-specific", ["14195919004","14332675510"])
c(100, "§8.3 Trend 2 — overall bug reporting fell by two-thirds (11.3 → 22.3 → 14.1 → 6.6 → 6.5%); 1★ share 5.5% (2024) / 5.7% (2025) → 2.6% (2026)", "timeline",
  "Trend 2 (improving, high confidence): any-bug rate 11.3% (2024H2) → 22.3% (2025H1) → 14.1% → 6.6% → 6.5%; the 1★ share fell from 5.5% (2024) and 5.7% (2025) to 2.6% (2026)", "stabilised", "praise", "22.3% → 6.5%; 1★ 5.7% → 2.6%", "none", "high", "app-specific", [])
c(101, "§8.4 Trend 3 — the 'cannot edit a habit' complaint appears only in 2024 (14 Jul–7 Nov) and vanishes; a May 2025 reviewer says 'easy to edit each habit/task' (fixed, medium confidence)", "timeline",
  "Trend 3 (fixed, medium confidence): all four 'cannot edit a habit' reports fall 14 July → 7 November 2024 and a May 2025 reviewer states the opposite ('easy to edit each habit/task'); medium because absence of complaint is weaker than presence of praise, n=4", "editing added after launch", "praise", "4 in 2024, 0 after", "none", "medium", "app-specific",
  ["11490852349","11673002290","11782815253","11922911236","12622290066"])
c(102, "§8.5 Trend 4 — the 'web indexing' prompt is new and confined to 2026 (emerging; high confidence on existence — three independent reviewers in two countries describe the same mechanic in near-identical terms — low on scale)", "timeline",
  "Trend 4 (emerging): the 'web indexing' monetisation prompt is new — zero mentions before 22 May 2026, three after (22 May, 25 May, 5 Aug), all 1★; high confidence it exists and is new (three independent reviewers in two countries describe the same specific mechanic in near-identical terms, not a coincidence pattern); low confidence on its reach", "SDK prompt shipped May 2026", "1★-burst", "0 before → 3 after, all 1★", "dont", "high (existence) / low (scale)", "yes",
  ["14092044479","14103247613","14391211979"])
c(103, "§8.6 Trend 5 — zero-cost praise is not fading and spiked in the latest half-year (47.2 → 44.7 → 42.2 → 46.7 → 61.3%, n=31); durable finding: 42–49% for two full years with no downward drift despite the web-indexing prompt arriving", "timeline",
  "Trend 5 (persistent, medium confidence): zero-cost praise 47.2% → 44.7% → 42.2% → 46.7% → 61.3% (2026H2, n=31 — do not over-read the spike); the durable finding is that the theme held between 42% and 49% for two full years with no downward drift despite the arrival of the web-indexing prompt in the same period", "free reputation intact", "praise", "42–49% for two years; 61.3% latest", "product-rule", "medium", "app-specific", [])
c(104, "§8.7 Trend 6 — the request mix shifted from 'make it work' (2024H2: editing 4, frequency 5, widget 4) to 'make it nicer' (2026: 8 of 15 dark-mode and 7 of 16 widget requests); flexible frequency persists in every period and is the only request theme that never resolves", "timeline",
  "Trend 6 (persistent theme, changing content, medium confidence): 2024H2 had the highest request rate (26.4%) dominated by structural gaps — editing 4, frequency 5, widget 4; 2026 requests are dominated by polish — 8 of the 15 dark-mode requests and 7 of the 16 widget requests are 2026; flexible-frequency requests persist in every period (2024H2 5, 2025 6, 2026 3) and are the only request theme that never resolves", "n/a", "complaint", "26.4% → 13–22%; dark mode 8/15 in 2026; widget 7/16", "must-have", "medium", "app-specific", [])
c(105, "§8.8 Trend 7 — rating-prompt complaints are all recent (Aug 2025, Jan 2026, Mar 2026); the ≤50-char 5★ share is broadly flat so the corpus cannot confirm prompting increased (low confidence, n=3)", "timeline",
  "Trend 7 (emerging, low confidence): all three rating-prompt complaints (Aug 2025, Jan 2026, Mar 2026) fall in the last 13 months; the share of ≤50-character 5★ reviews is broadly flat across eras, so the corpus cannot confirm prompting increased — only that complaints about it are recent", "n/a", "complaint", "3 in 13 months", "dont", "low", "app-specific", ["13059723695","13598041567","13848623635"])
c(106, "§8.9 What did not change — zero cost the dominant driver in every half-year (42–61%); simplicity steady; flexible frequency the top unresolved gap in every period; zero purchase evidence in every period; no widget and no dark mode, requested continuously for 26 months", "insight",
  "What did not change: zero cost as the dominant value driver (42–61% in every half-year); simplicity as the second driver; flexible frequency as the top unresolved capability gap, requested in every period 2024H2 → 2026H2; the absence of any purchase evidence in every period; and no widget and no dark mode — requested continuously for 26 months and present in zero reviews", "n/a", "mixed", "26 months", "none", "corpus-level fact", "yes", [])
# Part 9
c(107, "§9.1 #1 — decide and publicly disclose the web-indexing policy: move the ask off the launch screen to after first successful use; describe plainly what is shared; make it reversible in Settings; ensure declining costs the user nothing they currently have — protects the 46.99% zero-cost reputation", "product-rule",
  "Fix #1: decide and publicly disclose the web-indexing policy — move the ask off the launch screen to after first successful use; describe in plain language what is shared; make it reversible in Settings; ensure declining costs the user nothing they currently have; 3 reviews, 100% 1★, 2 of 3 churned before first use, plus 1 unprompted privacy question — protects the 46.99% zero-cost reputation that is this app's only durable asset", "SDK gate at launch", "1★-burst", "3 (100% 1★) + 1", "product-rule", "emerging — severity", "yes",
  ["14092044479","14103247613","14391211979","13506372310"])
c(108, "§9.1 #2 — ship a Home Screen widget: 16 reviews, 1 explicit payment offer, 1 named competitor substitution; addresses 6 of 41 4★; the only absent feature with proven substitution behaviour", "must-have",
  "Fix #2: ship a Home Screen widget — 16 reviews (4.37%, very strong), 1 explicit payment offer, 1 named competitor substitution; directly addresses 6 of the 41 4★ reviews; the only absent feature with proven substitution behaviour", "no widget", "churn", "16; 1 pay offer; 1 substitution", "must-have", "very strong", "yes", ["12003653249","12043735920"])
c(109, "§9.1 #3 — ship dark mode following the system setting: 15 reviews (mean 4.67), India 8.77% — the highest-satisfaction request group, delighted users naming one thing", "must-have",
  "Fix #3: ship dark mode following the system setting — 15 reviews (4.10%, very strong, mean 4.67), India 8.77%; the highest-satisfaction request group in the corpus — delighted users naming one thing", "no dark mode", "complaint", "15, mean 4.67", "must-have", "very strong", "yes", [])
c(110, "§9.1 #4 — add flexible frequency (x/week untethered from weekdays, every-other-n, monthly, multiple completions per day); closes the one structural gap persisting across all five half-years, incl. the only feature-driven 1★", "must-have",
  "Fix #4: add flexible frequency — x times per week untethered from weekdays, every-other-n, monthly, and multiple completions per day; 14 reviews including the corpus's only feature-driven 1★ and a 2★ driven purely by a missing capability class; closes the one structural product gap that has persisted across all five half-years", "weekday checkboxes only", "complaint", "14 (3.83%)", "must-have", "very strong", "yes", ["11700402770"])
c(111, "§9.1 #5 — add a local export / backup (CSV or JSON to Files) and, separately, optional iCloud backup, keeping it account-free; converts the worst-outcome bug class into a recoverable event without costing the no-account praise if it stays local-first", "must-have",
  "Fix #5: add a local export / backup (CSV or JSON to Files) and, separately, optional iCloud backup — keep it account-free; 9 data-loss reports (mean 2.11) + 3 sync requests + the documented 'reinstall to fix the date' loop; converts the worst-outcome bug class into a recoverable event and costs nothing against the no-account praise if it stays local-first", "no export, no backup", "churn", "9 + 3", "must-have", "meaningful", "yes", ["13625278409"])
c(112, "§9.1 #6 — close the residual month-boundary bug, specifically the weekday-header offset; each such review currently costs ~2 stars", "must-never-break",
  "Fix #6: close the residual month-boundary bug, specifically the weekday-header offset — four 2026 reports, latest 22 July 2026; removes the last 2.5–3.2% drag, and each such review currently costs ~2 stars", "weekday offset residual", "complaint", "4 in 2026", "must-never-break", "high", "yes",
  ["13579197540","13594048622","14195919004","14332675510"])
c(113, "§9.1 #7 — fix notification lifecycle: cancel scheduled notifications when a habit or reminder is deleted, honour time changes, stop the day's remaining reminders once checked off; two faults survive delete-and-reinstall", "must-never-break",
  "Fix #7: fix notification lifecycle — cancel scheduled notifications when a habit is deleted or its reminder removed; honour reminder-time changes; stop the day's remaining reminders once a habit is checked off; 6 bugs (mean 3.17) + 3 requests, and two of the six faults survive delete-and-reinstall, costing ratings from users who tried to fix it themselves", "stale scheduled notifications", "complaint", "6 + 3", "must-never-break", "meaningful", "yes", [])
c(114, "§9.1 #8 — delay the rating prompt to day 7 or after ~10 completions; trades a little rating volume for reviews that contain information — the developer has almost no diagnostic feedback despite 366 reviews", "dont",
  "Fix #8: delay the rating prompt to day 7 or after ~10 completions — 3 direct complaints + 39 contentless 5★ (median 27 chars, 100% 5★) + multiple day-one reviews; trades a small amount of rating volume for reviews that actually contain information — the developer currently has almost no diagnostic feedback despite 366 reviews", "prompt on first check-off", "5★-burst", "3 + 39", "dont", "emerging", "yes", [])
c(115, "§9.1 #9 — add habit reordering and specifically sort-by-reminder-time; satisfies 3 of 4 with no new data model", "feature",
  "Fix #9: add habit reordering, and specifically sort-by-reminder-time — 4 reviews including a 2★ calling the app 'virtually useless' without it; 2 of the 4 ask for time ordering specifically; sorting by existing reminder time satisfies 3 of 4 and needs no new data model", "no reorder", "complaint", "4", "free", "meaningful", "yes", ["14052990828","12072423999","13987910930"])
c(116, "§9.1 #10 — publish a working support address and answer it; with no account and no backup the review page is the only support channel, which is why bug reports arrive as public 1★", "must-have",
  "Fix #10: publish a working support address and answer it — 5 reviews (mean 2.00), one reporting a support link they judged unsafe; with no account and no backup the review page is currently the only support channel, which is why bug reports arrive as public 1★", "no working support", "complaint", "5", "must-have", "meaningful", "yes", ["13084927585"])
c(117, "§9.2 E1 — a one-time 'Pro' unlock for widget + dark mode + flexible frequency, never touching habit count or the existing free surface: new capability can be sold to this audience, existing capability cannot (n=2 on willingness — a hypothesis)", "monetization",
  "E1: a one-time 'Pro' unlock for widget + dark mode + flexible frequency — never touch habit count, never touch the existing free surface; hypothesis: new capability can be sold to this audience, existing capability cannot; support: the only payment offer is conditional on the widget and names a lifetime structure, another offers to 'contribute', and 'no subscription' is the highest-mean sub-theme at 4.98; not a fix — n=2 on willingness to pay", "free, no paid tier", "purchase-driver", "n=2", "build-paid", "hypothesis", "yes", ["12003653249","13459746040"])
c(118, "§9.2 E2 — optional iCloud backup, off by default, no account required: backup is the top latent need behind data loss but the no-account property is itself praised; the trade-off is untested", "must-have",
  "E2: optional iCloud backup, off by default, no account required — backup is the top latent need behind data loss (9 data-loss + 3 sync requests) but the no-account property is itself praised (1 explicit); the trade-off between the two is untested in this corpus", "no backup", "mixed", "9 + 3 vs 1", "must-have", "hypothesis", "yes", ["13625278409"])
c(119, "§9.2 E3 — Spanish localisation first, then Russian: non-listed-language markets are served in English and at least one user is blocked (8 Spanish-language reviews; limited evidence)", "market",
  "E3: Spanish localisation first, then Russian — non-listed-language markets are served in English today and at least one user is actively blocked; 8 Spanish-language reviews across UZ/CL/MX/AR/ES/US against zero Spanish support; limited evidence (8 records)", "no Spanish", "blocked-conversion", "8", "do", "limited evidence", "yes", ["14030455237"])
c(120, "§9.2 E4 — extend statistics rather than adding features (all-time records, monthly/yearly grid, export): the only advanced surface praised and asked to be extended, so depth there does not violate the simplicity promise", "feature",
  "E4: extend statistics rather than adding features — all-time records, a monthly/yearly grid, export; statistics is the only 'advanced' surface users praise and ask to extend, so depth added there does not violate the simplicity promise; 10 praise (mean 4.60) + 3 extension + 1 export request — directionally safe rather than proven", "basic stats", "praise", "10 + 3 + 1", "build-free", "hypothesis", "yes", [])
c(121, "§9.2 E5 — quantity / unit tracking (steps, litres, reps) as an optional habit type, one proposing a slider; risks the simplicity 119 came for if it appears in the default flow", "feature",
  "E5: quantity / unit tracking (steps, litres, reps) as an optional habit type — 4 reviews, one proposing a slider interaction; a minority want measurement not just a checkbox; risks the simplicity that 119 reviewers came for if it appears in the default flow", "checkbox only", "complaint", "4", "undecided", "hypothesis", "yes",
  ["12204928662","12699325873","13240818406","13730591333"])
c(122, "§9.3 Research questions Part 9 #1–#6 — what fraction see the web-indexing prompt and what do they do (the highest-value instrumentation question); does the rating recover after it scales; is the India/US gap real or a length/recency artefact; would a one-time unlock convert; how many hit the calendar bug and silently deleted (losing history on the way out); does prompt timing explain the 77.6% 5★ share", "data-caveat",
  "Research questions: what fraction of users see the web-indexing prompt, whether declining degrades the app, whether it is geo-limited — the highest-value instrumentation question; whether the rating recovers after the prompt scales (post-May 4.516 is not yet informative at partial rollout); whether the India/US satisfaction gap is real or a review-length and recency artefact; whether a one-time unlock would convert (zero purchase evidence, untested); how many users hit the calendar bug and silently deleted the app, losing their history on the way out via the reinstall loop; whether prompt timing explains the 77.6% 5★ share",
  "n/a", "none", "report gives none (questions)", "research", "open questions", "yes", [])
c(123, "§9.4 What not to change — do not cap habit count (the most protected property: 12 praise it, 52 arrived because a competitor capped them); do not add features to the main flow (simplicity 119 vs 'too basic' 3, 40:1); do not require an account; do not introduce a subscription ('no subscription' is the highest-rated sub-theme at 4.98 and 4 reviewers conditioned their loyalty on its absence)", "dont",
  "What not to change: do not cap habit count — 12 reviews praise the uncapped list by name and 52 comparison shoppers arrived because a competitor capped them, the single most protected property in the corpus; do not add features to the main flow — 119 praise simplicity, 3 call it too basic, 40:1; do not require an account — one names its absence as the deciding factor, so any backup must be optional and local-first; do not introduce a subscription — 'no subscription' is the highest-rated sub-theme (44 reviews, mean 4.98) and 4 reviewers have publicly conditioned their loyalty on its absence",
  "free, uncapped, simple, account-free", "praise", "12 / 52 / 119 vs 3 / 44 at 4.98 / 4", "dont", "very strong", "yes", ["13625278409"])

with open("Tools/prd_ledger/29/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
