"""Cards for report 29 — Part 4 (calendar defect), Part 5 (ratings), Part 6 (paid/monetisation)."""
import json, re
R = 29
rep = open("App Store Reports/29. Habit Tracker - Daily Goals - Motivation & Accountability (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(72, "§4.1 Counting rules — calendar_bug counts wrong date, refusing to advance, reverting to an earlier month, misaligned weekday headers, or blocked check-off for today; date feature requests excluded; 18 removed, 3 added; final 37 (10.11%)", "data-caveat",
  "Calendar-bug counting rule: the reviewer reports the app displaying a wrong date, refusing to advance to the current day, reverting to an earlier month, misaligning weekday headers against dates, or blocking check-off for today because of any of these; requests for date-related features (end dates, monthly frequency, back-dating) and unrelated 'stuck'/'month' excluded — 18 regex candidates removed, 3 added by hand; final 37 (10.11%)", "n/a", "none", "37 of 366", "none", "method", "yes", [])
c(73, "§4.2 The month-boundary fingerprint (verbatim table) — 29 of 37 (78.4%) filed on days 28–31 / 1–3 vs 27.6% of all reviews; reviewers name the mechanism ('doesn't know whether a month has 30 or 31 days… the 31st listed twice'; 'On the last day of every month the app has no idea what day it is… April 30 defaulted to Feb 28'; 'at the end of every month the days are off by one'; 'Monday thru Sunday instead of Sunday thru Saturday but the dates go Sunday thru Saturday'; 'went backwards into April instead of forwards into July') — one defect with two faces: month-length rollover and weekday-header offset", "must-never-break",
  "The month-boundary fingerprint: 29 of 37 calendar-bug reports (78.4%) were filed on days 30, 31, 1, 2, 3 (and 28–29) against 101 of 366 reviews (27.6%) overall — the strongest single piece of forensic evidence in the report; reviewers name the mechanism themselves — 'It doesn't seem to know how to account for whether a month has 30 or 31 days… I currently have the 31st listed twice for a month'; 'On the last day of every month, the app has no idea what day it is… I opened the app this morning (April 30) and the app defaulted to Feb 28'; 'at the end of every month the days are off by one day'; 'It goes Monday thru Sunday instead of Sunday thru Saturday but the dates go Sunday thru Saturday'; 'when the month changed for me it went backwards into April instead of forwards into July'; 'a small bug on the last day of each month where I'm unable to track my habits directly on the day' (Jul 2026) — one defect with two visible faces: a month-length rollover fault and a weekday-header offset",
  "month-length and weekday-offset date arithmetic", "1★-burst", table("## 4.2 The month-boundary fingerprint"), "must-never-break", "high", "yes",
  ["13460543209","12603431541","12299968183","12715196508","12835530003","14332675510"])
c(74, "§4.3 Rating impact (verbatim table) — calendar bug is 43.8% of all 1★, 66.7% of 2★, 62.5% of 3★, 24.4% of 4★, 1.4% of 5★; mean 2.95 vs 4.73; four 5★ reviewers reported it anyway ('A month of awesome, but then it wouldn't show me today's date'; title 'No dates available after Nov29 2025' with 'Great app') — the product is liked, the defect separable, loyal users say both", "insight",
  "Calendar-bug rating impact: 7 of 16 1★ (43.8%), 6 of 9 2★ (66.7%), 10 of 16 3★ (62.5%), 10 of 41 4★ (24.4%), 4 of 284 5★ (1.4%); mean 2.95 vs 4.73 for every other review; four 5★ reviewers reported the bug anyway — 'A month of awesome, but then it wouldn't show me today's date'; a review titled 'No dates available after Nov29 2025' whose body says 'Great app and love to be able to contribute to use it' — the product is liked, the defect is separable, and the most loyal users say both at once",
  "n/a", "1★-burst", table("## 4.3 Rating impact"), "must-never-break", "high", "yes",
  ["12255251536","12257572119","13459746040","14332675510"])
c(75, "§4.4 Where it turns into data loss — the sequence: the date breaks → the user reinstalls as a workaround → history gone because there is no backup ('deleted/redownloaded it and reentered all my habits. No luck'; 'Update- waited til the next day and app was back to normal just sad I lost my data from uninstalling it'; 'I just wish I didn't have to delete and reinstall it every 30 days for the calendar to work'); the reviews taught users that reinstalling fixes the date, and reinstalling destroys their data — the bug fix alone does not close the loop, an export/backup path does (three independent requests)", "must-have",
  "Where the calendar bug turns into data loss: the sequence is consistent — the date breaks → the user tries delete-and-reinstall as a workaround → the history is gone because there is no backup — 'I tried restarting the app and my phone, and even deleted/redownloaded it and reentered all my habits. No luck' (2★); 'I tried deleting it and adding habits again but still stuck on 1/30… Update- waited til the next day and app was back to normal just sad I lost my data from uninstalling it' (5★); 'I just wish I didn't have to delete and reinstalled it every 30 days for the calendar to work' (4★); 'When I manually moved it to July, it did not keep track of my habits and I would've had to re-enter them all again' (3★); the most actionable inference in the report: the app's own reviews taught users that reinstalling fixes the date, reinstalling destroys their data, and the bug fix alone does not close this loop — an export or backup path does, and three independent reviewers requested one",
  "reinstall workaround wipes local-only data", "churn", "9 data-loss; 4 reinstall narratives; 3 backup requests", "must-have", "interpretation", "yes",
  ["12604107314","12257572119","11789546578","12961148231","13276697912","13721332313","13987910930"])
c(76, "§4.5 Time trend (verbatim tables) — 2024 9.1% → 2025 17.7% → 2026 2.6%; half-year 9.4% → 20.2% → 14.1% → 2.5% → 3.2%; ~8× reduction between 2025H2 and 2026H1 as the corpus mean rose 4.473 → 4.487 → 4.647; 2026 survivors (Jan, Jan 'está desfasado', Jun 'dates/days don't line up', Jul 'last day of each month') show the weekday-offset face not fully fixed", "timeline",
  "Calendar-bug time trend: by year 2024 5/55 (9.1%) → 2025 28/158 (17.7%) → 2026 4/153 (2.6%); by half-year 2024H2 9.4% → 2025H1 20.2% → 2025H2 14.1% → 2026H1 2.5% → 2026H2 3.2%; the corpus mean tracks the fix — 4.473 → 4.487 → 4.647; the rollover fault appears substantially fixed between 2025H2 and 2026H1 (~8× reduction), but the weekday-offset face is not fully fixed — 2026 survivors on 1 Jan, 4 Jan (CL, 'está desfasado' / 'it's offset'), 18 Jun (AU, 'the dates/days in the calendar don't line up') and 22 Jul (US, 'the last day of each month'); high confidence on the trend, medium on attributing it to a specific release (no version field)",
  "rollover fixed ~2026H1; offset residual", "praise", table("## 4.5 Time trend") + " ; " + table("| Half-year | Rate |"), "must-never-break", "high (trend) / medium (cause)", "yes",
  ["13579197540","13594048622","14195919004","14332675510"])
# Part 5
c(77, "Part 5 ratings table (verbatim) — 5★ 77.6% (zero cost 53.9% of band, simplicity 37.0%); 4★ 11.2% (a missing feature 46.3% or a bug 31.7%); 3★ 4.4% (bugs 81.3%); 2★ 2.5% (bugs 66.7%, one pure missing feature); 1★ 4.4% (bugs 62.5%, and in 2026 the privacy prompt 18.8%)", "data-caveat",
  "Per-band dominant drivers: 5★ 284 (77.6%) — zero cost (53.9% of band) and simplicity (37.0%); 4★ 41 (11.2%) — a specific missing feature (46.3%) or a bug (31.7%) against an otherwise-liked app; 3★ 16 (4.4%) — bugs, overwhelmingly (81.3%); 2★ 9 (2.5%) — bugs (66.7%), one pure missing-feature case; 1★ 16 (4.4%) — bugs (62.5%) and, in 2026, the privacy prompt (18.8%)", "n/a", "mixed", table("# PART 5 — RATINGS ANALYSIS"), "none", "corpus-level fact", "app-specific", [])
c(78, "§5.1 5★ — 153 (53.9%) praise zero cost, 105 (37.0%) simplicity, 48 (16.9%) arrived from another tracker, 36 (12.7%) design; only 4 (1.4%) report a bug; 39 (13.7%) contentless (median 27 chars: 'Amazing', 'Wow / And wow', 'It good trust') and several barely used it ('Only used for 2 minutes'; 'One day in'); 34 (12.0%) still ask for something — dark mode (10), widget (7) — the highest-value reviews; one 1★ whose text is 'Best :: simple and free' is almost certainly a mis-tap", "insight",
  "5★ (n=284): 153 (53.9%) praise zero cost, 105 (37.0%) simplicity, 48 (16.9%) arrived from another tracker, 36 (12.7%) the design; only 4 (1.4%) report any bug; the band has a quality problem — 39 of 284 (13.7%) carry no theme (median 27 characters: 'Amazing', 'Wow / And wow', 'Good app', 'It good trust') and a further group state they have barely used the app ('Only used for 2 minutes'; 'So far so good, but first day using it'; 'One day in'; 'I've just downloaded it and already love it'); 34 of the 284 (12.0%) still ask for something, most often dark mode (10) or a widget (7) — delighted users naming the exact next thing, the highest-value reviews in the corpus; an anomaly the other way: a 1★ whose entire text is 'Best :: simple and free' is almost certainly a mis-tap, the clearest reason not to read the 1★ band (n=16) as 16 dissatisfied users",
  "n/a", "praise", "153 / 105 / 48 / 36; 4 bugs; 39 contentless; 34 still ask", "do", "corpus-level fact", "yes",
  ["11509187562","13594303114","13677716681","13575726176","13250604014","14058540814","13172589582","12512584748","14459698931","14141227686","11700084840","14001397712","13890862557"])
c(79, "§5.2 4★ — the 'one thing away' band: 19 of 41 (46.3%) request a feature and 13 (31.7%) report a bug; three name the exact withheld star (widget; dark mode 'what's missing for 5 stars'; rating prompt too early); wants: widget 6, flexible frequency 8, dark mode 5, notification fixes 3, calendar fix 10 — shipping widget, dark mode and flexible frequency addresses 19 of 41 four-star reviews directly", "insight",
  "4★ (n=41) is the 'one thing away' band — 19 of 41 (46.3%) contain a feature request and 13 (31.7%) report a bug, the highest request rate of any band; three name the exact star they withhold and why ('1 star removed as widget is not available'; dark mode 'is what's missing for 5 stars'; '-1 star for not giving me enough time to use the app before rating'); wants: widget 6, flexible frequency 8, dark mode 5, notification fixes 3, calendar fix 10 — 4★ is where this product's roadmap is written: a widget, dark mode and flexible frequency address 19 of the 41 directly",
  "n/a", "complaint", "19/41 requests; 13/41 bugs", "must-have", "corpus-level fact", "yes", ["12204928662","14024707633","13598041567"])
c(80, "§5.3 3★ — 13 of 16 (81.3%) report a bug, 10 the calendar bug: an almost pure bug-report channel from users who like the app ('I really love this app. The calendar has a glitch'; 'I LOVE this app, BUT it updated yesterday and lost ALL my Habits'); there is no 'meh' segment — 3★ means 'I like this and it broke'", "insight",
  "3★ (n=16): 13 (81.3%) report a bug and 10 (62.5%) the calendar bug specifically — an almost pure bug-report channel from users who like the app ('I really love this app. The calendar has a glitch'; 'I LOVE this app, BUT it updated yesterday and lost ALL my Habits'; 'Love it but stopped working'; 'now it is stuck in January'); the three non-bug 3★ are a missing widget, the rating prompt plus multi-part tasks, and a habit-add failure; there is no 'meh' segment in this corpus — 3★ means 'I like this and it broke'", "n/a", "complaint", "13/16 bugs; 10/16 calendar", "must-never-break", "corpus-level fact", "yes",
  ["13261739634","12959121316","13579197540","12252902482","13628525201","13848623635","14163084101"])
c(81, "§5.4 2★ — six of nine are the calendar bug; the other three: a missing widget with a named competitor, missing editing plus rewards, missing reordering ('Without it the app is virtually useless'); 3 of the 9 still praise zero cost in the same review", "insight",
  "2★ (n=9): six are the calendar bug; the other three are a missing widget with a named competitor ('Check Me'), missing editing plus missing rewards, and missing reordering ('Without it the app is virtually useless'); 3 of the 9 still praise zero cost in the same review, and one adds the support-path complaint", "n/a", "complaint", "6/9 calendar; 3/9 still praise free", "must-never-break", "corpus-level fact", "yes",
  ["11676955165","12604107314","12835530003","12837138619","13084927585","13577309961","12043735920","11490852349","14052990828"])
c(82, "§5.5 1★ table (verbatim) — calendar bug 7, data loss 4 (overlapping), web-indexing privacy prompt 3, cannot edit habit 2, notifications never fire 1, missing frequency option 1, app will not launch 1 ('Lässt sich nichtmal öffnen'), apparent mis-rating 1; not one 1★ is about price; all 11 one-stars in 2024–25 are functional, and of 5 in 2026, 3 are the privacy prompt — the app fixed its way out of one 1★ driver and introduced another", "timeline",
  "1★ (n=16): calendar bug 7; data loss 4 (overlapping); 'web indexing' privacy prompt 3; cannot edit habit 2; notifications never fire 1; missing frequency option 1; app will not launch 1 ('Lässt sich nichtmal öffnen' / 'It won't even open', DE); apparent mis-rating with positive text 1; two structural observations — not one 1★ in 366 records is about price (there is no price to object to), and the composition changed completely between eras: all 11 one-star reviews from 2024–2025 are functional (9 bugs, 2 missing capabilities), while of the 5 one-star reviews in 2026, 3 are the privacy prompt, 1 a launch failure and 1 the apparent mis-tap — the app fixed its way out of one 1★ driver and introduced another",
  "fixed calendar bug; added bandwidth-sharing prompt", "1★-burst", table("## 5.5 One star"), "dont", "high", "yes",
  ["12130015583","12132074900","12253431387","12254692368","12493412514","12602757554","13337918653","11673002290","14092044479","14103247613","14391211979","11782815253","12615584327","11700402770","14402480049","13890862557"])
# Part 6
c(83, "§6.1 Who is identifiable as a payer — nobody: 0 of 366 (sweep for paid/bought/purchased/subscribed/refund/restore returns zero); the listing confirms no IAP — this is not a gap in the data, it is the finding: no observable revenue relationship with any reviewer", "data-caveat",
  "Nobody in the corpus is identifiable as a payer — 0 of 366; a sweep for 'i paid', 'i bought', 'i purchased', 'i subscribed', 'my subscription', 'refund', 'restore purchase' and 'bought the' returns zero hits and the listing confirms no in-app purchases exist; this is not a gap in the data — it is the finding: the app has no observable revenue relationship with any of its 366 reviewers, and no conversion, ARPU or refund rate is computed or estimable", "free, no IAP", "none", "0 of 366", "none", "corpus-level fact", "app-specific", [])
c(84, "§6.2 What users say they would pay for — 2 (0.55%, mean 5.00): 'Just please add widget support happy to pay for a lifetime subscription' (conditional on the most-requested missing feature, and lifetime not recurring); 'love to be able to contribute' (in a review titled with a bug); hypothesis: willingness here is for a one-time or tip-style payment attached to a visible new capability, not a subscription on existing functionality — supported by 'no subscription' being the highest-mean sub-theme (4.98)", "monetization",
  "Two reviews (0.55%, emerging, mean 5.00) express willingness to pay: 'Absolutely amazing app. Just please add widget support happy to pay for a lifetime subscription ❤️' (GB, 5★) — conditional on the single most-requested missing feature and naming a lifetime structure rather than recurring; 'Great app and love to be able to contribute to use it' (US, 5★) — framed as a contribution in a review whose title is a bug report; two data points cannot support a pricing decision, but they support a hypothesis worth testing — the willingness that exists is for a one-time or tip-style payment attached to a visible new capability, not a subscription attached to existing functionality — with a third signal: the highest-mean sub-theme in the report is 'praises the absence of a subscription' (4.98 across 44)",
  "no paid tier", "purchase-driver", "2 (0.55%), mean 5.00", "build-paid", "emerging (n=2)", "yes", ["12003653249","13459746040"])
c(85, "§6.3 What users say they will not tolerate — 4 (1.09%, mean 5.00) pre-emptively warn against monetising while giving 5★ ('I will continue to use this app as long as it doesn't try to mark up the price from free'; 'I hope that it will last free of ads and subscriptions'; 'as long as this continues I'm gonna use this app every day'; 'Love the work never change') — its most enthusiastic users have publicly conditioned their loyalty on the absence of monetisation: a strong asset and a hard ceiling", "insight",
  "Four reviews (1.09%, meaningful, mean 5.00) pre-emptively warn against monetising, unprompted, while giving 5★ — 'I will continue to use this app as long as it doesn't try to mark up the price from free' (US); 'I hope that it will last free of ads and subscriptions ☀️' (FR); 'I haven't been forced into a subscription to use it and as long as this continues I'm gonna use this app every day' (US); 'Only app to have no ads or subscriptions!! Love the work never change' (AU) — the clearest statement of the commercial trap: the most enthusiastic users have publicly conditioned their loyalty on the absence of monetisation, a strong asset and a hard ceiling at the same time",
  "free", "praise", "4 (1.09%), mean 5.00", "product-rule", "meaningful", "yes",
  ["11813083900","11639983783","14041958995","12965689848"])
c(86, "§6.4 The actual monetisation and the reaction (verbatim table) — GB 22 May 2026 existing user now blocked ('now interrupts use unless you agree'); US 25 May never got past the opening screen; US 5 Aug never got past the opening screen ('You PAID for this free app'); larger than 0.82% because it is the only theme with a 100% 1★ rate, two of three churned before first use (the silent version of that cohort is invisible), and it inverts the app's entire value proposition", "must-never-break",
  "The actual monetisation and the reaction: a launch-screen prompt asking users to enable 'web indexing' — routing third-party web requests through their device and IP — for an ad-free experience; GB, 22 May 2026, an existing user now blocked ('now interrupts use unless you agree'); US, 25 May 2026, never got past the opening screen; US, 5 Aug 2026, never got past the opening screen ('You PAID for this free app'); three things make it larger than 0.82% — it is the only theme with a 100% 1★ rate (nothing else, not data loss at 2.11 nor the calendar bug at 2.95, produces uniform bottom-rating); two of three churned before first use, and a review corpus cannot see the silent version of that cohort; and it inverts the app's entire public value proposition ('You PAID for this free app' is the opposite of the 172 zero-cost reviews; 'No thanks.')",
  "bandwidth-sharing SDK gate on first launch", "1★-burst", table("## 6.4 The actual monetization"), "dont", "emerging — severity", "yes",
  ["14092044479","14103247613","14391211979"])
c(87, "§6.4 Counter-evidence with equal force — across 62 reviews from 1 May 2026 only 3 mention the prompt while 28 (45.2%) praise no ads / no subscription, including six in Aug–Sep 2026; post-May mean 4.516 vs 4.552; either a subset rollout, skippable, or geo-limited — the corpus cannot resolve it; both conditions hold simultaneously, which is exactly when a disclosure decision is cheapest", "data-caveat",
  "Counter-evidence stated with equal force: across the 62 reviews dated 1 May 2026 or later only 3 mention the prompt while 28 (45.2%) praise the absence of ads or subscriptions — including six posted in August and September 2026 and one in July — and post-May mean is 4.516 against 4.552; either the prompt is rolled out to a subset, or it is skippable and most skip it without comment, or it is geo-limited — the corpus cannot resolve it; what it does establish is that everyone who hit it rated 1★, two abandoned immediately, and as of September 2026 the public reputation is still 'actually free' — both conditions hold simultaneously, which is exactly the situation in which a disclosure decision is cheapest to make",
  "partial rollout", "mixed", "3 of 62 vs 28 of 62 (45.2%); 4.516 vs 4.552", "research", "interpretation", "app-specific",
  ["14381720374","14403840586","14432719449","14437514738","14493599797","14497877998","14312607560"])
c(88, "§6.5 Barriers to any future upgrade — (1) the reputation itself: 172 built on no cost, a paywall converts the largest asset into the largest liability on the review page; (2) the grievance comparison shoppers arrived with — paywalls and habit caps ('they all made me pay for more than 3 habits'); (3) no account and no sync — no restore path, no cross-device entitlement, and adding an account costs the no-email praise ('I didn't even have to list my email sold me'); (4) a support channel that does not work — charging without a working support address converts every billing question into a public 1★", "insight",
  "Anything sold here must survive four things the corpus already establishes: (1) the reputation — 172 reviews (46.99%) built on 'no cost, no ads, no subscription', so a paywall converts the app's largest asset into its largest liability and the review page becomes where it happens; (2) the grievance comparison shoppers arrived with — 52 named paywalls and habit caps as why they left the last app ('they all made me pay for more than 3 habits'), so a habit cap would be the exact betrayal they are primed to punish; (3) no account and no sync — no identity layer, so no restore path, no cross-device entitlement, no way to make a purchase feel durable, and one reviewer praises exactly that ('the fact I didn't even have to list my email sold me'), so adding an account for billing has its own cost; (4) a support channel that does not work — five report no reply and one an unsafe support link; charging money without a working support address converts every billing question into a public 1★ review",
  "free, no account, no support", "blocked-conversion", "172; 52; 1; 5", "product-rule", "interpretation", "yes",
  ["12152186871","13625278409","13084927585"])
c(89, "§6.6 A defensible monetisation test (hypotheses, n=2 on willingness) — sell the widget, not the tracker (the one payment offer is attached to it, it is the most-requested feature, and the only absent feature with substitution to a competitor; a one-time unlock for widget + dark mode + flexible frequency touches nothing existing users have); never cap habit count; make the web-indexing choice explicit, reversible, plainly explained and never a gate on first launch — move the ask to after first successful use", "product-rule",
  "A defensible monetisation test, stated as hypotheses because n=2 on willingness to pay: sell the widget, not the tracker — the one explicit payment offer is attached to the widget, it is the most-requested feature (16), and the only absent feature with demonstrated substitution to a competitor, so a one-time unlock for widget + dark mode + flexible frequency touches nothing any existing reviewer currently has; never cap habit count — 12 praise the uncapped list by name and it wins comparison shoppers; make the web-indexing choice explicit, reversible and clearly explained, and never a gate on first launch — both users who rejected it did so at the opening screen before seeing the product, so moving the ask to after first successful use and describing it plainly costs nothing and is the only change in this section supported by direct evidence rather than inference",
  "free; SDK gate at launch", "mixed", "n=2 willingness; 16 widget; 12 no-cap; 3 SDK 1★", "build-paid", "hypothesis", "yes",
  ["12003653249","12043735920","14103247613","14391211979"])

with open("Tools/prd_ledger/29/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
