# -*- coding: utf-8 -*-
"""Stage 3 merge for report 84 (Habit Tracker - HabitGrid, Edvard Adam Eros)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text

ext("C061", " Report 84 (HabitGrid, 86 reviews, 4.93★, no IAP at all): the free model is the reason 45.35% of reviewers give (U:free_model_any 39: MODEL_FREE 30, NO_ADS 12, NO_PAYWALL 7, VS_PAID 7, UNLIMITED 3), stable at 44–47% in every era through a language-mix change from 23% to 77% non-English — 'the one reason that does not depend on who is writing'; reviewers thank the developer for keeping it free ('the dev has generously made it free'; 'a big thank-you for keeping it free and without ads'); the free model is usually one item in a list of reasons alongside simplicity, the grid, widgets and fast replies.")
ext("C007", " Report 84 (HabitGrid): unlimited habits with no IAP — 'most of them only let you make around 4 habits before tealling you to pay. This one let me make as many as I wanted (10 so far)!'; two Russian reviewers searched 'a very long time' for a free app 'with unlimited habits and a clear chart'; U:paywall_contrast 16 (18.60%), all 5★, sets the app against the category's cap-then-pay default.")
ext("C214", " Report 84 (HabitGrid): the counter-case from the free side — 'Why anyone would be pay a monthly sub for an app like habitkit, which offers no benefit over this app, I haven't a clue' (5★); a developer 'sat down to write a similar app because the alternatives have paid subscriptions… I downloaded it and immediately closed Xcode' — a free, uncapped, ad-free grid tracker is the reference point the category's subscriptions are now compared against.")
ext("C246", " Report 84 (HabitGrid): MODEL_NO_ADS 12 (13.95%) cite 'no ads' as a reason for their rating; 'because it has no ads and no paying' (vi); §8.4 adding ads would contradict a stated reason 12 reviewers give.")
ext("C082", " Report 84 (HabitGrid): the no-ads, no-IAP counter-case — zero price or ad complaints in 86 reviews, all 23 price hits and 9 ad hits are praise.")
ext("C001", " Report 84 (HabitGrid): the pre-emptive form of the rule — a free app whose terms reserve the right to 'charge for their services at any time'; two reviewers make continued use conditional on it staying free ('I really hope it stays free, otherwise I will have to find a different habit tracker'; 'I hope it won't become a subscription, or at least that there will be an option to buy it once!'); §8.4 'charge for new capability, never for the free core' — do not cap habits, move widgets or statistics behind payment, or add ads; test an optional one-time purchase or tip for unshipped extras (watch, cloud backup, advanced frequency), announced in advance; 'the baseline is zero'.")
ext("C133", " Report 84 (HabitGrid): 'the distinction the corpus supports is between charging for what users already have (which is what they chose the app for) and charging for things they have asked for and do not yet have' — watch app, cloud backup, frequency modes are the only asks and none exists yet.")
ext("C003", " Report 84 (HabitGrid): the only payment model any reviewer proposes for a free app is a one-time purchase ('or at least that there will be an option to buy it once!'); zero volunteer a subscription; two reject subscription pricing for the category.")
ext("C104", " Report 84 (HabitGrid): §8.4 — if a charge is ever introduced, announce it in advance and measure the review stream for the first price complaints; the terms already reserve charging while the listing and reviews say free.")
ext("C006", " Report 84 (HabitGrid): 'simple' and 'complete' are praised together, not traded off — U:simplicity 40 (46.51%): 'Everything you need, and nothing more… no fancy or overly complicated features'; 'A laconic, simple tracker, and yet it has everything you need'; 'more simplistic, but it still has needed features, like reminders'; two US reviewers name feature bloat elsewhere as why they chose it ('too many features for my liking'); §8.8 do not add features for their own sake; the grid is named less often than simplicity (16 vs 40).")
ext("C178", " Report 84 (HabitGrid): 'Nothing superfluous, aesthetic, beautiful, intuitive. What I was looking for!' (ru); 'without extra noise'; OUT_FOUND_IT 15 (17.44%) — the search ended here; ACQ_TRIED_MANY 16.")
ext("C012", " Report 84 (HabitGrid): the grid is the app's name — 'remind me of github, very beautiful'; 'progress by day, week, for the year, clear statistics, beautiful visualisation. You can mark progress for past days and add a note. Ideal'; 'It is very motivating when you see your progress for the year'; U:visual_progress 16 (18.60%), free.")
ext("C234", " Report 84 (HabitGrid): week / month / year statistics are free and among the top three concrete strengths (PRAISE_STATS_VIEWS 9); a yearly percentage counted from the habit's start rather than the year is the one stats complaint (arguably a design choice; §8.2 an option rather than a fix).")
ext("C009", " Report 84 (HabitGrid): free interactive widgets are the third concrete strength (PRAISE_WIDGETS 8: 'keep a widget on my home screen, and tick the specific habit… and that's it!') and the only feature on both sides — 2 of the 7 problem reports involve them (a counter increment landing on the next day; only one widget with one habit); a reviewer asked for widgets five months after the first widget praise; §8.4 do not move widgets behind payment.")
ext("C040", " Report 84 (HabitGrid): 'incrementing a counter through the widget doesn't increase the count, or increases the count for the following day (possibly a time zone mismatch?)' (4★) — the most detailed bug report in the corpus, from a reviewer who calls widgets 'a huge plus'; 'can't add several widgets with different habits — it only gives one… please tell me how' (5★); widget praise stops in the final era (8 → 0).")
ext("C038", " Report 84 (HabitGrid): DEF_DATE_LOGIC 2, the only defect reported twice — a tick on Saturday or Sunday 'fills in/unfills both days'; a widget increment lands on the following day; both week/day-boundary errors; 1.0.19 'Custom week start' touches week boundaries and whether it fixes either is not established; §8.2 test completion writes across the week boundary, across time zones, and from widgets.")
ext("C142", " Report 84 (HabitGrid): MISUNDERSTAND_EXISTING 2 — a 4★ warns 'all your data will be deleted if you change your phone' while the listing advertises 'IMPORT AND EXPORT… restore it at any time' and zero reviews mention it; another asks for widgets five months after they were praised; 'discoverability problems, not missing features'; §8.3 surface export in onboarding and settings before building accounts — 'the cheapest change that answers both reviews'.")
ext("C020", " Report 84 (HabitGrid): import/export exists per the listing and is mentioned by zero of 86 reviews; the one data-safety warning and the one account request both come from users who did not find it.")
ext("C034", " Report 84 (HabitGrid): no actual data loss in 86 reviews; one warning it could happen on a phone change (4★) and one request for an optional account for backup — for a local-only app the fear itself costs a star.")
ext("C035", " Report 84 (HabitGrid): the no-account counter-case — 'No sign-in. No servers. No cloud.' is a headed section of the listing, praised for privacy, and the cost is one 4★ who believes data dies with the phone and one request for an optional account; the website mentions opt-in authentication and cloud backups that appear nowhere else.")
ext("C085", " Report 84 (HabitGrid): 'PRIVACY FOCUSED — No sign-in. No servers. No cloud.' is credited by two reviewers ('only anonymized data collection'; 'doesn't collect huge amounts of data') and questioned by none — but the privacy label lists analytics identifiers/usage/diagnostics, the policy is template text naming IP, approximate location, Amplitude and marketing, and the website offers cloud backup; §8.1 make the four sources agree: 'the risk is to a positioning that two reviewers already credit, not to a current complaint'.")
ext("C218", " Report 84 (HabitGrid): the listing understates the product — Languages: English only while 1.0.9 'Added languages', 62.79% of reviews are non-English and a Vietnamese UI is in use; 'No servers. No cloud.' contradicts the analytics label; the website's opt-in cloud backup is absent from the listing; §8.1 four text fixes, none a product change.")
ext("C027", " Report 84 (HabitGrid): release 1.0.9 'Added languages' (2025-10-29) was followed by a 2.7× rise in review rate (2.65 → 7.09 per 30 days) and a new dominant market — zero Russian-language reviews before it, 39 of 73 after, Russia now 43% of reviews and 44% of public ratings, all 5★ ('the best tracker in Russia'); the listing still says English only.")
ext("C255", " Report 84 (HabitGrid): a Vietnamese reviewer praises that the interface 'has Vietnamese' on a storefront where the listing advertises English only; Russian is written on five storefronts including us and ca.")
ext("C094", " Report 84 (HabitGrid): an in-app review prompt in every version since 1.0.1 (2025-07-03; 1.0.6 'Love the app? Now it's easier to leave a review') — 83 of 86 reviews postdate it, yet neither prompt release is followed by a rise in review rate; the rise follows localisation: 'the prompt alone does not explain the volume'.")
ext("C076", " Report 84 (HabitGrid): the soft form — six of the first 13 reviews come from the developer's home region (Romania 4, Hungary 2), two authors carry the developer's surname, none from either storefront appears after month five, and the website's testimonials ('John Harris', 'Maria Smith') match no App Store reviewer; disclosed not adjudicated; excluding the six moves the corpus mean 0.005★; §8.7 'the earliest ratings are the least independent… store rules on reviews from the developer's own circle should be checked, and the website testimonials should be real or removed'.")
ext("C231", " Report 84 (HabitGrid, 86 reviews): the zero-gap case — corpus 4.930★ vs public 4.939★ over 311 ratings (+0.009), every large storefront within 0.12★; 'the corpus is a complete census of text reviews and, on rating, is not distinguishable from the silent majority'; zero 1–2★ text reviews in 451 days (the only trace of a very dissatisfied user is one textless US 1★); 28 one-line 5★ (32.56%), all five-star; no churn statements; no storefront reaches 50.")
ext("C300", " Report 84 (HabitGrid): the no-gap baseline — +0.009★ between public and text means for a free app with no billing surface; the two-star gap in report 82 is a billing-surface artefact, not a property of star ratings.")
ext("C239", " Report 84 (HabitGrid): U:dev_relationship 25 (29.07%), every one 5★ — 'we need more developers like this'; 'the poor guy works on it alone ❤️'; the gratitude is for keeping the app free and localising it (17 of 37 Russian reviews thank the developer, none of them report a reply).")
ext("C059", " Report 84 (HabitGrid): DEV_RESPONSIVE 4 — 'send him a bug report, expect to hear back in <24 hours'; 'I suggested adding a watch app; I talked to the developer, he replied quickly and said he would try'; no review reports being ignored; the request → release record is visible: frequency requests 5 before 'Smarter habit goals', 0 of 27 after; categories praised 21 days after shipping.")
ext("C043", " Report 84 (HabitGrid): REQ_FREQUENCY 5 (5.81%), the only recurring request, in five variants (N per week without fixed days, specific weekdays, every N days, monthly, custom interval), one attaching rating elasticity ('if it appears, this app will have no equal'); all five predate 1.0.15 'Smarter habit goals' and none of the 27 reviews after repeats it; §8.5 check each variant against the shipped goals — where present, the fix is discoverability.")
ext("C022", " Report 84 (HabitGrid): REQ_WATCH 2 (2.33%), both recent; the developer told one reviewer he would try; 'two requests do not justify building one' — check the developer's own Discord/Reddit where requests are cheaper.")
ext("C058", " Report 84 (HabitGrid): the only acquisition channel named in 86 reviews is an LLM — 'GPT suggested I look at this app' (ru 5★) — plus one App Store search; no ad, article or social post is named; the developer runs Discord, Reddit, TikTok, Instagram, X and LinkedIn and none surfaces in a review.")
ext("C140", " Report 84 (HabitGrid): USE_NON_HABIT — a Russian reviewer uses it to remember watering plants; one moved from Apple Reminders 'to keep track how many times I actually completed them'.")
ext("C005", " Report 84 (HabitGrid): HabitKit named as the paid comparison ('a monthly sub for an app like habitkit, which offers no benefit over this app'); a near-identical name that is paid ('HabitGrid - Goal tracker' by another developer) exists on the store; Apple Reminders is the tool replaced.")
ext("C278", " Report 84 (HabitGrid): a near-identical paid app ('HabitGrid - Goal tracker', 2023) shares the name; a reviewer distinguishes this one as the free one — a name collision that so far works in the free app's favour.")
ext("C202", " Report 84 (HabitGrid): REQ_SOCIAL 1 (shared habits with friends); §8.8 do not prioritise.")
ext("C031", " Report 84 (HabitGrid): one launch failure 12 days after release ('worked pretty well for the first 7 days and then just stopped opening', the only 3★), never repeated; zero crash or freeze vocabulary since; §8.8 no stability overhaul.")
ext("C010", " Report 84 (HabitGrid): marking past days is praised ('You can mark progress for past days and add a note. Ideal').")
ext("C172", " Report 84 (HabitGrid): notes shipped in 1.0.5 and were praised eight months later; 'add a note' is part of the ideal described by a 5★.")
ext("C045", " Report 84 (HabitGrid): categories shipped in 1.0.14 and were praised 21 days later ('great that there are categories'); archiving shipped in 1.0.13 unmentioned.")
ext("C062", " Report 84 (HabitGrid): the defined high-spend group (25 reviews) mentions the free model and paywall contrast far more than everyone else (64.0% vs 37.7%; 32.0% vs 13.1%) — the 'no cap, no subscription' argument is a high-spend-market argument; the high-volume group is Russia's profile (gratitude, short reviews, frequency requests).")
ext("C130", " Report 84 (HabitGrid): the developer's home region (Romania/Hungary) supplied 6 of the first 13 reviews and then went silent — a launch cohort, not a market.")
ext("C185", " Report 84 (HabitGrid): 'aesthetic, beautiful, intuitive'; PRAISE_FLEXIBLE 6 (colours, icons, look — 'personalise to your taste'); design praise rides with simplicity rather than standing alone.")
ext("C261", " Report 84 (HabitGrid): colours and icons are customisable and praised (PRAISE_FLEXIBLE 6); one defect — icons in iOS's transparent/clear icon appearance.")
ext("C170", " Report 84 (HabitGrid): 1.0.19 'Custom week start' shipped after two week-boundary defects (a weekend tick toggling both days).")
ext("C024", " Report 84 (HabitGrid): weekly and monthly streaks shipped in 1.0.16 and no review mentions them; the year grid, not a streak, is what reviewers call motivating.")
ext("C097", " Report 84 (HabitGrid): §8.4 — if revenue is needed, test an optional one-time purchase or tip for unshipped capabilities rather than gating the free core.")

M = {
 "R84-001":["C012","C009","C178"], "R84-002":["C231"], "R84-003":["C231","C300"], "R84-004":["C094","C231"], "R84-005":["C076","C130","C231"],
 "R84-006":["C061","C007","C214","C246","C082"], "R84-007":["C006","C178","C012","C009"], "R84-008":["C001","C104","C003"], "R84-009":["C085","C218","C035","C027"], "R84-010":["C038","C040","C142","C031","C034","C261"],
 "R84-011":["C043","C022","C059","C202","C035"], "R84-012":["C027","C130","C231"], "R84-013":["C082","C031","C020"], "R84-014":["C059","C172","C045","C024","C170","C005"], "R84-015":["C231","C061","C006"],
 "R84-016":["C061","C246","C214","C239"], "R84-017":["C006","C178"], "R84-018":["C012","C234"], "R84-019":["C009","C040","C142"], "R84-020":["C239","C059"],
 "R84-021":["C178","C005","C058","C140","C278"], "R84-022":["C231"], "R84-023":["C038","C040","C031","C234","C142","C020","C034"], "R84-024":["C043","C022","C202","C035"], "R84-025":["C085"],
 "R84-026":["C231"], "R84-027":["C231","C038","C142"], "R84-028":["C082","C231"], "R84-029":["C061","C007","C214","C006"], "R84-030":["C003","C001"],
 "R84-031":["C001","C133","C007","C246","C003","C097"], "R84-032":["C231","C300"], "R84-033":["C239","C130","C062","C027"], "R84-034":["C062"], "R84-035":["C255","C218","C027"],
 "R84-036":["C027","C094","C231"], "R84-037":["C061","C239","C231"], "R84-038":["C043","C059","C076","C130"], "R84-039":["C218","C085","C255"], "R84-040":["C038","C040","C009","C261"],
 "R84-041":["C142","C020","C034"], "R84-042":["C001","C133","C097","C246","C007"], "R84-043":["C043","C022","C076"], "R84-044":["C031","C202","C006","C059"], "R84-045":["C239","C130"],
 "R84-046":["C214","C007","C006"], "R84-047":["C027","C218","C255"],
}
M["R84-024"] += ["C185"]; M["R84-001"] += ["C185"]; M["R84-018"] += ["C010"]
cards = [json.loads(l) for l in open("Tools/prd_ledger/84/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/84/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 84" in x["statement"] and not any(k.startswith("R84-") for k in x["cards"])])
