"""Cards for report 27 — Part 6 (country), Part 7 (trends), Part 8 (implications)."""
import json, re
R = 27
rep = open("App Store Reports/27. Goal Streak - Habit Tracker - Build a growth mindset, daily (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

# Part 6
c(52, "§6.1 Eligibility — no country qualifies (US max 43); §6.2 Full storefront table (verbatim, all 23, all limited evidence)", "market",
  "No storefront reaches the 50-review threshold (US 43, IN 19, CA 15, AU 11, CN 7, GB 7, DE 6, PH 4, SE 4, MX 3, six with 2, seven with 1) so the report is global-only; every country observation is limited evidence presented for a future larger extraction to test",
  "n/a", "mixed", table("## 6.2 Full storefront table"), "none", "limited evidence", "app-specific", [])
c(53, "§6.3 High-volume markets (≥10 reviews: US, IN, CA, AU = 88, 63.77%) table (verbatim) — the US carries the dissatisfaction (5 of 11 sub-4★, lowest mean 4.53, 5 of 9 widget complaints); India most simplicity-first (47%), zero design or outcome praise, short price-aware reviews; Canada most satisfied (4.87) and the only source of both tip-jar requests; Australia highest free-praise (55%) and design-praise (36%), zero complaints", "market",
  "Limited-evidence observations on the four ≥10-review markets: the US carries the corpus's dissatisfaction — 5 of the 11 sub-4★ reviews, the lowest mean (4.53), and 5 of the 9 widget complaints; India is the most simplicity-first market (47% vs 26% US) with zero design-aesthetic praise and zero outcome statements — short, functional, price-aware reviews ('Thanks a lot for making it free'; 'Found a good one among who ask so much'); Canada is the most satisfied (4.87, 14 of 15 at 5★) and the only source of both tip-jar requests — where a voluntary-payment experiment should start; Australia has the highest free-praise (55%) and design-praise (36%) rates and zero complaints",
  "n/a", "mixed", table("## 6.3 High-review-volume markets"), "none", "limited evidence", "app-specific",
  ["13169445559","13338573061","13414248154","13608165763","14239313970","10942093874","11527965143","13463476864","10787472094","11393669723"])
c(54, "§6.4 High-spend markets (US, JP, GB, CA, AU, DE, FR, CN = 92, 66.67%, mean 4.641) vs rest (46, mean 4.652) — indistinguishable; the app is not rated differently in high-spend markets; per-market table (verbatim)", "market",
  "High-spend markets (US 43 + CA 15 + AU 11 + CN 7 + GB 7 + DE 6 + JP 2 + FR 1 = 92, 66.67%, mean 4.641) against all other storefronts (46, mean 4.652) are indistinguishable — Goal Streak is not rated differently in high-spend markets; per market: US 4.53 (lowest, all widget complaints), CA 4.87 (both tip-jar requests), AU 4.82 (zero complaints), CN 4.00 (lowest of any market with ≥5), GB 4.86 (one regression), DE 4.83 (both Monday-week-start requests German-market or German-language), JP 5.00 (one switched from Streaks), FR 5.00",
  "n/a", "mixed", table("## 6.4 High-spend markets"), "none", "limited evidence", "app-specific", ["13215630472","10966990397","10795403293","13903934801"])
c(55, "§6.4 China — the most interesting limited-evidence signal: all 7 Chinese reviews are 4★ or below on average (4.00) and 4 of 7 are feature requests or regression complaints (month view, year-progress %, crash, note-export regression, annual-grid demotion + backfill loss); Chinese reviewers engage as power users and are the group most damaged by the 2025 restructure — a hypothesis, not a finding", "market",
  "China (n=7, mean 4.00 — the lowest of any market with ≥5 reviews): 4★×4, 5★×2, 2★×1, and 4 of the 7 are feature requests or regression complaints — month view, year-progress %, a 2023 crash, the note-export regression and workflow loss, the annual-grid demotion and backfill loss; only two are pure praise; Chinese reviewers engage with the app as power users — naming specific views, export workflows and backfill mechanics — and are the group most damaged by the 2025 restructure; a hypothesis for a larger extraction, not a finding",
  "n/a", "complaint", "n=7, mean 4.00; 4 of 7 requests/regressions", "research", "limited evidence (n=7)", "app-specific",
  ["8918509405","8882537119","10639973409","13178799590","13077199701","9631112670","14165879048"])
c(56, "§6.5 Global vs country — price sensitivity is uniform not regional (free-praise in 12 of 23 storefronts across AE, AU, CA, CZ, DE, GB, IN, NG, NL, RU, TH, US; no high-/low-income split — the anti-paywall stance is category-wide); localisation is not an issue (zero complaints; seven non-English reviews, none mentions a defect; the two week-start complaints are the only regional-convention issue); support is not an issue anywhere because nobody mentions it", "insight",
  "Price sensitivity is uniform, not regional — free-praise appears in 12 of the 23 storefronts spanning AE, AU, CA, CZ, DE, GB, IN, NG, NL, RU, TH and US with no high-income/low-income split; the anti-paywall stance is a category-wide attitude, not a market-specific one; localisation is not an issue (not one review complains about language, translation, currency or formatting; seven non-English reviews mention no defect; the two Monday-week-start complaints are the only regional-convention issue); support is not an issue anywhere because no reviewer in any market mentions support at all",
  "n/a", "praise", "12 of 23 storefronts; 0 localisation complaints; 0 support mentions", "none", "limited evidence", "yes", ["10795403293","10966990397"])
# Part 7
c(57, "§7.1 Era table (verbatim) — 2022–23 n=12 mean 4.750; 2024 29 / 4.828; 2025 55 / 4.436 (1★ 4); 2026 42 / 4.762; volume roughly doubles each year (5 → 7 → 29 → 55 → ~63 annualised) — the app is growing and the growth is accelerating in 2026 despite the 2025 dip", "timeline",
  "Eras by calendar year (2022 and 2023 merged): 2022–23 n=12 (8.70%), mean 4.750, 5★ 75.0%; 2024 n=29, 4.828, 82.8%; 2025 n=55, 4.436, 74.5% with all four 1★; 2026 (to 25 Aug) n=42, 4.762, 83.3%; review volume roughly doubles each year — 5 (2022) → 7 (2023) → 29 (2024) → 55 (2025) → 42 in eight months of 2026 (≈63 annualised) — the app is growing and the growth is accelerating in 2026 despite the 2025 quality dip",
  "n/a", "praise", table("## 7.1 Method"), "none", "corpus-level fact", "app-specific", [])
c(58, "§7.2 Theme rate by era table (verbatim) — simplicity 33.3 → 44.8 → 41.8 → 28.6 (softening); free 25.0 → 51.7 → 21.8 → 40.5 (volatile); switched-from-competitor 0 → 10.3 → 5.5 → 16.7 (rising); price contrast 8.3 → 14.3 (rising); outcomes 0 → 11.9 (rising); crash 8.3 → 0 → 7.3 → 0 (spiked, fixed); regression 0 → 9.1 → 0; widget gap 25.0 → 6.9 → 5.5 → 2.4 (declining); flexible frequency / unlimited / stats / reminders new in 2025–26; monthly view persistent; long-range view 16.7 → 0 (declining)", "timeline",
  "Theme rates by era (2022–23 / 2024 / 2025 / 2026): simplicity 33.3% → 44.8% → 41.8% → 28.6% (persistent, softening); free/no-IAP 25.0 → 51.7 → 21.8 → 40.5 (persistent, volatile); design 16.7 → 20.7 → 9.1 → 14.3; switched from competitor 0.0 → 10.3 → 5.5 → 16.7 (rising); competitor price contrast 8.3 → 6.9 → 7.3 → 14.3 (rising); behaviour-change outcomes 0.0 → 3.4 → 7.3 → 11.9 (rising); crash 8.3 → 0.0 → 7.3 → 0.0 (spiked then fixed); regression 0 → 0 → 9.1 → 0 (spiked then stopped); data-durability 0 → 3.4 → 5.5 → 0; onboarding confusion 8.3 → 3.4 → 5.5 → 0; widget gap 25.0 → 6.9 → 5.5 → 2.4 (declining); widget praise 16.7 → 3.4 → 0 → 4.8; flexible frequency, unlimited habits, stats/export and reminders praise all new in 2025–26 (features shipped); monthly view 8.3 → 0 → 3.6 → 4.8 (persistent, unresolved); Monday week start 0 → 6.9 → 0 → 0 (stopped, may be fixed); tip jar 0 → 6.9 → 0 → 0; long-range view 16.7 → 3.4 → 1.8 → 0.0 (declining)",
  "n/a", "mixed", table("## 7.2 Theme rate by era"), "none", "corpus-level fact", "app-specific", [])
c(59, "§7.3 Trend 1 — a reliability collapse in autumn 2025 and a complete recovery by 2026 [strong]: 2025-09-01 → 2026-01-31 holds 37 reviews, mean 4.162, 10 of the 11 sub-4★; every other period 101 reviews, mean 4.822, 1 sub-4★; from 2026-02-01 35 reviews, mean 4.829, zero 1★/2★ — this single window explains the entire negative history; a solo-developer app with no in-app support pays for such a break entirely in public rating", "timeline",
  "Trend 1 [strong]: a reliability collapse in autumn 2025 and complete recovery by 2026 — the window 1 Sep 2025 → 31 Jan 2026 holds 37 reviews at mean 4.162 with 10 of the corpus's 11 sub-4★ reviews; every other period combined holds 101 at mean 4.822 with 1 sub-4★; from 1 Feb 2026, 35 reviews at 4.829 with zero 1★ and zero 2★; this single window explains the entire negative history of the app — an update landing around September 2025, colliding with the iOS 26 transition, broke launch on some devices and removed or relocated features, fixed within roughly four months; a solo-developer app with no in-app support channel pays for such a break entirely in public rating",
  "OS-transition break, no support channel", "1★-burst", "37 / 4.162 / 10 sub-4★ vs 101 / 4.822 / 1; post-Feb 35 / 4.829", "must-never-break", "strong", "yes",
  ["13169445559","13178799590","13240874103","13243690627","13338573061","13414248154","13444084049","13498254162","13608165763","13642789952"])
c(60, "§7.3 Trend 2 — the 2025 update was a net feature restructure and reviewers reported both sides [strong]: gained multiple check-ins per day, flexible weekly frequency, habit reordering; lost one-tap note export, the day-tap record popup, the single-screen annual overview, backfill from the annual grid, a selectable 365-dot view; one reviewer reports a gain and a loss in one review ('the recent update is cool… but the annual overview that used to be on the same screen has disappeared')", "timeline",
  "Trend 2 [strong]: the 2025 update was a net feature restructure and reviewers reported both sides — gained: multiple check-ins per day ('the multiple check-ins per day feature is very handy'; 'I can adjust and see as much times I can do something in the day'), flexible weekly frequency ('tasks that can be completed a few times a week rather than everyday'), habit reordering; lost: one-tap note export, the day-tap record popup, the single-screen annual overview, backfill from the annual grid, a selectable 365-dot view; the same reviewer reports a gain and a loss in one review — 'the recent update is cool… but I noticed the annual overview that used to be on the same screen has disappeared'",
  "restructure with removals", "mixed", "gained 3 features (4 IDs); lost 5 (3 IDs)", "product-rule", "strong", "yes",
  ["13077199701","13987574053","13903934801","12973708986","13178799590","13215630472"])
c(61, "§7.3 Trend 3 — requested features do get shipped on a 6–18 month lag [moderate]: per-weekday flexibility (Jul 2025 → Mar 2026 praise); reordering (Sept 2024 complaint → Aug 2025 praise); Monday week start asked twice in early 2024 then never again (plausibly shipped); goal end date asked Dec 2025 → listing now lists countdown visualizations and archiving; absence of repeat complaints is weak evidence in a 138-review corpus", "timeline",
  "Trend 3 [moderate]: requested features do get shipped, on a 6–18 month lag — per-weekday flexibility requested July 2025 → weekly-frequency praise March 2026; habit reordering complained about Sept 2024 → praised as shipped Aug 2025; Monday week start asked twice in Jan–Feb 2024 → never asked again in 29 months (plausibly shipped, not confirmed); goal end date asked Dec 2025 → the listing now lists countdown visualizations for goal end dates and habit archiving; caveat: absence of repeat complaints is weak evidence of a fix in a 138-review corpus — verify against the changelog",
  "solo developer ships requests", "praise", "4 request→ship pairs", "do", "moderate", "yes",
  ["12944050597","13903934801","11762567349","12973708986","10795403293","10966990397","13498254162"])
c(62, "§7.3 Trend 4 — the year grid, once a headline differentiator, has stopped being praised [moderate]: 16.7% → 3.4% → 1.8% → 0.0%; the corpus's first review is about it ('I love how you can see the progress of an entire year'); by late 2025 it appears only as a loss; the thing the bundle ID is still named after (goalStreakCalendar) is being quietly de-emphasised and the users who valued it most noticed", "timeline",
  "Trend 4 [moderate]: the year-at-a-glance grid, once a headline differentiator, has stopped being praised — 16.7% (2022–23) → 3.4% → 1.8% → 0.0% (2026), counts 2, 1, 1, 0; the two earliest reviews in the corpus are about it ('I love how you can see the progress of an entire year, helps me keep to my goals!'; 'Most apps does not let me see the progress of my habits over the months') and by late 2025 it appears only as a loss; the 'Goal Streak Calendar' year grid — what the bundle ID is still named after — is being quietly de-emphasised and the users who valued it most are the ones who noticed; counts small, treat as hypothesis",
  "signature view demoted", "churn", "16.7% → 0.0%; counts 2/1/1/0", "product-rule", "moderate (small n)", "yes",
  ["8819961417","10477776521","13077199701","13215630472"])
c(63, "§7.3 Trend 5 — the competitive-escape narrative is strengthening [moderate]: switched 0 → 10.3 → 5.5 → 16.7%; price contrast 8.3 → 14.3%; 2026 reviews increasingly open by describing the alternatives ('I must have tried almost all the habit trackers on the App Store'; 'literally unmatched') — as the category monetises harder, Goal Streak's position sharpens without the app changing; market drift working in its favour, entirely contingent on staying free", "insight",
  "Trend 5 [moderate]: the competitive-escape narrative is strengthening — switched-from-competitor 0.0% → 10.3% → 5.5% → 16.7%, competitor price contrast 8.3% → 6.9% → 7.3% → 14.3%; 2026 reviews increasingly open by describing the alternatives ('I must have tried almost all the habit trackers on the App Store'; 'I've tried dozens upon dozens of apps and this is literally unmatched'; 'Most apps like this are really bad'; 'unlike other apps it's free') — as the category monetises harder, Goal Streak's position sharpens without the app changing; market drift working in its favour, and entirely contingent on staying free",
  "free in a subscription-ising category", "purchase-driver", "16.7% + 14.3% in 2026", "product-rule", "moderate", "yes",
  ["13903934801","13989106663","13974276382","14037309039","14118395021","13846689652","14281981627"])
c(64, "§7.3 Trend 6 — reviewers increasingly report actual behaviour change, not just app quality [moderate]: 0 → 3.4 → 7.3 → 11.9%; the cohort using the app for years now writes about outcomes rather than features — a retention signal; the review base is maturing, not churning", "insight",
  "Trend 6 [moderate]: reviewers increasingly report actual behaviour change rather than app quality — outcomes 0.0% → 3.4% → 7.3% → 11.9%, with the 2026 examples the strongest in the corpus (two years of use producing 'a much much much better person'; 'the only way i can actually be consistent'; 'it holds you accountable') — a retention signal: the cohort that has used the app for years is writing about outcomes, not features; the review base is maturing, not churning",
  "n/a", "praise", "0.0 → 3.4 → 7.3 → 11.9%", "none", "moderate", "app-specific", ["13761980153","14099500769","13923424034"])
c(65, "§7.4 What persisted unchanged across four years — free praise in every era; simplicity the most stable theme; the monthly-view gap asked in 2022, 2025, 2026 (four years, five reviewers, still open); the widget gap asked every single year; zero support mentions, zero ad complaints, zero paywall encounters", "insight",
  "Persisted unchanged across four years: free/no-IAP praise present in every era (never absent); simplicity praise the most stable theme; the monthly-view gap asked in 2022, 2025 and 2026 — four years, five reviewers, still open; the widget gap asked in every single year 2022–2026; and zero support mentions, zero ad complaints, zero paywall encounters across 138 reviews in 23 countries",
  "n/a", "mixed", "monthly 5 across 4 years; widget 9 across 5 years", "must-have", "corpus-level fact", "yes",
  ["8918509405","13155678708","13463476864","13642789952","14239313970","8865309570","9631112670","10197682121","11272404025","11937614517","13111651177","13255216161","13414248154","14088668819"])
c(66, "§7.5 One thing to watch — simplicity praise fell 41.8% → 28.6% while switched-from-competitor rose 5.5% → 16.7%; both boundary-of-minimalism reviews are recent ('still a bit simple'; 'Limited featuees' at 3★): as the app attracts refugees from feature-rich paid apps, expectations rise and 'pleasantly minimal' shades into 'missing things'; the monthly view is the first place this shows", "insight",
  "One thing to watch: simplicity praise fell 41.8% (2025) → 28.6% (2026) while switched-from-competitor rose 5.5% → 16.7% (counts 23→12 and 3→7, may be nothing) — but the two reviews marking the boundary of the minimalism virtue are both recent ('still a bit simple', Feb 2026; 'Limited featuees', 3★, Jan 2026); hypothesis: as the app attracts more refugees from feature-rich paid apps, expectations rise and 'pleasantly minimal' starts shading into 'missing things' — the monthly view is the first place this shows",
  "minimal product meeting power-user refugees", "mixed", "41.8% → 28.6%; 5.5% → 16.7%", "research", "hypothesis", "yes", ["13784793079","13642789952"])
# Part 8
c(67, "§8.1 Part 8 #1 — make the widget show real data and update (current streak, today's completion, colour change when done), then make it tappable to check off; explicit specs from reviewers ('a small widget that just showed the current streak count'; 'a streak counter like duolingo'; 'grayed out if still to do and coloured if done'); the only feature to generate a 1★ on its own; requested every year", "must-have",
  "Fix #1: make the widget show real data and update — at minimum current streak count, today's completion state and a colour change when done, then make it tappable to check off; reviewers gave the spec ('a small widget that just showed the current streak count for a single goal'; 'a streak counter on the widget like duolingo'; 'a grayed out version if it's still to do and a coloured version if it's done'); the only feature to generate a 1★ on its own ('Just says 0% ALL the time'), requested in every one of the four years; in a streak app the widget is the retention surface",
  "static, sometimes blank widget", "complaint", "9 (6.52%, high-priority)", "must-have", "high-priority", "yes",
  ["8865309570","9631112670","10197682121","11272404025","11937614517","13111651177","13255216161","13414248154","14088668819"])
c(68, "§8.1 Part 8 #2 — fix habit ordering so the chosen order persists; a shipped feature that silently fails, one user avoids it for fear of data loss", "must-never-break",
  "Fix #2: fix habit ordering so the chosen order persists — a shipped feature that silently fails; one user avoids it entirely for fear of data loss", "reorder does not stick", "complaint", "3 + 1 confirming", "must-never-break", "meaningful [THIN]", "yes", ["11762567349","13118792795","13608165763","12973708986"])
c(69, "§8.1 Part 8 #3 — make existing tags selectable and group duplicates; two storefronts, two months apart, same bug, both cost stars", "must-never-break",
  "Fix #3: make existing tags selectable and group duplicates — two storefronts, two months apart, the same bug, both cost stars", "tag picker broken", "complaint", "2", "must-never-break", "meaningful [THIN]", "yes", ["13243690627","13491426055"])
c(70, "§8.1 Part 8 #4 — stop the reminder firing for a goal already marked complete today; a notification that contradicts app state trains users to ignore notifications", "must-never-break",
  "Fix #4: stop the reminder firing for a goal already marked complete today — a notification that contradicts app state actively trains users to ignore notifications", "reminder fires after completion", "complaint", "1 (DE, 4★)", "must-never-break", "single review", "yes", ["14088668819"])
c(71, "§8.1 Part 8 #5 — fix the icon/symbol edit reverting to the original; a write that silently fails, same release window as the crashes", "must-never-break",
  "Fix #5: fix the icon/symbol edit reverting to the original — a write that silently fails, in the same release window as the crash cluster", "edit reverts", "complaint", "1 (CA, 3★)", "must-never-break", "single review", "yes", ["13498254162"])
c(72, "§8.1 Part 8 #6 — fix the dead website link in Settings; minutes of work, reported by a promoter, and it currently breaks the support path entirely", "must-have",
  "Fix #6: fix the dead website link in Settings ('it leads to an inactive domain') — minutes of work, reported by a 5★ promoter, and it currently breaks the only support path", "support link dead", "complaint", "1 (CA, 5★)", "must-have", "single review", "yes", ["11393669723"])
c(73, "§8.1 Part 8 #7 — restore the full-year grid as a selectable view and restore backfill from it; the app is literally named after this view; a 5★ reviewer still said 'I loved it before the previous update'", "product-rule",
  "Fix #7: restore the full-year grid as a selectable view and restore backfill from it — the app is literally named after this view ('Goal Streak Calendar'), four early reviewers praised it, and a 5★ reviewer still said 'I loved it before the previous update'", "demoted signature view", "complaint", "2 regression + 4 praise", "product-rule", "meaningful [THIN]", "yes",
  ["13077199701","13215630472","8819961417","10477776521","10787472094","12944050597"])
c(74, "§8.1 Part 8 #8 — restore one-tap note export and the day-tap record popup; the corpus's only 2★; one reviewer represents a workflow, not a preference", "product-rule",
  "Fix #8: restore one-tap note export and the day-tap record popup — the corpus's only 2★; a power-user workflow removal; one reviewer represents a workflow, not a preference", "removed export", "churn", "1 (CN, 2★)", "product-rule", "single review", "yes", ["13178799590"])
c(75, "§8.2 Part 8 #9 — ship a monthly view and monthly summary; the only feature request that repeatedly costs stars (2 of 6 3★); open four years across four storefronts", "feature",
  "Feature #9: ship a monthly view and a monthly summary — the app has daily, weekly and yearly and the month is missing; the only feature request that repeatedly costs stars (2 of the 6 3★), open for four years across four storefronts", "no month view", "complaint", "5 (3.62%, very strong)", "must-have", "very strong", "yes",
  ["8918509405","13155678708","13463476864","13642789952","14239313970"])
c(76, "§8.2 Part 8 #10 — make iCloud sync and backup visible and verifiable in-app ('Backed up to iCloud · last synced <time>' plus an explicit restore path); users cannot tell a shipped feature is working; one churned over presumed data loss; a communication fix, not an engineering one", "must-have",
  "Feature #10: make iCloud sync and backup visible and verifiable in-app — a Settings line 'Backed up to iCloud · last synced <time>' plus an explicit restore path; the listing confirms iCloud storage exists but users cannot tell it is working; one churned over presumed data loss and another asks the question directly in a 5★ review; a communication fix, not an engineering one", "invisible sync", "complaint", "4 + 3 sync", "must-have", "meaningful [THIN]", "yes",
  ["11762567349","13444084049","13481955817","13491588986","10655126869","11937614517","12900579642"])
c(77, "§8.2 Part 8 #11 — per-weekday scheduling ('run 1 mile per day during the week, and skip Saturday + Sunday') and streak import by start date ('the streak being automatically completed from that date'); both concrete, bounded, asked by 5★ users", "feature",
  "Feature #11: per-weekday scheduling ('I want to run 1 mile per day during the week, and skip Saturday + Sunday') and streak import by start date ('setting a start date and the streak being automatically completed from that date, moving to a new phone was a bit tedious') — both concrete, bounded, asked by 5★ users; weekly-frequency support already partially exists", "no weekday schedule; no streak import", "complaint", "1 + 1", "must-have", "single reviews", "yes", ["12944050597","13481955817","13903934801"])
c(78, "§8.2 Part 8 #12 — a 30-second skippable first-run explainer; four of five survived the confusion, one gave 1★; keep it skippable — minimalism is the product", "must-have",
  "Feature #12: add a 30-second first-run explainer that can be skipped — four of five confused reviewers survived and stayed, one gave 1★; keep it skippable because minimalism is the product (52 reviews)", "no onboarding", "mixed", "5 (3.62%)", "must-have", "very strong (n=5)", "yes",
  ["10477776521","12128390503","12146867601","13220635530","13414248154"])
c(79, "§8.2 Part 8 #13 — make the streak length readable from the day list (a full interaction spec given); #14 — a Monday week-start setting (two early-2024 requests, none since — verify whether it shipped)", "feature",
  "Feature #13: make the streak length readable from the day list — the streak is the core metric and currently requires drilling in (a full interaction spec given); Feature #14: a Monday week-start setting — two requests in early 2024 and none since, so verify whether it already shipped before building", "streak hidden in list; week start fixed", "complaint", "1; 2", "must-have", "single / [THIN]", "yes", ["11088501172","10795403293","10966990397"])
c(80, "§8.3 Part 8 #15 — add a tip jar / 'buy the developer a coffee': optional, non-blocking, dismissible, no feature attached; low risk — both requesters paired it with 'keep the app free'; gratitude is already the dominant register of the 5★ band", "monetization",
  "Monetisation #15: add a tip jar / 'buy the developer a coffee' — optional, non-blocking, dismissible, with no feature attached; two direct requests plus 10 developer-gratitude reviews (all 5★) and 'made this with joy, not for money'; low risk — both requesters paired it with 'keep the app free', and gratitude is already the dominant emotional register of the 5★ band", "no tip jar", "purchase-driver", "2 + 10", "do", "meaningful [THIN]", "yes", ["10787472094","11393669723","12936194802"])
c(81, "§8.3 Part 8 #16 — do not gate any existing capability: no habit cap, no subscription for current features, no ads, no required account; the highest-risk action available — it would invalidate the stated reason 34% chose the app, in a corpus where 9.42% arrived specifically to escape paywalls; one user is already watching", "product-rule",
  "Monetisation #16: do not gate any existing capability — no habit cap, no subscription for current features, no ads, no required account; 47 free-praise (34.06%), 13 competitor-price rejections, 4 keep-free pleas, 3 unlimited-habits praises, 12 no-ads praises, 4 privacy praises, and one user already watching ('No ads (yet, but I don't think there are any)'); the highest-risk action available — it would invalidate the stated reason 34% of reviewers chose the app, in a corpus where 9.42% arrived specifically to escape paywalls", "free, ungated", "praise", "47 + 13 + 4 + 3 + 12 + 4", "product-rule", "high-priority", "yes", ["11085682019"])
c(82, "§8.3 Part 8 #17 — if paid capability is ever needed, attach it only to something that does not exist today (Watch, Health, macOS, advanced analytics) and never move an existing feature behind it; even this should be A/B'd and framed as 'new, optional', not 'premium'", "product-rule",
  "Monetisation #17: if paid capability is ever needed, attach it only to something that does not exist today — an Apple Watch app, Health sync, a macOS app, or advanced analytics — and never move an existing feature behind it; platform requests exist (Watch, Health, macOS) and advanced-stats appetite too; moderate risk; even this should be A/B'd and framed as 'new, optional', not 'premium'", "no paid tier yet", "mixed", "3 platform + 3 stats requests", "paid", "interpretation", "yes",
  ["14001830867","13999741050","10655126869","13807267873","12146188261","13987574053"])
c(83, "§8.4 Research questions Part 8 #1–#7 — did the Sept 2025 update or iOS 26 cause the crash; is iCloud sync working for everyone (opt-in, silently failing, or invisible); did Monday start, goal end date and archiving ship; why does China rate lowest while writing the most detailed reviews; would a tip jar cannibalise goodwill; what does the silent majority think; is the year-grid de-emphasis deliberate", "data-caveat",
  "Research questions: did the September 2025 update cause the crash or did iOS 26 (two reviewers blame each — crash logs would settle it and change the release-process fix); is iCloud sync actually working for everyone (opt-in, silently failing, or just invisible); did Monday week-start, goal end date and archiving ship (the listing suggests the latter two); why does China rate lowest (4.00, n=7) while writing the most technically detailed reviews; would a tip jar cannibalise goodwill (both requests Canadian, both 2024, none since — a limited rollout with rating monitoring); what does the silent majority think (138 reviews over four years is a thin record); is the year-grid de-emphasis deliberate (if so, the trade-off was under-priced)",
  "n/a", "none", "report gives none (questions)", "research", "open questions", "yes", ["13240874103","13444084049","13338573061","13169445559","10655126869"])
c(84, "§8.5 What not to do — do not add gamification (two name its absence as why they chose it; 52 praise minimalism); do not add ads, even one interstitial (12 praise their absence); do not require an account (4 praise; no-data privacy label is part of the positioning); do not remove features without an opt-out (the 2025 restructure produced the only 2★ and cost 5★ goodwill); do not over-build ('does everything you need it to do with very little drama' is the product spec)", "dont",
  "What not to do: do not add gamification — two reviewers name its absence as the reason they chose this app ('There's not pets to take care of, there's no flashy graphics'; 'removes a direct emphasis on urgency and/or self-competition') and 52 praise minimalism; do not add ads, even a single interstitial (12 praise their absence by name); do not require an account (4 praise its absence; the no-data-collection privacy label is part of the positioning); do not remove features in updates without an opt-out (the 2025 restructure produced the only 2★ and cost goodwill from 5★ users); do not over-build — 'this app does everything you need it to do with very little drama' is the product spec: ship the widget, the month view and the sync assurance; resist the rest",
  "minimal, free, ad-free, account-free", "praise", "52 + 12 + 4; 1 2★ + 1 5★ regression", "dont", "high-priority", "yes",
  ["13807267873","13933124385","13215630472"])

with open("Tools/prd_ledger/27/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
