"""Cards for report 27 — Part 4 (ratings) and Part 5 (monetisation-forward)."""
import json, re
R = 27
rep = open("App Store Reports/27. Goal Streak - Habit Tracker - Build a growth mindset, daily (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(39, "§4.1 Distribution table (verbatim) — 5★ 109 (79.0%), 4★ 18, 3★ 6, 2★ 1, 1★ 4; substantive mean 4.594 vs 4.645; no short-review inflation (only 12 ≤25 chars, 101 >60) — a corpus of people who wrote something", "data-caveat",
  "Rating distribution 5★ 109 (79.0%) · 4★ 18 (13.0%) · 3★ 6 (4.3%) · 2★ 1 (0.7%) · 1★ 4 (2.9%), mean 4.645; restricting to substantive reviews (>60 chars, n=101) the mean is 4.594 — essentially unchanged; there is no short-review inflation problem (12 records ≤25 chars vs 101 over 60): a corpus of people who wrote something",
  "no aggressive review prompt", "praise", table("## 4.1 Distribution"), "none", "corpus-level fact", "app-specific", [])
c(40, "§4.2 1★ table (verbatim) — 4 reviews, 100% about a broken build in a five-week window (won't open after update; iOS 26 crash; widget 0% permanently; won't open and all progress lost); not one 1★ is about price, features, ads or the developer — the entire downside risk is release quality", "insight",
  "All four 1★ reviews fall between 8 Oct and 26 Nov 2025 and are about a broken build — won't open after the update ('this was one of the best apps I have had now it just doesn't work'), immediate crash on iOS 26, a widget showing 0% permanently ('If I'm missing something, then it's not very intuitive'), and won't open with all progress lost (the only stated churn); not one 1★ is about price, features, ads or the developer — Goal Streak has no structural sources of one-star reviews; its entire downside risk is release quality",
  "free app; only defects produce 1★", "1★-burst", table("### 1★ — 4 reviews"), "must-never-break", "corpus-level fact", "yes",
  ["13240874103","13338573061","13414248154","13444084049"])
c(41, "§4.2 2★ — one review, a feature removal: a power user losing a workflow (one-tap note export removed; day-tap popup gone), not a beginner failing to onboard", "anti-pattern",
  "The only 2★ is a feature removal — the one-tap note export was removed, forcing day-by-day copying, and tapping a day no longer pops up that day's record ('the overall usability after the update is worse by more than a little'): a power user losing a workflow, not a beginner failing to onboard", "removed export in an update", "churn", "1 (0.72%)", "product-rule", "single review", "yes", ["13178799590"])
c(42, "§4.2 3★ table (verbatim) — six reviews, all 'good app, one specific gap': iOS 26 crash ('Good app. Does its job.'), cannot select an existing tag, symbol edit reverts + goal end date, categorise by time of day, 'can't summarize by week or by month', 'Only con is… a monthly overview'; two of six are the monthly view — the highest-leverage feature", "insight",
  "All six 3★ reviews are 'good app, one specific gap' — the iOS 26 crash (opening with 'Good app. Does its job.'), cannot select an existing tag, symbol edit reverts plus a goal end date that preserves history, habits categorised by time of day, 'I can't summarize by week or by month', 'Only con is it would be nice if there was a monthly overview'; two of the six are the monthly-view gap — the only feature request that repeatedly costs stars, making the monthly view the highest-leverage feature on the list",
  "n/a", "complaint", table("### 3★ — 6 reviews"), "must-have", "corpus-level fact", "yes",
  ["13169445559","13243690627","13498254162","13608165763","13642789952","14239313970"])
c(43, "§4.2 4★ — the 'one small fix' band: every 4★ contains explicit praise plus exactly one named improvement ('Almost perfect'; 'Would be perfect with watch support'; 'Good app but would like to see apple health integration'); a fully specified backlog from people who like the app — 17 of 18 would plausibly become 5★ on a single shipped item", "insight",
  "Every one of the 18 4★ reviews contains explicit praise plus exactly one named improvement — titles alone tell it: 'Almost perfect', 'Great for a free app! One small fix…', '9/10 highly recommend', 'Would be perfect with watch support', 'Nice app, but two things I would recommend to add', 'Good app but would like to see apple health integration', 'great app, hoping a month view can be added'; the asks in full: Monday start, streak visibility, reorder, onboarding difficulty, journal log, better icons, theme tuner, restore the annual grid, widget progression, tags, note-taking purpose, Health, Watch, reminder logic + widget state, monthly view, year-progress %, crash, and 'found a good one among who ask so much' — a fully specified product backlog written by people who like the app; 17 of 18 would plausibly become 5★ on a single shipped item",
  "n/a", "complaint", "18 (13.0%); 18 named asks", "do", "corpus-level fact", "yes",
  ["11088501172","11762567349","12973708986","14001830867","14088668819","13999741050","8882537119","8918509405","10795403293","12128390503","12473008094","12877783902","13077199701","13255216161","13491426055","13761980153","10639973409","11527965143"])
c(44, "§4.2 5★ reasons table (verbatim, segment rates against 109) — simplicity 43.1%, free/no IAP 38.5%, design 15.6%, came from a worse/paid competitor 10.1%, no ads 9.2%, developer gratitude 9.2%, behavioural outcome 7.3%, generic 11.0%; 21 of 109 five-star reviewers still asked for something — 5★ means 'I am grateful', not 'I have no needs'; treat the 5★ band as a requirements source", "insight",
  "5★ dominant reasons (segment rate of 109 / global of 138): simplicity 47 (43.1% / 34.06%), free/no IAP 42 (38.5% / 30.43%), design 17 (15.6%), came from a worse or paid competitor 11 (10.1%), no ads 10 (9.2%), developer gratitude 10 (9.2%), stated behavioural outcome 8 (7.3%), generic-only 12 (11.0%); twenty-one of the 109 five-star reviewers still asked for something (weekday scheduling, widget, monthly view, streak import, backup recovery, dead link + donation, interactive widget + iPad sync + stay free, the 365-dot view, accidental tap) — 5★ here means 'I am grateful', not 'I have no needs'; treat the 5★ band as a requirements source, not a satisfaction ceiling",
  "n/a", "praise", table("Dominant reasons, as a share of the 109:"), "do", "corpus-level fact", "yes",
  ["12944050597","13111651177","13463476864","13481955817","13491588986","11393669723","11937614517","13215630472","12023192028"])
c(45, "§4.3 Themes in both directions (verbatim table) — widget 5 praise vs 9 gaps; simplicity 52 vs 'still a bit simple' / 'Limited featuees'; notes/journal engaging vs pointless; the 2025 update 'cool' (multi-check-in) vs the crash cluster and removals; ease of use vs 5 onboarding-confusion reviews", "contradiction",
  "Themes that cut both ways: the widget (5 praise vs 9 missing/static/blank); simplicity (52 praise vs 'still a bit simple', 'Limited featuees' at 3★, 'the note taking doesn't really have a point'); notes/journal ('simply yet engaging daily memo questions' vs pointless / export removed / wants more); the 2025 update ('the recent update is cool' for multi-check-in, in the same review that reports the year-grid regression, plus the crash cluster); ease of use (52 simplicity reviews vs 5 onboarding-confusion reviews)",
  "minimal by design", "mixed", table("## 4.3 Themes that appear in both directions"), "product-rule", "corpus-level fact", "yes",
  ["13784793079","13642789952","13761980153","12136156984","13077199701","13215630472","13178799590"])
c(46, "§4.3 Onboarding — a real first-run comprehension cost: four of five confused reviewers got past it and still rated 4–5★ ('a lil hard to figure out at first but now super easy'), the fifth did not and gave 1★; survivable for the motivated, fatal for the impatient; a 30-second first-run explainer is a low-risk fix that does not compromise minimalism", "must-have",
  "Onboarding has a real first-run comprehension cost: four of the five confused reviewers got past it and still rated 5★ or 4★ ('Took me a little while to figure out how to put in the streaks'; 'a lil hard to figure out at first but now super easy'; 'It took a few minutes for me to figure out how to navigate the different fields'), the fifth did not and gave 1★ — survivable for motivated users and fatal for the impatient; a 30-second first-run explainer is a low-risk fix that does not compromise minimalism",
  "no first-run explainer", "mixed", "5 (3.62%), mean 4.00; 4 recovered, 1 did not", "must-have", "very strong (n=5)", "yes",
  ["10477776521","12146867601","13220635530","12128390503","13414248154"])
# Part 5
c(47, "Part 5 intro — zero paid users by construction: a probe for purchase language returns 0 matches across 138 records; no trial, paywall, refund, cancellation, restore failure or billing dispute anywhere in four years", "data-caveat",
  "This app has never had a paid tier and there are zero paid users in the corpus: a direct probe for 'I paid / I bought / I subscribed / my subscription / refund' across all 138 records returns 0 matches; no trial, paywall, refund, cancellation, restore-purchase failure or billing dispute appears anywhere in four years of reviews", "free, no IAP", "none", "0 of 138", "none", "corpus-level fact", "app-specific", [])
c(48, "§5.1 What would trigger a purchase — exactly 2 reviews volunteer money unprompted (both Canadian, both 5★, both frame payment as gratitude, both pair it with keeping the app free, neither asks for a feature in return): the entire direct evidence base points at one mechanism, a voluntary tip jar", "monetization",
  "Exactly two reviews (1.45%, [THIN], mean 5.00) volunteer money without being asked — 'Keep the free app, consider adding a tip jar for users who are thankful' and 'it would be nice to donate to the dev since it's a free app'; both Canadian, both 5★, both frame payment as gratitude, both pair it with keeping the app free, and neither asks for a feature in return — the entire direct evidence base for willingness to pay, and it points at one mechanism only: a voluntary tip jar",
  "no tip jar", "purchase-driver", "2 (1.45% [THIN]), mean 5.00", "do", "meaningful [THIN]", "yes", ["10787472094","11393669723"])
c(49, "§5.2 What would block a purchase (verbatim table) — chose it because free 47; rejected a competitor over price 13; asked to keep it free 4; praised unlimited habits 3; praised no-account 4; praised no ads 12 — a self-selected anti-paywall cohort; one user is watching for monetisation ('No ads (yet, but I don't think there are any)'); a retroactive gate would land on precisely this population", "insight",
  "The indirect evidence against a gate is much larger than the evidence for a purchase: 47 chose the app because it is free (the acquisition reason, not a perk); 13 explicitly rejected a competitor over its paywall (already refused to pay in this category); 4 asked the developer to keep it free (anticipatory anxiety); 3 praised unlimited habits by name (the specific gate they fled); 4 praised no-account/no-data (rules out ad- or data-funded models); 12 praised no ads (rules out an ad tier); the most explicit refusals — 'Don't get streaks for $6. Get this! No ads (yet, but I don't think there are any)' (this user is watching for monetisation); 'no BS subscriptions'; 'without asking for my personal details and trying to get me to buy stuff'; 'doesn't pressure you to go premium' — a self-selected anti-paywall cohort; the users who chose to write about Goal Streak chose it specifically to escape paying, and a retroactive gate on existing free functionality would land on precisely this population",
  "free with no gate", "praise", table("## 5.2 What would block a purchase"), "product-rule", "high-priority", "yes",
  ["11085682019","14037309039","14118395021","13974276382","13086712965","11699207962","12146188261"])
c(50, "§5.3 Monetisation options ranked (verbatim table) — tip jar: the only option positively endorsed; paid cosmetics: plausible, untested; paid new capability (Watch, Health, Mac, advanced stats): defensible iff nothing existing moves behind it; habit cap on free: directly attacks the reason users are here; subscription for existing features: highest risk; advertising: contradicted by 12 no-ads reviews; data/required account: contradicted by evidence and the listing", "monetization",
  "Monetisation options ranked by corpus support: a tip jar / one-off 'buy me a coffee' — 2 direct requests, 10 developer-gratitude reviews, no risk observed: the only option the corpus positively endorses; paid cosmetic extras (themes, icon packs) — 10 customisation-praise reviews, low risk if existing themes stay free: plausible, untested; paid new capability (Watch, Health, macOS, advanced stats) — 4 singleton platform requests, moderate risk: defensible if and only if nothing existing moves behind it; a habit cap on the free tier — zero support, 3 praise unlimited, 47 praise free, 13 fled competitors' caps: directly attacks the stated reason users are here; subscription for existing features — zero support, 4 keep-free pleas, 13 competitor-price rejections: the highest-risk option; advertising — contradicted by 12 no-ads reviews; data monetisation / required account — contradicted by 4 privacy reviews and the listing's no-data label",
  "free; forward options", "mixed", table("## 5.3 Monetisation options ranked by what the corpus supports"), "product-rule", "interpretation", "yes", [])
c(51, "§5.4 The one observed churn event — 'It doesnt open with the update, ive lost all my progress, guess its time for a new app' — a reliability-plus-data-loss event, not a price event; churn risk is concentrated entirely in release quality and data durability", "must-never-break",
  "The one observed churn event — 'It doesnt open with the update, ive lost all my progress, guess its time for a new app. Thanks btw.' — is a reliability-plus-data-loss event, not a price event; with 'this was one of the best apps I have had now it just doesn't work', the corpus shows the app's churn risk is concentrated entirely in release quality and data durability, not in monetisation", "update broke launch and lost data", "churn", "1 stated churn; 4 1★ all reliability", "must-never-break", "corpus-level fact", "yes", ["13444084049","13240874103"])

with open("Tools/prd_ledger/27/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
