"""Cards for report 28 — Part 8 (trends) and Part 9 (product implications)."""
import json, re
R = 28
rep = open("App Store Reports/28. Habit Rabbit - Habit Tracker - Your productivity pet (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(121, "Part 8 Method; §8.1 The headline series (verbatim table) — per-year mean, 5★, 1★, ad complaint, Study Bunny, bugs, onboarding, paywall 2021–2026; buckets below n=40 flagged", "timeline",
  "Headline series by year: 2021 (Sep–Dec) n=85, mean 4.729, 5★ 83.5%, 1★ 0.0%, ads 3.5%, Study Bunny 31.8%, bugs 5.9%, onboarding 5.9%, paywall 3.5%; 2022 178, 4.180, 62.9%, 9.0%, 9.6%, 9.0%, 10.7%, 2.8%, 6.7%; 2023 106, 3.877, 50.9%, 12.3%, 12.3%, 16.0%, 11.3%, 6.6%, 8.5%; 2024 211, 3.810, 50.7%, 14.2%, 31.3%, 8.5%, 1.4%, 6.6%, 5.2%; 2025 136, 3.846, 50.0%, 11.8%, 33.1%, 3.7%, 0.7%, 2.2%, 2.9%; 2026 (to 6 Sep) 105, 4.048, 58.1%, 8.6%, 18.1%, 3.8%, 4.8%, 3.8%, 3.8%; no version field so every change is inferred from date plus testimony; buckets below n=40 (2023H2, 2025H2, 2026H2) flagged",
  "n/a", "mixed", table("## 8.1 The headline series"), "none", "corpus-level fact", "app-specific", [])
c(122, "§8.2 Trend 1 — ads emerged 2021, escalated 2024H2, partially retreated 2026 (worsening then improving, high confidence); five independent longitudinal reviewers report a real increase; the 2026 decline is the clearest good news in the corpus", "timeline",
  "Trend 1 (high confidence): ads emerged 2021, escalated 2024H2, partially retreated 2026 — half-year rate 3.5% → 11.9% → 7.4% → 11.8% → 13.2% → 22.0% → 39.6% → 34.4% → 32.6% → 18.8% → 16.7%; five independent longitudinal reviewers report a real increase; the 2026 decline is supported by 105 records across both halves and is the clearest good news in the corpus", "ad load raised then eased", "mixed", "39.6% peak → 16.7%", "dont", "high", "yes",
  ["9016620744","11585029310","12646697365","12891214594","13565718990"])
c(123, "§8.3 Trend 2 — the launch honeymoon ended in 2022 and never returned (high confidence): 2021 had 83.5% 5★ and zero 1★; by 2024 50.7% and 14.2%; the launch cohort was Study Bunny loyalists on cross-promotion, explicitly forgiving because the app was in beta ('Best beta app ever'); that grace period is gone", "timeline",
  "Trend 2 (high confidence): the launch honeymoon ended in 2022 and the app never regained it — 2021 had 85 reviews, 83.5% five-star and zero one-star; by 2024 the 5★ share was 50.7% and 1★ 14.2%; the launch cohort was overwhelmingly Study Bunny loyalists arriving on cross-promotion and explicitly forgiving because the app was in beta ('Best beta app ever'; 'the fact that it is still in beta means it will probably just get better'); that grace period is gone",
  "beta goodwill from a sibling-app cohort", "churn", "83.5% → 50.7% 5★; 0.0% → 14.2% 1★", "none", "high", "yes",
  ["7810155283","7814100388","7819707744","7820368483","7822994215","7824183159","7825110155","7825681921","7991549510","7963282358"])
c(124, "§8.4 Trend 3 — Study Bunny cross-promotion is fading fast (31.8% → 3.8%); the app now acquires largely on its own store presence, raising the stakes of the rating and the ad policy; cross-app requests: single sign-on and a shared bunny across both apps, and a third app ('self care hare', 'sleep sheep')", "timeline",
  "Trend 3 (high confidence): Study Bunny cross-promotion is fading fast — 31.8% (2021) → 9.0% → 16.0% (within noise) → 8.5% → 3.7% → 3.8% (2026); Habit Rabbit now acquires largely on its own store presence, which raises the commercial stakes of the rating and therefore of the ad policy — the cushion that absorbed the 2022–2024 rating decline is thinner; cross-app requests users still make: single sign-on and a shared bunny across both apps, and a third app ('self care hare', 'sleep sheep', one about hares)",
  "sibling-app funnel thinning", "mixed", "31.8% → 3.8%", "do", "high", "yes",
  ["10309270138","10883208523","9082534470","9242932170"])
c(125, "§8.5 Trend 4 — bug reports collapsed after 2023 (5.9 → 10.7 → 11.3 → 1.4 → 0.7%) then ticked up in 2026 (4.8%); the 2022–23 defects (orange-screen launch failure, rabbit off-screen, can't clean the room) essentially vanished — a genuine stabilisation; the 2026 uptick (n=5) is consistent with OS drift on an unreleased build given the listing's last version date of 18 Nov 2025 ('needs an update to keep up with ios')", "timeline",
  "Trend 4 (medium confidence): bug reports collapsed after 2023 — 5.9% (2021) → 10.7% → 11.3% (2023) → 1.4% (2024) → 0.7% (2025) → 4.8% (2026); the 2022–23 era was dominated by three defects that essentially vanish afterwards (8 of 15 launch reports are 2022; 10 of 12 rabbit-off-screen are 2021–23; all 7 can't-clean-the-room are 2021–22) — the app was stabilised across 2023–24 and the improvement is genuine; the 2026 uptick is small (5) but specific and consistent with a stale build ('lately it's been freezing every time I open the app, I think it needs an update to keep up with ios'; 'sometimes it randomly crashes'; 'It is always glitching'; login broken; can't add habits) — given the listing's last version date of 18 Nov 2025, most likely OS drift on an unreleased build",
  "stabilised 2023–24; stale build 2026", "mixed", "11.3% → 0.7% → 4.8%; 2026 n=5", "must-never-break", "medium", "yes",
  ["14264271258","13994061660","14197625518","14260811378","13974442185"])
c(126, "§8.6 Trend 5 — onboarding confusion is persistent, not improving (5.9 → 2.8 → 6.6 → 6.6 → 2.2 → 3.8%); the content is unchanged across five years — the tutorial does not teach habit CRUD (Sep 2021: 'went through the tutorial and then my room was dirty and I'm not sure how to clean it'; Mar 2026: 'am I suppose to do the task that's in the game? I'm soooo confused'); four and a half years, same complaint", "timeline",
  "Trend 5 (medium confidence): onboarding confusion is persistent, not improving — 5.9% → 2.8% → 6.6% → 6.6% → 2.2% → 3.8% with no monotonic direction and unchanged content: the tutorial does not teach habit CRUD; compare Sep 2021 ('I opened the app, went through the tutorial and then my room was dirty and I'm not sure how to clean it') with Mar 2026 ('am I suppose to do the task that's in the game? And then click on the task in the game I'm soooo confused') — four and a half years, same complaint",
  "tutorial never fixed", "complaint", "5.9 → 3.8%, flat", "must-have", "medium", "yes", ["7827681816","13859274524"])
c(127, "§8.7 Trend 6 — free-tier caps peaked as a topic in 2023 (8.5%) and declined (5.2 → 2.9 → 3.8%); the decline may not mean the caps got better — in 2024–25 the ad load plausibly crowded out every other complaint; caps are still named in 2026 at a steady low rate", "timeline",
  "Trend 6 (medium confidence): free-tier caps peaked as a topic in 2023 (8.5%) and declined (5.2% → 2.9% → 3.8%); labelled inference: the decline may not mean the caps got better — in 2024–25 the ad load so dominated the review conversation that it plausibly crowded out every other complaint; the caps are still named in 2026 at a steady low rate",
  "caps unchanged, drowned out by ads", "complaint", "8.5% → 3.8%", "product-rule", "medium", "app-specific",
  ["14047483354","14362430505","14445631071","14518675611"])
c(128, "§8.8 Trend 7 — review-prompt nagging is new in 2026 (5 of 7; low-medium confidence, n=7), including a 1★ given solely for the prompt", "timeline",
  "Trend 7 (low-medium confidence, n=7): review-prompt nagging is new in 2026 — 5 of 7 complaints are 2026 against 1 in 2022 and 1 in 2024; an early signal, but it includes a 1★ given solely for the prompt", "rating prompt escalated 2026", "1★-burst", "5 of 7 in 2026", "dont", "low-medium", "yes",
  ["14304401769","14376864779","14404977610","14489106892","14495169235"])
c(129, "§8.9 What did not change — cuteness praise flat across five years (27.1 → 24.8%); the room loop praised every year; the widget request runs continuously Apr 2022 → Sep 2026; no reviewer in any year mentions AI features as something they want — the only AI mention in 821 reviews is a complaint about AI homework-cheating ads served inside it: no evidence of AI demand", "insight",
  "What did not change: cuteness praise is flat across all five years (27.1% → 21.3% → 25.5% → 28.0% → 22.1% → 24.8%) — the art has never stopped working; the room-cleaning loop is praised in every year 2021–2026; the widget request runs continuously from April 2022 to September 2026 with no sign of being fulfilled; and no reviewer in any year mentions AI features, AI coaching or AI-generated content as something they want — the only AI mention in 821 reviews is a complaint about AI homework-cheating ads served inside it; stated explicitly as a real negative finding: there is no evidence of AI demand in this audience",
  "n/a", "mixed", "cute 27.1 → 24.8%; widget 5 years; AI 0 of 821", "dont", "corpus-level fact", "yes", ["7824183159","14374523863","10481431006"])
# Part 9
c(130, "§9.1 F1 — move the interstitial off the habit check-off tap; users propose batching ('let me tick them all off and then show me an ad'), capping ('max one every time you open the app'), reducing ('back to like 1 or 2 ads max'); the 3★ and 4★ bands are 214 reviews of which 76 carry ad complaints — this is where rating recovery lives", "product-rule",
  "F1: move the interstitial off the habit check-off tap — 164 reviews (19.98%), 52.4% of all 1★, mean 2.73 vs 4.35, 33 naming the per-action mechanic, 30 calling the app unusable, 19 churning, 19 five-star reviewers still complaining; users themselves propose the fix — batch it ('at least let me tick them all off and then show me an ad'), cap it ('Maybe max one every time you open the app'), reduce it ('go back to like 1 or 2 ads max'); the 3★ and 4★ bands are 214 reviews of which 76 carry ad complaints — this is where rating recovery lives",
  "ad on the reward tap", "1★-burst", "164; 76 of 214 in 3–4★", "product-rule", "high-priority", "yes", ["13331183751","8256803229","11108270607"])
c(131, "§9.1 F2 — make every ad dismissible and verify the 'decline the rewarded ad, get a forced ad anyway' path; three independent non-dismissible reports ('no way to exit the ad's pop-up window. I must force quit'; 'can't close after 15 seconds') — a store-guidelines risk as well as a UX one", "must-never-break",
  "F2: make every ad dismissible and verify the 'decline the rewarded ad, get a forced ad anyway' path — 'no way to exit the ad's pop-up window. I must force quit'; 'when the ad appears you can't get out of it' (TR); 'can't close after 15 seconds'; plus the report that declining the rewarded double still serves an unrewarded ad; three independent reports of non-dismissible ads is a store-guidelines risk as well as a UX one",
  "non-dismissible ads; punitive decline path", "1★-burst", "3 + 1", "must-never-break", "limited evidence, high consequence", "yes",
  ["11782177772","13141273505","9174047672","13918308778"])
c(132, "§9.1 F3 — fix purchase delivery and add an in-app 'Restore purchases' + 'Contact support' entry point; counter-evidence that support works: a 1★ → 5★ after a single e-mail; also audit whether the consumable-only architecture is the root cause of restore failures and whether 'no ads' should be a non-consumable product", "must-never-break",
  "F3: fix purchase delivery and add an in-app 'Restore purchases' and 'Contact support' entry point — 10 purchase failures (41.7% of identified payers), 'There is no Support button in the app. Nor on developer's website', restore failing on a new device, e-mails unanswered; counter-evidence that support works when reached: a 1★ upgraded to 5★ after a single e-mail; also audit whether the consumable-only architecture is the root cause of restore failures and whether 'no ads' should be a non-consumable product",
  "no restore/support entry point; consumables not restorable", "1★-burst", "10 (41.7% of 24 payers)", "must-never-break", "meaningful", "yes",
  ["8283139377","12064766837","10852008291","10450143353"])
c(133, "§9.1 F4 — teach habit add / edit / delete in onboarding and make the tutorial skippable; 38 onboarding complaints + 11 CRUD-failure reports are indistinguishable from the outside", "must-have",
  "F4: teach habit add / edit / delete in onboarding and make the tutorial skippable — 38 onboarding complaints (4.63%, mean 3.24) plus 11 CRUD-failure reports (1.34%, mean 2.36) that are indistinguishable from the outside; five reviewers name the same gap and one 1★ wants to skip it entirely",
  "tutorial teaches fiction not CRUD", "complaint", "38 + 11", "must-have", "very strong", "yes",
  ["11007342459","10747867482","10689805061","11190208726","10475830356","11655072177"])
c(134, "§9.1 F5 — ship the widget: 14 requests, mean 4.64, zero negatives, continuous Apr 2022 → Sep 2026, behaviour specified (tap the widget to check a habit done)", "must-have",
  "F5: ship the widget — 14 requests (1.71%), mean 4.64, zero negative ratings, continuous April 2022 → September 2026, desired behaviour specified: tap the widget to check a habit done", "no widget", "complaint", "14, mean 4.64", "must-have", "meaningful", "yes", ["14517374247"])
c(135, "§9.1 F6 — uncap or rename the priority slots: the complaint is never 'I want more features', it is that the cap forces a false statement about the user's own life; if the cap must stay, rename the tiers so they read as labels rather than the app's judgement of importance, or let users choose the colours ('just let us choose the colour ourself and not give us a max amount')", "product-rule",
  "F6: uncap or rename the priority slots — 15 reviews (1.83%, mean 3.40); the complaint is never 'I want more features', it is that the cap forces a false statement about the user's own life; if the cap must stay for monetisation, rename the tiers so they read as labels rather than as the app's judgement of importance, or let users choose the colours ('just let us choose the colour ourself and not give us a max amount')",
  "semantic cap on priority", "complaint", "15, mean 3.40", "product-rule", "meaningful", "yes",
  ["8348335779","8245454882","9199521271","8968448221","9124737122"])
c(136, "§9.1 F7 — verify the app on current iOS and ship an update: listing version 5.12 dated 18 Nov 2025; 2026 freezing/crash/login reports; medium confidence, n=5, near-zero cost to check", "must-never-break",
  "F7: verify the app on current iOS and ship an update — listing version 5.12 dated 18 November 2025 (accessed 11 September 2026) and 2026 reports of freezing ('needs an update to keep up with ios'), random crashes, glitching and broken login; medium confidence, n=5, but the cost of checking is near zero", "stale build", "complaint", "n=5", "must-never-break", "medium", "yes",
  ["14264271258","13994061660","14197625518","14260811378"])
c(137, "§9.1 F8 — fix the Chinese localisation defects and audit CJK font fallback + string truncation (Japanese glyphs rendered for Chinese, habit names silently truncated; large untranslated English with Chinese selected; historical 'every r a black square' regression; Portuguese partial translation)", "must-never-break",
  "F8: fix the Chinese localisation defects and audit CJK font fallback plus string truncation — Japanese glyphs rendered for Chinese text and habit names silently truncated (1★); large amounts of untranslated English with Chinese selected (5★); the historical precedent of every 'r' rendered as a black square after a localisation update; Portuguese reports the same partial-translation problem", "localisation encoding defects", "complaint", "3 + 1 historical", "must-never-break", "meaningful", "yes",
  ["13744289117","12296652523","9179812608","13582227455"])
c(138, "§9.1 F9 — dial back the rating prompt: 7 complaints, 5 in 2026, a 1★ given only for the prompt and a 5★ asking it to stop; prompting into an ad-frustrated session is actively harvesting negative ratings", "dont",
  "F9: dial back the rating prompt — 7 complaints, 5 of them in 2026, including a 1★ given only for the prompt and a 5★ asking it to stop; prompting into an ad-frustrated session is actively harvesting negative ratings", "rating prompt on open and on check-off", "1★-burst", "7; 5 in 2026", "dont", "emerging", "yes", ["14495169235","14404977610"])
c(139, "§9.2 E1 — a cheap, short premium trial mirroring Study Bunny's reported $2 / 30-day model; the current funnel requires users to endure the worst version of the product before they can buy the good one; 5 blocked by no trial + 5 payers who converted only after extended free use; measure trial-start, trial→purchase and the 1–3★ ad-complaint share", "monetization",
  "E1: a cheap, short premium trial mirroring Study Bunny's reported $2 / 30-day model — the current funnel requires users to endure the worst version of the product before they can buy the good one, and a trial inverts that; evidence: 5 explicitly blocked by the absence of a trial plus 5 payers who converted only after extended free use; measure trial-start rate, trial→purchase rate and the change in the 1–3★ ad-complaint share",
  "no trial; ad-saturated free tier", "blocked-conversion", "5 + 5", "research", "emerging", "yes",
  ["11631739795","11925342130","11782177772","12094245435","9884921571","8230449667","11264169679","11156342874","14057599797","14155124146"])
c(140, "§9.2 E2 — unbundle the purchase, or make what each purchase unlocks explicit; an opaque consumable bundle suppresses purchases and generates support load ('just pay like two dollars to just get unlimited tasks'; moods sold separately; cloud access discovered by accident; paid $10 then charged again for a new feature)", "product-rule",
  "E2: unbundle the purchase, or at minimum make what each purchase unlocks explicit — an opaque consumable bundle suppresses purchases and generates support load: 'There should be an option to just pay like two dollars to just get unlimited tasks'; moods wanted sold separately; 'I now realize just buying anything gives u cloud access' discovered by accident; a user who paid $10 was then charged again for a new paid feature", "opaque consumable bundle", "blocked-conversion", "4 named reviews", "product-rule", "meaningful", "yes",
  ["9089433219","10878892150","12148758031","9407269123"])
c(141, "§9.2 E3 — late-game content: add rooms or ship a 'prestige' / reset loop; completion of the house is a hard retention cliff; 16 reviews incl. a paying customer leaving and a fully specified user design (reset the house, count resets as a progress metric)", "must-have",
  "E3: late-game content — add rooms, or ship a 'prestige' / reset loop; completion of the house is a hard retention cliff: 16 reviews (1.95%) including a paying customer leaving over it and a fully specified design from a user (reset the house, count resets as a progress metric)", "finite content", "churn", "16 (1.95%)", "must-have", "meaningful", "yes",
  ["8703335659","9623080855","9177007332","9891058432","12416426978","11918683339","8852905838"])
c(142, "§9.2 E4 — flexible habit frequency (monthly, every-other-week, multiple-times-per-day, specific weekdays); the weekly-only model wastes limited habit slots and blocks purchase ('I can't see myself purchasing without being able to make these distinctions')", "feature",
  "E4: flexible habit frequency — monthly, every-other-week, multiple-times-per-day, specific weekdays; the weekly-only model wastes limited habit slots and blocks purchase: 'I'd love for this to be my constant app, but I can't see myself purchasing without being able to make these distinctions'", "weekly-target only", "blocked-conversion", "15 (1.83%)", "must-have", "meaningful", "yes",
  ["11136830862","7868151028","8222834153","8282086026","11146992358","11264169679","14099704149"])
c(143, "§9.2 E5 — localise Spanish, Turkish, Russian and complete Chinese; rest-of-world markets already rate higher (4.181 vs 3.956) and are blocked mainly by language (5.56% vs 1.09%); two name language as their reason for leaving, one says the opposite if localised", "market",
  "E5: localise Spanish, Turkish, Russian and complete Chinese — rest-of-world markets already rate the app higher (4.181 vs 3.956) and are blocked mainly by language (5.56% vs 1.09% localisation demand); two reviewers name language as their reason for leaving and one says the opposite — 'i don't even want to look for another tracker' — if it were localised", "partial localisation", "complaint", "21 (2.56%); 5.56% vs 1.09%", "do", "meaningful", "yes",
  ["12403260326","11644145389","11946017120"])
c(144, "§9.2 E6 — separate the decay mechanic from the data model, and say so: users cannot distinguish intentional punishment from a bug and both produce the same 1★; a visible backup/restore state and a gentler or optional decay would separate the two; a defender values the stakes — make it a setting, not a removal", "product-rule",
  "E6: separate the decay mechanic from the data model, and say so — users cannot distinguish intentional punishment from a bug and both produce the same 1★ (12 data-loss reports + 10 decay complaints, overlapping in five reviews); a visible backup/restore state and a gentler or optional decay would separate the two; a defender values the stakes ('isn't that how the check-in and task system works?'), so make it a setting rather than removing it",
  "decay indistinguishable from data loss", "churn", "12 + 10, 5 overlapping", "product-rule", "meaningful", "yes",
  ["8412783427","8650393283","9564128000","11271378008","11980405124","11960853599"])
c(145, "§9.2 E7 — reward the to-do list, not just habits ('we should be able to earn energy / rewards for getting your todo list done'; 'allow the timer to be used for todo list tasks with carrot rewards… the more irksome and time consuming tasks that you procrastinate on')", "feature",
  "E7: reward the to-do list, not just habits — 9 requests (1.10%, mean 4.44): 'we should be able to earn energy / rewards for getting your todo list done'; 'Please allow the timer to be used for todo list tasks with carrot rewards… these are usually the more irksome and time consuming tasks that you procrastinate on'", "to-dos unrewarded", "complaint", "9 (1.10%), mean 4.44", "research", "meaningful", "yes",
  ["10705887680","13365326137","10029940699","11112031723","12752487585"])
c(146, "§9.3 Research questions Part 9 #1–#6 — is ad frequency tenure-scaled (server config answers in minutes); what does the check-off interstitial earn vs the ratings it costs (the central trade-off); do CN users see ads at all (a natural control group); how much 2026 5★ volume is prompt-driven; is the sibling-app funnel recoverable; what is the retention curve after house completion", "data-caveat",
  "Research questions: is ad frequency tenure-scaled (one reviewer suspects it and several long-tenured reviewers report escalation — server-side configuration would answer this in minutes and materially changes the fix); what is the actual conversion rate and how much revenue does the check-off interstitial earn versus the ratings it costs (the central trade-off, undecidable from reviews); do CN storefront users see ads at all (12 CN reviews, zero ad complaints — a natural control group); how much of the 2026 5★ volume is prompt-driven (134 contentless records plus the 2026 prompt spike); is the sibling-app funnel recoverable (31.8% → 3.8%); what is the retention curve after house completion",
  "n/a", "none", "report gives none (questions)", "research", "open questions", "yes", ["9016620744","11585029310","12891214594","13565718990"])
c(147, "§9.4 What not to change — do not simplify away the gamification (the differentiator; one prefers Habit Rabbit because it is less feature-heavy than Finch); do not add AI features on category trend (zero of 821 request them); do not raise the price (16 objections; the winning position is 'more affordable alternative'); do not remove the rabbit's emotional stakes entirely (40 describe attachment as the mechanism; the decay complaint is about calibration and recoverability, not the concept)", "dont",
  "What not to change: do not simplify away the gamification — it is the differentiator, and one reviewer prefers Habit Rabbit precisely because it is less feature-heavy than Finch; do not add AI features on the strength of category trend — zero of 821 reviews request them; do not raise the price — 16 price objections already and the winning competitive position is 'more affordable alternative'; do not remove the rabbit's emotional stakes entirely — 40 reviews describe attachment as the mechanism that works, and the decay complaint is about calibration and recoverability, not the concept",
  "gamified, cheap, emotionally staked", "praise", "40 attachment; 16 price; 0 AI", "dont", "corpus-level fact", "yes",
  ["14075378286","11488297687","11960853599"])

with open("Tools/prd_ledger/28/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
