# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/71")
from _lib import c, table, save

c(19, "§0.6 table (verbatim); §3.6", "data-caveat", "What nobody complains about — seventeen negative claims tested by regex over all 32 (verbatim): " + table("## 0.6 What nobody complains about", 0) + " — no data loss, crash or login failure ('for a six-year-old social app with a server backend, that is a real quality signal — thin, because the corpus is thin'); no free trial, refund or support contact; not a defect rate, not a country comparison, not a price-sensitivity measure, not a statement about the 2026 product, nothing about GB, CA, AU or VN", "n/a", "none", "17 × 0 matches", "none", "limited evidence", "generalisable", ["10372917549"])
c(20, "§0.7; §5.1; §5.3; §5.5; §8.6 #1; part 8 #1", "data-caveat", "There is not one paying reviewer in this corpus: zero state they paid, subscribed, trialled, renewed or asked for a refund; five money-keyword hits, two false positives ('Little efforts pay off'; 'weekly, daily or monthly') and three refusals; no conversion, renewal, refund, ARPU or elasticity claim is made; the paid tier's value is unevidenced — nobody describes what $5.99–$29.99 buys; willingness-to-pay appears once as a counter-offer for a bigger free tier; latent willingness in the 5★ population (multi-year retention, daily dependence 'one of the few I open every day… I depend on it', 8 in the book / podcast ecosystem, 7 recruiting others) is 'inferred interest, not purchase evidence, and the distinction is load-bearing'; the release notes hint at 2024 purchase-flow problems (v2.62 'improved subscriptions', v2.64 'Fix subscription bug') no review corroborates; research #1: what do paying users think — 'the single largest gap'", "n/a", "none", "0 payers", "research", "research", "generalisable", ["9659580036","8444987832","9465102914"])
c(21, "§3.1 table (verbatim); §3.2 table (verbatim)", "data-caveat", "Complete global theme table with Wilson CIs (verbatim): " + table("## 3.1 Complete global theme table", 0) + " || unions (verbatim) " + table("## 3.2 Composite unions", 0), "n/a", "mixed", "50 codes; 13 unions; criticism union 8 (25.0%) 3.50", "none", "table", "generalisable", ["9401363375"])
c(22, "§4.2 tables (verbatim); §4.3 table (verbatim); §4.6 table (verbatim)", "insight", "Bands — 5★ built on outcomes and people, not features (verbatim) " + table("## 4.2 Five stars", 0) + " — two 5★ carry a complaint as a footnote ('that is literally my only feedback'; 'just wish the app speed was a little better but great concept and amazing people!'); 4★ every one carries a criticism (verbatim) " + table("## 4.3 Four stars", 0) + " — 'If this corpus had 400 reviews instead of 32, the 4★ band is where the roadmap would come from'; against the grain (verbatim) " + table("## 4.6 Rating does not fix theme direction", 0) + " — 'Filtering this corpus by star rating would discard three-quarters of its product intelligence'", "n/a", "mixed", "6 of 32 (18.8%) complaints inside 4–5★", "none", "limited evidence", "generalisable", ["9845025034","10042208408","12003973648"])
c(23, "§3.3 N6; §8.2 #7, #8", "must-never-break", "Reliability, thin and stale: PERF-SLOW 1 inside a 5★ ('Amazing app just wish the app speed was a little better', 2023-06) — v2.51 (2023-11-16) lists performance improvements and v2.71 (2025-05-07) fixes slowness on the challenge scoreboard; BUG-COMMUNITY-POST 1 posting into a Community was buggy (Sep 2023); §8.2 #7, #8: re-test the community posting path and perceived speed before triaging — 1 review each, 3 years stale", "n/a", "complaint", "PERF-SLOW 1; BUG-COMMUNITY-POST 1", "must-never-break", "limited evidence (stale)", "generalisable", ["10042208408","10372917549"])
c(24, "§6.1 table (verbatim); §6.2 table (verbatim); §6.3; §6.4; §6.5; §8.6 #4, #5; part 8 #5", "market", "No country qualifies (verbatim): " + table("## 6.1 Eligibility", 0) + " — US (verbatim) " + table("## 6.2 The United States", 0) + " — all 3 monetization complaints are US, a consequence of 28 of 32 reviews being American, not price sensitivity; leads only: Italy — 'share with friends, students and people I want to be accountable to or vice versa' (a teacher or coach use case, 'worth a targeted interview, not a roadmap line'); New Zealand — the densest feedback; South Africa — the interface critique (ZA 3 public ratings at 3.67); Brazil — the only non-English review ('Atende muito bem a proposta! / Até agora o maior app de acompanhamento de metas'); GB, CA, AU, VN polled with zero text; market groups not analysable (no spend source; high-volume group would be the US alone); localisation: listed EN, IT, JA, ZH while BR and ZA hold reviews and JP / CN are not recorded as polled — 'a collection gap, not a market finding'; research #4 why GB, CA, AU, VN hold ratings but no text; #5 were JP and CN ever polled", "n/a", "mixed", "US 28 @ 4.64; 75 public ratings; 0 eligible", "research", "limited evidence", "app-specific", ["8393594655","10372917549","10341126586","9618663208"])
c(25, "§8.1 table (verbatim); §8.2 table (verbatim); §8.5 #1, #2; part 8 #1; part 8 #2; §0.8 table (verbatim)", "product-rule", "The seven decisions (verbatim) " + table("## 0.8 The seven decisions", 0) + " — monetization surface (verbatim) " + table("## 8.1 Immediate — the monetization surface", 0) + " — integrity and defects (verbatim) " + table("## 8.2 Immediate — integrity and defects", 0) + " — experiments: (1) does a larger free cap (5 and 10 vs current) increase or decrease revenue; (2) does a feature-based paywall convert better than a count-based one — 'a reasoned argument, not a measured result'; what to do first: re-collect the corpus, fix the paywall's shape not its price, ship the widget and cadence edit, close the Discover-count loophole", "n/a", "mixed", "3 cap reviews = 100% of 1★", "do", "moderate / hypothesis", "generalisable", ["10540595375","12003973648","9845025034","10372917549"])
c(26, "§8.4; §5.2", "contradiction", "The paywall is placed on the commodity, not the differentiator: reviewers praise the community (11, mean 4.91) and outcomes (21) that competitors cannot copy, while the charge is on the streak count that 'every free competitor already gives away' — and the corpus's reviewers know it ('there are so many alternatives that don't make you pay when you've hit a max of 2 goals'; 'if I find a better one I'll definitely switch'); against the common assumption that a cap on the core counter is the natural freemium line, here it is 'a product that cannot do the job at all' for a multi-domain habit practice", "counter capped; community ungated", "churn", "social 11 @ 4.91 vs cap 3 @ 2.00", "research", "moderate", "generalisable", ["10540595375","12003973648","9618210059"])
c(27, "§3.4 P5; §5.3", "audience", "Committed long-tenure advocates write the reviews: ADV-RECOMMEND 7 (21.9%, mean 5.00) explicitly tell the reader to download it; ADV-FUTURE 3 optimistic about growth ('crazy good app and I think will be popular over time'); streaks of 823 days, 900+ days, 'over 2 years'; several arrived through the book or podcast — while the three cap complainants are newer users who hit the wall early (at the third streak; before starting)", "n/a", "praise", "advocacy union 12 (37.5%) 5.00", "none", "moderate", "generalisable", ["9422100038","9401363375","9903758816","11896566865"])
save("a")
