import sys; sys.path.insert(0, "Tools/prd_ledger/56")
from _lib import c, table, save

c(24, "§3.4 table (verbatim)", "feature", "Unmet needs — complete backlog, 26 requesters (38.81%, mean 4.85) (verbatim): reminders / notifications 6 (8.96%, 5.00, Apr → Aug 2026); non-daily scheduling 6 (8.96%, 4.67, Feb → Aug); more icons / custom emoji 5 (7.46%, 4.60); reorder habits 4 (5.97%, 4.75, May → Jul); per-habit description / notes 3 (4.48%, 4.67); more / richer widgets (multi-habit, >4, transparency) 3 (4.48%, 5.00); more colours 2; cross-device iPhone ↔ iPad sync 1; data export JSON/CSV 1; Apple Watch 1; dark mode 1; light mode 1; streaks 1; analytics / charts 1; back-date a missed day 1; separate lists / habit groups 1; donation / tip option 1 — three already answered (reminders and reorder shipped by 29 Jul, export in v2.3.0, icons to 42 in v2.3.0); dark mode (Feb) and light mode (Jul) are opposite requests five months apart", "n/a", "n/a", table("## 3.4 Unmet needs", 0), "none", "table", "app-specific", ["13958079059","14235241668","14239464502","14363670791","14392368857","14444070845"])
c(25, "§3.4 scheduling; §4.3; §8.2 D1; part 8", "feature", "Non-daily scheduling is qualitatively the most important request: the oldest (review #2 of the corpus, 20 Feb 2026), the only one still recurring unanswered at the end (11 Aug), and the only request with a rating penalty — the corpus's only 3★: 'Great daily but no weekly… I love the daily tracking for free with no premium version, but I feel like we need a weekly/monthly/select days option!' (GB, 25 Apr) — praising the free model and docking two stars in one sentence; forms requested: 'goal schedule' (KR), weekly / monthly / select days (GB), once a week / once a month (PH), x times per week (US), daily or weekly (AR), deadline (TW); five of six reduce to 'this habit is not daily'; D1: ship per-habit frequency (daily / specific weekdays / N per week) as one field defaulting to daily, invisible to the 58% who want daily-only; keep the deadline request out — a time-bounded goal is a different product", "daily-only habits", "complaint", "6 (8.96%, 4.67); 6 storefronts; the only 3★", "must-have", "pattern", "generalisable", ["13770961885","13996707039","14239464502","14272015279","14392368857","14414692804"])
c(26, "§3.4 table form rows (verbatim)", "feature", "Scheduling forms requested (verbatim table)", "n/a", "n/a", table("## 3.4 Unmet needs", 1), "none", "table", "app-specific", [])
c(27, "§3.4 deadline", "feature", "A deadline — a time-bounded goal rather than a recurring habit — requested once (TW); a different product model and UI from recurring habits, kept out of scheduling work", "absent: deadlines", "complaint", "n=1", "research", "single", "generalisable", ["14414692804"])
c(28, "§3.4 icons, colours, notes", "feature", "Cosmetic requests: more icons / custom or system emoji 5 (7.46%), more colours 2 (2.99%), per-habit description / notes 3 (4.48%) — one note request ('notes/comments… to help track progress') is closer to journaling than labelling", "limited icons and colours; no notes", "complaint", "5 / 2 / 3", "build-free", "pattern", "generalisable", ["13842468107","14109432526","14354352389","14461677979","14405635940"])
c(29, "§3.4 widgets", "feature", "More / richer widgets 3 (4.48%, 5.00): a multi-habit widget designed in detail — a grid with dates across the top and habits down the side, or 4 habits in one calendar widget; more than 4 widgets; widget transparency (may already exist)", "per-habit widgets, max 4", "complaint", "3 (4.48%)", "build-free", "corroborated", "generalisable", ["14400919999","14330479445","14210943801"])
c(30, "§3.4 singles", "feature", "Single requests: iPhone ↔ iPad sync; data export (answered in v2.3.0); Apple Watch app; dark mode (Feb) and light mode (Jul) — opposite requests, likely because the app shipped light-first and later became dark-default; streaks (1); analytics / charts; back-date a missed day; separate lists / habit groups", "n/a", "complaint", "1 each", "research", "single", "generalisable", ["14235241668","14330479445","14201304150","13784066083","14260223015","14174214597","14461677979","14226473114","14173024754"])
c(31, "§3.5 table (verbatim) and severity ranking", "must-never-break", "Negative surface — six reviewers (8.96%), none below 4★ (verbatim): B_SYNC_DATALOSS 'I think the recent update about sync made my habits disappear, is there anyway I can get them back??' (PH, 4★, 4 Jul); B_CALENDAR_OFFSET 'the calendar is a day out so when you complete a dot on the Monday it highlights the Sunday before' (GB, 5★); B_LANGUAGE 'today it randomly switched to chinese' (DE, 5★); B_WIDGET_TAP 'the widget… often opens the app instead of progress the habit' (BE, 4★; fixed in v2.3.2); B_CAL_DISAPPEAR calendar of each habit disappears on leaving the app (US, 4★); F_UI_MENUBAR 'The menu bar at the bottom blocks views if you have 9+ habits' (US, 4★); F_DISCOVERABILITY 'where do I set the widget transparency feature like the one in the preview?' (KR, 5★) — severity by consequence, not frequency: 1 sync data loss (silent history loss from an update; promoted regardless of share); 2 calendar off-by-one silently corrupts the record; 3 widget tap misfire breaks the most-praised interaction; 4 menu-bar occlusion at 9+ habits — the unlimited-habits differentiator leads directly into the bug; 5 language switch and calendar disappearing are annoyances; 6 discoverability — third instance of 'the capability exists; the user cannot find it'; forgiveness caveat — defect reporters average 4.50 and wrap complaints in praise; the corpus cannot measure impact because those driven away did not review", "sync update deleted habits; date off by one; widget tap misfire; menu bar blocks list at 9+ habits", "complaint", table("## 3.5 Negative themes in detail", 0), "must-never-break", "single (each)", "generalisable", ["14260223015","14201101389","14194139904","14422180050","14262513041","14210943801"])
c(32, "§3.5 menu bar at 9+ habits", "must-never-break", "Menu bar occludes the habit list at 9+ habits — a scale bug that triggers exactly where 'unlimited habits' invites users; one reviewer set up 8 habits, one below the threshold", "layout breaks at 9+ habits", "complaint", "n=1", "must-never-break", "single", "generalisable", ["14262513041","14440814553"])
c(33, "§3.5 locale switch", "must-never-break", "The app UI switched to Chinese unprompted on a German storefront and the user could not find how to change it back", "locale switched unprompted", "complaint", "n=1", "must-never-break", "single", "generalisable", ["14194139904"])
c(34, "§3.5 store preview discoverability", "anti-pattern", "A store preview shows a widget-transparency setting the user cannot find in the app (KR) — the listing promises what the user cannot locate", "preview shows unreachable setting", "complaint", "n=1", "dont", "single", "generalisable", ["14210943801"])

# PART 4
c(35, "§4.1 table (verbatim)", "insight", "5★ n=62 (92.54%) drivers (verbatim): simplicity 36 (58.06%); free / no paywall 29 (46.77%); design 19 (30.65%); search ended at Dots 14 (22.58%); thanks to the developer 13 (20.97%) — the modal 5★ is short (median 119 characters) and names 'it's simple' and 'it's free' ('Great, simple and free habit tracker! I love it!'); 23 of 62 five-stars (37.10%) still contain a request — 5★ means 'nothing is wrong', not 'nothing is missing'", "n/a", "praise", table("## 4.1 Five stars", 0), "none", "table", "app-specific", ["14376181527"])
c(36, "§4.2 table (verbatim)", "insight", "4★ n=4, each with a specific cause and each still praising (verbatim): ZA — 'i would have a 5 star rating if a few small changes could be made' (custom/system emoji, more colours, per-habit description — three cosmetic requests cost one star); PH — reorder, light mode, icons plus the data-loss report as an in-text update; US — menu-bar occlusion at 9+ habits and calendar view disappearing ('Just some minor drawbacks'); BE — widget tap opens the app instead of completing — 2 of 4 lost a star to cosmetic limits, 2 to defects; nothing about pricing or the core mechanic", "n/a", "mixed", table("## 4.2 Four stars", 0), "none", "table", "app-specific", ["14109432526","14260223015","14262513041","14422180050"])
c(37, "§4.2 cosmetic requests cost a star", "insight", "Cosmetic limits demonstrably cost stars: half the 4★ reviews name icons, colours or descriptions as the only thing between them and 5★ — cheap to fix and partly fixed already (42 icons in v2.3.0)", "limited cosmetics", "complaint", "2 of 4 4★", "build-free", "single", "generalisable", ["14109432526","14260223015"])
c(38, "§4.5 table (verbatim)", "data-caveat", "Rating / text contradictions (verbatim): a 5★ reporting a date-rendering bug ('the calendar is a day out… would be perfect if fixed'); a 5★ reporting the UI switching language unprompted — both inflate the mean; with zero 1★/2★ they support the conclusion that star ratings systematically understate friction: use theme counts, not the star average", "n/a", "mixed", table("## 4.5 Rating / text contradictions", 0), "none", "table", "generalisable", ["14201101389","14194139904"])
c(39, "§4.6", "data-caveat", "How themes differ by rating: P_FREE in 29 of 62 five-stars and in both non-5★ reviews that mention money — praise for the free model is rating-independent; P_SIMPLE 58.06% of 5★ and 3 of 5 non-5★; R_ICONS splits 3 / 2 between 5★ and lower — the same request costs a star for some and not others; every defect other than the two contradictions appears in a 4★ — defects move the rating, requests mostly do not", "n/a", "n/a", "report gives none", "none", "method statement", "generalisable", [])

# PART 5
c(40, "§5.1 table (verbatim); §5.4", "monetization", "The paid segment is empty (verbatim): explicit payers 0 (0.00%); trialists 0; refund / cancel requests 0; reviewers complaining about another app's paywall 9 (13.43%); praising Dots' absence of payment 31 (46.27%); asking for a way to give money 1 (1.49%) — a hand search in original language for payment, purchase, subscription, premium, pro, upgrade, unlock, trial, renewal, refund, cancel, price, currency and non-English equivalents found only absence-of-payment in Dots or payment in other apps; 'This is not a data gap. It is the finding'; no conversion rate, ARPU or willingness-to-pay may be inferred", "no commercial surface", "praise", table("## 5.1 Defining the segment", 0), "none", "table", "app-specific", ["14444070845"])
c(41, "§5.2 donation request", "monetization", "The single piece of direct inbound demand: 'Simple Pretty Flexible and Shill-free. Thank you. Eager next for notification and donation options' (US, 5★, 18 Aug 2026) — one reviewer unprompted asked to donate; zero asked for a premium tier, pro unlock or paid features; supported by unusually high goodwill (13 thank the developer) — 'plausibility is not evidence, and one request is one request'", "no tip option", "purchase-driver", "R_DONATE 1; P_GRATITUDE 13", "research", "single", "generalisable", ["14444070845","14210943801","14173024754","14504042664","14067204894"])
c(42, "§5.2 table (verbatim)", "dont", "What reviewers said they would not tolerate, drawn from what made them leave competitors (verbatim): subscription required for core use — caused them to delete the competitor; habit-count cap behind a paywall — explicitly rejected, 'unlimited' is why they stayed; widgets gated behind a subscription — rejected; free-trial-then-charge ('no obnoxious free-trial trick'; 'no false promises') — rejected; ads — caused instant deletion of competitors", "n/a", "churn", table("## 5.2 What would trigger a purchase", 0), "dont", "table", "generalisable", ["14040460063","14160827585","14151336984","14392368857","14109432526","14148473814","14363670791","14389211332"])
c(43, "§5.3", "product-rule", "Upgrade barriers — the inverse finding: 35 of 67 (52.24%) volunteered praise for the absence of monetisation, and for 9 a competitor's monetisation is why they are here; introducing a paywall over any currently-free capability — unlimited habits, widgets, all view formats, no ads — would contradict the promise that produced half the positive sentiment", "fully free", "praise", "35 (52.24%); 9 competitor-paywall", "product-rule", "dominant", "generalisable", [])
c(44, "§5.5 table (verbatim)", "must-never-break", "Issues that would become refund triggers if a paid tier existed (verbatim): sync data loss ('losing paid-for habit history is a refund trigger, not a 4★'); calendar off-by-one ('a paying user will not rate a visibly wrong record 5★'); widget tap misfire (the headline feature); menu-bar occlusion at 9+ habits (hits the power users most likely to pay); feature discoverability — reminders, back-dating, widget transparency ('a paying user who cannot find the feature they paid for asks for money back')", "n/a", "n/a", table("## 5.5 Issues that would affect paid users", 0), "must-never-break", "table", "generalisable", ["14260223015","14201101389","14422180050","14262513041","14210943801","14226473114","14392368857","14444070845"])

# PART 6
c(45, "§6.1 table (verbatim)", "market", "The 50-review threshold — zero storefronts qualify (verbatim): US 24 (35.82%, 4.96); GB 8 (4.75); AR 5 (5.00); DE 5 (5.00); KR 5 (5.00); PH 3 (4.67); BR, CA, ES, IN 2 each; AU, BE, HU, KZ, NL, RU, SG, TW, ZA 1 each — no standalone country claim", "n/a", "n/a", table("## 6.1 The 50-review threshold", 0), "none", "table", "app-specific", [])
c(46, "§6.2 table (verbatim) and hypotheses", "market", "United States n=24 (limited evidence), mean 4.96 (verbatim table: simple 54.2% vs rest 60.5%; free 45.8% vs 46.5%; gratitude 29.2% vs 14.0%; outcome 25.0% vs 9.3%; search-end 20.8% vs 23.3%; design 20.8% vs 34.9%; widget 16.7% vs 11.6%; no ads 16.7% vs 11.6%; notifications request 12.5% vs 7.0%; competitor paywall 12.5% vs 14.0%; no-signup 8.3% vs 0.0%; scheduling request 4.2% vs 11.6%) — hypotheses only: US reviewers describe outcomes more and praise design less; the US supplies both no-signup reviews, both describing onboarding friction at competitors as the reason for switching", "n/a", "praise", table("## 6.2 ⚠️ United States", 0), "none", "table", "app-specific", ["14268546710","13838078059","14354352389","13853268363","14504042664"])
c(47, "§6.3, §6.4, §6.5, §6.6, §6.7", "market", "Small storefronts (severely limited evidence): GB n=8 mean 4.75, the only 3★ (scheduling) and the most detailed review (ADHD); AR n=5 all 5★, 4 of 5 name free-ness or a competitor's paywall and two specifically reject competitors' habit-count caps (not generalisable to price sensitivity); DE n=5 all 5★ and all five written in English — the only multi-review non-anglophone storefront where nobody wrote in the local language; contains the locale bug and the earliest dark-mode request; KR n=5 all 5★, 4 in Korean, the only storefront where widget design headlines the review, source of the transparency report, the earliest review and earliest scheduling request (both 20 Feb 2026); PH n=3 mean 4.67, the data-loss report and a scheduling request", "n/a", "mixed", "GB 8; AR 5; DE 5; KR 5; PH 3", "none", "limited evidence", "app-specific", ["13996707039","14472221855","14201101389","13914688458","14151336984","14389211332","14392368857","13784066083","14122888123","14173024754","14194139904","14376181527","14370026168","14210943801","13768486794","13770961885","14260223015","14239464502"])
c(48, "§6.8 table (verbatim)", "market", "Storefronts with 1–2 reviews — 22 reviews (32.84%), callouts only (verbatim table): GB the ADHD review; SG 'No subscription, no guilt', only back-log praise and only analytics request; NL Spanish text on a Netherlands storefront; IN only export and only '>4 widgets' requests, both answered in v2.3.0; ES the only review naming privacy as the primary value and the only non-habit use case (project tracking); HU the only review naming optional iCloud sync as a design decision; KZ the only Russian-language outcome report; TW the only deadline request; BE the only widget-tap defect; ZA the most explicit rating rationale", "n/a", "n/a", table("## 6.8 ⚠️ Storefronts with 1–2 reviews", 0), "none", "table", "app-specific", ["14472221855","14461677979","14401566211","14330479445","14294687098","14408586581","14227146007","14414692804","14422180050","14109432526"])
c(49, "§6.9", "audience", "The ADHD / neurodivergent signal, n=1 (GB, 5★, 26 Aug 2026), quoted because it articulates the implied positioning: 'The minimalism is absolutely perfect for people who actually want to track their habits without the faff. My ADHD makes organisation challenging and over the year I've tried countless apps that claim to help neurodivergent people or be perfect for those who procrastinate. They end up being made for quick cash grabs or having a wildly confusing interface that is overwhelming and challenging to navigate. With Dots, you get exactly what you download' — joins competitor paywall rejection, interface overwhelm and 'you get exactly what you download' into one causal chain; the category advertises heavily to this audience and Dots serves it without claiming it — a hypothesis, not market sizing; D6: do not claim the ADHD positioning on this evidence — earn it by staying simple", "no ADHD claim in positioning", "praise", "S_ADHD 1 (1.49%)", "research", "single", "generalisable", ["14472221855"])
c(50, "§6.10 tables (verbatim)", "market", "High-spend group (conventional proxy, not measured: US, GB, CA, AU, DE, KR, TW, SG, NL, BE, ES) 51 reviews (76.12%, 4.922) vs other 16 (23.88%, 4.875) (verbatim): P_FREE 47.1% vs 43.8%; P_SIMPLE 56.9% vs 62.5%; competitor paywall 11.8% vs 18.8%; widget 11.8% vs 18.8%; design 35.3% vs 12.5% (least reliable, 2 reviews) — the finding that matters: praise for free-ness is essentially flat between high-spend and other markets, so 'free' is not a low-ARPU phenomenon that could be paywalled away in rich storefronts", "n/a", "praise", table("## 6.10 High-spend market group", 0) + " || " + table("## 6.10 High-spend market group", 1), "product-rule", "table", "generalisable", [])
c(51, "§6.11 table (verbatim) and reading", "market", "High-review-volume group (review volume only, not downloads: US 24, GB 8, AR 5, DE 5, KR 5) 47 (70.15%, 4.936) vs other 14 storefronts 20 (4.850) (verbatim); 24 of 43 polled storefronts returned zero reviews, including Japan, France, Italy, Mexico, Turkey, Poland, Portugal, Thailand, Indonesia, Vietnam and Ukraine — speculative distribution reading: traction concentrated in US/UK plus AR, DE, KR and absent from most of Europe, Latin America outside Argentina and Brazil, Japan and Southeast Asia; the Japanese zero is most striking because the listing claims Japanese localisation — check against install data", "claims Japanese localisation; zero Japanese reviews", "n/a", table("## 6.11 High-review-volume market group", 0), "research", "table", "app-specific", [])
c(52, "§6.12 table (verbatim) and localisation", "market", "Global comparison: uniform — zero complaints about Dots' own monetisation in all 19 storefronts; 14 of 19 storefronts mean exactly 5.00 (exceptions US 4.96, GB 4.75, PH 4.67, BE 4.00, ZA 4.00, each explained by a specific fixable cause); every top theme drawn from simplicity, free-ness or design; aggregate uniformity is not storefront uniformity (verbatim scatter table: P_SIMPLE / P_FREE — US 54% / 46%, GB 62% / 75%, AR 20% / 80%, DE 80% / 40%, KR 60% / 20%, PH 67% / 0%) — noise on 3–8 reviews, not national character; not uniform (hypotheses): scheduling requests skew non-US (5 of 6), design praise non-US and high-spend, outcome narration US, widget-as-headline KR; localisation: 16 non-English reviews (Spanish 8, Korean 4, Portuguese 2, Russian 1, Traditional Chinese 1) rate 5.000 vs English 4.882", "n/a", "praise", table("## 6.12 Global comparison", 0), "none", "table", "app-specific", [])
save("a")
