# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/85")
from _lib import c, table, save

c(14, "§3.1 table (verbatim); §3.1", "data-caveat", "Prioritised theme table (verbatim): " + table("## 3.1 The prioritised picture", 0) + " — half the corpus praises something and two in five report a defect; 409 (11.87%) do both; PR_CONCEPT (285) averages 3.40★ and 82 of its reviews are 1–2★: 'Great idea, broken app' is the most typical low-star shape.", "n/a", "mixed", "praise∩defect 409 (11.87%); PR_CONCEPT 285 / 3.40★, 82 at 1–2★", "none", "table", "generalisable", ["1223698024"], "", "")

c(15, "§3.2 game-layer table (verbatim); §3.2 game layer", "insight", "The game layer and the people around it (verbatim): " + table("### The game layer and the people", 0) + " — three mechanisms recur: instant reward (gold and XP land the moment a task is ticked), consequence (missed Dailies cost health, and in a party hurt friends), collection (eggs, pets and mounts keep people returning after novelty fades — 'I am constantly doing chores just to earn food for them'); parties turn the consequence social ('In my group, we keep each other motivated'); non-gamers find value too (SEG_NONGAMER 21: 'Best habit tracking app, even without the gamification').", "instant reward + social consequence + collection", "praise", "PR_GAMIFY 468; PR_PARTY 158; PR_COLLECT 88; SEG_GAMER 107; SEG_NONGAMER 21", "build-free", "High-priority", "generalisable", ["13979172887", "12016804932", "14383426803"], "", "")

c(16, "§3.2 outcomes table (verbatim); §3.2 outcomes", "audience", "Outcomes and use contexts (verbatim): " + table("### Outcomes and use contexts", 0) + " — families use it as a chore system for children (USE_FAMILY 58: 'I went from nagging my 11 year old son to do tasks. Now he is asking for more'); professionals recommend it to clients (SEG_PRO 16: a psychotherapist, a life coach, an autism/ADHD support worker, therapists who suggested it to reviewers).", "n/a", "praise", "U_OUTCOME 502; USE_FAMILY 58; SEG_PRO 16; USE_ADHD 71; USE_MENTAL 51", "do", "High-priority", "generalisable", ["13270474069", "1930536403", "13463206718"], "", "")

c(17, "§3.2 structure table (verbatim); §3.2 structure", "insight", "Structure, customisation and being free (verbatim): " + table("### Structure, customisation, and being free", 0) + " — the split into Habits, Dailies and To-Dos is the structural feature named most (PR_TASKTYPES 91); being free is praised as a reason to trust, and to pay: 'No annoying pop ups (which makes me actually want to spend money to support the devs)'.", "three task types; free, no ads", "praise", "PR_TASKTYPES 91; PR_CUSTOM 66; PR_ORGANIZE 95; PR_FREE 68; PR_REWARDS 49", "build-free", "High-priority", "generalisable", ["9505373909"], "", "")

c(18, "§3.3 table (verbatim); §3.3", "must-never-break", "Reliability (verbatim): " + table("## 3.3 Reliability", 0) + " — 386 of 488 1★ (79.1%) carry a defect code; sign-up failure is the harshest (1.55★): 'they haven't been able to program a functional login screen in two years'; recent defects (E5) ranked: BUG_TASK 28, SLOW 27, SIGNUP 22, RESET 21, SERVER 19, WIDGET 15, ACCOUNT 14, CRASH 13 — day rollover and widgets rank much higher than in earlier eras; workarounds REV_TIP 33 (reinstall, log out/in, use the website); REV_UPDATED 35 edited after a fix or relapse ('When that issue is fixed, 5 stars', 1★).", "n/a", "complaint", "1★ with defect 79.1%; E5 top: TASK 28, SLOW 27, SIGNUP 22, RESET 21; REV_UPDATED 35", "must-never-break", "High-priority", "generalisable", ["2784799182", "1753724012", "1835618625"], "", "")

c(19, "§3.4 table (verbatim); §3.4", "market", "Platform gaps (verbatim): " + table("## 3.4 Platform gaps", 0) + " — parity complaints peak in E1 (7.2%) when the rebuilt app launched without web features and without Facebook login (NEG_FB_LOGIN 18, 14 in July 2015); the watch request never stops (every era, 2015-12 → 2026-04); NEG_CHINA_NET 16 (0.46%) — unreachable from mainland China without a VPN, 2015–2026 ('翻墙连接也不行' — even using a VPN does not work).", "iOS behind web; no Watch; China unreachable", "complaint", "NEG_PARITY 141; FB_LOGIN 18; CHINA_NET 16; REQ_WATCH every era", "must-have", "Very strong", "generalisable", ["2841387385", "1223779586"], "", "")

c(20, "§3.5 table (verbatim); §3.5", "positioning", "Community and governance (verbatim): " + table("## 3.5 Community and governance", 0) + " — 'Habitica was one of the least toxic social spaces on the internet' (1★, on the closure); it also produced complaints (NEG_COMMUNITY 20: moderators or party members rude or controlling); after the closure the social requests are small and safe — friend lists, cheering between party members, a party finder for solo players (NEG_SOLO 16).", "guilds/tavern removed; parties remain", "mixed", "PR_COMMUNITY 116; NEG_COMMUNITY 20; NEG_SOLO 16; REQ_SOCIAL 29", "research", "Meaningful", "generalisable", ["10216174483", "12975896573"], "", "")

c(21, "§3.6 table (verbatim); §3.6", "feature", "Unmet needs (verbatim): " + table("## 3.6 Unmet needs", 0) + " — two request-like themes sit outside REQ_*: missing languages (195) and web-only features (141); the language ask alone is larger than any single REQ_* code (largest REQ_CONTENT 79).", "n/a", "complaint", "REQ_CONTENT 79; STATS 71; WIDGET 68; WATCH 67; FREQ 45; CALENDAR 33; REORDER 30; SOCIAL 29; LISTS 20; REMINDERS 20; TRADE 12; DUE 12; REPEAT_TODO 9; PAUSE 7", "none", "table", "generalisable", ["3169036055"], "", "")

c(22, "§3.7 language table (verbatim); §3.7 storefront table (verbatim); §3.7", "market", "Localisation — languages named inside NEG_LANG (verbatim): " + table("## 3.7 Localisation", 0) + " || by storefront (verbatim): " + table("## 3.7 Localisation", 1) + " — three distinct problems share the code: no translation at all (Turkish, Korean, Arabic, Vietnamese); translated elsewhere but not on iOS (Korean and Ukrainian on Android and web); broken language switching where screens mix languages or revert to English; PR_LANG 8.", "n/a", "complaint", "Korean 40; Chinese 55; Turkish 18; Ukrainian 13; Russian 11; kr 76.9%; hk 55.6%; tw 48.4%; tr 40.0%; ua 36.4%; cn 20.4%", "do", "High-priority", "generalisable", ["1568505654", "1822589128", "3401370011", "1237532014", "8745917033"], "", "")

c(23, "§3.8 table (verbatim); §3.8; §8.9", "insight", "Onboarding and game-design friction (verbatim): " + table("## 3.8 Onboarding", 0) + " — newcomers struggle to tell Habits, Dailies and To-Dos apart ('Why are there 3 sections. Doesn't make sense', 2★; NEG_LEARNING_CURVE 73); long-term players say the game runs out ('they are all essentially the same'); the death penalty splits users — some want it softer for illness ('I don't want to be punished again for my health problems', 3★; REQ_PAUSE 7), others find it meaningless ('there was no consequence for losing health', 2★); the honour system is noticed (NOTE_CHEAT 27) but rarely treated as a flaw.", "three task types; health penalty; honour system", "mixed", "NEG_LEARNING_CURVE 73; NEG_PUNISH 23; NEG_GAMEPLAY 64; BUG_DEATH 12; REQ_PAUSE 7; NOTE_CHEAT 27; NEG_DAYSTART 16", "undecided", "Meaningful", "generalisable", ["12882490533", "13581528753", "13501831658", "13882582042"], "", "")

c(24, "§3.9 table (verbatim); §3.9", "insight", "Failure, churn and switching (verbatim): " + table("## 3.9 Failure", 0) + " — churn statements average 1.84★ and are driven by defects (83 of 124 carry a defect code) and the community closure (9 of 124); returners are common (CHURN_RETURN 31), often after a hard period: 'I crashed out from the penalties when having a tough time and ended up uninstalling it for almost 3 years'.", "n/a", "churn", "churn 124 / 1.84★, 83 with defect; CHURN_RETURN 31", "none", "Very strong", "generalisable", ["14308350433"], "", "the penalty mechanic drives churn in hard periods and returns afterwards")

save("a")
