# -*- coding: utf-8 -*-
"""Stage 3 merge for report 85 (Habitica, HabitRPG, Inc.)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C302", "product-rule", "A premium currency must have a slow, honest earned path — a currency free players cannot earn turns free-core goodwill into 'pay-to-win' and rewards lying",
    "Report 85 (Habitica, 3,445 reviews over eleven years): the free core earns goodwill (PR_FREE 68, MON_NOT_REQUIRED 44: 'it doesn't hide functionality behind a paywall'; 'No annoying pop ups (which makes me actually want to spend money to support the devs)') and the gem economy spends it — MON_GEM_GATE 47 (1.36%, mean 3.34★): quests, hairstyles, backgrounds and pet food sit behind gems that free players can barely earn ('The quests and many customization items are stuck behind gem paywalls'); MON_P2W_PERCEIVED 19 at 1.84★ ('After subscribing you are allotted the ability to buy 24 gems for only $6 more dollars'); the complaint is growing — 4.2% of E5 reviews against at most 1.0% in any earlier era; the current free route is challenge prize draws, and 'you have to just lie and say you did it'; the request is not for free gems but for a slow, earned route (streak rewards, achievements, an expensive gold-for-gem exchange); §8.5 replace prize draws with a small earned trickle and measure subscription starts and honesty proxies, not gem balances. Stated purchasers are few (55, 1.60%) and buy as patronage — 'I upgraded just to help support the developers' (23.6% of payers) — so the subscription's value is trust, which the currency erodes. Related: [[C241]] (sell entitlements as non-consumables), [[C270]] (earned free capacity reads as generosity), [[C164]] (a random-rotation shop with paid re-rolls is a friction generator), [[C238]] (a rewarded path for those who cannot pay), [[C061]] (goodwill conversion).")

ext("C024", " Report 85 (Habitica, 3,445 reviews): the fullest gamification in the series — PR_GAMIFY 468 (13.58%, mean 4.72★ vs corpus 3.71); three mechanisms: instant reward (XP and gold on the tick), consequence (missed Dailies cost health, and in a party hurt friends: 'I still have adhd but now I feel anxious that my team could get dmg because of me not doing the dishes'), collection (eggs, pets, mounts: 'I am constantly doing chores just to earn food for them'); U_OUTCOME 502 (14.57%, 4.70★); PR_STICKY 78; the cost side: long-term players say the game runs out ('they are all essentially the same'; 'A progressão fica meio estagnada'), REQ_CONTENT 79 asks for battles and an endgame, and non-gamers still find value (SEG_NONGAMER 21: 'Best habit tracking app, even without the gamification').")
ext("C157", " Report 85 (Habitica): the health penalty for missed Dailies is the pressure some need (PR_PENALTY 34) and drives others out — NEG_PUNISH 23, BUG_DEATH 12, REQ_PAUSE 7: 'I don't want to be punished again for my health problems' (3★); 'I crashed out from the penalties when having a tough time and ended up uninstalling it for almost 3 years' (4★, returned); §8.9 make resting in the inn discoverable and time-limited and test milder death penalties (keep levels) — 'fewer punishment-triggered quits without losing the pressure PR_PENALTY reviewers value'.")
ext("C016", " Report 85 (Habitica): 'rest in the inn' pauses the health penalty but is undiscoverable (PR_REST 6, REQ_PAUSE 7); §8.9 an illness mode.")
ext("C015", " Report 85 (Habitica): parties that fight quest bosses together, where a missed Daily damages the whole party, are the strongest social-accountability mechanic in the series — PR_PARTY 158 (4.59%), party praise held at 5.0% of reviews even after the public community was removed; 'In my group, we keep each other motivated'; NEG_SOLO 16 want a party finder; BUG_SOCIAL 78.")
ext("C202", " Report 85 (Habitica): after guilds and the tavern were removed the social requests are small and safe — friend lists, cheering between party members, a party finder for solo players; NEG_COMMUNITY 20 (rude or controlling moderators and party members) shows the moderation cost of the larger version.")
ext("C155", " Report 85 (Habitica): closing guilds and the tavern on 2023-08-08 — NEG_GUILD_SHUTDOWN 32 (2.25★, 2023 → 2026: 'The guilds were the soul of this app'; 'I was in a guild that basically acted as a sort of support group'), multi-year users at 23.3% of these reviews vs 3.86% overall, two of the thirteen most-voted reviews in the corpus, E4 the lowest-rated era (3.37★), community praise 4.4% → 1.0%; the US description still lists Guilds three years later; §8.7 replace what the guilds did with small opt-in moderated groups and a party-matching queue.")
ext("C165", " Report 85 (Habitica): a staff–volunteer-moderator dispute handled in public — STAFF_CONTROVERSY 19 (0.55%, mean 1.74★, 2022-12 → 2024-11: 'When workers asked for better conditions, they were treated disrespectfully and many were fired'; 'Habitica was one of the least toxic social spaces on the internet') preceded and compounded the guild closure; SUP_NOT_LISTENING 4.7% of E4.")
ext("C175", " Report 85 (Habitica): U_BUG_ANY 1428 (41.45%, mean 2.81★) over eleven years — BUG_CRASH 415, BUG_REGRESSION 201 blame a specific update; the waves are dated: 2016-11 (72 reviews, 54 crashes on the Rewards page), 2017-10 (86, 45 crash on launch), 2021-08-20 (49 reviews in one day, 47 crashes: 'crashes and auto closes in a matter of seconds'); crash reports fall to 2.1% from 2024 but the newer defects are quieter and more corrosive — Dailies not resetting (BUG_RESET 93), taps on the wrong task, widgets not refreshing; 386 of 488 1★ carry a defect; §8.1 'a staged rollout with crash-rate gating would have contained 2016-11, 2017-10 and 2021-08-20'.")
ext("C156", " Report 85 (Habitica): §8.1 staged rollout with crash-rate gating — the corpus holds 201 reviews blaming a specific update and single days with 49 crash reports; a halted rollout would have contained three waves.")
ext("C031", " Report 85 (Habitica): BUG_CRASH 415 (12.05%, 2015 → 2026) in dated waves after updates; 'The latest 2 versions of the app have ceased to work at all for me. They crash on startup' (1★); crash share 16.2% of reviews in 2015–16 → 2.1% from 2024.")
ext("C038", " Report 85 (Habitica): BUG_RESET 93 (2.70%) — 'the app will tell me it started a new day, but it hasn't cleared out my dailies' (3★); NEG_DAYSTART 16; in the latest era day-rollover failures rank fourth among defects; §8.1 make 'start new day' (cron) idempotent and visible and never let a failed rollover block ticking tasks.")
ext("C170", " Report 85 (Habitica): NEG_DAYSTART 16 — the custom day start interacts with a server-side rollover that sometimes fails (BUG_RESET 93).")
ext("C077", " Report 85 (Habitica): BUG_SIGNUP 139 (4.03%, mean 1.55★ — the harshest code: 'people who never got in have nothing else to say'; 'they haven't been able to program a functional login screen in two years'), BUG_ACCOUNT 85: the onboarding Finish button, Google sign-in returning to the same screen, prefilled usernames that cannot be changed; the 2018-02-26 App Store feature day brought new users who could not reach the servers to register (22 reviews that day, 2018 the lowest-rated year at 3.32★); §8.2 'sign-up and login that never dead-ends'.")
ext("C235", " Report 85 (Habitica): §8.2 an offline-first first run so a server error does not stop someone creating their first task — the sign-up failure waves (139 reviews, 1.55★) and NEG_OFFLINE 55 are the evidence.")
ext("C188", " Report 85 (Habitica): NEG_OFFLINE 55 (1.60%) and BUG_SERVER 126 (3.66%) — a server-dependent client that cannot open or tick tasks during outages (2023-09-16: 20 reviews in a day, 17 server errors); NEG_CHINA_NET 16 unreachable from mainland China without a VPN ('翻墙连接也不行' — even using a VPN does not work).")
ext("C132", " Report 85 (Habitica): the service is unreachable from mainland China without a VPN for the whole eleven years (NEG_CHINA_NET 16, 14 of them on the cn storefront, 15× lift) — cn is the second-largest storefront (201 reviews) and its defect share (53.2%) the highest of the eleven eligible.")
ext("C295", " Report 85 (Habitica): a server-dependent client sold on the Chinese storefront that cannot reach its servers there — 'in mainland China it keeps failing to connect' (4★); access complaints outnumber game complaints on cn.")
ext("C251", " Report 85 (Habitica): NEG_PARITY 141 (4.09%, in every era 1.9–7.2%) — challenges, guild management, the market, stats and inbox exist only on the web and the web is faster; NEG_IOS_BEHIND 21 — Korean and Ukrainian on Android but not iPhone, a Wear OS watch app but no watchOS ('安卓使用者是人，蘋果不是人喔' — Android users are people, Apple users aren't?); the corpus's last review (2026-09-06, 5★) recommends the website as the workaround; §8.10 'the web version as a stable fallback until the app matches it'.")
ext("C022", " Report 85 (Habitica): REQ_WATCH 67 (1.94%), in every era from 2015-12-07 to 2026-04-29 — the longest-running unshipped request in the corpus; a Wear OS version exists ('It doesn't make sense that Habitica hasn't released for Apple Watch but Wear Os'); §8.8 a watchOS companion for checking off Dailies and Habits.")
ext("C040", " Report 85 (Habitica): widgets arrived and became a defect source — BUG_WIDGET 22 (all from 2021), 15 of them in the latest era where widget failures rank sixth among defects; REQ_WIDGET 68 (1.97%).")
ext("C011", " Report 85 (Habitica): an eleven-year-old gamified tracker still lacks history and statistics — REQ_STATS 71 (2.06%), REQ_CALENDAR 33 ('if it had a calender for the habits and I could see how many days in a month I completed the task' carries 14 votes, more than any other request); §8.6 hypothesis: 'users who can see progress outside the avatar keep using the app past the point where the game content runs out'.")
ext("C012", " Report 85 (Habitica): the avatar is the only progress view; REQ_CALENDAR 33 and REQ_STATS 71 ask for the grid/history that every other tracker in the series has.")
ext("C043", " Report 85 (Habitica): REQ_FREQ 45 (1.31%) — '3 times a week'; 'there being no option for truly weekly tasks' (1★); REQ_DUE 12; REQ_REPEAT_TODO 9; §8.6 'N times per week' Dailies.")
ext("C075", " Report 85 (Habitica): NEG_LEARNING_CURVE 73 — newcomers struggle to tell Habits, Dailies and To-Dos apart ('Why are there 3 sections. Doesn't make sense', 2★); NEG_HOWTO 8 in Japan (6.5× lift: how to get the Orb of Rebirth, how quests start); France 4.0×; the three task types are also the structural feature praised most (PR_TASKTYPES 91).")
ext("C119", " Report 85 (Habitica): the mid-2018 redesign removed sorting pets by colour; a 2026 redesign splits users (two like it, three do not); NEG_REDESIGN present across eras.")
ext("C027", " Report 85 (Habitica): NEG_LANG 195 (5.66%) is the most-voted complaint in the corpus — four of the six most-voted reviews ask for Turkish (154 votes between them); Korea is a single-issue storefront (40 of 52 reviews, 76.9%, about the missing Korean translation — which exists on Android); the listing declares 18 languages but not Korean or Turkish ('Man, there's even Hebrew but no Turkish'); three problems share the code — no translation at all (Turkish, Korean, Arabic, Vietnamese), translated elsewhere but not on iOS, and broken language switching (screens mix languages or revert to English; BUG_DISPLAY 20 of 63 in cn); §8.3 publish a translation call inside the storefronts asking loudest.")
ext("C255", " Report 85 (Habitica): translations are volunteer work and a volunteer reports the finished Ukrainian iOS translation had not shipped for months (2026-05-18) while 'Немає української мови' earns a 1★ — 'ship the translations volunteers already made'; a language setting that reverts to English and mixed-language screens are their own defect class.")
ext("C286", " Report 85 (Habitica): sold on the Korean and Turkish storefronts for a decade with no Korean or Turkish UI — kr NEG_LANG 76.9%, tr 40.0% and the corpus's most-voted reviews.")
ext("C042", " Report 85 (Habitica): USE_ADHD 71 (2.06%, 4.41★) is the fastest-growing audience — 6.0% of E5 vs ≤1.3% in E1–E3; the instant reward of XP and gold is the mechanism they name ('The first app that helps me with my ADD'; 'I have ADHD and find it hard to do tasks, but this app has been a game changer'); the same audience names the failure modes: pop-ups that derail the task, punishments that feel arbitrary or absent ('ADHD, autism, and executive dysfunction, not helpful', 2★), too much stimulus ('Demasiados impulsos texto y provoca que te distraigas', 2★), and the loss of a guild that worked as a support group; USE_MENTAL 51; professionals recommend it (SEG_PRO 16: a psychotherapist, a life coach, an autism/ADHD support worker).")
ext("C183", " Report 85 (Habitica): 'For people with depression, like me, this app is incredible' (18 votes, the most-voted purely positive review); 'Points go in where you can see them, so you want to do it even when you're not motivated' (jp) — instant visible reward as the executive-function aid.")
ext("C103", " Report 85 (Habitica): the mental-health cohort (USE_ADHD 71, USE_MENTAL 51) is both the most enthusiastic and the most exposed — a guild used as a support group was removed in 2023, and a punishment mechanic drove a struggling user out for three years; therapists recommend it to clients.")
ext("C068", " Report 85 (Habitica): USE_FAMILY 58 — a chore system for children ('I went from nagging my 11 year old son to do tasks. Now he is asking for more'); gift subscriptions for friends and family (3); a paid group plan for shared task lists is 'not usable in the iOS app' per one reviewer.")
ext("C174", " Report 85 (Habitica): families run it as a shared chore system (USE_FAMILY 58) and a paid group plan exists for shared task lists — but is reported unusable in the iOS app.")
ext("C061", " Report 85 (Habitica): the subscription sells as patronage — MON_SUPPORT_DEV 13 of 55 purchasers (23.6%: 'I upgraded just to help support the developers'; 'I don't mind contributing $5 a month to keep the app and website going'), long-term users 21.8% of payers vs 3.86% of all; 'No annoying pop ups (which makes me actually want to spend money to support the devs)'; MON_ALT_SUPPORT 5 want 'a donate button not add ons'.")
ext("C097", " Report 85 (Habitica): donations were an option 2015–2018 (MON_DONATE 2) and five reviewers ask for a donate button instead of add-ons — for an open-source, free-core product, patronage is the stated purchase motive.")
ext("C239", " Report 85 (Habitica): 'an open-source app run by a small team that's made better by the work of volunteers' — the listing's framing is why purchasers pay (support, 23.6%) and why the 2023 dispute with volunteer moderators cut so deep (STAFF_CONTROVERSY 19 at 1.74★).")
ext("C065", " Report 85 (Habitica): stated purchasers (55) average 3.25★ and 15 of 55 report a purchase that went wrong — paid then the app would not open ('Paid for premium but can barely use it as it constantly crashes', 1★), gems not credited ('I got a month subscription and the gems didn't credit to my account', 1★), could not cancel ('Habitica keeps charging for new subscriptions', 1★), left over the 2023 changes; MON_PAID_UNHAPPY 17.")
ext("C033", " Report 85 (Habitica): BUG_IAP 9 — subscription benefits and gems not credited after payment; §8.4 restore/credit checks and a preview of paid backgrounds.")
ext("C112", " Report 85 (Habitica): MON_CANCEL_HARD 4 — 'Habitica keeps charging for new subscriptions' (1★); §8.4 a visible cancel path and clear App Store subscription management.")
ext("C064", " Report 85 (Habitica): MON_PRICE_HIGH 8 — '12 month usage cost as much as a tripple AAA vid game title' (2★); 'I'd gladly pay $10-$15 for the full program but nickel and diming users is off-putting' (2★); regional pricing in Russia and 'a bit expensive' in Turkey; MON_PRICE_FAIR 6; 'I'm a subscriber now, it's not expensive'.")
ext("C003", " Report 85 (Habitica): 'I'd gladly pay $10-$15 for the full program but nickel and diming users is off-putting' — a one-off wanted instead of subscription + consumable gems.")
ext("C231", " Report 85 (Habitica, 3,445 reviews over eleven years): the US listing shows 4.27★ from 3,324 ratings against a US corpus mean of 3.76★ and the public mean exceeds the corpus mean by 0.26–0.78★ in all eleven eligible storefronts — 'people write when something breaks'; the distribution is bimodal (5★ 44%, 1★ 14%); CONTRA_RATING 46 — 44 are 5★ reviews reporting a defect, 42 of them before 2022-12 and cn over-represented, 'consistent with reviewers treating the star field as a contact form'; single days hold 49 (crash), 22 (feature day) and 20 (outage) reviews and excluding them moves no headline more than 5.4 points; three authors on >1 storefront; 'great app!' recurs across three authors years apart.")
ext("C300", " Report 85 (Habitica): public exceeds corpus by 0.26–0.78★ in every eligible storefront for an app with an eleven-year defect history — the ordinary 'people write when something breaks' gap, an order of magnitude below the report 82 anomaly.")
ext("C002", " Report 85 (Habitica): the offer is free and the ratings still fell — E2 3.52★ and E4 3.37★ are reliability and governance eras; 'Great idea, broken app' is the most typical low-star shape (PR_CONCEPT 285 at 3.40★, 82 at 1–2★); the rating recovers to 4.04★ in 2026 as crashes fall to 4 a year while gem-gating and request shares rise.")
ext("C059", " Report 85 (Habitica): REV_UPDATED 35 edited after a fix or relapse ('When that issue is fixed, 5 stars'); PR_UPDATE 170; PR_DEV 11 in Russia; the developer-relationship counter-signal is SUP_NOT_LISTENING 4.7% of E4 and the moderator dispute.")
ext("C094", " Report 85 (Habitica): a 1★ given in protest at a rating prompt (CONTRA_RATING); reviewers use the 5★ field as a contact form for bug reports (44 of 46 contradictions).")
ext("C225", " Report 85 (Habitica): the counter-case — an App Store feature on 2018-02-26 landed on a day the servers could not register new users: 22 reviews that day, 67 in the month at 2.91★ ('Downloaded the app this morning because of the App Store recommendation', 1★); a promotion the service cannot serve converts into a 1★ wave.")
ext("C058", " Report 85 (Habitica): therapists, a psychotherapist, a life coach and an autism/ADHD support worker recommend it to clients (SEG_PRO 16, 13 in the US); an AI assistant is a new acquisition route ('I asked ChatGPT for ideas on making my life more like a video game—enter Habitica', 5★, 2025).")
ext("C237", " Report 85 (Habitica): the collection loop (eggs, pets, mounts: PR_COLLECT 88) retains after novelty fades, but REQ_CONTENT 79 (2.29%) — more content, actual battles, an endgame — and 'they are all essentially the same' show the runway ends; REQ_TRADE 12.")
ext("C164", " Report 85 (Habitica): challenge prize draws are the main free route to gems and reviewers say they reward lying ('you have to just lie and say you did it', 3★); NOTE_CHEAT 27 notice the honour system.")
ext("C169", " Report 85 (Habitica): NOTE_CHEAT 27 — the honour system is noticed but rarely treated as a flaw; it becomes one where gems are the prize ('you have to just lie and say you did it').")
ext("C005", " Report 85 (Habitica): 'this is essentially a planner pretending to be a game' (3★); CMP_OTHER_APPS present; compared as a game against 'tripple AAA' titles on price.")
ext("C062", " Report 85 (Habitica): payment and gem-gating signals concentrate in English-speaking storefronts (paid signal 2.4% US vs 0.8% non-English eligible) while non-English storefronts carry the language complaint (15.7% vs 0.3% US); defect shares 15.4% (kr) to 53.2% (cn); Germany the lowest-rated eligible storefront (3.31★, 1–2★ 34.3%).")
ext("C130", " Report 85 (Habitica): the US (42.99%) carries the pay-to-win objection (15 of 19), the professional recommenders (13 of 16), trading requests (11 of 12) and the guild-closure grievance (19 of 32).")
ext("C140", " Report 85 (Habitica): Habits (+/− counters with no schedule), Dailies and To-Dos plus custom real-life rewards — 'a planner pretending to be a game'; PR_CUSTOM 66; PR_ORGANIZE 95.")
ext("C209", " Report 85 (Habitica): an account is mandatory and sign-up is the harshest failure in the corpus (BUG_SIGNUP 139 at 1.55★); NEG_FB_LOGIN 18 when the rebuilt app launched without Facebook login.")
ext("C267", " Report 85 (Habitica): NEG_ART 35 — the 16-bit art divides; NEG_CHILDISH 3; NEG_RPG_UNWANTED 3.")
ext("C216", " Report 85 (Habitica): PR_GRACE 10 and PR_REST 6 vs NEG_PUNISH 23 — a health bar that regenerates and an inn to rest in are the forgiving elements; users ask for them to be discoverable and time-limited.")
ext("C123", " Report 85 (Habitica): BUG_NOTIF 50 vs PR_NOTIF 24; REQ_REMINDERS 20; pop-ups that derail the task are named by ADHD users.")

M = {
 "R85-001":["C024","C140","C251"], "R85-002":["C231"], "R85-003":["C231","C300"], "R85-004":["C175","C231"], "R85-005":["C024","C015","C183","C042"],
 "R85-006":["C175","C031","C038","C077","C188"], "R85-007":["C251","C022","C040","C188"], "R85-008":["C155","C165","C202","C103"], "R85-009":["C027","C255","C286"], "R85-010":["C302","C061","C065","C164"],
 "R85-011":["C011","C012","C043","C237"], "R85-012":["C042","C183","C103","C123"], "R85-013":["C302","C061","C097","C174"], "R85-014":["C231","C002"], "R85-015":["C024","C015"],
 "R85-016":["C068","C174","C058","C042"], "R85-017":["C140","C061","C075"], "R85-018":["C175","C077","C059","C038"], "R85-019":["C251","C022","C188","C132","C295","C209"], "R85-020":["C202","C155","C165"],
 "R85-021":["C011","C043","C237","C022","C040"], "R85-022":["C027","C255","C286"], "R85-023":["C075","C157","C016","C169","C216","C119"], "R85-024":["C157","C002"], "R85-025":["C231"],
 "R85-026":["C231","C094"], "R85-027":["C065"], "R85-028":["C061","C097","C239","C068"], "R85-029":["C065","C033","C112"], "R85-030":["C302","C064","C003","C164"],
 "R85-031":["C065"], "R85-032":["C231"], "R85-033":["C130","C005"], "R85-034":["C132","C295","C027"], "R85-035":["C225","C077","C062"],
 "R85-036":["C062","C064"], "R85-037":["C075","C027"], "R85-038":["C062"], "R85-039":["C027","C231"], "R85-040":["C002","C231"],
 "R85-041":["C175","C225","C058","C119","C002"], "R85-042":["C231","C022"], "R85-043":["C175","C156","C038","C040"], "R85-044":["C077","C235","C188","C209"], "R85-045":["C027","C255"],
 "R85-046":["C033","C112","C065"], "R85-047":["C302","C164","C169"], "R85-048":["C011","C043","C022","C012"], "R85-049":["C155","C202","C015"], "R85-050":["C157","C016","C216"],
 "R85-051":["C024","C061","C251"], "R85-052":["C058","C255"], "R85-053":["C155","C165","C239"], "R85-054":["C251","C059"], "R85-055":["C225","C077"],
}
M["R85-023"] += ["C267"]; M["R85-043"] += ["C170"]
cards = [json.loads(l) for l in open("Tools/prd_ledger/85/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/85/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 85" in x["statement"] and not any(k.startswith("R85-") for k in x["cards"])])
