# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/86")
from _lib import c, table, save

c(52, "§8.1; part 8 #1", "must-never-break", "§8.1 immediate fix — make check-in latency independent of history size: write latency grows with accumulated check-ins (diagnosed at ~200, total failure past 1,000, 5 seconds per tap after three years, over a minute); 24.3% of those reviewers also record leaving or being blocked; 'the highest-leverage fix in the report because of who it hits: the users with the longest histories are the ones who proved the product works, are most likely to have paid, and are most likely to be publicly enthusiastic'; 'test it the way users experience it: seed 20 habits × 1,000 check-ins and measure tap-to-confirmation. Do not test on a fresh install.'", "latency proportional to history", "churn", "BUG_PERF 70 / 3.92% (16.95% of E5); churn among them 24.3%", "must-never-break", "Very strong", "generalisable", ["11596711598", "9295872427", "3827656315", "8580429365"], "", "")

c(53, "§8.2; part 8 #2", "must-never-break", "§8.2 immediate fix — restore purchases reliably and make restore discoverable: MON_RESTORE 18 over nine years plus IAP_FAIL 11 and OVERCHARGE 2; reviewers reinstall, lose premium and conclude they were scammed; one found Settings → Restore Purchases himself — 'the function exists and is undiscoverable'; fix receipt validation and 'surface restore at the paywall, not buried in Settings. Every user hitting the paywall who has already paid is a support ticket and a one-star review.'", "restore buried in Settings", "1★-burst", "RESTORE 18; IAP_FAIL 11; OVERCHARGE 2", "must-never-break", "Meaningful", "generalisable", ["6868594425", "5727531937", "1698805807"], "", "")

c(54, "§8.3; part 8 #3", "must-never-break", "§8.3 immediate fix — reminders must fire and must not stop when a user misses a day: BUG_NOTIF 63 across the full life of the app, 10 say it makes the app useless; the behaviour reported in 2017 and 2021 — 'the app seems to stop its reminders even if you miss just one activity so the following day, you don't get a reminder (surely this is the most important time to have a reminder?)' — 'a habit app that goes quiet precisely when the user lapses has inverted its own purpose'.", "reminders silenced after a missed day", "complaint", "BUG_NOTIF 63; stop-after-miss 2", "must-never-break", "Very strong", "generalisable", ["1712510655", "7936221496"], "", "")

c(55, "§8.4; part 8 #4", "must-never-break", "§8.4 immediate fix — never lose data, and never lose it from a paid backup: 12 of 55 data-loss reviewers had paid and backup is the paid feature (a wiped three-year history; a backup overwritten by the restore flow; 'lost ALL my information on 2 occasions'); minimum bar: restore must never destroy the backup it is reading, a failed restore must leave existing data intact, covers/photos must survive a restore; the right shape is probably optional account-based sync — not mandatory, because on-device data is something reviewers actively praise.", "paid backup that overwrites itself", "1★-burst", "dataloss_any 55; paid 12; REQ_ACCOUNT 3; PR_PRIVACY 4", "must-never-break", "Very strong", "generalisable", ["5866189908", "2168696471", "6432248651", "2955539119"], "", "")

c(56, "§8.5; part 8 #5", "feature", "§8.5 immediate fix — ship the iOS home-screen widget: REQ_WIDGET 47, the only request that grows as the corpus shrinks (1.98% → 16.95%), home-screen requests 2020-09 → 2025-12; conversion evidence is unusually direct — 'they urgently need a widget and I swear I'd pay premium'; 'its lack of a widget means I'll probably need to look for something else'; the NC widget's history proves the value: the primary interface when it existed (PR_WIDGET 28, 4.50★), 11 complaints in six languages when it vanished for two months.", "no home-screen widget in 5.5 years", "blocked-conversion", "REQ_WIDGET 47; PR_WIDGET 28 / 4.50★; removal complaints 11", "build-free", "Very strong", "generalisable", ["10949219510", "12176761820", "7786249554"], "", "")

c(57, "§8.6; part 8 #6", "feature", "§8.6 experiment — let a habit be paused, archived or legitimately skipped: REQ_ARCHIVE 11 + REQ_SKIP 11, the corpus's most-upvoted request; 'the current design forces a user who has succeeded to delete their habit and destroy the record of succeeding. That is a strange thing for a habit app to do'; two needs — archive ('already formed or no longer needed, but currently you can only delete it') and skip (illness, travel, 'a bad mental-health day' — one uses it to manage depressive episodes and calls it the reason the app worked); a skip feature already exists and nobody understands it — three ask what it does and one reports it damaging streak statistics: 'fixing the explanation may be worth more than building anything'.", "no archive; skip exists but unexplained and stat-damaging", "complaint", "ARCHIVE 11; SKIP 11; top-voted request 22/36; skip-confusion 3", "must-have", "Meaningful", "generalisable", ["2223367800", "1562859639", "5692422621"], "", "")

c(58, "§8.7; part 8 #7", "dont", "§8.7 experiment — resolve the 'bad habits' promise: the listing says 'Quit bad habits and stay on track' and the product cannot track a limit (REQ_BREAKBAD 15, USE_QUIT 16 trying anyway); two honest options — build a 'maximum N per period' habit type as five reviewers describe and as Done and HabitBull are named as having, or remove the promise; 'what is not defensible is the current state: advertising a capability, collecting users who need it, and having them discover the gap after purchase'.", "listing promise without the feature", "complaint", "BREAKBAD 15; USE_QUIT 16", "dont", "Emerging", "generalisable", ["7645092267", "5953889344"], "", "")

c(59, "§8.8; part 8 #8", "must-have", "§8.8 experiment — give the one-page-per-habit model an escape hatch: REQ_DASHBOARD 70 (ten years), BUG_SWIPE 39, UX_FRICTION 41; 'the full-screen-photo model is the differentiator and the scaling problem. Do not remove it; make it optional past a threshold' — users have specified the fix: 'list as a default view; tap on an item will add a point; a habit image as a part of a row'; 'I want the task list shown on launch' (jp); 'the ability to not use a picture for every habit but rather just a simply background to make the app faster' (1★ — connecting the visual model to the performance problem).", "no list/overview view", "complaint", "DASHBOARD 70; SWIPE 39; FRICTION 41", "must-have", "Very strong", "generalisable", ["5294830409", "3440039586", "2026175358"], "", "")

c(60, "§8.9; part 8 #9; §8.13 #1", "product-rule", "§8.9 experiment — re-examine the free tier with the corpus's own evidence: 1 habit → MON_FREE1 78 at 1.97★ (71 in 2016 alone; the complaint returned within months of the cap being restored ~2022); 3 habits → MON_FREE3 67 at 3.60★, the same grievance 1.63 stars higher; 3–5 habits → zero one-habit complaints in four years; MON_TRIAL_REQ 33 made identically in 2016 and 2024 — 'one habit is not a trial, it is a screenshot. A one-habit cap in an app whose paid value is multi-habit dashboards prevents the prospect from ever seeing the thing they would be buying'; caveat: the 1★ at a 1-habit cap come disproportionately from people who never used the app — removing them may raise the rating without raising revenue; §8.13 #1 A/B test with revenue, not rating, as the metric.", "1-habit cap restored ~2022", "blocked-conversion", "FREE1 78 / 1.97★; FREE3 67 / 3.60★; TRIAL_REQ 33; 0 complaints 2017–2020", "product-rule", "High-priority", "generalisable", ["1346034110", "8311997753", "1346019622", "10949219510", "1351843491"], "", "")

c(61, "§8.10; part 8 #10", "dont", "§8.10 immediate fix — the $299.99 tier needs an explanation or a change: $3.99/month, $9.99/year and $299.99 'All premium features' — 'why is Today Premium $10 per year, but ALL Premium Features are $300 ❓ what is the difference' (2★); 30× the annual price — 'whatever the intent — a lifetime tier, a price-anchoring device, a legacy artefact — it currently reads to users as either a mistake or contempt, and it sits next to a history of paying customers losing their purchase'; MON_SUBSCRIPTION 8, all post-2022, none positive, vs PR_ONETIME 23 at 4.61★ praising the replaced model.", "$299.99 lifetime beside $9.99/yr", "blocked-conversion", "lifetime 30× annual; SUBSCRIPTION 8 / 0 positive; ONETIME 23 / 4.61★", "dont", "Meaningful", "generalisable", ["8946229677", "8448197948", "13865667618"], "", "")

c(62, "§8.11; §8.12; part 8 #11; part 8 #12", "do", "§8.11 immediate fix — answer support, and be seen to: SUP_NORESP 25 vs PR_DEV 39 (30 of 39 pre-2019), FIX_CONFIRM 33 (21 pre-2019); repeated documented instances of a reply converting a 1★ into a 5★; the in-app support email address is misspelled (toda@neybox.com) and the corrected one got no reply — 'the cheapest fix in this report'. §8.12 copy: the full-screen personal photo per habit (the single most-credited mechanism), a per-habit configurable dashboard (PR_CARDS 4.69★), one-time pricing honestly priced (4.61★), visible responsiveness (a rollback earning public rating upgrades), no ads / no account / on-device data; do not copy: one screen per habit as the only navigation, selling backup then losing data, gating the biometric lock then shipping a build where enabling it crashes, a visual design whose data layer scales worse than the visuals, advertising a capability you do not have, letting an unlaunchable build sit for 1,030 days — 'what converts a category-leading app into abandonware'.", "n/a", "mixed", "SUP_NORESP 25; PR_DEV 39; FIX_CONFIRM 33; misspelled support address", "do", "High-priority", "generalisable", ["12543093674", "3493496861", "3491619389", "1974586345"], "", "")

c(63, "§8.13", "insight", "§8.13 research questions: does a wider free tier raise revenue or only the rating (A/B with revenue as the metric); who actually pays (18 reviewers name a trigger — instrument the paywall); the real retention curve (98 announce leaving; silent churn invisible); do cards drive retention or just enthusiasm (they correlate with the highest-rated reviews and with confusion — measure card usage against 90-day retention); is there an accessibility problem (2 mentions in 1,785; a full-screen-photo app with text over imagery has obvious contrast risk, reported in 2016); can the 2025–26 revival recover the base (E6 is 13 reviews — re-run in twelve months).", "n/a", "mixed", "report gives none", "research", "limited evidence", "generalisable", ["1449566698", "13496344540"], "", "")

c(64, "§7.3 Wave 3; §2.3 (lock paid); §8.12", "anti-pattern", "Gating the biometric lock as a paid feature — one reviewer objects on principle — and then shipping a build (March 2018) where enabling it crashed the app on entry: 'after enabling fingerprint unlock, pressing the fingerprint crashes, entering the password also crashes. What was my 30 yuan for?… I appealed to Apple and was told no refund' (cn 1★); the same fortnight carried the purchase outage; and the lock leaks the habit list via the widget, 3D Touch and background resume (three reports, three languages).", "paid lock that crashed and leaks", "1★-burst", "wave 3: 5 in 9 days; lock-leak 3; PRIV_CONCERN 4", "dont", "Meaningful", "generalisable", ["2273762627", "5116388115", "2004605175"], "", "")

c(65, "§0.8; §7.5 Act 2; §8.12", "anti-pattern", "Silent removals and silent abandonment: the Notification-Centre widget was removed in 1.9.55 (2021-09-02) with release notes that said nothing about it — 11 complaints in six languages in three months, 'the main way i used the app… I probably won't keep up' (1★); then 1.9.63 (2022-11-09) shipped a black screen for many users and nothing followed for 1,030 days while the support address in the app was misspelled and Twitter went quiet — DEV_STALE 67 (20.34% of E5), users auditing the developer and concluding 'likely abandoned'.", "unannounced widget removal; 1,030-day silence after a broken build", "churn", "removal complaints 11; DEV_STALE 67 / 20.34% of E5; 1,030 days", "dont", "Very strong", "generalisable", ["7786249554", "9271340335", "12543093674", "6453348017"], "", "")

save("a")
