# -*- coding: utf-8 -*-
"""Stage 3 merge for report 86 (Today Habit tracker, Neybox Digital Ltd.)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C303", "must-never-break", "Check-in latency must be independent of accumulated history — an app that slows with every completed day drives away exactly the users who proved it works and most likely paid",
    "Report 86 (Today Habit tracker, 1,785 reviews over 10.3 years): the most damaging defect in the corpus appears only once a user has succeeded — BUG_PERF 70 (3.92%), rising from 0.74% of E1 to 16.95% of E5; reviewers quantify it: 'it takes about 5 seconds to register, if I'm registering a long streak of 50 day's or so, which is how I've been using it for 3 years, it takes so long I've stopped bothering' (gb 1★); 'past 1,000 days a single tap means a mysterious freeze then a crash' (jp 1★); '200 check-ins is not really a large amount of data; the storage must be inefficiently programmed' (de 3★); 'It can take over a minute from when you mark something as done… I've contacted support multiple times over the past 6 months' (1★); 17 of the 70 (24.3%) also record leaving or being blocked; Germany is the performance-complaint market (11.69%, three times global); paid reviewers report defects at a higher rate because they use it longer with more habits — 'exactly the condition under which this app degrades'; one reviewer connects the full-screen-photo visual model directly to the slowness. §8.1: 'test it the way users experience it: seed 20 habits × 1,000 check-ins and measure tap-to-confirmation. Do not test on a fresh install.' Related: [[C083]] (performance must not degrade with habit count), [[C264]] (log-entry friction is sacred), [[C065]] (paying customers are the highest 1★ risk).")

ext("C083", " Report 86 (Today): the sibling failure — latency growing with accumulated check-ins rather than habit count ([[C303]]); 'as my list of habits gets longer (and my dashboards get more complex), it gets very slow and the list gets very difficult to navigate' (za 3★); a performance fix in Mar/May 2020 was confirmed ('The latest update fixed the lag. I've dealt with that tedious issue every single day for months') and the complaint returned.")
ext("C079", " Report 86 (Today): the strongest evidence in the series for a personal photo per habit — PR_DESIGN 460 (25.77%, the largest theme) with PR_PHOTOS 97 in a visual union of 523 (29.30%, 4.36★); reviewers treat it as the mechanism: 'I'm a very visual person, so the combination of large pictures and colourful calendars/graphs is great. I really feel motivated to tick things off, more than any other habit app'; 'It sets a craving, when I see the image, I want to accomplish the goal'; custom covers named as the one reason productivity improved most across 15 trackers; custom covers are a named purchase trigger ('I purchased the full thing just because to put my own photo covers'); PR_DESIGN holds at 15.25% even in the abandonment era — 'the app never stopped being beautiful. It stopped working'; §8.12 'copy: the full-screen personal photo per habit'; the costs: one page per habit does not scale ([[C254]]) and the image layer is blamed for slowness; a paid feature later taken away with users' existing covers ('you have to pay to use your own pictures and completely took everything i had on my profile off', 1★).")
ext("C254", " Report 86 (Today): the one-page-per-habit model is the differentiator and the scaling ceiling — REQ_DASHBOARD 70 (3.92%, 2016-03-21 → 2026-07-13, ten years: 'see all habits at once'), BUG_SWIPE 39 (horizontal swipe fighting vertical scroll, 2016 → 2024 in seven languages, 'the single longest-running unfixed complaint'), UX_FRICTION 41 — 'Requiring each habit to be its own page makes this impractical for tracking more than a small number of items' (2★); 'I have more than 30 habits… please minimize that dashboard so i could see all my habits at once' (2026); users specify the fix — 'list as a default view; tap on an item will add a point; a habit image as a part of a row'; §8.8 'do not remove it; make it optional past a threshold'.")
ext("C007", " Report 86 (Today): the clearest natural experiment on cap size in the series — the free tier went 1 → 3 (Mar 2016) → 5 (2017, n=1) → 1 (~2022): at one habit MON_FREE1 78 reviews at 1.97★ (71 in 2016 alone, the dominant theme of the first fortnight), raised to three within two weeks and noticed within a day ('because they actually listened to there customers I just paid full price for it!'), then zero one-habit complaints for four years (2017–2020); narrowing back to one in ~2022 re-imported the complaint in the same words ('you can only track ONE habit with the free version… If they had just advertised this as a paid app, it would have been fair', 2★); three-habit complaints (67) average 3.60★ — 'the same grievance, attached to a tier three times wider, arrives with a rating 1.63 stars higher'.")
ext("C297", " Report 86 (Today): the cap's own size is the bundle here — the same one-habit grievance at 1.97★ vs the three-habit grievance at 3.60★, and a four-year silence in between; a single review attests a 5-habit stage.")
ext("C293", " Report 86 (Today): the counter-evidence at small numbers — raising the cap from one to three did buy back sentiment (71 complaints in 2016 → 0 in 2017–2020, one angry 1★ converting to full price the same month) because one habit is 'a screenshot, not a trial'; the null result in report 75 was 3 → 5, past the point where the cap stopped being the objection.")
ext("C191", " Report 86 (Today): the free tier was narrowed back from three (or five) habits to one in ~2022 and 'the complaint came back with it' — 'I understood the free version allowed up to 3' (pe 1★); premium photo covers were also moved behind payment 'and completely took everything i had on my profile off to do so' (MON_REGRESS 3).")
ext("C296", " Report 86 (Today): 'one habit is not a trial, it is a screenshot. A one-habit cap in an app whose paid value is multi-habit dashboards prevents the prospect from ever seeing the thing they would be buying' — MON_TRIAL_REQ 33 (1.85%) made identically in 2016 ('Expand the free app to allow a proper trial and then ask for money') and 2024 ('one is not enough for a trial'); a confused user who deleted the app 'otherwise I'd have bought it'.")
ext("C147", " Report 86 (Today): 'unable to evaluate it with only one card… this should be listed as a paid app not free' (1★, 2016); the paid value (multi-habit dashboards, cards) is invisible at a one-habit cap; §8.9 caveat: the 1★ at a one-habit cap come disproportionately from people who never used the app — removing the cap 'may raise the rating without raising revenue', so test with revenue as the metric.")
ext("C063", " Report 86 (Today): the free tier is the trial and MON_TRIAL_REQ 33 (1.85%) — 'a real one' — was the most-requested monetisation change in 2016 and still asked in 2024.")
ext("C003", " Report 86 (Today): a one-time ~$4.99 unlock (2016–~2021) was praised as the reason to choose the app — PR_ONETIME 23 (4.61★), U:pro_pricing 124 (6.95%, 4.75★): 'Paying once (4.99) for all these features is the prime reason I use this app as a Habit Tracker compared to others'; 'some apps out there have a yearly subscription circa £30… this one is a steal at £5'; MON_DEFEND 44 argue against other reviewers' price complaints; the model was then replaced (~2022) by $3.99/month, $9.99/year and a $299.99 'All premium features' tier — MON_SUBSCRIPTION 8, all post-2022, none positive.")
ext("C177", " Report 86 (Today): three IAPs — Today Premium Monthly $3.99, Today Premium Annual $9.99, 'All premium features' $299.99 — and reviewers cannot parse them: 'why is Today Premium $10 per year, but ALL Premium Features are $300 ❓ what is the difference' (2★); 'premium used to be $4.99 and now… $299.99' (gt 2★); §8.10 'whatever the intent — a lifetime tier, a price-anchoring device, a legacy artefact — it currently reads to users as either a mistake or contempt'.")
ext("C113", " Report 86 (Today): a $299.99 lifetime SKU beside a $9.99 annual — 30× — reads as 'either a mistake or contempt' next to a history of paying customers losing their purchase; regional launch pricing (CA$7 vs US$4.99) drew its own cap complaint in Canada ('$7 in the app world is premium', 2★).")
ext("C186", " Report 86 (Today): 'I bought the one-time version from before the subscription started' — now unable to manage habits at all (jp 1★, 2026); a one-time buyer's covers removed when photos went premium (MON_REGRESS 3).")
ext("C294", " Report 86 (Today): 'I paid for this app and reviewed it years ago (when it was under a different pricing model)… for the $300 you're asking for now' (5★) — a decade of one-time-price reviews now sits beside a $299.99 SKU.")
ext("C033", " Report 86 (Today): MON_RESTORE 18 (2016-03-28 → 2021-02-12), a nine-year unresolved defect — 'I bought it last year — why does it charge again after reinstalling?' (cn 5★); 'I delete the app, now I install it again (on the same phone) and I have to buy the features again' (nl 4★); '¿Es una estafa?' (es 1★); 'I paid for the Premium twice' (2★); China carries 8 of the 18; one reviewer found Settings → Restore Purchases himself — 'the function exists and is undiscoverable'; MON_IAP_FAIL 11 incl. a March 2018 cluster where the product showed as 'no longer available' ('I am trying to give you $4.99… It keeps failing. I wrote for help and no response', 1★); §8.2 'surface restore at the paywall, not buried in Settings'.")
ext("C142", " Report 86 (Today): Restore Purchases exists in Settings and reviewers who lost premium on reinstall never found it (MON_RESTORE 18); statistics live in the profile screen and were found 'by accident' (UX_CONFUSE 74); a skip feature exists and 'nobody understands it' — 'fixing the explanation may be worth more than building anything'.")
ext("C176", " Report 86 (Today): backup and restore is the paid feature and 12 of the 55 data-loss reviewers had paid — 'selling backup and then losing data is the corpus's sharpest breach of trust': 'the third time I've opened the app to find months worth of data has been randomly corrupted/lost… despite having paid extra to back it up' (1★); 'I lost my 3 years data due to an issue in restore backup' (it 1★); 'the crucial backup was overwritten and even the restore data was wiped' (jp, titled 'Farewell, Today'); nobody in the corpus reports buying for backup — 'the paid features that convert are the ones users can see'.")
ext("C034", " Report 86 (Today): U:dataloss_any 55 (3.08%, 2.67★): BUG_DATALOSS 33, BUG_BACKUP 28, BUG_ICLOUD 17 ('iCloud was clearly on but there was no automatic backup — all the data is gone', cn 1★), BUG_SAVE 12; 'these people have lost ALL my information on 2 occasions' (pe 1★); §8.4 restore must never destroy the backup it is reading, a failed restore must leave existing data intact, covers must survive a restore; REQ_ACCOUNT 3 want a login so history is not hostage to one device — but on-device data is praised, so 'optional account-based sync, not mandatory'.")
ext("C153", " Report 86 (Today): iCloud Drive / Dropbox backup was manual and paid; BUG_ICLOUD 17 — 'iCloud was clearly on but there was no automatic backup'.")
ext("C230", " Report 86 (Today): a restore flow that overwrote the backup it was reading and wiped the restore data (jp, 'Farewell, Today') — restore must be non-destructive.")
ext("C039", " Report 86 (Today): BUG_NOTIF 63 (3.53%, 2.57★), 2016-04-04 → 2025-02-10 — ten years never fully fixed ('notifications are straight up not working for habits. I have 3 set up and they never go off'; 'out of ten habits it notifies one or two, and for days no notification is delivered', br); 10 of 63 say it makes the app unusable; a specific reproducible behaviour reported independently in 2017 and 2021 — 'if I don't check in every single day, the reminders stop all together'; 'surely this is the most important time to have a reminder?' — §8.3 'a habit app that goes quiet precisely when the user lapses has inverted its own purpose'.")
ext("C258", " Report 86 (Today): the inverse of the nag-until-done reminder — reminders that stop after a missed day (reported 2017 and 2021), abandoning the user at the moment they lapse.")
ext("C216", " Report 86 (Today): a skip day is used as a mental-health tool — 'to sort days when I felt bad out of the streak. Over time it became easier to assess my successes' (de 5★, depressive phases) — and the skip feature that exists is misunderstood by three reviewers and reported as damaging streak statistics.")
ext("C016", " Report 86 (Today): REQ_SKIP 11 (illness, travel, a bad mental-health day) + REQ_ARCHIVE 11 — the corpus's most-upvoted request (22 up / 36): 'could you add a way to stop a habit? Sometimes a habit is already formed or no longer needed, but currently you can only delete it, and all the data goes with it' (cn 5★); 'the design forces a user who succeeded to destroy their record of succeeding'; a skip exists and 'nobody understands it'.")
ext("C227", " Report 86 (Today): REQ_ARCHIVE 11 restated across five years and four languages — a formed habit can only be deleted, taking its history; the most-upvoted request in 1,785 reviews.")
ext("C256", " Report 86 (Today): 'I can not to figure out what different between skipped and not to check in' (tw 4★); REQ_FAILMARK 6 want to record a missed day explicitly; a skip that damages streak statistics (one report).")
ext("C218", " Report 86 (Today): the listing says 'Quit bad habits and stay on track' and the feature does not exist — REQ_BREAKBAD 15 (2016 → 2026), USE_QUIT 16 trying anyway; 'the description talks about losing bad habits: we need an explanation. In what way does this app concern itself with our bad habits?' (fr 4★); §8.7 'advertising a capability, collecting users who need it, and having them discover the gap after purchase' is not defensible — build a 'maximum N per period' type (Done and HabitBull named as having it) or remove the promise.")
ext("C019", " Report 86 (Today): a limit-type habit is the missing shape — 'if I only want to limit my intake to, say, two sodas a day, I can't both log each drink and show success for not going over the limit' (5★); REQ_BREAKBAD 15; USE_QUIT 16 (soda, meat, smoking, drinking).")
ext("C102", " Report 86 (Today): 'maximum N per period' as a habit type — five reviewers describe it; competitors Done and HabitBull are named as having it.")
ext("C104", " Report 86 (Today): the Notification-Centre widget was removed in 1.9.55 (2021-09-02) with release notes that said nothing about it — 11 complaints in six languages in three months ('No more widget. Which is the main way i used the app. So, I probably won't keep up to be using it', 1★; 'Give it back'; '还我小组件') — restored two months later with a note ('Thank you for making the widget come back!'); photo covers were moved behind payment taking existing covers with them (2023).")
ext("C155", " Report 86 (Today): a widget that had become the primary interface for many (PR_WIDGET 28, 4.50★) was removed without a word and restored under pressure; the iOS-14 home-screen widget requested from 2020-09 to 2025-12 was never built — REQ_WIDGET 47 is 'the only request that grows as the corpus shrinks' (1.98% of E1 → 16.95% of E5).")
ext("C009", " Report 86 (Today): the Notification-Centre widget shipped Oct 2016 after a day-two request and became the main way many used the app ('son Widget super bien pensé'); the home-screen widget never shipped in 5.5 years — 'they urgently need a widget and I swear I'd pay premium' (mx 4★); 'its lack of a widget means I'll probably need to look for something else'; a reviewer asks for one 'for IOS 26'.")
ext("C040", " Report 86 (Today): BUG_WIDGET 35 (1.96%) — 'the widget has a bug on iOS 10; purple blocks keep appearing' (5★); the 3D Touch widget reveals the habit list past the paid lock.")
ext("C022", " Report 86 (Today): the Watch app was requested for 14 months (REQ_WATCH 34 from 2016-03-11), shipped ~May 2017, and never worked properly — BUG_WATCH 88 (4.93%, 2.98★) vs 21 praising it: check-ins revert ('I tap an icon to say I've done it, then 20 minutes late it's unchecked again!!'), phone and watch disagree, the complication works on one watch face; Infograph complication requests recur for seven years unanswered; watchOS 5 broke it ('Broken since iOS 12 / watchOS 5… App hasn't had an update in nearly 2 months'); a purchase trigger for one ('I bought this app for the watch incorporation') and a condition for others ('I will gladly pay for the full version but I really need it to work on my watch') — 'a shipped-but-unreliable companion app is a larger negative than its absence'.")
ext("C175", " Report 86 (Today): five datable crash waves in ten years — launch Mar 2016 (Editors' Choice, 21 crash reviews in three weeks, 'Great crash simulator'), iOS 9/10 Oct–Nov 2016 (18), Face ID / Touch ID Mar 2018 (enabling the paid lock crashed the app), iOS 12 / watchOS 5 Sep 2018 (the Watch app), and the black-screen build 1.9.63 of 2022-11-09 with the next release 1,030 days later; BUG_UPDATE 42 (2.55★); the mean fell 4.16 → 4.14 → 3.59 → 3.51 → 3.07 across five eras — 'reliability, not features, is what destroyed this product'; the pre-2019 vs 2019-onward gap is 0.61★ over 458 reviews, 'not a bad week; it is the product's trajectory'.")
ext("C031", " Report 86 (Today): BUG_CRASH 126 (7.06%, 2.71★), BUG_LAUNCH 58 (3.25%, 2.26★ — the lowest defect mean); the launch crash under an Editors' Choice feature pinned 228 reviews (12.77% of the whole corpus) at 3.25★ to the listing; a black-screen build shipped and was never fixed for 1,030 days.")
ext("C071", " Report 86 (Today): the extreme case — 1,030 days between releases (2022-11-09 → 2025-09-04, zero releases in 2023 or 2024), beginning with a build that would not launch; DEV_STALE 67 (3.75%, 20.34% of E5 reviews); users audited the developer ('no update in 2 years… copyright dates only thru 2021… email bounces because the embedded address is toda@neybox.com… Odd because sister app Pillow is working well'); 'the pattern is latency, not absence' — dark mode two years after the request, a time-zone bug fixed six and a half years after the first report, and iPad / home-screen widget / bad-habit tracking / archive / overview never in ten years; 11 releases since Sep 2025 but only 13 reviews to judge by; 'what converts a category-leading app into abandonware'.")
ext("C225", " Report 86 (Today): launched 8 March 2016 as an Apple Editors' Choice (MKT_EDITORS 6) — and crashed immediately for a large fraction of users while gating the free tier at one habit: 209 reviews that month at 3.11★, 54 on a single day, 228 reviews (12.77% of the ten-year corpus) permanently attached to the listing at 3.25★; 'When I saw this was an editors choice app I checked it out… all I get is the screen that says today. And then everything crashes' (1★).")
ext("C156", " Report 86 (Today): a paid biometric lock shipped in a build where enabling it crashed the app on entry (March 2018, 5 reviews in nine days: 'What was my 30 yuan for?… I appealed to Apple and was told no refund'); the same fortnight carried an IAP outage — 'the month this app broke its paying users on two axes at once'.")
ext("C119", " Report 86 (Today): the November 2018 check-in redesign (NEG_REDESIGN 23, 3.22★) — single-tap check-in became multiple steps, the calendar mark shrank 'from a fully filled-in square to a TINY dot', no visual done-indicator so users tapped twice — was rolled back within months and reviewers upgraded in public: 'Dev Team reacted quite quick… Happy to have single tap check in back… Changed my rating to 5 stars ;-)' (edited 1★ → 5★); 'Thank you for listening!' — 'the corpus's clearest demonstration of responsiveness converting anger into loyalty'.")
ext("C264", " Report 86 (Today): 'Instead of a single tap to log a habit for the day, you're forced to go through multiple steps now!' (1★) — the Nov 2018 redesign that added taps to check-in was rolled back and the 1★ became a 5★; UX_FRICTION 41 (too many taps); the visual model's latency ([[C303]]) is the other tax on the tap.")
ext("C059", " Report 86 (Today): responsiveness was visibly the conversion engine early — 'They reply very quickly and kindly' (2016); 'not only did I get a reply, the problem was fixed within days' (cn 2017); FIX_CONFIRM 33 (4.76★), 21 of them before 2019; PR_DEV 39 (4.59★), 30 pre-2019 — 'and it stopped': SUP_NORESP 25 (2.20★), 'haven't heard back from anyone in 6 months +' (2023), a three-week wait for a one-line 'import is currently not possible' (jp); RATING_LEVERAGE 16 withhold a star until something ships.")
ext("C036", " Report 86 (Today): SUP_ASK 54 (3.03%) ask the developer a question in a review — 'a signal that the in-app support path is not obvious'; the embedded support address is misspelled (toda@neybox.com) and the corrected one got no reply; §8.11 'the cheapest fix in this report'.")
ext("C096", " Report 86 (Today): the paid passcode / Touch ID / Face ID lock leaks the habit list — via the 3D Touch widget after force-close (ua 4★), on background resume ('no password is required to launch the app'), and for an instant before the fingerprint screen (jp) — three reports in three languages over three years; one reviewer objects on principle to paying for a lock.")
ext("C017", " Report 86 (Today): the passcode / biometric lock is a paid feature, objected to on principle by one, crashed the app when enabled in March 2018, and leaks the habit list through the widget and background resume — 'a paid privacy feature that leaks is worse than none'.")
ext("C006", " Report 86 (Today): simplicity is defined negatively — 'No frills, no fuss—no need to sit through way-too-long animations and stories and celebrations every time you do something' (4★); 'a check-in app doesn't need lots of frills; this is just right' (cn); 'It doesn't give you confetti or a cookie but it helps form that path in your brain'; 'Perfect app. Don't ruin it with clutter!'; PR_SIMPLE 361 (20.22%, 4.68★); in China simplicity is valued above beauty (25.21% vs 21.25%, 简约不简单).")
ext("C185", " Report 86 (Today): PR_DESIGN 460 (25.77%) appears in every star band — 10.6% of 1★ still praise the design: 'beauty does not protect the rating; it is what makes the failure worth writing about'; PR_BEST 204 at 4.78★, the highest mean of any large theme; a Good Design Award recipient calls it 'one of the most thoughtfully designed apps I have used' (2026); design praise held at 15.25% even in the abandonment era.")
ext("C144", " Report 86 (Today): per-habit 'cards' (counters, custom charts, milestones, journal, photo gallery, Apple Health metrics, a stress card) — PR_CARDS 70 (4.69★), U:depth_differentiator 192 (10.76%, 4.72★): 'the deciding factor was the extensibility of supplementary information via cards' (jp, paid); ''lead indicators' like calories consumed beside 'lag indicators' like your weight'; 'I use it as sort of a memory box for things I've done'; a named purchase trigger ('little motivation boards was what made me pay'); and NEG_FEATURE_UNUSED 15 (2.80★: 'cards that are unusable in 95% cases') with UX_CONFUSE 74 — 'the cards are simultaneously the reason power users pay and a source of confusion for everyone else'; §8.13 measure card usage against 90-day retention.")
ext("C021", " Report 86 (Today): PR_HEALTHKIT 38 — 'EVERYTHING that is in your Apple Healthkit can be displayed and values for can be entered… I tried all popular health dashboards and activity tracker, but this is miles ahead'; a weight graph and a distance-swum card (jp); REQ_AUTOCHECK 11 (auto check-in from Health) never shipped.")
ext("C075", " Report 86 (Today): UX_CONFUSE 74 (4.15%), UX_ONBOARD 20 — people cannot find check-in ('I could never figure out how to check in', 2★), cannot understand the custom chart or counter, cannot tell skipped from missed, cannot find the statistics ('I only stumbled on the charts in the profile section by accident!'); the cost stated plainly: 'The statistics are in the profile. You can't start the app with the list of goals… So I deleted it; otherwise I'd have bought it' (ch 1★).")
ext("C217", " Report 86 (Today): the custom chart, counter and milestone cards go unexplained (UX_CONFUSE 74; NEG_FEATURE_UNUSED 15) and a skip state is misunderstood by three — the depth layer that converts power users confuses everyone else.")
ext("C172", " Report 86 (Today): a journal card exists (PR_JOURNAL 24) yet a note per check-in is the second-most-upvoted request (31 up / 47: 'to record it at that point in time. That way you can know yourself more accurately', cn 5★; REQ_NOTE 12) — never shipped.")
ext("C231", " Report 86 (Today, 1,785 reviews over ten years): corpus 3.97★ vs every public storefront 4.5–4.8★ — 'do not present 3.97★ as the app's rating'; the corpus is front-loaded (45.32% in E1, 645 reviews from 2016) so 'any global percentage is mostly a statement about 2016–17'; volume decayed 45× (59.1 → 1.3 per month); CONTRA_RATING 46 — 40 are 5★ whose text is only a complaint ('Blank Screen after IOS update' — entire text) so the public average is inflated 'by a measurable population of users who write a complaint and tap five stars anyway'; Japan reports the most defects (42.11%) while rating above the mean — 'any market-health read that uses the rating alone will systematically under-weight Japanese defect signal'; RATING_LEVERAGE 16; 40 five-star reviews contain no praise at all; 152 reviews carry both praise and a bug code — 'people who like the app describing what is broken in it'.")
ext("C002", " Report 86 (Today): the offer changed twice (cap 1 → 3 → 1; one-time → subscription + $299.99) and reliability collapsed; the era means 4.16 → 3.07 track defects (12.36% → 50.85%), not the offer — 'In 2016 people left over the paywall. From 2018 they leave over reliability. That shift is the whole story of this product compressed into one table.'")
ext("C065", " Report 86 (Today): paid reviewers (188, 10.53%) average 3.69★ vs 3.97 and report defects at 34.57% vs 26.27% — they use it longer with more habits, the condition under which it degrades; 12 of 55 data-loss reviewers paid for the backup that lost their data; MON_PAID_EXPLICIT is 16.13% of 1★ — 'paying does not make people kind'; U:purchase_friction 51 (2.61★): restore 18, IAP failure 11, regret 12, refund 7 (two refused by Apple), overcharge 2, features taken back 3.")
ext("C061", " Report 86 (Today): MON_SUPPORT_DEV 8 ('I bought the full version to support an app I use often'); China frames the price as buying the developer a meal ('what's 30 yuan — think of it as buying the developer dinner'); PR_WORTH 73 at 4.84★; 'because they actually listened to there customers I just paid full price for it!'")
ext("C025", " Report 86 (Today): the most self-aware affordability review in the series — 'Why 4 stars — mainly because I'm poor… I hesitated for one day and 22 hours over whether to uninstall… under 10 yuan I could accept. Isn't the point of making an app to let more people use it?' (cn 4★; MON_AFFORD 3); Canada's CA$7 launch price vs US$4.99 drew the highest cap-complaint rate among eligible markets ('$7 in the app world is premium').")
ext("C092", " Report 86 (Today): a regional price visibly above the US price (CA$7 vs $4.99 at launch) produced Canada's 13.92% MON_FREE1 rate — the highest among eligible markets; US reviewers argue price in public ('just a cup of coffee?… come on people, app devs gotta make a living' vs 'In a market where most apps are $2.99 or less…').")
ext("C064", " Report 86 (Today): $4.99 one-time was defended by reviewers against each other (MON_DEFEND 44; 'a steal at £5'; 'just a cup of coffee') and objected to as 'premium' at CA$7; German reviewers accept the pricing below the global rate (7.79% vs 10.98%); the objection that stuck is structure ($299.99 beside $9.99/yr), not level.")
ext("C027", " Report 86 (Today): Chinese and Japanese localisation shipped Sep 2016 and was immediately criticised ('what the hell is check-in translated as? If you can't translate, add a language option'; the 3D Touch menu and widget untranslated); Traditional Chinese still missing in 2018 and never added (tw 16 reviews); a user posted an iOS Settings walkthrough in a review to force the language; 1,112 reviews (62.3%) are in English but only 595 from the US — 'country-based segmentation and language-based segmentation are different operations'.")
ext("C255", " Report 86 (Today): a shipped translation criticised the day it arrived — 'what the hell is check-in translated as? If you can't translate, add a language option' (cn 5★); partial screens (3D Touch menu, widget) in English; Simplified only, no Traditional.")
ext("C043", " Report 86 (Today): scheduling covers daily / weekdays / N per week (max 6) or month (max 25) / multiple check-ins a day — the most complete in the series — yet REQ_FREQ 27 still ask for every-N-days ('If the app had this capability, I would rate it 5 stars and purchase the full version') and weekday-only reminders ('add weekday-only reminders and I'll pay immediately', cn).")
ext("C010", " Report 86 (Today): REQ_BACKFILL 18 (2016 → 2021) — 'partially, then made harder'; the Nov 2018 redesign made checking in for an old day three taps.")
ext("C020", " Report 86 (Today): 'Manage Data' export/delete shipped May 2018 ('Kudos for the new Manage Data section… If only more companies would follow suit'); REQ_EXPORT 14; a twenty-item 2016 request list asked for Excel export.")
ext("C141", " Report 86 (Today): REQ_IPAD 27 (1.51%, 2016 → 2026) — never in ten years; 'Si la tuviesen para Ipad la compraría' (es).")
ext("C044", " Report 86 (Today): REQ_MAC 14 (2016 → 2021) — never; Momentum's desktop sync envied ('I like their desktop sync, wink!').")
ext("C046", " Report 86 (Today): REQ_INTEGRATION 34 (Shortcuts / third-party, 2016 → 2026) — a URL scheme only; 'any plans on giving us an update for iOS 14. Widgets, Shortcuts integration… The silence is a little concerning' (2020).")
ext("C066", " Report 86 (Today): REQ_TIMER 18 (1.01%, 2016 → 2020) — a timer / duration tracking, never shipped.")
ext("C045", " Report 86 (Today): REQ_CATEGORY 11 (2016 → 2023) never; REQ_SORT 11 added but slow.")
ext("C073", " Report 86 (Today): reorder/sort was added but 'slow' (two reports); parent/child habits requested in a 2016 twenty-item list.")
ext("C005", " Report 86 (Today): CMP_NAMED 48 — Way of Life, Momentum, Coach.me, Streaks, Done, Productive, HabitBull, Habity, Strides, Due, Shanbay, Todoist, Notion, and Apple's Reminders/Calendar/Health/Activity as both the thing replaced and the fallback; the corpus's most-voted review (38 up / 82): 'blew Momentum, Strides, and Way of Life out of the water… Momentum is too minimalistic… Strides has a bubbly interface I can't stand'; PR_BEST 204 (11.43%, 4.78★); the UK writes the most detailed comparisons ('over 15 different habit trackers in the last three years').")
ext("C178", " Report 86 (Today): 'No frills, no fuss'; 'It doesn't give you confetti or a cookie but it helps form that path in your brain'; positioned against 'bubbly' rivals; reviewers say it is not a to-do list, calendar or workout tracker — 'Habits are different than to-dos and should be tracked differently'.")
ext("C140", " Report 86 (Today): 'just a yes/no - did you hit the gym today?' — reviewers draw the line against to-do lists and workout trackers; PR_OUTCOME 106 (4.84★, the highest mean): 60lbs, 50 meat-free days, quitting soda, five languages, 200 days of fitness, quitting smoking, six years of habit-formation.")
ext("C103", " Report 86 (Today): 'I started using this app to get a better grip on my depressive phases, and to sort days when I felt bad out of the streak' (de 5★) — a skip/forgiving state as a mental-health tool; accessibility is an evidence gap (2 mentions in 1,785; text over photos has obvious contrast risk, reported in 2016).")
ext("C171", " Report 86 (Today): accessibility evidence is absent — 2 incidental mentions in 1,785 — 'an evidence gap, not an all-clear'; a full-screen-photo app with text over imagery has obvious contrast risk and 'unreadable text on light wallpapers' was reported in 2016.")
ext("C209", " Report 86 (Today): no account, no login, no server sync for ten years — praised ('no account') and blamed in equal measure; REQ_ACCOUNT 3 arrive only from users who lost data; §8.4 'optional account-based sync — not mandatory'.")
ext("C085", " Report 86 (Today): the label declares no tracking; PR_PRIVACY 4, PR_NOADS 7, PR_SECURITY 3 vs PRIV_CONCERN 4; 'no ads, no account, on-device data — quiet assets that cost nothing and are named unprompted'.")
ext("C246", " Report 86 (Today): no advertising at any point in ten years; PR_NOADS 7.")
ext("C062", " Report 86 (Today): the high-spend (us, jp, cn, gb, de) and high-volume (us, cn, gb, ca, de) groups differ only in Japan vs Canada and profile almost identically at 3.96★ — 'there is no market where this app is quietly working well'; the US is the most negative eligible market (3.81★) and China the most positive (4.27★); Japan reports the most defects and rates generously; Germany diagnoses performance; Canada objects to a regional price.")
ext("C130", " Report 86 (Today): China (353, 19.78%) values simplicity above beauty, pays more (12.18%), suffers restore failures most (8 of 18), and was the first market to get — and to criticise — a localisation.")
ext("C094", " Report 86 (Today): reviews used as a support desk (SUP_ASK 54) and a bug tracker (40 complaint-only 5★); RATING_LEVERAGE 16 withhold stars until a feature ships ('I'll be sure to change my rating to 5 stars when the updates come out!').")
ext("C300", " Report 86 (Today): public 4.5–4.8★ vs corpus 3.97★ — a 0.6–0.8 gap on a ten-year corpus with a collapsed review rate; 'the true signal is in the text, which is why every finding here is text-derived'.")
ext("C024", " Report 86 (Today): 'It doesn't give you confetti or a cookie' is praise; badges and milestones exist and are unremarked; NEG_REDESIGN objected to a shrunken calendar mark — the visual record, not a reward, is the motivator.")
ext("C012", " Report 86 (Today): the streak calendar card is the record users protect ('changed the check-in marks on the calendar from a fully filled-in square to a TINY dot', 2★); REQ_DASHBOARD 70 want all habits on one screen; statistics live in a profile screen found 'by accident'.")
ext("C234", " Report 86 (Today): PR_STATS 65 free; the statistics screen is undiscoverable ('I only stumbled on the charts in the profile section by accident!'); nobody reports buying for statistics.")
ext("C038", " Report 86 (Today): a time-zone check-in bug first reported Feb 2019 was fixed Oct 2025 — six and a half years later; a day-start-time setting was in a 2016 twenty-item request list.")
ext("C170", " Report 86 (Today): day-start time requested in 2016 (a twenty-item Japanese list); a time-zone check-in bug fixed 6.5 years after the first report.")
ext("C239", " Report 86 (Today): the sister app (Pillow) being 'updated, working well' while Today sat unreleased for 1,030 days is what reviewers cite when concluding the developer moved on — a studio's other products are read as evidence of intent.")

M = {
 "R86-001":["C079","C144","C254","C209"], "R86-002":["C231"], "R86-003":["C231","C300"], "R86-004":["C079","C185","C006","C178"], "R86-005":["C144","C217","C075"],
 "R86-006":["C175","C002","C031","C022","C039","C040"], "R86-007":["C303","C083","C065"], "R86-008":["C022","C175"], "R86-009":["C007","C297","C293","C191","C296"], "R86-010":["C003","C177","C113","C294","C186"],
 "R86-011":["C071","C031","C239"], "R86-012":["C007","C063","C147","C017","C176"], "R86-013":["C096","C017","C085","C209"], "R86-014":["C231"], "R86-015":["C079","C185"],
 "R86-016":["C006","C178","C024"], "R86-017":["C005","C185","C178"], "R86-018":["C140","C103","C216"], "R86-019":["C144","C021","C012"], "R86-020":["C003","C064","C061"],
 "R86-021":["C175","C031"], "R86-022":["C039","C258"], "R86-023":["C176","C034","C153","C230","C209"], "R86-024":["C254","C264","C012"], "R86-025":["C075","C217","C234","C142"],
 "R86-026":["C009","C254","C022","C046","C043","C141","C144","C066","C010","C019","C044","C020","C172","C227","C073","C045","C016","C021","C256"], "R86-027":["C016","C227","C216"], "R86-028":["C218","C019","C102"], "R86-029":["C172"], "R86-030":["C002","C065"],
 "R86-031":["C059","C036"], "R86-032":["C231"], "R86-033":["C231","C185","C094"], "R86-034":["C002","C007"], "R86-035":["C231","C300","C094"],
 "R86-036":["C065","C176","C231"], "R86-037":["C079","C144","C007","C061","C022","C176"], "R86-038":["C033","C065","C142","C186","C191"], "R86-039":["C063","C147","C296","C009","C022","C141","C043"], "R86-040":["C231"],
 "R86-041":["C092","C064","C062"], "R86-042":["C130","C006","C061","C025","C033","C027","C255"], "R86-043":["C005","C092","C025"], "R86-044":["C303","C231","C171","C170"], "R86-045":["C062","C027"],
 "R86-046":["C175","C002","C185"], "R86-047":["C175","C031","C225","C156","C022","C071"], "R86-048":["C119","C264","C059"], "R86-049":["C009","C155","C104","C040"], "R86-050":["C071","C038","C020"],
 "R86-051":["C175","C231"], "R86-052":["C303","C083"], "R86-053":["C033","C142"], "R86-054":["C039","C258"], "R86-055":["C176","C034","C230","C209"],
 "R86-056":["C009","C155"], "R86-057":["C016","C227","C216","C256"], "R86-058":["C218","C019","C102"], "R86-059":["C254","C264","C079"], "R86-060":["C007","C296","C147","C063","C293"],
 "R86-061":["C177","C113","C003"], "R86-062":["C059","C036","C079","C144","C003","C119","C246","C085"], "R86-063":["C144","C171","C065"], "R86-064":["C017","C096","C156"], "R86-065":["C104","C155","C071","C239"],
 "R86-066":["C216","C103","C016"], "R86-067":["C225","C007","C293","C059"],
}
M["R86-036"] += ["C033"]; M["R86-041"] += ["C130"]; M["R86-019"] += ["C234"]; M["R86-026"] += ["C038","C170"]
cards = [json.loads(l) for l in open("Tools/prd_ledger/86/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/86/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 86" in x["statement"] and not any(k.startswith("R86-") for k in x["cards"])])
