# Hand codes by index in read.txt (sorted by first mode, then key). Unlisted = NR.
S = """
0 OWN_CLOUD_NAMED
1 OWN_CLOUD_SYNC
2 OWN_CLOUD_NAMED AUTO_BACKUP_WANT
3 OWN_CLOUD_NAMED
5 OWN_CLOUD_SYNC
6 OWN_CLOUD_SYNC
7 OWN_CLOUD_SYNC
8 OWN_CLOUD_SYNC BACKUP_AS_SYNC_PAIN
9 OWN_CLOUD_SYNC BACKUP_AS_SYNC_PAIN
10 OWN_CLOUD_SYNC
11 OWN_CLOUD_SYNC
12 OWN_CLOUD_SYNC
13 OWN_CLOUD_NAMED
14 OWN_CLOUD_SYNC
15 OWN_CLOUD_NAMED MOVE_FAILS
16 OWN_CLOUD_NAMED CHOOSE_WHERE
17 OWN_CLOUD_NAMED MOVE_FAILS
18 OWN_CLOUD_NAMED
32 MOVE_FAILS
39 MOVE_FAILS
41 WHERE_UNKNOWN AUTO_BACKUP_WANT
42 BACKUP_AS_SYNC_PAIN
43 WANT_TRANSFER
45 WANT_TRANSFER
46 WANT_TRANSFER
47 WANT_TRANSFER ACCOUNT_NAMED LEFT
49 MOVE_FAILS LEFT
50 MOVE_FAILS
52 OWN_CLOUD_NAMED WANT_TRANSFER
53 ACCOUNT_NAMED WANT_TRANSFER
55 ACCOUNT_NAMED WANT_TRANSFER
56 ACCOUNT_NAMED WANT_TRANSFER
57 MOVE_FAILS
59 WANT_TRANSFER
60 MOVE_FAILS
61 MOVE_FAILS
62 ACCOUNT_NAMED WANT_TRANSFER
63 MOVE_FAILS
64 BACKUP_AS_SYNC_PAIN
66 MOVE_FAILS
69 MOVE_FAILS
70 MOVE_FAILS
71 MOVE_FAILS
72 MOVE_WORKS
73 AUTO_BACKUP_WANT
74 MOVE_FAILS ACCOUNT_NAMED
75 MOVE_FAILS
76 MOVE_FAILS
77 MOVE_WORKS
78 MOVE_WORKS
79 MOVE_FAILS
80 MOVE_WORKS
81 MOVE_WORKS
82 ACCOUNT_NAMED WANT_TRANSFER
83 WANT_TRANSFER
84 WANT_TRANSFER AUTO_BACKUP_WANT
85 ACCOUNT_NAMED WANT_TRANSFER
87 MOVE_FAILS
88 MOVE_FAILS
89 AUTO_SYNC_PRAISE
90 BACKUP_AS_SYNC_PAIN
94 AUTO_BACKUP_WANT
95 AUTO_BACKUP_WANT ACCOUNT_NAMED
98 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
99 AUTO_BACKUP_WANT
100 AUTO_BACKUP_WANT
102 BACKUP_FREQ
107 AUTO_BACKUP_WANT LEFT
108 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
109 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
111 AUTO_BACKUP_WANT WANT_TRANSFER
112 BACKUP_FREQ
113 ICLOUD_NOT_OPTION
115 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
121 AUTO_BACKUP_WANT
122 BACKUP_AS_SYNC_PAIN ACCOUNT_NAMED
123 BACKUP_AS_SYNC_PAIN OWN_CLOUD_NAMED
124 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
125 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
126 AUTO_BACKUP_WANT
127 AUTO_BACKUP_WANT ACCOUNT_NAMED
128 AUTO_BACKUP_WANT
134 AUTO_BACKUP_WANT OWN_CLOUD_NAMED CHOOSE_WHERE
137 AUTO_BACKUP_WANT
138 AUTO_BACKUP_WANT
141 AUTO_BACKUP_WANT
142 AUTO_BACKUP_WANT
143 AUTO_BACKUP_WANT
144 MOVE_FAILS
146 BACKUP_AS_SYNC_PAIN
147 AUTO_BACKUP_WANT ACCOUNT_NAMED
148 AUTO_BACKUP_WANT
149 BACKUP_FREQ
150 AUTO_BACKUP_WANT
153 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
154 OWN_CLOUD_SYNC
155 BACKUP_AS_SYNC_PAIN ACCOUNT_NAMED
157 BACKUP_AS_SYNC_PAIN BACKUP_FREQ
159 BACKUP_FREQ
160 AUTO_BACKUP_WANT
161 AUTO_BACKUP_PRAISE
162 BACKUP_AS_SYNC_PAIN
164 BACKUP_FREQ
165 AUTO_BACKUP_WANT
172 AUTO_BACKUP_WANT
173 AUTO_BACKUP_WANT
175 AUTO_BACKUP_WANT ACCOUNT_NAMED
176 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
177 AUTO_BACKUP_WANT
178 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
179 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
180 AUTO_BACKUP_WANT ACCOUNT_NAMED
181 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
182 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
183 AUTO_BACKUP_WANT
185 AUTO_BACKUP_WANT ACCOUNT_NAMED
186 AUTO_BACKUP_WANT ACCOUNT_NAMED
187 AUTO_BACKUP_WANT ACCOUNT_NAMED
188 AUTO_BACKUP_WANT
189 AUTO_BACKUP_WANT BACKUP_FREQ
190 AUTO_BACKUP_WANT
191 AUTO_BACKUP_WANT
192 AUTO_BACKUP_WANT
193 AUTO_BACKUP_WANT ACCOUNT_NAMED
194 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
195 AUTO_BACKUP_WANT ACCOUNT_NAMED OWN_CLOUD_NAMED
196 AUTO_BACKUP_WANT
197 AUTO_BACKUP_WANT
198 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
199 AUTO_BACKUP_WANT
200 AUTO_BACKUP_WANT ACCOUNT_NAMED
201 AUTO_BACKUP_WANT
202 AUTO_BACKUP_WANT
203 AUTO_BACKUP_WANT
204 AUTO_BACKUP_WANT ACCOUNT_NAMED OWN_CLOUD_NAMED
205 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
206 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
207 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
208 AUTO_BACKUP_WANT ACCOUNT_NAMED
209 AUTO_BACKUP_WANT
210 AUTO_BACKUP_WANT
211 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
212 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
214 AUTO_BACKUP_WANT ACCOUNT_NAMED
215 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
216 AUTO_BACKUP_WANT
217 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
218 AUTO_BACKUP_WANT
219 AUTO_BACKUP_WANT OWN_CLOUD_NAMED LEFT
220 AUTO_BACKUP_WANT
221 AUTO_BACKUP_WANT
222 AUTO_BACKUP_WANT
223 AUTO_BACKUP_WANT ACCOUNT_NAMED
224 MOVE_WORKS AUTO_BACKUP_WANT
225 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
226 AUTO_BACKUP_WANT ACCOUNT_NAMED
227 AUTO_BACKUP_WANT ACCOUNT_NAMED
228 AUTO_BACKUP_WANT
229 AUTO_BACKUP_WANT ACCOUNT_NAMED
230 AUTO_BACKUP_WANT ACCOUNT_NAMED
231 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
232 BACKUP_AS_SYNC_PAIN
233 AUTO_BACKUP_WANT PRIVACY_OFFLINE_OK
234 AUTO_BACKUP_WANT
235 AUTO_BACKUP_WANT ACCOUNT_NAMED
236 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
237 AUTO_BACKUP_PRAISE MOVE_WORKS
238 AUTO_BACKUP_WANT
240 AUTO_BACKUP_WANT
241 AUTO_BACKUP_WANT
242 AUTO_BACKUP_WANT
243 AUTO_BACKUP_WANT
244 AUTO_BACKUP_PRAISE
246 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
247 AUTO_BACKUP_WANT
248 AUTO_BACKUP_WANT
249 AUTO_BACKUP_WANT
250 AUTO_BACKUP_WANT
251 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
252 AUTO_BACKUP_WANT ACCOUNT_NAMED
253 AUTO_BACKUP_WANT ACCOUNT_NAMED
254 AUTO_SYNC_PRAISE
258 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
259 AUTO_BACKUP_WANT OWN_CLOUD_NAMED
261 AUTO_BACKUP_WANT ACCOUNT_NAMED
262 AUTO_BACKUP_WANT
263 AUTO_BACKUP_PRAISE
"""
IDX = {int(l.split()[0]): l.split()[1:] for l in S.strip().splitlines()}
