import json, re, collections
C = {
 'E01_shades_amount': r"(shade|darker|lighter|intensit|gradient|opacity|transparen|deeper|lighter|half[- ]?(?:fill|color|square|box)|partial|partly|深浅|颜色.{0,6}深|渐变|濃淡|濃く|薄く|진하|연하|그라데|оттен|темнее|светлее|насыщен|tono|más oscuro|más claro|parcial|tom mais|mais escuro|plus foncé|plus clair|dunkler|heller|abstuf|tonalit|più scuro|odcień|ciemniejsz|donker|lichter|đậm|nhạt|درجة)",
 'E02_year_long': r"(\byear\b|yearly|annual|365|whole history|all[- ]time|years? view|年度|一年|全年|年間|1年|연간|1년|일년|\bгод|годов|\baño\b|anual|\bano\b|année|annuel|\bjahr|jährlich|\banno\b|\byıl|\brok\b|roczn|\bjaar\b|\btahun\b|\bnăm\b|سنة)",
 'E03_tap_edit_day': r"(tap(?:ping)? (?:on )?(?:a |the |any )?(?:day|square|box|cell|date)|click(?:ing)? (?:on )?(?:a |the )?(?:day|square|box|date)|edit(?:ing)? (?:past|previous|old)|go back|back ?fill|retroactiv|previous days?|past days?|forgot to (?:check|log|mark)|补卡|补打卡|補打卡|过去|過去の|과거|지난 날|소급|прошл\w* дн|задним числом|días anteriores|dias anteriores|jours précédents|vergangene tage|giorni passati|önceki gün|poprzednie dni|vorige dagen|hari sebelumnya|ngày trước)",
 'E04_labels': r"(\bdates?\b|weekday|day of the week|month (?:name|label)|label|which day|no (?:dates|days|weeks)|日期|星期|曜日|날짜|요일|дат[аы]|день недели|fecha|días de la semana|\bdata\b|dia da semana|datum|wochentag|giorno della settimana|tarih|dzień tygodnia|tanggal)",
 'E05_widget': r"(widget|小组件|小組件|小部件|ウィジェット|위젯|виджет)",
 'E06_colour_choice': r"(colou?r (?:option|choice|picker|palette|customi|for each)|choose (?:a |the |my )?colou?rs?|custom colou?r|own colou?r|more colou?rs|each habit (?:a|its own) colou?r|自定义颜色|颜色选择|色を選|色の|색상|색깔|цвет[аов]? (?:для|привыч)|выбор цвет|elegir (?:el )?color|más colores|escolher (?:a )?cor|mais cores|choisir (?:la )?couleur|plus de couleurs|farbe wählen|mehr farben|più colori|renk seç|daha fazla renk|więcej kolor|meer kleuren|pilih warna|màu sắc)",
 'E07_all_habits': r"(all (?:my |the |of my )?habits|overview|combined|in one (?:view|place|screen|grid)|all at once|全部|所有习惯|すべての習慣|全部の|전체|모든 습관|все привычки|общ\w+ (?:вид|картин)|todos (?:los|mis|os) hábitos|visão geral|tous les habitudes|toutes mes habitudes|alle gewohnheiten|übersicht|tutte le abitudini|tüm alışkanlık|wszystkie nawyki|alle gewoontes|semua kebiasaan|tất cả thói quen)",
 'E08_multi_per_day': r"(times? (?:a|per) day|multiple times|several times|more than once|count|counter|how many times|repetition|target|一天多次|多次|次数|1日に?複数|何回|회수|횟수|여러 번|несколько раз|раз в день|количеств|varias veces|veces al día|várias vezes|vezes por dia|plusieurs fois|fois par jour|mehrmals|mal am tag|più volte|günde birkaç|kilka razy|meerdere keren|beberapa kali|nhiều lần)",
 'E09_skip_fail_off': r"(skip|rest day|day off|days off|not scheduled|off days?|fail|missed|blank|empty (?:day|square|box)|excus|vacation|holiday|sick|跳过|休息|请假|空白|失败|未完成|スキップ|休み|お休み|休日|건너|휴식|쉬는 날|실패|пропуск|пропущ|выходн|отдых|провал|saltar|omitir|descanso|fallad|vacacion|pular|folga|falh|sauter|repos|jour off|échec|überspring|pausier|ruhetag|fehl|saltare|riposo|atla|dinlen|başarısız|pomiń|odpoczyn|overslaan|rustdag|lewati|istirahat|bỏ qua|nghỉ)",
 'E10_weekly_flexible': r"(times? (?:a|per) week|per week|weekly goal|x a week|days? a week|every other day|specific days|certain days|每周|一周.{0,3}次|週.{0,2}回|週に|주 ?\d ?회|일주일에|в неделю|por semana|veces a la semana|vezes por semana|par semaine|fois par semaine|pro woche|mal (?:pro|die) woche|a settimana|haftada|w tygodniu|per week|keer per week|per minggu|mỗi tuần)",
 'E11_size_density': r"(more days|fewer days|less days|how many (?:days|weeks)|bigger|smaller|compact|zoom|size|too small|too big|scroll|fit more|display (?:fewer|more|less)|number of (?:days|weeks)|太小|大小|缩放|小さ|大き|크기|작|размер|мелк|крупн|tamaño|tamanho|taille|größe|dimension|boyut|rozmiar|grootte|ukuran|kích)",
 'E12_streak': r"(streak|in a row|consecutive|连续|連続|连胜|연속|스트릭|серия|подряд|racha|seguid|sequência|seguidos|série|d'affilée|serie|hintereinander|di fila|üst üste|seri|z rzędu|op rij|beruntun|liên tiếp)",
 'E13_notes': r"(\bnotes?\b|journal|comment|备注|笔记|日记|メモ|日記|메모|일기|заметк|комментар|nota|notas|anotac|remarque|notiz|tagebuch|appunt|not ekle|notatk|notitie|catatan|ghi chú)",
 'E14_week_start': r"(monday|sunday|week start|start of the week|周一|週一|星期一|月曜|일요일|월요일|понедельник|воскресен|lunes|domingo|segunda|lundi|dimanche|montag|sonntag|lunedì|domenica|pazartesi|poniedziałek|maandag|senin|thứ hai)",
 'E15_fill_satisfaction': r"(fill(?:ing|ed)? (?:up|in|out)?|satisf|motivat|addict|gaps?|break the (?:chain|streak)|keep .{0,10} going|empty (?:spot|square|box)|填满|填滿|打卡.{0,4}(?:满|滿)|成就感|埋め|埋まる|達成感|채우|성취감|заполн|мотивир|удовлетвор|llenar|rellenar|motiv|satisfac|preench|satisfa|remplir|motiv|ausfüll|befriedig|riempi|soddisf|doldur|motive|wypełn|satysfak|vullen|voldoening|mengisi|memotivasi|lấp đầy|động lực)",
 'E16_contrast_look': r"(dark mode|light mode|theme|ugly|contrast|hard to (?:see|read|tell|distinguish)|can'?t (?:see|tell|distinguish)|too similar|same colou?r|看不清|分不清|难以区分|見づら|見にく|区別|구분|대비|보기 힘|контраст|плохо видно|не различ|difícil de ver|contraste|mismo color|difícil de distinguir|difícil de ver|contraste|difficile à voir|schwer zu erkennen|kontrast|difficile da vedere|zor görünüyor|kontrast|moeilijk te zien|sulit dilihat|khó nhìn)",
 'E17_share_export': r"(share|sharing|screenshot|export|print|分享|共享|导出|共有|エクスポート|공유|내보내|поделит|экспорт|compartir|exportar|partilhar|compartilhar|partager|exporter|teilen|exportieren|condivid|esporta|paylaş|udostępni|eksport|delen|exporteren|bagikan|chia sẻ)",
 'E18_stats_percent': r"(stats?\b|statistic|percent|%|rate|analytics|chart|graph|统计|統計|完成率|達成率|통계|달성률|статистик|процент|estadística|porcentaje|estatística|porcentagem|statistique|pourcentage|statistik|prozent|statistiche|percentual|istatistik|yüzde|statystyk|procent|statistiek|statistik|persen|thống kê)",
 'E19_wrong_lost': r"(disappear|vanish|wrong day|shifted|off by one|lost (?:my |all )?(?:data|progress|streak|history)|reset|deleted|消失|丢失|不见|错位|消えた|ずれ|사라|날아|пропал|исчез|сбил|desaparec|perdí|se borr|sumiu|perdi|apagou|disparu|perdu|verschwunden|verloren|scompars|perso|kayboldu|silindi|zniknę|utracił|verdwenen|kwijt|hilang|biến mất|mất)",
 'E20_month_calendar': r"(month(?:ly)? (?:view|calendar)|calendar view|calendar|月视图|月历|日历|月表示|カレンダー|월간|달력|캘린더|календар|месячн|calendario|vista mensual|calendário|calendrier|kalender|monatsansicht|calendario mensile|takvim|aylık|kalendarz|miesięczn|kalender|maandoverzicht|kalender|lịch)",
}
RX = {k: re.compile(v, re.I) for k, v in C.items()}
rows = json.load(open('Temp/heatmap_expect/corpus.json'))
for r in rows: r['codes'] = [k for k, rx in RX.items() if rx.search(r['text'])]
json.dump(rows, open('Temp/heatmap_expect/tagged.json', 'w'), ensure_ascii=False)
c = collections.Counter(k for r in rows for k in r['codes'])
print(len(rows), 'untagged', sum(1 for r in rows if not r['codes']))
for k in C: print(f"{k:22} {c[k]}")
