"""Cards for report 30 — header, warnings, executive summary, Parts 1–2."""
import json, re
R = 30
rep = open("App Store Reports/30. Habit Tracker - Simple&Powerful - Goal,task & Routine Planner (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(1, "header lines 1-9; §9.2 External sources", "positioning",
  "Habit Tracker: Simple&Powerful — 'Goal, task & Routine Planner' (App Store ID 6745508692, GAL APP LTD) — a young (Jul 2025→) minimalist tracker: free download with a hard habit cap (2, raised to 3 by Apr 2026), subscription + lifetime IAP — listing shows Monthly Premium $5.99 · Yearly $44.99 · Yearly (second SKU) $29.99 · Lifetime $59.99 and 'Track up to 2 habits with free version'; version 1.4.7; US listing 4.9★ from 45 ratings",
  "developer of record GAL APP LTD; bundle app.hbt.tem; extracted 8 Sep 2026; analysis 11 Sep 2026; store rank 30; 2→3 free habits, paid widget and unlimited", "mixed",
  "166 reviews · 21 storefronts · 8 Jul 2025 → 19 Aug 2026; mean 4.398; 5★ 133 (80.12%) / 4★ 7 / 3★ 4 / 2★ 3 / 1★ 19", "none", "corpus-level fact", "app-specific", [])
c(2, "How to read this; Seven warnings; §1.1 Files used; §1.2 Schema; §1.3 Coverage and reconciliation; §1.5 Processing method; §1.6 Limitations and known biases", "data-caveat",
  "Method: 166/166 read in full in the original language (Russian 60+, Spanish 25+, English 50+, plus pt/fr/de/nl/ar/tr/it/ja/ko/uk) and hand-assigned to 29 leaf + 4 union themes (no classifier at this size); a template-detection pass normalised bodies and grouped cross-language equivalents into five phrase-bank families (exact-normalised or containment in bodies under 80 chars — a floor); each review flagged substantive (names a feature, defect, request or pricing fact) — 47 of 166 (28.3%); rates computed globally (0.60pp per review), for Russia (n=56, 1.79pp) and for the substantive segment; all 33 sub-5★ and all 47 substantive re-read and every ID asserted; overlapping theme boundaries between cap, paywall and price (11 carry two of three) so quote the union (29) for scale; half the corpus is not organic (83 phrase-bank, all 5★); only Russia reaches 50; the US storefront (31, all 5★, 22 phrase-bank) contains zero English-language criticism — US sentiment is unmeasured; no version field; the US listing's 45 ratings vs 31 written reviews means written reviews are most US ratings, itself unusual; purchase evidence thin but real (6); is_edited false for all; votes 0 on 157; 11 reviews in a language not matching their storefront; near-absence of 2–3★ (7 of 166) consistent with a prompt routing satisfied users to the store; one reviewer references a developer reply",
  "n/a", "none", "166/166; 21 storefronts; 0 duplicates; 0 excluded; substantive 47 (28.3%)", "none", "method", "yes",
  ["14338216422","13680381966","13670832453","13678734774","14264524351","13705764332","13882804582","13707712022"])
c(3, "Executive summary #1 — the free-tier habit cap is the defining problem: 15 (9.04%, HIGH, mean 2.00) name it — 31.9% of the 47 substantive reviews, 8 of 19 one-stars, all 3 two-stars ('if the app is about habits, allowing only 2 is too much'; 'your premium plan not so expensive, but it should be at least 5 free habit entry'; 'It would be smarter to create attractive features that persuade the user to pay rather than limiting tracking to a mere two'); a 2–3 habit cap is below the minimum viable unit of the job — it produces a 1★ and an uninstall, not a conversion", "monetization",
  "The free-tier habit cap is this product's defining problem: 15 of 166 reviews (9.04%, high-priority, mean 2.00) name the free-habit limit as the reason for their rating — 31.9% of the 47 substantive reviews, 8 of 19 one-star reviews, and all 3 two-star reviews — 'Se o app é de habitos, deixar cadastrar somente 2 é demais' ('if the app is about habits, allowing only 2 is too much', BR, 2★); 'yeah your premium plan not so expensive, but it should be at least 5 free habit entry' (KZ, 1★); 'It would be smarter to create attractive features that persuade the user to pay rather than limiting tracking to a mere two' (TR, 1★); 'Всего 2 бесплатные привычки…' (RU, 1★); a 2–3 habit cap is below the minimum viable unit of the job — a habit tracker with three habits is a to-do list, users say so, and the cap does not convert them: it produces a 1★ review and an uninstall",
  "2-then-3 free habits", "1★-burst", "15 (9.04%, high-priority), mean 2.00; 15/47 substantive (31.9%); 8/19 1★; 3/3 2★", "product-rule", "high-priority", "yes",
  ["13441364320","13139338718","13286447070","13015082250","13057771438","13078324005","13283076453","13487320234","13678734774","13679689890","13707712022","13710940338","14007543484","14262833547","14438894096"])
c(4, "Executive summary #2 — 84% of one-star reviews are about money, not software: 16 of 19 1★ (9.64% global) are monetisation or billing — cap 8, price-for-value 4, no trial 2, failed charge 1, denied refund 1, undisclosed IAP 1, mis-sold lifetime 1; only 3 describe a defect; the app is rated down for its business model, so engineering will not move the rating — packaging will", "insight",
  "84% of one-star reviews are about money, not the software: 16 of 19 1★ (84.2% segment; 16 of 166 = 9.64% global, high-priority) are monetisation or billing complaints — the cap (8), price-for-value (4), no trial (2), a failed charge (1), a denied refund (1), undisclosed IAP (1), mis-sold 'lifetime' (1); only 3 of 19 describe a software defect (can't edit a habit; a name-entry bug ×2); the app is not being rated down for quality but for its business model — engineering work will not move this rating; packaging will",
  "capped freemium", "1★-burst", "16/19 1★ (84.2%); 9.64% global", "product-rule", "high-priority", "yes",
  ["13576406218","13511113509","13596102043"])
c(5, "Executive summary #3 — the purchase experience is broken four separately-evidenced ways: (a) charged, premium never unlocked; (b) the monthly SKU cannot be bought ('it charges for a year'); (c) 'lifetime' sold as lifetime, delivered as annual ('Te dicen que es de por vida el plan y es solo para un año') on a shelf carrying both $59.99 Lifetime and $44.99 Yearly; (d) no trial before a full annual charge ('I paid the anual subscription… It doesn't have a trial version and it wasn't what I was looking for'); plus a refund dead end — five of the six reviewers who reached payment had a bad outcome; the highest-severity finding, invisible in the star average", "must-never-break",
  "The purchase experience itself is broken in four distinct, separately-evidenced ways: (a) charged, premium never unlocked ('Списаны деньги за подписку, премиум функция не открылась', RU, 1★); (b) the monthly SKU cannot be bought ('не могу приобрести про версию на месяц, выдает оплату за год' — 'can't buy the monthly pro version, it charges for a year', RU, 4★); (c) 'lifetime' sold as lifetime and delivered as annual ('Te dicen que es de por vida el plan y es solo para un año', ES, 1★) — matching a store shelf carrying both a $59.99 Lifetime and a $44.99 Yearly SKU; (d) no trial before a full annual charge ('I paid the anual subscription… It doesn't have a trial version and it wasn't what I was looking for', AR, 1★; UA, 1★); plus a refund dead end (MX, 1★); these are five of the six reviewers in the whole corpus who reached the payment step, and five of six had a bad outcome — the highest-severity finding, invisible in the star average",
  "ambiguous SKU shelf; entitlement and billing failures", "1★-burst", "5 of 6 payers bad outcome", "must-never-break", "high-severity, small n", "yes",
  ["13670832453","13678734774","13705764332","13680381966","13679689890","14264524351"])
c(6, "Executive summary #4 — what people genuinely like is one attribute, minimalism, stated with specificity the templated reviews never reach: 23 (13.86%, mean 5.00) praise simplicity and 12 (7.23%) everyday convenience ('minimalist, no unnecessary junk'; 'Good app, minimalistic, effective'; 'Clean UI'); 7 (4.22%) report a behaviour outcome ('finally started sticking to healthy eating and a little sport'; 'I keep it as a widget and practise small habits'); the thesis works, the packaging fails — do not respond by adding features; the 4 who call it too thin mean for its price", "insight",
  "What people genuinely like is one attribute — minimalism — stated with a specificity the templated reviews never reach: 23 of 166 (13.86%, high-priority, mean 5.00) praise simplicity/minimalism and 12 (7.23%, high-priority) everyday convenience — 'минималистичное без лишнего мусора' ('minimalist, no unnecessary junk'); 'Good app, minimalistic, effective'; 'Muy practica, minimalista y buena app!'; 'Clean UI, awesome app'; 'понятный и удобный интерфейс. Без заморочек'; 7 (4.22%, very strong) report a concrete behaviour outcome ('finally started sticking to healthy eating and a little sport'; 'that description is exactly right; I keep it as a widget and practise small habits', KR); the product thesis works and the packaging is what fails — do not respond by adding features: the 4 reviewers (2.41%) calling the app too thin are making a price objection, not a feature request",
  "minimalist tracker", "praise", "simplicity 23 (13.86%), mean 5.00; convenience 12 (7.23%); outcomes 7 (4.22%)", "product-rule", "high-priority", "yes",
  ["14338216422","13292317774","14008217420","13701569896","12868175538","12958650866","14107277631"])
c(7, "Executive summary #5 — the price complaint is a value complaint with its own counter-evidence: 5 (3.01%, mean 1.40) object — but harsh sceptics say the price is fine ('ce n'est pas cher' still 2★ because of the cap; 'your premium plan not so expensive, but…') and a 5★ likes the price; the objection is always price ÷ what you get free ('a very expensive app for so little… a VERY EXPENSIVE checklist'; 'too simple for a paid app') — raising the free cap is cheaper than cutting price and would neutralise most price objection", "monetization",
  "The price complaint is a value complaint and the corpus contains its own counter-evidence: 5 reviews (3.01%, very strong, mean 1.40) object to price, but two of the harshest sceptics say the price itself is fine — 'ce n'est pas cher' (FR, still 2★ because of the cap) and 'your premium plan not so expensive, but…' (KZ, 1★) — and a 5★ volunteers 'также понравилась цена!' ('I also liked the price'); the objection is always price ÷ what you get free — 'Una app muy cara para tan poco… Es un check list CARÍSIMO' (AR, 1★); 'The price is too high for this quality' (JP, 1★); 'para ser de pago es demasiado simple' (ES, 1★); raising the free cap is a cheaper fix than cutting the price and the corpus predicts it would neutralise most of the price objection too",
  "$5.99/mo, $29.99–44.99/yr, $59.99 lifetime", "complaint", "5 (3.01%, very strong), mean 1.40; 2 say price is fine; 1 5★ likes price", "product-rule", "very strong", "yes",
  ["13487320234","13139338718","12933316146","13755696898","13625113466","13705764332"])
c(8, "Executive summary #6 — the Home Screen widget is paywalled and costing installs to competitors: 'I downloaded it only for the widget. Turned out it's a paid feature… competitors include it free — I went there' (4★); a 5★ whose only negative is the same fact; the widget in the store screenshots is not the widget the app provides; the one user who has it is unreservedly positive — an acquisition promise and a paywall at once, screenshots writing a cheque the free tier does not honour", "feature",
  "The Home Screen widget is paywalled and it is costing installs to competitors — only 2 reviews (1.20%, meaningful) name it but one is an explicit documented switch to a rival: 'скачивала только ради виджета. Оказалось, это платная фича… У конкурентов эта фича входит в бесплатную версию — ушла туда' ('I downloaded it only for the widget. Turned out it's a paid feature… competitors include it free — I went there', RU, 4★); the other is a 5★ whose only negative sentence is the same fact; a third reviewer reports the widget shown in the store screenshots is not the widget the app provides (UY, 5★); the one reviewer who has the widget is unreservedly positive (KR, 5★); low count, high diagnostic value — the widget is both an acquisition promise and a paywall, and the screenshots write a cheque the free tier does not honour",
  "widget paid; screenshots show a different widget", "churn", "2 (1.20%) + 1 mismatch + 1 praise", "free", "meaningful — high diagnostic", "yes",
  ["13081229555","13130702696","13706323164","14107277631"])
c(9, "Executive summary #7 — scheduling flexibility is the only genuine feature gap with multi-market evidence: 4 (2.41%) from 4 storefronts want non-daily habits — day-of-week, weekly/monthly, frequency configuration; Skip breaks the daily completion ring, and deleting a finished habit destroys its history because there is no end-date — a frequency field plus an end-date field", "feature",
  "Scheduling flexibility is the only genuine feature gap with multi-market evidence: 4 reviews (2.41%, meaningful) from 4 storefronts ask for habits that are not every-day — day-of-week selection (KZ, CL), weekly/monthly habits (GB), frequency configuration (ES); the CL 4★ documents the downstream damage precisely: using Skip breaks the daily completion ring, and deleting a finished habit destroys its history because there is no end-date; the one build-it item on the list, and it is small — a frequency field plus an end-date field",
  "daily-only habits; no end date", "complaint", "4 (2.41%) from 4 storefronts", "must-have", "meaningful", "yes",
  ["13249103798","13176696608","13032875149","13705764332"])
c(10, "Executive summary #8 — rating quality is deteriorating fast as the seeded reviews stop: half-year mean 2025H2 4.65 (n=138) → 2026H1 3.17 (23) → 2026H2 3.00 (5); phrase-bank reviews 35/53 of July 2025, 1 in Jan 2026, 0 after; non-phrase-bank 4.14 → 3.09 → 3.00; substantive 3.15 → 2.53 → 2.50 — the public 4.4★ is a decaying artefact; the organic trajectory is ~3.0★ and the cap is the reason", "timeline",
  "Rating quality is deteriorating fast as the seeded reviews stop: mean by half-year 2025H2 4.65 (n=138) → 2026H1 3.17 (n=23) → 2026H2 3.00 (n=5); phrase-bank reviews ran at 35 of 53 in July 2025 and stop almost entirely after December 2025 (1 in Jan 2026, 0 after); on the non-phrase-bank subset the decline is milder, 4.14 → 3.09 → 3.00, and on substantive reviews 3.15 → 2.53 → 2.50 — the public 4.4★ average is a decaying artefact; the organic trajectory is roughly 3.0★ and the cap is the reason",
  "seeded launch reviews expiring", "churn", "4.65 → 3.17 → 3.00; substantive 3.15 → 2.53 → 2.50", "product-rule", "high", "app-specific", [])
c(11, "§1.4 Date range and shape (verbatim monthly table) — 2025-07 53, 08 32, 09 14, 10 10, 11 15, 12 14, 2026-01 9, 02 6, 03 2, 04 3, 05 3, 06 0, 07 3, 08 2; 51.2% (85) in the first two months, where 53 phrase-bank reviews concentrate; from Mar 2026 ~2–3 written reviews a month", "timeline",
  "Monthly volume 2025-07 53 · 08 32 · 09 14 · 10 10 · 11 15 · 12 14 · 2026-01 9 · 02 6 · 03 2 · 04 3 · 05 3 · 06 0 · 07 3 · 08 2; 51.2% of the corpus (85 of 166) falls in the first two months, where 53 of the phrase-bank reviews concentrate; from March 2026 the app produces roughly 2–3 written reviews per month", "n/a", "none", table("## 1.4 Date range and shape"), "none", "corpus-level fact", "app-specific", [])
c(12, "§1.3 Coverage table (verbatim) — 166 lines, 166 distinct IDs, 21 country files match, manifest total/per-country/rating distribution/mean 4.398 match, 0 empty, 0 excluded", "data-caveat",
  "Coverage exact on every check: 166 lines parsed, 166 distinct IDs (no deduplication), 21 per-country files sum to 166 with no orphans, manifest total/per-country/rating distribution (5★133 · 4★7 · 3★4 · 2★3 · 1★19)/mean 4.398 all match, 0 empty bodies, 0 excluded; _state.json reports complete for every storefront crawled, including 0-result storefronts like cn", "n/a", "none", table("## 1.3 Coverage and reconciliation"), "none", "method", "app-specific", [])
# Part 2
c(13, "§2.1 Feature inventory table (verbatim)", "data-caveat", "Feature inventory with review-derived gating", "n/a", "mixed", table("## 2.1 Feature inventory derived from reviews"), "none", "inventory", "app-specific", [])
c(14, "§2.1 Create + check off daily habits free, capped at 2 then 3; unlimited habits paid; Home Screen widget paid; the interactive/streak widget in screenshots mismatches the app's actual widget", "feature",
  "Creating and checking off daily habits is free but capped at 2, then 3; unlimited habits and the Home Screen widget are the paid unlock; the interactive/streak widget shown in the screenshots does not match the app's actual widget", "cap + paid widget", "complaint", "inventory rows", "free", "inventory", "yes",
  ["13015082250","14262833547","13441364320","13707712022","14007543484","14107277631","13130702696","13081229555","13706323164"])
c(15, "§2.1 Reminders present (an alarm requested as an upgrade); progress/streak tracking and a daily completion ring free; within-month history editing works but not to prior months; edit/delete/pause exist but users cannot find them; Skip exists and breaks the completion ring; no habit end-date (deleting wipes history); no day-of-week/weekly/monthly frequency; no per-habit/per-day percentages", "feature",
  "Reminders exist (an alarm is requested as an upgrade on them); progress/streak tracking and a daily completion ring are free; history editing works inside the current month but not for prior months; edit/delete/pause exist but users cannot find them; Skip exists and breaks the daily completion ring; there is no habit end-date, so deleting is the only way out and it wipes history; there is no day-of-week / weekly / monthly frequency and no per-habit or per-day percentages",
  "basic free core with discoverability gaps", "complaint", "inventory rows", "must-have", "inventory", "yes",
  ["13267951780","12950173104","13176696608","13710940338","13085435338","13324437553","13576406218","13449993538","13249103798","13032875149","13705764332"])
c(16, "§2.1 Localisation in 13 languages functioning; name/profile entry at onboarding broken for Arabic-locale users; colour themes and iCloud sync on the store page only — no reviewer mentions either", "feature",
  "Localisation works in ES, RU, KO, AR, PT, FR, DE, NL, IT, HE, JA, TR and UK; name/profile entry at onboarding is broken for Arabic-locale users; colour themes and iCloud sync appear on the store page only — no reviewer mentions either, which for a paid-feature list is itself notable", "broad localisation; Arabic onboarding bug", "complaint", "2 name-entry bug reviews", "must-never-break", "inventory", "yes",
  ["13941632555","14107277631","13511113509","13596102043"])
c(17, "§2.2 External SKU table (verbatim) — Monthly $5.99 · Yearly $44.99 · Yearly (second SKU) $29.99 · Lifetime $59.99; listing 'Track up to 2 habits with free version', advertises streak/interactive widget, iCloud sync, history, colour themes, multi-language; v1.4.7 ~8 Sep 2026; US 4.9★ from 45", "monetization",
  "Store listing (US, accessed 11 Sep 2026): Monthly Premium $5.99, Yearly Premium $44.99, Yearly Premium (second SKU) $29.99, Lifetime Premium $59.99; 'Track up to 2 habits with free version'; advertises the streak/interactive widget, iCloud sync, history, colour themes and multi-language support; version 1.4.7 updated ~8 Sep 2026; US rating 4.9★ from 45 ratings", "four SKUs incl. two yearly", "none", table("## 2.2 Free / paid classification"), "none", "external", "app-specific", [])
c(18, "§2.2 Three store-page conflicts — (1) the page says 2 free habits but reviews from Apr 2026 consistently say 3 (stale page or cap varies by build/region); (2) two annual SKUs ($44.99, $29.99) plus a $59.99 'Lifetime' is exactly the configuration that produces 'they tell you the plan is for life and it's only for a year'; (3) no free trial anywhere, consistent with the no-trial 1★s", "anti-pattern",
  "Three material conflicts between store page and corpus: (1) the cap number is stale or inconsistent — the page says 2, reviews from April 2026 onward consistently say 3; (2) two annual SKUs at $44.99 and $29.99 plus a $59.99 'Lifetime' is exactly the configuration that produces 'they tell you the plan is for life and it's only for a year' (ES, 1★) — whether mis-sold or misread, the SKU shelf is ambiguous enough to generate the complaint; (3) no free trial appears anywhere, consistent with the two no-trial 1★ reviews",
  "ambiguous, stale SKU shelf; no trial", "1★-burst", "3 conflicts; 3 reviews", "must-never-break", "interpretation", "yes",
  ["14007543484","14262833547","14438894096","13705764332","13680381966","13679689890"])
c(19, "§2.3 Corpus integrity — the phrase bank (verbatim table): 83 of 166 (50.00%) match one of five short phrases or translations — RECOMMEND 37, VERY_GOOD 19, LIKE_SO_MUCH 11, BEST_ONE 9, SIMPLE_PERFECT 7 — all 83 5★, 1 carries substantive content", "data-caveat",
  "The phrase bank: 83 of 166 reviews (50.00%) match one of five short phrases or their translations, all 83 are 5★ (0 exceptions) and 1 also carries substantive content — RECOMMEND 37 ('I highly recommend it' / 'Lo recomiendo encarecidamente' / 'Ik beveel het ten zeerste aan' / 'Рекомендую'), VERY_GOOD 19 ('Very good' / 'Muy bueno' / 'Все супер'), LIKE_SO_MUCH 11, BEST_ONE 9 ('The best one' / 'El mejor' / 'De beste'), SIMPLE_PERFECT 7 ('so simple, perfect' in five languages)",
  "seeded 5★ launch reviews", "5★-burst", table("## 2.3 ⚠️ Corpus integrity — the phrase bank"), "dont", "high", "yes", [])
c(20, "§2.3 Five corroborating signals — (1) rating purity: 83/83 5★ vs the remaining 83 at mean 3.80; (2) cross-language identity: the same Dutch sentence on the NL and RU storefronts a day apart concatenating all five phrase families ('a phrase list, not a sentence'); (3) 11 storefront/language mismatches; (4) two discrete campaigns — GB+US 15 Jul–19 Sep 2025 (38), ES+CL 18 Nov–22 Dec 2025 (16); monthly Jul 35 · Aug 18 · Sep 9 · Oct 0 · Nov 10 · Dec 10 · Jan 1 · then zero for seven months; (5) GB stops dead after 19 Sep 2025 (19 reviews, 16 phrase-bank)", "data-caveat",
  "Five independent corroborating signals of seeding: (1) rating purity — 83/83 phrase-bank are 5★ while the remaining 83 are 1★19 · 2★3 · 3★4 · 4★7 · 5★50 (mean 3.80), and a 100%-5★ subgroup of 83 does not occur by chance; (2) cross-language identity — the same Dutch sentence appears on the NL storefront and on the Russian storefront a day apart, 'Ik beveel het ten zeerste aan, super, ik vind het zo leuk, heel goed, zo eenvoudig, perfect, de beste', a concatenation of all five phrase families — a phrase list, not a sentence; (3) 11 storefront/language mismatches (RU→Dutch, RU→Spanish 'el mejor', US→Russian, US→Portuguese, FR→Spanish, English in UA/KZ/AR/TR); (4) temporal clustering by market — GB+US phrase-bank reviews 15 Jul–19 Sep 2025 (38), ES+CL 18 Nov–22 Dec 2025 (16): two discrete campaigns in two language groups; monthly Jul 35 · Aug 18 · Sep 9 · Oct 0 · Nov 10 · Dec 10 · Jan 1 · then zero for seven months; (5) GB stops dead — 19 reviews, 16 phrase-bank, none at all after 19 September 2025",
  "seeded review campaigns by language group", "5★-burst", "83/83 5★ vs 3.80; 2 campaigns; 11 mismatches", "dont", "high", "yes",
  ["13403875241","13404072755","13442553415","14338216422","12928535001","13406815450"])
c(21, "§2.3 What this does and does not license — it makes the 4.398 mean, 80.1% 5★ share and every US/GB/ES/NL figure unusable as satisfaction; it does not make the positive findings false (42 give a reason; specific idiosyncratic ones read as genuine); it does not touch the negative findings (0 of 83 phrase-bank below 5★); interpretation: the seeded reviews were bought to establish a launch rating and are expiring, which is why the half-year mean fell 4.65 → 3.00", "insight",
  "What the phrase bank does and does not license: it does make the 4.398 mean, the 80.1% 5★ share and every US/GB/ES/NL figure unusable as satisfaction measures; it does not make the positive findings false — 42 reviews (25.3%) give a reason for liking the app and the specific, idiosyncratic ones read as genuine; it does not touch the negative findings at all, since 0 of 83 phrase-bank reviews are below 5★ and every complaint comes from the organic 83; interpretation (pattern, not attribution): the seeded reviews were bought to establish a launch rating and are now expiring, which is precisely why the half-year mean has fallen 4.65 → 3.00",
  "seeded launch rating decaying", "mixed", "42 with reasons; 0 of 83 negative", "dont", "interpretation", "yes",
  ["14338216422","13292317774","14008217420","12868175538","14107277631","12958650866","13242409709"])
c(22, "§2.4 The substantive segment — 47 of 166 (28.31%), rating 1★19 · 2★3 · 3★4 · 4★7 · 5★14, mean 2.87; the 119 non-substantive are all 5★ (mean 5.00); all 33 sub-5★ reviews are substantive and zero are phrase-bank — everyone with something specific to say rated it 2.87", "insight",
  "The substantive segment: 47 of 166 (28.31%) — 1★19 · 2★3 · 3★4 · 4★7 · 5★14, mean 2.87 — while the 119 non-substantive reviews are all 5★ (mean 5.00); all 33 sub-5★ reviews are substantive and zero are phrase-bank — the cleanest structural fact in the data: everyone who had something specific to say about this product, and was not part of the phrase bank, rated it 2.87 on average",
  "n/a", "complaint", "47 (28.31%), mean 2.87 vs 119 at 5.00", "none", "corpus-level fact", "app-specific", [])

with open("Tools/prd_ledger/30/cards.jsonl", "w") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards written")
