"""Cards for report 30 — Part 6 (country), Part 7 (trends), Part 8 (implications)."""
import json, re
R = 30
rep = open("App Store Reports/30. Habit Tracker - Simple&Powerful - Goal,task & Routine Planner (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(63, "§6.1 Distribution (verbatim table) — RU 56 (4.52, phrase-bank 46%, substantive 15, 1★ 5); US 31 (5.00, 71% phrase-bank, 1 substantive); GB 19 (4.89, 84%); ES 13 (4.69, 77%); CL 11 (4.82, 55%); AR 4 (2.00, 0%, 3 1★); BR 4 (3.75); FR 4 (3.50); KZ 4 (4.00); NL 3; SA 3 (2.33); UA 3 (2.33); DE 2; TR 2 (2.00); 7 singletons; only Russia clears 50", "market",
  "Storefront distribution with phrase-bank and substantive counts: RU 56 (33.7%, mean 4.52, phrase-bank 26 = 46%, substantive 15, 1★ 5, Jul 2025 → Aug 2026); US 31 (5.00, 22 = 71%, 1, 0); GB 19 (4.89, 16 = 84%, 2, 0, Jul–Sep 2025 only); ES 13 (4.69, 10 = 77%, 1, 1); CL 11 (4.82, 6 = 55%, 3, 0); AR 4 (2.00, 0, 3, 3); BR 4 (3.75, 0, 4, 0); FR 4 (3.50, 1, 2, 0); KZ 4 (4.00, 0, 2, 1); NL 3 (5.00, 2, 0, 0); SA 3 (2.33, 0, 2, 2); UA 3 (2.33, 0, 2, 2); DE 2 (5.00); TR 2 (2.00); AM, IL, IT, JP, KR, MX, UY 1 each (0 phrase-bank, 7 substantive, 4 1★); only Russia clears 50", "n/a", "mixed", table("## 6.1 Distribution"), "none", "corpus-level fact", "app-specific", [])
c(64, "§6.2 Russia (verbatim table) — n=56, 5★46 · 4★3 · 3★2 · 1★5; cap 12.50% (above 9.04%); monetisation friction 16.07%; functional defect 8.93%; simplicity 10.71%; convenience 10.71%; behaviour change 5.36%; crash 3.57%; billing failure 3.57%; the only continuous 13-month stream; both billing failures and both crashes are Russian; the most nuanced feedback ('bad for free use, excellent for paid'; the only person who liked the price); non-phrase-bank RU mean 4.10, substantive 3.20 — the product's real market, and where the payment flow is visibly breaking", "market",
  "Russia (n=56, 33.7%, mean 4.52; 5★46 · 4★3 · 3★2 · 2★0 · 1★5; phrase-bank 26 = 46.4%; substantive 15 = 26.8%): free habit cap 7 (12.50%, above global 9.04%), monetisation friction 9 (16.07%), functional defect 5 (8.93%), simplicity 6 (10.71%), convenience 6 (10.71%), behaviour change 3 (5.36%), crash 2 (3.57%), billing failure 2 (3.57%), cannot find edit/delete 1; distinctive: the only market with a continuous 13-month review stream (every month but June 2026 — every other storefront is a burst); both billing failures in the entire corpus are Russian (a Russia-specific payment-processing check is warranted since RU is the only market producing purchase attempts continuously); both crash reports are Russian, both launch week; Russian reviewers volunteer the most nuanced feedback — a polite request for prior-month editing, a 1★ titled 'Для бесплатного плохо, для платки отлично' ('bad for free use, excellent for paid') that then praises the app, and the only person in the corpus who says they liked the price; the 30 non-phrase-bank RU reviews average 4.10 and the 15 substantive 3.20 — Russia is the product's real market (highest volume, longest tail, most engaged feedback, most purchase attempts) and where the payment flow is visibly breaking",
  "n/a", "mixed", table("## 6.2 Russia"), "research", "meaningful (only eligible country)", "app-specific",
  ["13670832453","13678734774","12883902100","12886833369","13085435338","13078324005","12933316146"])
c(65, "§6.3 High-spend markets (US, JP, GB, DE, FR, CA, AU, KR; tier definition, no spend data) — present: US 31 · GB 19 · FR 4 · DE 2 · JP 1 · KR 1 = 58 (34.9%); CA and AU zero; US unmeasured (22/31 phrase-bank, 31/31 5★, the one substantive review in Russian); GB nothing after 19 Sep 2025; 8 substantive reviews total, 5 of them monetisation complaints, mean 3.50 vs headline 4.79 — essentially no measured organic reception in the highest-spend markets, the single most important thing to fix about how this product is evaluated", "market",
  "High-spend markets (tier definition — US, JP, GB, DE, FR, CA, AU, KR — not spend data; review volume never used as a download or revenue proxy): present US 31 · GB 19 · FR 4 · DE 2 · JP 1 · KR 1 = 58 (34.9%); CA and AU produced zero; US is unmeasured (22/31 phrase-bank, 31/31 five-star, the one substantive review written in Russian); GB is 16/19 phrase-bank with nothing after 19 September 2025 and its one real review is 3★; FR's two substantive reviews are both 2★ cap complaints; DE's is a 5★ asking for a bigger free tier; JP's is 'The price is too high for this quality' (1★); KR's is the only happy widget user; across the group 8 substantive reviews, 5 of them monetisation complaints, mean 3.50 against a headline 4.79 — the product has essentially no measured organic reception in its highest-spend markets; the US and GB numbers are a launch artefact, a gap in market knowledge rather than evidence of success, and the single most important thing to fix about how this product is being evaluated",
  "seeded US/GB launch reviews", "mixed", table("## 6.3 High-spend markets"), "research", "group-level, stated limitation", "app-specific",
  ["13032875149","13283076453","13487320234","13625113466","13682739906","14107277631"])
c(66, "§6.4 High-review-volume markets (n≥10: RU, US, GB, ES, CL = 130, 78.3%) hold 80 of 83 phrase-bank reviews (96.4%); headline mean 4.73 vs substantive 3.41 (n=22); 130 reviews yield 22 substantive while the other 36 over 16 storefronts yield 25 — volume and signal are inversely related; weight decisions toward the long tail (AR, BR, SA, UA, TR, IT, JP, MX, IL, UY, KZ)", "data-caveat",
  "High-review-volume storefronts defined from this corpus (n ≥ 10: RU 56, US 31, GB 19, ES 13, CL 11 = 130, 78.3%) hold 80 of the 83 phrase-bank reviews (96.4%; the other 3 in NL and FR); combined headline mean 4.73 vs substantive mean 3.41 (n=22); the high-volume group is the least informative per review — 130 reviews yield 22 substantive records while the other 36 reviews across 16 storefronts yield 25; volume and signal are inversely related, so product decisions should be weighted toward the long tail — AR, BR, SA, UA, TR, IT, JP, MX, IL, UY, KZ — where the organic reviewers are",
  "n/a", "none", "80/83 phrase-bank in top 5; 22 vs 25 substantive", "none", "method", "yes", [])
c(67, "§6.5 Spanish-language markets (ES + CL + AR + MX + UY = 30, 18.1%; limited evidence) — ES and CL 16/24 phrase-bank at 4.75 vs AR, MX, UY 0/6 phrase-bank at 2.33; the organic Spanish reviews are the harshest ('Es un check list CARÍSIMO'; 'Cuidado, engañan' — careful, they deceive; 'no puedo recuperar el dinero'); the most detailed constructive review is also Spanish-language (CL, 4★)", "market",
  "Spanish-language markets grouped (ES + CL + AR + MX + UY = 30, 18.1%; limited evidence): ES (13) and CL (11) are 16/24 phrase-bank and average 4.75, while AR (4), MX (1) and UY (1) are 0/6 phrase-bank and average 2.33; the organic Spanish-language reviews are the harshest in the corpus — 'Es un check list CARÍSIMO'; 'Cuidado, engañan' ('careful, they deceive', ES); 'no puedo recuperar el dinero'; counterweight: the single most detailed constructive review is also Spanish-language (CL, 4★); 6 organic reviews cannot characterise a language market",
  "n/a", "1★-burst", "ES+CL 4.75 (16/24 seeded) vs AR+MX+UY 2.33 (0/6)", "none", "limited evidence", "app-specific",
  ["13755696898","13705764332","14264524351","13176696608"])
c(68, "§6.6 Sub-50 storefronts promoted as hard defects — SA (n=3): 2 of 3 the same onboarding name-entry blocker (both 1★, Dec 2025 and Jan 2026) — a hard block for an entire locale; UA (n=3): 2 of 3 store-disclosure / trial complaints (both 1★); no other sub-50 storefront supports a standalone conclusion", "market",
  "Two sub-50 observations promoted because they are hard defects rather than opinions: Saudi Arabia (n=3) — 2 of 3 reviews are the same onboarding name-entry blocker (both 1★, Dec 2025 and Jan 2026), limited by count but a hard block affecting an entire locale; Ukraine (n=3) — 2 of 3 are store-disclosure / trial complaints (both 1★); AR's 2.00 mean, TR's 2.00, IT/JP/MX/IL 1★ singletons and KR/UY/AM/DE 5★ singletons carry no country-level claim",
  "Arabic onboarding blocker; disclosure/trial", "1★-burst", "SA 2/3; UA 2/3", "must-never-break", "limited evidence, hard defects", "app-specific",
  ["13511113509","13596102043","13679689890","13864202916"])
c(69, "§6.7 Global vs country comparison (verbatim table) — mean 4.40 / RU 4.52 / high-spend 4.79 / long tail 3.19; substantive share 28.3 / 26.8 / 13.8 / 69.4%; substantive mean 2.87 / 3.20 / 3.50 / 2.40; phrase-bank 50.0 / 46.4 / 67.2 / 8.3%; monetisation friction 17.5 / 16.1 / 8.6 / 47.2% — where the phrase bank is absent the substantive rating is 2.4–3.5 and monetisation is the complaint; in the long tail 47.2% carry a monetisation complaint at mean 3.19", "insight",
  "Global vs Russia vs high-spend vs long tail: mean 4.40 / 4.52 / 4.79 / 3.19; substantive share 28.3% / 26.8% / 13.8% / 69.4%; substantive mean 2.87 / 3.20 / 3.50 / 2.40; phrase-bank share 50.0% / 46.4% / 67.2% / 8.3%; monetisation friction 17.5% / 16.1% / 8.6% / 47.2% — the pattern is consistent in every cut: where the phrase bank is absent the substantive rating is 2.4–3.5 and monetisation is the complaint; in the long tail (36 reviews outside the five high-volume storefronts) 47.2% of all reviews carry a monetisation complaint and the headline mean is 3.19",
  "n/a", "complaint", table("## 6.7 Global vs country comparison"), "product-rule", "high", "yes", [])
# Part 7
c(70, "§7.1 Headline series (verbatim table) — 2025H2 138 / 4.65 / non-phrase-bank 56 at 4.14 / substantive 26 at 3.15 / 1★ 5.1%; 2026H1 23 / 3.17 / 22 at 3.09 / 17 at 2.53 / 1★ 43.5%; 2026H2 5 / 3.00 / 5 at 3.00 / 4 at 2.50 / 1★ 40.0% (no independent weight)", "timeline",
  "Headline series by half-year: 2025H2 n=138, mean 4.65, non-phrase-bank 56 at 4.14, substantive 26 at 3.15, 1★ 5.1% (7/138); 2026H1 n=23, 3.17, 22 at 3.09, 17 at 2.53, 1★ 43.5% (10/23); 2026H2 n=5, 3.00, 5 at 3.00, 4 at 2.50, 1★ 40.0% (2/5, no independent weight); no version field so no release-based cut", "n/a", "churn", table("## 7.1 The headline series"), "none", "corpus-level fact", "app-specific", [])
c(71, "§7.2 Trend 1 — the cap was raised from 2 to 3 and it did not help (confirmed, high confidence) — dated table (verbatim): 12 reviews say '2' from 14 Aug 2025 to 4 Feb 2026, then 3 say '3' from 29 Apr to 17 Aug 2026, no overlap; the store page still says 2; the complaint continued at the same rate and with the same ratings (1★, 3★, 4★) — +1 was not enough, a reviewer had already named 5 as the floor", "timeline",
  "Trend 1 (confirmed change, high confidence): the free cap was raised from 2 to 3 and it did not help — every review naming the limit before 4 Feb 2026 says 2 (12 reviews, 14 Aug 2025 → 4 Feb 2026: RU 1★, RU 1★, RU 1★, KZ 1★, FR 2★, TR 1★, BR 2★, FR 2★, RU 4★, UA 1★, RU 1★, RU 5★) and every review from 29 Apr 2026 says 3 (CL 4★ 29 Apr, RU 3★ 4 Jul, IT 1★ 17 Aug) with no overlap — a clean fingerprint; the store page still says 2 (a separate listing-accuracy problem); the developer responded to the complaint by adding one habit and the complaint continued at the same rate with the same ratings — +1 was not enough, and a reviewer had already named 5 as the floor",
  "raised cap 2 → 3 in Feb–Apr 2026", "1★-burst", table("## 7.2 Trend 1"), "product-rule", "high", "yes",
  ["13015082250","13057771438","13078324005","13139338718","13283076453","13286447070","13441364320","13487320234","13678734774","13679689890","13707712022","13710940338","14007543484","14262833547","14438894096"])
c(72, "§7.3 Trend 2 — the seeded reviews ran out and the rating collapsed (high confidence): phrase-bank Jul 35 · Aug 18 · Sep 9 · Oct 0 · Nov 10 · Dec 10 · Jan 1 · Feb–Aug 0 — two campaigns then nothing for seven months; organic flat-to-declining Jul 18 · Aug 14 · Sep 5 · Oct 10 · Nov 5 · Dec 4 · Jan 8 · Feb 6 · Mar 2 · Apr 3 · May 3 · Jun 0 · Jul 3 · Aug 2; the 4.40 mean and 4.9★ US store rating are propped up by a supply that has stopped — organic run-rate ~3 reviews/month at ~3.0★; left alone the public rating decays toward 3", "timeline",
  "Trend 2 (high confidence): the seeded reviews ran out and the rating collapsed — phrase-bank reviews by month Jul 35 · Aug 18 · Sep 9 · Oct 0 · Nov 10 · Dec 10 · Jan 1 · Feb–Aug 0 (two campaigns — English-language Jul–Sep 2025, Spanish/Dutch-language Nov–Dec 2025 — then nothing for seven months); organic reviews flat to declining but steady: Jul 18 · Aug 14 · Sep 5 · Oct 10 · Nov 5 · Dec 4 · Jan 8 · Feb 6 · Mar 2 · Apr 3 · May 3 · Jun 0 · Jul 3 · Aug 2; the 4.40 corpus mean and the 4.9★ US store rating are propped up by a supply that has stopped — the organic run-rate is ~3 reviews/month at ~3.0★, and left alone the public rating decays toward 3",
  "seeded launch reviews stopped", "churn", "phrase-bank 35 → 0; organic ~3/month at ~3.0★", "dont", "high", "yes", [])
c(73, "§7.4 Trend 3 — complaints migrated from 'it's broken' to 'it's not worth paying for' (medium-high): 2025H2 substantive complaints crashes 2, cap 8, edit/pause 2, scheduling 2, alarm 1, scroll/density 2, paid-model confusion 1; 2026 cap 7, price/value 4, purchase-flow 4, no trial 2, refund 1, store disclosure 1, name-entry 2, slow 1; zero crashes after Jul 2025, zero purchase-flow complaints before Jan 2026 — the software stabilised and the commercial layer became the entire problem; all four purchase-flow defects are 2026 events (a monetisation change or growing purchase volume — indistinguishable)", "timeline",
  "Trend 3 (medium-high confidence): complaints migrated from 'it's broken' to 'it's not worth paying for' — 2025H2 substantive complaints: crashes 2, cap 8, edit/pause discoverability 2, scheduling 2, alarm 1, scroll/density 2, paid-model confusion 1; 2026: cap 7, price/value 4, purchase-flow failures 4, no trial 2, refund 1, store disclosure 1, name-entry bug 2, slow 1; zero crash reports after July 2025 and zero purchase-flow complaints before January 2026 — the software stabilised and the commercial layer became the entire problem; all four purchase-flow defects (Jan, Jan, Feb, Jul) are 2026 events, suggesting either a monetisation change or growing purchase volume in 2026 — the corpus cannot distinguish",
  "stabilised software, broken commercial layer", "1★-burst", "crash 2 → 0; purchase-flow 0 → 4", "must-never-break", "medium-high", "yes",
  ["13670832453","13678734774","13705764332","14264524351"])
c(74, "§7.5 Trend 4 — one-star rate rose 8× (high confidence): 5.1% of 2025H2 (7/138) → 42.9% of 2026 (12/28); against the non-phrase-bank subset alone 12.5% (7/56) → 44.4% (12/27) — not an artefact of the phrase bank disappearing: the organic one-star rate more than tripled", "timeline",
  "Trend 4 (high confidence): the one-star rate rose 8× — 5.1% of 2025H2 reviews (7/138) → 42.9% of all 2026 reviews (12/28); even against the non-phrase-bank subset only, 12.5% (7/56) → 44.4% (12/27) — not an artefact of the phrase bank disappearing: the organic one-star rate itself more than tripled", "n/a", "1★-burst", "5.1% → 42.9%; organic 12.5% → 44.4%", "none", "high", "app-specific", [])
c(75, "§7.6 Trend 5 — the name-entry bug confined to Dec 2025 – Jan 2026, then a plain Saudi 5★ in May 2026 ('great app for keeping habits going'); possibly fixed — a guess, not a finding (low confidence, n=2)", "timeline",
  "Trend 5 (low confidence, n=2): the Arabic name-entry bug is confined to 14 Dec 2025 and 5 Jan 2026, followed by a plain Saudi 5★ on 17 May 2026 ('تطبيق رائع لمتابعة استمرار العادات' — 'great app for keeping habits going'); possibly fixed — with n=3 in the storefront, a guess not a finding", "possibly fixed onboarding bug", "praise", "2 then a 5★", "none", "low", "app-specific", ["13511113509","13596102043","14074890221"])
c(76, "§7.7 What did not change — simplicity praise in every period (the only constant positive); the cap complaint in all 13 months before and after 2→3; the widget-paywall complaint Sep 2025 → Feb 2026, never addressed; nobody has ever mentioned iCloud sync or colour themes in any period or market", "insight",
  "What did not change: simplicity praise is present in every period and is the only constant positive; the cap complaint is present in all 13 months, before and after the 2→3 change; the widget-paywall complaint spans Sep 2025 to Feb 2026, persistent and never addressed; nobody has ever mentioned iCloud sync or colour themes — both advertised paid features — in any period or any market", "n/a", "mixed", "13 months", "research", "corpus-level fact", "yes", ["13130702696","13706323164"])
# Part 8
c(77, "§8.1 F1 — audit the purchase flow end to end: entitlement delivery, the monthly SKU and the Lifetime-vs-Yearly labelling; treat paid-no-unlock as a P0 incident; removes the highest-severity, most store-policy-exposed failures and directly affects revenue realisation", "must-never-break",
  "F1: audit the purchase flow end to end — entitlement delivery, the monthly SKU, and the Lifetime-vs-Yearly labelling — and treat the paid-no-unlock report as a P0 incident; 5 of the 6 identifiable payers had a bad outcome across 4 distinct defects; removes the highest-severity and most store-policy-exposed failures and directly affects revenue realisation", "broken purchase flow", "1★-burst", "5 of 6 payers; 4 defects", "must-never-break", "high severity", "yes",
  ["13670832453","13678734774","13705764332","14264524351"])
c(78, "§8.1 F2 — raise the free cap to at least 5 habits and move monetisation to depth (widget, sync, themes, history, stats) instead of count; the single highest-leverage change, and it also neutralises most of the price objection", "product-rule",
  "F2: raise the free cap to at least 5 habits and move monetisation to depth — widget, sync, themes, history, stats — instead of count; evidence: 15 cap reviews (9.04%, high-priority, mean 2.00), all 3 two-star reviews, 8 of 19 one-star, and users' own proposals (5 free habits; 'put some features in pro instead'); the single highest-leverage change in the report, which also neutralises most of the price objection",
  "2–3 habit cap", "1★-burst", "15; 3/3 2★; 8/19 1★", "product-rule", "high-priority", "yes", ["13139338718","13441364320"])
c(79, "§8.1 F3 — fix the Arabic-locale name-entry blocker: a hard block at first launch for an entire locale, small fix, total impact for affected users", "must-never-break",
  "F3: fix the Arabic-locale name-entry blocker — 2 of 3 Saudi reviews, both 1★; a hard block at first launch for an entire locale, a small fix with total impact for affected users", "onboarding name field", "1★-burst", "2 of 3 SA", "must-never-break", "limited, hard block", "yes", ["13511113509","13596102043"])
c(80, "§8.1 F4 — make edit / delete / pause discoverable: the feature exists; three reviewers in three countries could not find it, one rating 1★; pure UX, no new functionality", "must-have",
  "F4: make edit / delete / pause discoverable — the feature exists and three reviewers across three countries could not find it, one of them rating 1★; pure UX that removes a 1★ cause with no new functionality", "hidden controls", "complaint", "3", "must-have", "meaningful", "yes", ["13324437553","13576406218","13449993538"])
c(81, "§8.1 F5 — correct the store listing: the cap is 3 not 2; the advertised widget must match the shipped widget; make IAP disclosure visible at the decision point — removes expectation-mismatch 1★ reviews and reduces store-policy risk", "do",
  "F5: correct the store listing — the cap is 3, not 2; ensure the advertised widget matches the shipped widget; make IAP disclosure visible at the decision point; removes expectation-mismatch 1★ reviews and reduces store-policy risk", "stale, mismatched listing", "complaint", "listing conflicts + 2 reviews", "do", "meaningful", "yes", ["13706323164","13864202916"])
c(82, "§8.1 F6 — introduce a trial, or a reversible first purchase: addresses the two no-trial 1★ reviews ('paid annual blind'; 'won't buy without trying') and the review that cannot tell if the app is paid", "monetization",
  "F6: introduce a trial, or a reversible first purchase — directly addresses the two no-trial 1★ reviews (paid annual blind; won't buy without trying) and the 3★ that cannot tell whether the app is paid", "no trial", "blocked-conversion", "2 + 1", "research", "meaningful", "yes", ["13680381966","13679689890","13214738742"])
c(83, "§8.1 F7 — fix the scroll-jump-to-top bug and add a compact list density; it only manifests above ~10 habits so it degrades the paid experience specifically — fix it before F2 raises habit counts", "must-never-break",
  "F7: fix the scroll-jump-to-top bug and add a compact list density — it only manifests above ~10 habits, i.e. it degrades the paid experience specifically; fix it before F2 raises habit counts", "list scroll resets on tick", "complaint", "1 (GB, 3★)", "must-never-break", "emerging", "yes", ["13032875149"])
c(84, "§8.2 B1 — the only build item: non-daily scheduling (days of week, x per week, weekly, monthly) + an end-date + Skip that preserves the daily completion ring — one coherent feature closing unmet needs #1, #2, #3 and #5 and stopping the data loss; explicitly do not build in response to 'too basic' — all 4 also object to price, a value complaint wearing a feature costume that would attack the one proven strength", "must-have",
  "B1: non-daily scheduling — per-habit frequency (days of week, x per week, weekly, monthly), an end-date, and Skip that preserves the daily completion ring — one coherent feature closing unmet needs #1, #2, #3 and #5 simultaneously and stopping the history loss on delete; 4 storefronts, 4 languages (n=4, 2.41%); the only feature build the corpus supports; explicitly do not build in response to 'the app is too basic' — all 4 who say it also object to price, a value complaint wearing a feature costume, and adding surface area would attack the product's one proven strength (simplicity 23 + convenience 12 + outcomes 7)",
  "daily-only; no end date", "complaint", "4 (2.41%)", "must-have", "meaningful", "yes",
  ["13032875149","13176696608","13249103798","13705764332"])
c(85, "§8.3 E1 — free cap at 5 vs 3: raising the cap increases both retention and paid conversion because evaluation becomes possible (predicted by every cap review; 'It would be smarter to create attractive features that persuade the user to pay'); read-out conversion, D7/D30 retention, 1★ rate", "monetization",
  "E1: free cap at 5 vs 3 — hypothesis: raising the cap increases both retention and paid conversion because evaluation becomes possible, predicted by every cap review and stated outright ('It would be smarter to create attractive features that persuade the user to pay rather than limiting tracking to a mere two'); read-out: conversion rate, D7/D30 retention, 1★ rate", "3-habit cap", "blocked-conversion", "experiment", "research", "hypothesis", "yes", ["13286447070"])
c(86, "§8.3 E2 — widget free vs paid: the widget is an acquisition driver being used as a paywall — a documented completed switch to a free-widget competitor, and the widget is the engagement loop for the happiest user; read-out install→activation and churn to competitors", "feature",
  "E2: widget free vs paid — hypothesis: the widget is an acquisition driver being used as a paywall; a documented, completed switch to a competitor with a free widget, and the widget is the engagement loop for the happiest user in the corpus; read-out: install → activation and churn to competitors", "widget paid", "churn", "experiment", "free", "hypothesis", "yes", ["13081229555","14107277631"])
c(87, "§8.3 E3 — collapse the SKU shelf: four SKUs including two yearly prices and a $59.99 'Lifetime' generated the mis-sold-lifetime 1★; a simpler shelf should reduce refunds and mis-sale complaints; read-out refund rate and purchase-theme 1★", "monetization",
  "E3: collapse the SKU shelf — four SKUs including two yearly prices and a $59.99 'Lifetime' generated the mis-sold-lifetime 1★; a simpler shelf should reduce refunds and mis-sale complaints; read-out: refund rate and 1★ rate on purchase themes", "four overlapping SKUs", "1★-burst", "experiment", "research", "hypothesis", "yes", ["13705764332"])
c(88, "§8.3 E4 — alarm-style reminders: users set a second alarm in the system Clock because the notification is not strong enough ('receives an alarm from the app itself and doesn't need another alarm'); read-out notification → completion rate", "feature",
  "E4: alarm-style reminders — users are setting a second alarm in the system Clock app because the notification is not strong enough ('assim a pessoa recebe um alarme com o próprio app e não precisa fazer outro alarme no celular'); read-out: notification → completion rate", "notification only", "complaint", "1 (BR, 4★)", "research", "hypothesis", "yes", ["13267951780"])
c(89, "§8.4 Research questions Part 8 #1–#5 — the real reception in US, GB, DE, FR, CA, AU (58 high-spend reviews yield 8 substantive; method: in-app survey or a clean review-prompt cohort, not more store reviews); why both billing failures are Russian; did the 2→3 change run and when; does anyone pay and stay happy (zero satisfied-payer reviews); what happens to the public rating over the next two quarters (~3.0★ trajectory — forecast internally, don't discover it)", "data-caveat",
  "Research questions: what is the real reception in the US, GB, DE, FR, CA and AU — 58 high-spend reviews yield 8 substantive records, the product is commercially blind in its highest-value markets (method: in-app survey or a clean review-prompt cohort, not more store reviews); why are both billing failures Russian — payment processing, SKU availability, or simply the only market with continuous purchase attempts; did the 2→3 cap change actually run and when (release notes would confirm); does anyone pay and stay happy — zero satisfied-payer reviews, so retention/renewal is entirely unmeasured; what happens to the public rating over the next two quarters — the organic trajectory is ~3.0★, forecastable internally and to be monitored, not discovered",
  "n/a", "none", "report gives none (questions)", "research", "open questions", "yes", [])
c(90, "§8.5 What not to change — do not add features to the free tier's surface area, add habit slots (simplicity is the largest positive theme and the only attribute volunteered unprompted); do not cut the price (three say it is acceptable, including a 1★ and a 2★ who rated low for the cap); do not rely on the current star rating for any decision", "dont",
  "What not to change: do not add features to the free tier's surface area — add habit slots (simplicity is the single largest positive theme, 23, 13.86%, and the only attribute anyone volunteers unprompted); do not cut the price — three reviewers say the price is acceptable, including two who rated 1★ and 2★ for the cap, so the objection is value, not price; do not rely on the current star rating for any decision (seeded launch reviews, decaying)",
  "minimal, fairly priced, capped", "mixed", "23; 3 price-acceptable", "dont", "high", "yes", ["12933316146","13487320234","13139338718"])

with open("Tools/prd_ledger/30/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
