"""Cards for report 30 — Part 3 (global), Part 4 (ratings), Part 5 (paid users)."""
import json, re
R = 30
rep = open("App Store Reports/30. Habit Tracker - Simple&Powerful - Goal,task & Routine Planner (REPORT).md").read().split("\n")
def table(after, k=0):
    i = next(n for n, l in enumerate(rep) if after in l)
    blocks, cur = [], []
    for l in rep[i+1:]:
        if l.startswith("|"): cur.append(l)
        elif cur:
            blocks.append(cur); cur = []
            if len(blocks) > k: break
    if cur: blocks.append(cur)
    rows = [l for l in blocks[k] if not re.match(r"^\|[\s\-:|]+\|$", l)]
    return " ; ".join(re.sub(r"\s*\|\s*", " | ", l.strip("|")).replace("**","").replace("`","").strip() for l in rows)
cards = []
def c(seq, where, kind, claim, does, react, mag, direction, conf, gen, ids, side="", cond=""):
    cards.append(dict(id=f"R{R:02d}-{seq:03d}", report=R, where=where, kind=kind, claim=claim,
        this_app_does=does, user_reaction=react, magnitude=mag, direction=direction,
        report_confidence=conf, generalisable=gen, side_effects=side, conditions=cond,
        review_ids=ids, canonical=[]))

c(23, "§3.1 Master table (verbatim), 32 themes + integrity rows, with substantive-segment rates", "data-caveat", "Master theme table, denominator 166, with substantive segment %", "n/a", "mixed", table("## 3.1 Master table"), "none", "corpus-level fact", "app-specific", [])
T = [
 (24,"#1 Any monetization friction (union)","monetization","Any monetisation friction (union)","29 (17.47%, HIGH), sub. 61.7%, mean 2.17","product-rule","1★-burst"),
 (25,"#5 Any functional defect (union)","must-never-break","Any functional defect (union)","12 (7.23%, HIGH), sub. 25.5%, mean 3.00","must-never-break","complaint"),
 (26,"#6 Paywall too aggressive / 'not really free'","monetization","Paywall too aggressive / 'not really free' — the framing objection","11 (6.63%, HIGH), sub. 23.4%, mean 1.82","product-rule","1★-burst"),
 (27,"#7 Any feature request (union)","feature","Any feature request (union)","8 (4.82%, very strong), sub. 17.0%, mean 3.88","none","complaint"),
 (28,"#9 UI / visual design praised","feature","UI / visual design praised","6 (3.61%, very strong), mean 4.83","do","praise"),
 (29,"#12 'Too basic / too thin for the price'","monetization","'Too basic / too thin for the price' — every one also carries a price objection","4 (2.41%, meaningful), mean 1.50","product-rule","complaint"),
 (30,"#13 Price described as acceptable","monetization","Price described as acceptable","3 (1.81%, meaningful), mean 2.67","build-paid","mixed"),
 (31,"#14 Cannot find edit / delete / pause","must-have","Cannot find edit / delete / pause — discoverability, not a missing feature","3 (1.81%, meaningful), mean 3.33","must-have","complaint"),
 (32,"#16 No free trial","monetization","No free trial","2 (1.20%, meaningful), mean 1.00","research","blocked-conversion"),
 (33,"#17 Billing failure (charge / wrong SKU)","must-never-break","Billing failure — charge without entitlement / wrong SKU","2 (1.20%, meaningful), mean 2.50","must-never-break","1★-burst"),
 (34,"#18 Store-listing mismatch","do","Store-listing mismatch (widget screenshot; undisclosed IAP)","2 (1.20%, meaningful), mean 3.00","do","complaint"),
 (35,"#19 Crash / won't open","must-never-break","Crash / won't open (Jul 2025 only)","2 (1.20%, meaningful), mean 3.50","must-never-break","complaint"),
 (36,"#20 Name-entry bug (Arabic locale)","must-never-break","Name-entry bug (Arabic locale)","2 (1.20%, meaningful), mean 1.00","must-never-break","1★-burst"),
]
for seq, w, kind, claim, mag, d, react in T:
    c(seq, f"§3.1 Master table {w}", kind, claim, "see §3.1", react, mag, d, "theme-table signal", "yes", [])
c(37, "§3.1 Master table #21–#32 single-record rows — refund refused; 'lifetime' delivered as annual; cannot edit prior months (5★); deleting a habit destroys its history; scroll jumps to top after ticking; list rows too large; app runs slowly (5★); alarm requested; per-habit/per-day percentages requested; Skip breaks the completion ring; widget praised by a paying user; Spanish localisation praised", "data-caveat",
  "Single-record rows (0.60%, emerging): refund refused (1★); 'lifetime' plan delivered as annual (1★); cannot edit prior months (5★); deleting a habit destroys its history (4★); scroll jumps to top after ticking (3★); list rows too large, no density control (3★); app runs slowly (5★); alarm, not just a notification, requested (4★); per-habit / per-day percentages requested (4★); Skip breaks the daily completion ring (4★); widget praised by a paying user (5★); Spanish localisation praised (5★); integrity rows: phrase bank 83 (50.00%, 5.00), non-substantive praise 119 (71.69%, 5.00)", "see §3.1", "mixed", "12 single-record rows", "none", "emerging (anecdotes)", "yes", [])
c(38, "§3.2 Simplicity — 23 (13.86%, mean 5.00); caveat: 9 are SIMPLE_PERFECT phrase-bank strings; the organic 14 remain the largest genuine positive theme ('clear, convenient interface, no fuss'; 'minimalist, no unnecessary junk'; 'es sencilla y fácil de usar')", "insight",
  "Simplicity/minimalism (23, 13.86%, mean 5.00) — caveat: 9 of the 23 are SIMPLE_PERFECT phrase-bank strings; the organic 14 remain the largest genuine positive theme and describe the same attribute in their own words: 'понятный и удобный интерфейс. Без заморочек' ('clear, convenient interface, no fuss'); 'минималистичное без лишнего мусора'; 'Muy practica, minimalista'; 'Good app, minimalistic, effective'; 'Clean UI, awesome app'; 'es sencilla y fácil de usar'", "minimalist", "praise", "23 (14 organic)", "product-rule", "high", "yes",
  ["12868175538","12879111396","12906449491","12928535001","12951242331","12952151986","13028574593","13105956090","13130702696","13292317774","13330607664","13351540188","13403875241","13404072755","13406815450","13449993538","13524579586","13572998737","13701569896","13706323164","14008217420","14338216422","14445598360"])
c(39, "§3.2 Everyday convenience — 12 (7.23%, mean 5.00): 'convenient for tracking progress in any undertaking; helps me not forget to do something'; 'Cool and convenient application for life'", "insight",
  "Everyday convenience (12, 7.23%, mean 5.00): 'Удобное приложение, чтобы отслеживать свои успехи в любых начинаниях. Помогает не забыть сделать что-то' ('convenient for tracking progress in any undertaking; helps me not forget to do something'); 'Cool and convenient application for life'; 'it's convenient to record all your habits and goals'", "n/a", "praise", "12 (7.23%)", "none", "high", "yes",
  ["12868175538","12898221749","12906449491","12927513076","12943312203","12950173104","12999068209","12999307390","13017650184","13040469782","14338216422","14445598360"])
c(40, "§3.2 Concrete behaviour change — 7 (4.22%, mean 5.00): 'I've changed so much because of this app… I'm reaching what I waited 12 years for'; 'I finally started sticking to healthy eating'; 'It's very easy to instill new habits!'; 'I keep it up as a widget and I'm practising small habits' — the product's proof of value and the argument for fixing packaging, not product", "insight",
  "Concrete behaviour change (7, 4.22%, very strong, mean 5.00) — the strongest outcome claims: 'Я настолько изменился из за этого приложения… благодаря вам я достигаю того чего ждала 12 лет' ('I've changed so much because of this app… thanks to you I'm reaching what I waited 12 years for', AM); 'I finally started sticking to healthy eating and a bit of sport'; 'It's very easy to instill new habits!'; 'I keep it up as a widget and I'm practising small habits… very good' (KR) — the product's proof of value and the argument for fixing the packaging rather than the product", "n/a", "praise", "7 (4.22%), mean 5.00", "none", "very strong", "yes",
  ["12950173104","12958650866","13152209815","13242409709","13710940338","14072034839","14107277631"])
c(41, "§3.2 UI / design — 6 (3.61%, mean 4.83), one a 4★ opening with design praise then reporting a billing failure; localisation — 1 explicit compliment ('Idioma en español y buen diseño de app') from a Spanish-language market where 13 of 13 other ES/CL reviews say nothing specific (limited evidence)", "insight",
  "UI/design praised by 6 (3.61%, mean 4.83), one of them a 4★ that opens with design praise and then reports a billing failure; localisation praised once ('Idioma en español y buen diseño de app', CL) — limited evidence, but the only explicit localisation compliment and from a Spanish-language market where 13 of 13 other ES/CL-storefront reviews say nothing specific", "n/a", "praise", "6; 1", "none", "limited", "app-specific",
  ["12868175538","12943312203","13028574593","13678734774","13701569896","13941632555"])
c(42, "§3.3 Free habit cap — 15 IDs split by era (12 in the 2-habit era, 3 in the 3-habit era); rating spread 1★8 · 2★3 · 3★1 · 4★2 · 5★1 — people who like the app and dock it anyway ('Wonderful app… minus: the free version allows only 2 habits'; 'La app es buenísima. Peero, para añadir más de tres hábitos hay que pagar'); two propose the fix — 5 free habits, and 'put some features in pro instead'; 'Nobody forms a habit portfolio of two. The cap converts evaluation into rejection'", "product-rule",
  "The free habit cap in detail: 12 reviews in the 2-habit era and 3 in the 3-habit era; rating spread 1★8 · 2★3 · 3★1 · 4★2 · 5★1 — the 4★ and 5★ are people who like the app and dock it anyway ('Замечательное приложение… Из минусов — в бесплатной версии можно добавить только 2 привычки', 5★; 'La app es buenísima. Peero, para añadir más de tres hábitos hay que pagar… te ves obligado a pagar para medir más hábitos', 4★); two reviewers propose the fix themselves — 5 free habits (KZ) and 'Quer cobrar? Coloque algumas versões na versão pro. Não faz sentido deixar cadastrar 2 habitos' ('Want to charge? Put some features in the pro version. It makes no sense to allow only 2 habits', BR); 'It would be smarter to create attractive features that persuade the user to pay rather than limiting tracking to a mere two' (TR); the cap is set below the point where the user can experience the product at all — nobody forms a habit portfolio of two, and the cap converts evaluation into rejection",
  "2 → 3 habit cap", "1★-burst", "15; 1★8 · 2★3 · 3★1 · 4★2 · 5★1", "product-rule", "high-priority", "yes",
  ["13015082250","13057771438","13078324005","13139338718","13283076453","13286447070","13441364320","13487320234","13678734774","13679689890","13707712022","13710940338","14007543484","14262833547","14438894096"])
c(43, "§3.3 Paywall too aggressive / 'not really free' — the framing objection distinct from the cap: 'in this case the app completely loses its meaning as free'; 'in app have paid offers, but this is not writes in a Appstore'; 'For all the options you need the paid version'; 'Bitte mehr für kostenlose Nutzer' (the only 5★); one 3★ cannot work out whether the app is paid or free", "monetization",
  "Paywall too aggressive / 'not really free' (11, 6.63%, mean 1.82) — distinct from the cap, this is the framing objection that the app presents as free and is not: 'В данном случае приложение полностью теряет свой смысл как «бесплатное»' ('in this case the app completely loses its meaning as free', RU); 'in app have paid offers, but this is not writes in a Appstore' (UA); 'Para todas las opciones tenes que tener la versión paga' (AR); 'Bitte mehr für kostenlose Nutzer' ('please more for free users', DE — the only 5★ in the theme); a 3★ is pure confusion — the reviewer cannot work out whether the app is paid or free",
  "presented as free, heavily gated", "1★-burst", "11 (6.63%), mean 1.82", "product-rule", "high-priority", "yes",
  ["13078324005","13214738742","13283076453","13286447070","13441364320","13487320234","13679689890","13682739906","13707712022","13864202916","13882804582"])
c(44, "§3.3 'Too basic / too thin' — every one of the four also carries a price objection; no reviewer calls the app too basic without also complaining about paying — it is the value complaint restated, and adding features to answer it would be the wrong read", "contradiction",
  "'Too basic / too thin' (4, 2.41%, mean 1.50): every one of these four also carries a price objection, and no reviewer in the corpus calls the app too basic without also complaining about paying for it — not a feature-depth complaint but the same value complaint restated; adding features to answer it would be the wrong read", "minimal app at premium price", "complaint", "4/4 also price objection", "product-rule", "meaningful", "yes",
  ["13032875149","13625113466","13705764332","13755696898"])
c(45, "§3.3 Cannot find edit / delete / pause — 'how do you pause a habit? how do you edit? I've looked everywhere' (4★); 'I couldn't find a place to edit or remove a habit' (1★); the capability exists — a discoverability defect costing a 1★", "must-have",
  "Cannot find edit / delete / pause (3): 'Como pausa um hábito? como edita? Já procurei por tudo e não consigo editar' ('how do you pause a habit? how do you edit? I've looked everywhere', BR, 4★); 'I couldn't find a place to edit or remove a habit' (IL, 1★); 'только не могу понять как удалить или изменить привычку' (RU, 5★); the capability exists (another reviewer edits within the current month) — a discoverability defect, not a missing feature, and it costs a 1★", "hidden edit/delete/pause", "complaint", "3 (1.81%)", "must-have", "meaningful", "yes",
  ["13324437553","13576406218","13449993538","13085435338"])
c(46, "§3.3 Billing failures — the highest-severity records: charged, premium never unlocked; monthly SKU cannot be purchased, flow charges annually; adjacent accidental subscription with no refund route and 'lifetime' delivered as annual; 5 of the 6 who reached payment report a bad outcome, the sixth paid and complains everything is still gated — every one a 1★-or-downgrade event, three potential store-policy issues", "must-never-break",
  "Billing failures are the highest-severity records: money taken with premium never unlocked (RU, 1★); the monthly SKU cannot be purchased and the flow charges annually instead (RU, 4★); adjacent — an accidental subscription with no route to a refund (MX, 1★) and 'lifetime' delivered as annual (ES, 1★); of the 6 reviewers who reached the payment step anywhere in the corpus, 5 report a bad outcome and the sixth (AR) paid and complains everything is still gated — segment rate 5 of 6 on a tiny denominator, but every single one is a 1★-or-downgrade event and three are potential store-policy issues",
  "purchase flow defects", "1★-burst", "5 of 6 payers", "must-never-break", "meaningful — high severity", "yes",
  ["13670832453","13678734774","14264524351","13705764332","13680381966","13882804582"])
c(47, "§3.3 Name-entry bug (Arabic locale) — 'it won't let me in except with a particular name; I tried its suggestions several times'; 'it won't accept any name'; 2 of the 3 SA-storefront reviews — the app is unusable at step one; promoted because it is a hard-block defect with a locale fingerprint", "must-never-break",
  "Name-entry bug in the Arabic locale (2, mean 1.00): 'مو راضي يدخل الا باسم معين و كذا مره جربت اقتراحاته و لسه بعد' ('it won't let me in except with a particular name; I tried its suggestions several times and still nothing'); 'مو راضي يقبل اي إسم' ('it won't accept any name'); 2 of the 3 Saudi-storefront reviews are this same onboarding blocker — the app is unusable at step one for these users; limited evidence by count, promoted because it is a hard-block defect with an identifiable locale fingerprint",
  "onboarding name field rejects Arabic input", "1★-burst", "2 of 3 SA reviews, mean 1.00", "must-never-break", "limited, promoted — hard block", "yes", ["13511113509","13596102043"])
c(48, "§3.3 Crash / won't open — both 12–13 Jul 2025, days after launch ('It just doesn't open… on iOS 18.5 and on the iOS 26 beta'; 'I don't want to spoil your rating, but please update the app'); no crash report in the subsequent 13 months — resolved", "must-never-break",
  "Crash / won't open (2): 'Вылетает' (RU, 3★) and 'Скачала его, но так и не смогла войти. Оно просто не открывается. Причем проблема как на iOS 18.5, так и на бете IOS 26' ('downloaded it and could never get in… on iOS 18.5 and on the iOS 26 beta', RU, 4★ — 'I don't want to spoil your rating, but please update the app'); both 12–13 July 2025, days after launch; no crash report anywhere in the subsequent 13 months — treat as resolved", "launch-week crash, fixed", "complaint", "2, Jul 2025 only", "must-never-break", "meaningful (historical)", "yes", ["12883902100","12886833369"])
c(49, "§3.3 Scroll-jump + list density — with more than 10 habits the list jumps back to the top after each tick and rows cannot be made smaller (GB, 3★, the most detailed review); this defect only manifests above ~10 habits, i.e. only for paying users — a paid-tier quality problem hiding behind a free-tier cap", "must-never-break",
  "Scroll-jump and list density (1 each, the most detailed review in the corpus, GB, 3★): with more than 10 habits the list jumps back to the top after each tick, forcing a re-scroll for every habit, and rows cannot be made smaller; this defect only manifests above ~10 habits — i.e. only for paying users — a paid-tier quality problem hiding behind a free-tier cap", "list resets scroll on tick", "complaint", "1 review", "must-never-break", "emerging", "yes", ["13032875149"])
c(50, "§3.4 Unmet needs (verbatim table) — non-daily scheduling 4 (4 storefronts, the only true build item); habit end-date 1 (today the workaround destroys data); Skip should preserve the completion ring 1; edit history beyond the current month 1; per-habit/per-day percentages 1; alarm not just a notification 1 ('receives an alarm from the app itself and doesn't need another alarm on the phone'); three of the top five come from one diagnostic review — prioritised because a frequency field also resolves the end-date and skip-ring issues", "data-caveat",
  "Unmet needs ranked: non-daily habit scheduling (day-of-week, x/week, weekly, monthly) 4 — four storefronts, four languages, the same ask, the only true build item; habit end-date (stop a habit without deleting its history) 1 — today the workaround destroys data; Skip should preserve the daily completion ring 1 — users feel they failed a day they completed; edit history beyond the current month 1 (asked politely by a 5★); per-habit and per-day completion percentages 1; an alarm, not just a notification 1 ('assim a pessoa recebe um alarme com o próprio app e não precisa fazer outro alarme no celular'); three of the top five come from a single review (CL, 4★) quoted because it is the most diagnostic record, not because one review is a trend — prioritised because the fix for #1 (a frequency field) also resolves #2 and #3",
  "n/a", "complaint", table("## 3.4 Unmet needs — ranked"), "must-have", "meaningful / emerging", "yes",
  ["13032875149","13176696608","13249103798","13705764332","13085435338","13267951780"])
c(51, "§3.4 Habit end-date + Skip preserving the completion ring + per-habit percentages — deleting a finished habit wipes its history and skipping breaks the ring", "must-never-break",
  "A habit end-date is missing, so deleting a finished habit wipes its history; using Skip breaks the daily completion ring so users feel they failed a day they completed; per-habit and per-day percentages are absent — one diagnostic 4★ from Chile", "no end date; skip breaks ring", "complaint", "1 review (emerging)", "must-never-break", "emerging", "yes", ["13176696608"])
# Part 4
c(52, "Part 4 ratings table (verbatim) — 5★ 133 (substantive 14, phrase-bank 83; contentless praise, else minimalism); 4★ 7 (100% substantive, 'I like it, but…'); 3★ 4 (cap, crash, paid-model confusion); 2★ 3 (the 2-habit cap, all three); 1★ 19 (monetisation and billing, 16 of 19)", "data-caveat",
  "Per band: 5★ 133 (80.12%; substantive 14 = 10.5%; phrase-bank 83 = 62.4%) — contentless praise, else minimalism; 4★ 7 (100% substantive, 0 phrase-bank) — 'I like it, but…', every one names a specific gap; 3★ 4 (100%) — cap, crash, or paid-model confusion; 2★ 3 (100%) — the 2-habit cap, all three; 1★ 19 (100%) — monetisation and billing, 16 of 19", "n/a", "mixed", table("# PART 4 — RATINGS ANALYSIS"), "none", "corpus-level fact", "app-specific", [])
c(53, "§4.1 5★ — 119 of 133 (89.5%) contain no specific content; the 14 substantive split into outcome reports, specific praise, and 5★ reviews carrying a complaint (cap; widget paywalled; more for free users; can't find delete/edit; can't edit prior months; slow + wrong widget in screenshots) — 6 of 14 substantive 5★ contain a negative: not a clean satisfaction signal even after removing the phrase bank", "insight",
  "5★ (n=133): 119 (89.5%) contain no specific content — 83 phrase-bank and 36 equally short non-template ('Все супер', 'Amazing'); the 14 substantive split into genuine outcome reports, specific praise, and five-star reviews carrying a complaint — the cap, the widget paywalled, 'more for free users', can't find delete/edit, can't edit prior months, slow and the wrong widget in screenshots; 6 of the 14 substantive 5★ contain a negative — the 5★ bucket is not a clean satisfaction signal even after the phrase bank is removed", "n/a", "mixed", "119/133 contentless; 6/14 substantive 5★ negative", "none", "corpus-level fact", "yes",
  ["13242409709","12958650866","13152209815","14107277631","12950173104","14338216422","13292317774","14008217420","13941632555","13701569896","14445598360","13710940338","13130702696","13682739906","13449993538","13085435338","13706323164"])
c(54, "§4.2 4★ — all 7 follow the identical shape: sincere praise then one blocking specific ('I don't want to spoil your rating, but please update the app'); five of the seven blockers are monetisation or purchase-flow items (widget paywall → switched to a competitor; can't buy monthly + cap; 3-habit cap)", "insight",
  "4★ (n=7) all follow the identical shape — sincere praise, then one blocking specific: won't open ('I don't want to spoil your rating, but please update the app'), widget paywalled → switched to a competitor, scheduling/end-date/percentages/skip/data loss, an alarm request, can't pause or edit, can't buy monthly + cap, the 3-habit cap; five of the seven blockers are monetisation or purchase-flow items", "n/a", "complaint", "7; 5/7 monetisation", "product-rule", "corpus-level fact", "yes",
  ["12886833369","13081229555","13176696608","13267951780","13324437553","13678734774","14007543484"])
c(55, "§4.3 3★ — crashes; glitches + scroll-jump + thin functionality + 'not really worth the money'; cannot determine whether the app is free or paid; 3-habit max", "insight",
  "3★ (n=4): crashes (RU); glitches, scroll-jump, thin functionality and 'not really worth the money' (GB); cannot determine whether the app is free or paid (TR); 3-habit maximum (RU)", "n/a", "complaint", "4", "none", "corpus-level fact", "yes", ["12883902100","13032875149","13214738742","14262833547"])
c(56, "§4.4 2★ — all three are the habit cap and nothing else; one explicitly says the price is fine ('Elle est payante on peut mettre que 2 habitude sans payer mais ce n'est pas cher') and still rates 2★ — the cleanest possible evidence that the cap, not the price, produces the low ratings", "contradiction",
  "2★ (n=3): all three are the habit cap and nothing else, and one explicitly says the price is fine — 'Elle est payante on peut mettre que 2 habitude sans payer mais ce n'est pas cher' ('It's paid, you can only add 2 habits without paying, but it's not expensive', FR) — and still rates 2★: the cleanest possible evidence that the cap, not the price, is what produces the low ratings", "2-habit cap at a fair price", "complaint", "3/3 cap; 1 says price fine", "product-rule", "corpus-level fact", "yes", ["13283076453","13441364320","13487320234"])
c(57, "§4.5 1★ table (verbatim) — cap 8 (42.1%), price/value 4 (21.1%), purchase-flow failure 4 (21.1%), undisclosed IAP 1, software defect 3 (15.8%); 16 of 19 monetisation/billing; the most geographically dispersed group (11 storefronts: AR 3 · RU 5 · SA 2 · UA 2 · ES, IL, IT, JP, KZ, MX, TR 1) — not local; one-star rate rose from 5.1% of 2025H2 reviews to 42.9% of 2026 reviews (12 of 28)", "timeline",
  "1★ (n=19): free habit cap 8 (42.1%); price/value 4 (21.1%); purchase-flow failure 4 (21.1% — charged with nothing unlocked, refund refused, no trial then annual charge, mis-sold lifetime); undisclosed IAP on the store page 1; software defect 3 (15.8% — name-entry ×2, can't edit/remove); 16 of 19 (84.2%) monetisation or billing; the most geographically dispersed group — AR 3 · RU 5 · SA 2 · UA 2 · ES 1 · IL 1 · IT 1 · JP 1 · KZ 1 · MX 1 · TR 1, 11 storefronts, so the complaint is not local; date profile: 7 of 19 in 2025H2 and 12 in 2026 — the one-star rate rose from 5.1% of 2025H2 reviews to 42.9% of 2026 reviews (12 of 28)",
  "n/a", "1★-burst", table("## 4.5 One star"), "product-rule", "high", "yes",
  ["13015082250","13057771438","13078324005","13139338718","13286447070","13679689890","13707712022","14438894096","13625113466","13705764332","13755696898","13882804582","13670832453","14264524351","13680381966","13864202916","13511113509","13596102043","13576406218"])
# Part 5
c(58, "§5.1 Who is identifiable as a payer (verbatim table) — 6 (3.61%): annual with no trial → regret; charged, premium did not unlock; accidental purchase, refund refused; mis-sold plan term; still gated after paying; cannot buy the monthly SKU; 5 of 6 are 1★ and not one describes a satisfactory purchase; four are distinct reproducible purchase-flow defects — facts about the flow, not sentiment", "must-never-break",
  "Six reviewers (3.61%) reach the payment step: AR 1★ 'I paid the anual subscription' — regret, no trial, product not as expected; RU 1★ 'Списаны деньги за подписку' — charged, premium did not unlock; MX 1★ 'quise cancelar suscripción… no puedo recuperar el dinero' — accidental purchase, refund refused; ES 1★ 'Te dicen que es de por vida el plan y es solo para un año' — mis-sold plan term; AR 1★ 'Para todas las opciones tenes que tener la versión paga' — still gated after paying; RU 4★ 'не могу приобрести про версию на месяц, выдает оплату за год' — cannot buy the SKU they want; 5 of 6 are 1★ and not one describes a satisfactory purchase (the one happy widget user does not state they paid); review corpora over-sample unhappy payers so this is not a satisfaction rate, but four of the six are distinct, reproducible purchase-flow defects — a failed entitlement, an unpurchasable SKU, an ambiguous plan label and a missing trial — facts about the flow, not sentiment",
  "broken purchase flow", "1★-burst", table("## 5.1 Who is identifiable as a payer"), "must-never-break", "high severity, n=6", "yes",
  ["13680381966","13670832453","14264524351","13705764332","13882804582","13678734774","14107277631"])
c(59, "§5.2 What triggers the desire to upgrade — only two features are ever named: more habits (all 15 cap reviews; 'at least 5 free habit entry') and the widget (downloaded solely for it; the happiest reviewer uses it; wants the one in the screenshots); nobody mentions iCloud sync, colour themes or statistics as a reason to pay though the first two are advertised paid features", "monetization",
  "Only two features are ever named as worth paying for: more habits (all 15 cap reviews, with the users' own anchor 'at least 5 free habit entry') and the widget (one downloaded solely for it, one wanted it, the happiest reviewer in the corpus uses it, one wants the widget from the screenshots); no reviewer anywhere mentions iCloud sync, colour themes or statistics as a reason to pay — even though the first two are advertised paid features", "unlimited habits + widget as the paid layer", "purchase-driver", "15 + 4", "research", "meaningful", "yes",
  ["13139338718","13081229555","13130702696","14107277631","13706323164"])
c(60, "§5.3 Upgrade barriers in order of evidence weight (verbatim table) — cap too low to evaluate (15: you cannot experience a habit tracker with 2–3 habits so nothing builds intent to pay); no trial (2: 'before buying something you should be able to try it'); perceived value gap (5); purchase-flow defects (4); free alternatives give away the paywalled feature (1, a completed switch); confusion about whether it's paid (1)", "blocked-conversion" if False else "monetization",
  "Upgrade barriers by evidence weight: the cap is too low to evaluate the product (15 — you cannot experience a habit tracker with 2–3 habits, so nothing builds the intent to pay); no trial (2 — 'перед тим як щось придбати треба ж спробувати це', 'before buying something you should be able to try it'); perceived value gap at the price point (5 — price × thinness, not price alone); purchase-flow defects (4 — the user tried to give money and the flow failed); free alternatives give away the paywalled feature (1 — a documented, completed switch); confusion about whether it's paid at all (1 — a 3★ who never resolved it)",
  "cap below evaluation threshold; no trial; broken flow", "blocked-conversion", table("## 5.3 Upgrade barriers"), "product-rule", "high", "yes",
  ["13680381966","13679689890","13081229555","13214738742"])
c(61, "§5.4 Refund, cancellation and store-policy exposure — accidental subscription with no money back (normally Apple-side, the reviewer blames the app); a 'lifetime' plan that lasted a year on a shelf listing both Lifetime and Yearly — the class of complaint that attracts store review; 'in app have paid offers, but this is not writes in a Appstore' — disclosure not visible at the decision point; paid with no entitlement — 'unambiguously a bug and should be treated as a P0 incident, not a review'", "must-never-break",
  "Refund, cancellation and store-policy exposure: an accidental subscription the user could not recover money from (MX, 1★ — normally an Apple-side flow, but the reviewer blames the app); a 'lifetime' plan that lasted a year (ES, 1★) on a shelf listing both a $59.99 Lifetime and a $44.99 Yearly — whether mis-selling or misreading, ambiguous enough to reliably generate this complaint, the class that attracts store review; 'in app have paid offers, but this is not writes in a Appstore' (UA, 1★) — the US listing does disclose IAP, so either the storefront presentation differs or the disclosure is not visible at the decision point; paid with no entitlement (RU, 1★) — 'unambiguously a bug and should be treated as a P0 incident, not a review'",
  "ambiguous SKUs; entitlement failure; disclosure not seen", "1★-burst", "4 reviews", "must-never-break", "high severity", "yes",
  ["14264524351","13705764332","13864202916","13670832453"])
c(62, "§5.5 What the corpus does and does not support — supported: the cap is the dominant blocker to usage and purchase; the widget is the most wanted paid feature; the purchase flow has at least four defects; price objections are value objections; not claimed: any conversion, ARPU, refund or trial-start rate, or relative SKU performance — the corpus cannot see anyone who paid and was quietly happy", "data-caveat",
  "Supported: the cap is the dominant blocker to both usage and purchase; the widget is the most wanted paid feature; the purchase flow has at least four specific defects; price objections are value objections; not supported and not claimed: any conversion rate, ARPU, refund rate, trial-start rate, or the relative performance of the four SKUs — the corpus cannot see anyone who paid and was quietly happy", "n/a", "none", "report gives none (scope statement)", "none", "method", "yes", [])

with open("Tools/prd_ledger/30/cards.jsonl", "a") as f:
    for k in cards: f.write(json.dumps(k, ensure_ascii=False) + "\n")
print(len(cards), "cards appended")
