# -*- coding: utf-8 -*-
"""Stage 3 merge for report 64 (Critique AI: Habit Tracker, With Bytes LLC)."""
import json
C = {x["id"]: x for x in json.load(open("Tools/prd_ledger/canonical.json"))}
def ext(cid, text):
    if text not in C[cid]["statement"]: C[cid]["statement"] += text
def add(cid, section, title, statement):
    if cid in C: return
    C[cid] = dict(id=cid, title=title, statement=statement, section=section, cards=[], reports=[], merged_from=[])

add("C279", "must-never-break", "An AI analysis must consume its input — reject empty, silent or black input instead of returning a confident score",
    "Report 64 (Critique AI, 419 reviews): four independent reviewers in four storefronts over ten months ran the same adversarial test and got a confident result — a black photo returned 'things that were good and stuff to work on' (paid $25), a voice coach toggled off 'without saying a word' gave the same generic feedback (paid $50: 'It doesn't actually listen'), silence into a speaking exercise scored 79 ($12.99/mo), and 'No matter what photo you upload, it gives the same results' — 'a claim that at least one analysis path does not consume its input', the highest-severity product finding in the report; three of the four had paid and publicly concluded the product was fake; AI_QUALITY 8 (1.91%, mean 2.00), 7 of 69 users who got in (10.1%), 3 of 13 payers, 7 of 8 from Feb 2026 as the user base grew enough to audit the headline feature; F2: reject empty/null input in every AI path. Related: [[C056]], [[C148]] (the paid product must deliver what the ads demonstrate), [[C267]].")
add("C280", "must-never-break", "An app-blocking focus mode must always unlock when its condition is met, never lock apps permanently, never override OS Screen Time, and never depend on a notification the OS can suppress",
    "Report 64 (Critique AI): focus mode — block selected apps, earn them back for ~15 min by doing push-ups or meditation — is 'the most distinctive thing in the corpus and it is also the most broken': 10 mentions (2.39%, mean 3.40), 6 of them failures (1.43%, mean 3.50) — the unlock exercise 'takes me no where', apps stay locked after 10 push-ups so the user turns the mode off 'which gets rid of the point', apps blocked permanently overriding Screen Time permissions (paid $25), no in-between state, and a 5★ defender supplies the root cause: 'you can't unlock apps in focus mode in silent mode because you cant receive the notification'; four of the six are 4★/5★ advocates; one reviewer installed specifically for it and never reached it; Clearspace named as the free substitute; F3. Related: [[C066]] (focus timer), [[C272]] (timers survive backgrounding).")
add("C281", "do", "Brief every creator and acquisition channel to state the price — an audience told 'it's free' converts marketing spend into permanent 1★",
    "Report 64 (Critique AI): 42 reviews (10.02%, mean 2.38) name a creator, YouTube, TikTok or a friend as the reason they installed (13 name the founder-creator); 30 (7.16%, mean 1.23 — the lowest-rated theme after 'scam', 25 of 30 at 1★) believed the app was free: 'Ich wurde von nem YouTuber angelockt das es kostenlos sei aber es ist so ein scam' (de); 'advertised on a YouTubers channel and he never mentioned anything about a paid subscription' (us); 'Say that in the videos. Just disrespectful.' (co) — 'the highest-leverage finding in the report that costs nothing to fix': the product is not mispriced, it is mis-expected, and every such reviewer 'was acquired at full marketing cost and converted into a permanent 1★'; the only major theme with no downward movement across 17 months (6.5% / 8.8% / 5.6% / 7.8%); M2, and with price-before-quiz (M1) it addresses 53 reviews (12.65%) at mean 1.28. Related: [[C058]] (discovery channels), [[C218]] (listing copy stays true), [[C181]] (paid-only says so up front).")
add("C282", "must-have", "A generated plan belongs to the user — it persists, every assigned task can be deleted, declined and reordered, and it is built around the user's fixed commitments",
    "Report 64 (Critique AI): plan rigidity is the top non-price complaint among users who got in — 9 (2.15% global, 13.0% of the 69 inside, mean 2.00) — in five mechanics each named by at least two reviewers: the plan regenerates weekly and own tasks must be re-entered every week; assigned tasks cannot be deleted or declined; tasks cannot be moved; the plan ignores real constraints ('It just says leg day on Wednesday… What if you don't train on Wednesday?'; a gym → home setting that will not change; too advanced for a 12-year-old); content reads as generic filler ('more like XP grabs'; 'all it does is organize workouts I had already organized myself'); three of the eight feature requests are the same ask — build the schedule around school, sport and work; R1, R2; complaint order after price among users: plan rigidity → AI quality → focus failures, 'the list that governs retention rather than acquisition'. Related: [[C203]] (user authors their routine first), [[C266]] (generated programme escalates on completion), [[C073]] (reorder and edit free).")
add("C283", "dont", "Never sell by telling the user they are deficient — an onboarding score that invents a shortfall reads as manipulation",
    "Report 64 (Critique AI): TRUST_MANIP 6 (1.43%, mean 1.17): 'tells you that you are 27% less confident than the average even if you are 100% confident in your answers. I dislike companies that lie especially to manipulate others insecurities' (us); independently, in Hebrew: 'I love myself and have confidence, and the app decided I don't have much confidence and I need to pay monthly to improve it' (il) — on an audience that is substantially 12–15 years old; R6: review the onboarding score's framing. Related: [[C095]] (neutral tone), [[C103]] (minors are a sensitive surface), [[C111]] (no long quiz before the price).")

ext("C147", " Report 64 (Critique AI): the purest case in the ledger — no free tier, 0 of 419 report free ongoing use; 166 (39.62%, mean 1.52) blocked at the paywall; 82.58% never got in (mean 2.35) against 3.87 for those who did (+1.52 stars); 95 (22.67%) propose a way in (free tier 66, trial 26, tiers 21, ads 12); strip out money and 126 reviews remain at 4.41; the 3★ band is 'I want to buy this and cannot' (PAY_PRICE 45.7%, PAY_SCAM zero) — 'If a free or cheaper tier ships, this band converts first'; M3: tracking + XP / leaderboard free, AI analysis, focus mode and coach paid; 'Nobody defends the price from outside the paywall — which is the whole argument for a free tier in one sentence'.")
ext("C182", " Report 64 (Critique AI): only three first-person purchase accounts in 419 — a $2/month exit discount, 75% off annual, and creator trust; 'No reviewer in this corpus says they paid because of a specific feature' — 'sold on price anchoring and creator trust, not on value demonstration'; 13 self-stated payers average 1.85, 12 of 13 report a defect or shortfall, 1 of 13 unreservedly satisfied.")
ext("C002", " Report 64 (Critique AI): 69.93% of 419 reviews are about money (mean 1.81) while the 126 that are not average 4.41; the 1★ band is 66.7% blocked at the paywall and only 5.6% from inside — 'an acquisition problem, not a quality problem'.")
ext("C145", " Report 64 (Critique AI): a paywall that reads as uncloseable — PAY_SOFTLOCK 39 (9.31%, mean 1.72) across 20 storefronts and 17 months ('no cancel button, no ignore button, no X button. NOTHING!'; 'I cannot press the don't pay now button even if I press it 20 times'; returns after relaunch) — reconciled by one German reviewer: the X 'is invisible, tiny and impossible to find'; two trapped users rated 4★ while asking for help; the rate fell 16.9% → 6.8% after launch but 7 reports remain in the latest quarter; F1: large, visible, reachable on first paint, verified on small screens and after force-relaunch.")
ext("C110", " Report 64 (Critique AI): with no free tier the 'continue' path is only a dismiss control, and a tenth of the corpus cannot find it — 'you are stuck In the buy screen. You literally can't do anything but just stare at it'.")
ext("C111", " Report 64 (Critique AI): PAY_QUIZWALL 23 (5.49%, mean 1.35) — a long survey, a physique photo and an account, then the price: 'why the need to do a survey if it isn't free? couldn't it be mentioned before the survey?'; rose from 3.2% to 8.7% in the latest quarter; M1: disclose the price before the quiz — 'Zero engineering cost, zero revenue cost'.")
ext("C150", " Report 64 (Critique AI): 'it got me to rate it before it charged me money so I gave it a 5 thinking that it was free because I am 13 and broke' — the likely mechanism behind a −2.09-star gap (written 2.589 on 419 vs public 4.68 on 18,785, ≥ 1.84 in every storefront), with 57 reviews (13.60%, mean 4.54) rated without product experience; research: does the prompt fire before the paywall — 'it changes how every dashboard in the business should be read'.")
ext("C180", " Report 64 (Critique AI): an exit-intent 'one-time offer' after dismissing the first paywall — 80% / 75% off, '$2/month' — splits 5×1★ / 3×5★ (PAY_DISCOUNT 9, 2.15%, mean 2.44): it produced the only clean purchase-trigger record in 419 reviews and it reads as 'Preis 80% Rabatt, wenn man Zahlung abbricht. Unglaubwürdig.'; a second paywall 8 (1.91%, mean 1.25); M7: at minimum show the billed total on the discounted offer.")
ext("C113", " Report 64 (Critique AI): the same year quoted as $40, £40, £24, 40–45€, $39.99, $45, $50, $60, $100, $192, $200 and ₦69,900, plus weekly and monthly SKUs and an exit discount (£2.08/mo advertised, £24/yr charged) — PAY_SCAM 21 (5.01%, mean 1.05).")
ext("C109", " Report 64 (Critique AI): a 3-day trial that requires card details up front, charges the full year on expiry without warning ('it didn't let me know that it was over so it took my money'), cannot be cancelled in-app, and is not reached at all by others — PAY_TRIAL 26 (6.21%, mean 1.58), persistent across 17 months; 3 days cannot test a habit product ('Getting into stuff like this will take at least a month to stick'); M4: 14 days, no card.")
ext("C063", " Report 64 (Critique AI): 'at least bring back the free trial' — the one review implying a trial was removed; 10 reviewers found a 3-day trial while 26 say there is none (possibly A/B-varied).")
ext("C029", " Report 64 (Critique AI): 'On the website it said cancel anytime but it immediately billed me'; 'They say that they give a three day trial but charge you for the full year upfront'; reinstall charged again — PAY_BILLING 8 (1.91%, mean 1.50), 6 of 13 self-stated payers.")
ext("C163", " Report 64 (Critique AI): annual-upfront is an upgrade barrier and the billing-dispute class — three payers expected trial or monthly flexibility and got a full-year charge; 'Almeno dividessero il prezzo in mesi'; M5: a monthly or one-time SKU visible before the annual.")
ext("C003", " Report 64 (Critique AI): 'you might as well just sell your app instead of using subscriptions' — PAY_TIERS 21 (5.01%, mean 1.48) ask for tiers, one-off, monthly split or a teen tier; no lifetime SKU is visible.")
ext("C033", " Report 64 (Critique AI): paid but still gated — the paywall popup persists after purchase (age 15), restore fails ('I can't restore my purchase so basically I can't do anything now'), reinstall demands payment again, and a second device refuses login ('you have to pay for each device') — 4 of 13 payers (30.8%), 3 of 13 fully gated (23.1%) — 'converts a completed sale into a 1★ and a fraud accusation'; F4.")
ext("C065", " Report 64 (Critique AI): 13 self-stated payers average 1.85 (10 at 1★) against 3.87 for users who got in without stating payment — access more than doubles satisfaction and stating that you paid halves it again; 12 of 13 report a defect or shortfall.")
ext("C036", " Report 64 (Critique AI): three 1★ reviews are unanswered, resolvable tickets — a parent's three emails on a login issue got one 'please clarify' then silence ('My son was so excited to use this app, but now it's just taking up space'); billing; a frozen paid app — F5: 'low rate, 100% conversion to 1★'.")
ext("C103", " Report 64 (Critique AI): the creator audience is young — 20 reviews (4.77%, mean 1.90) are minors or argue for them (ages 12–15 self-stated; 'everyone on it seems to be like 12-15 years old'), 13 of 20 in the US; a ~$40/yr annual-upfront plan needs a payment instrument they do not control; a parent bought it for a 12-year-old and asked for a refund; the most-upvoted review (9 votes) asks for an adult tier and a free teen tier; research: what share of installs are under 13 — 'a compliance question as much as a pricing one'.")
ext("C238", " Report 64 (Critique AI): 12 reviewers (2.86%) volunteer ads as the price of access on a teen-heavy app with no free tier; one paying adult objects ('I'd rather pay than see ads'); a free teen tier is the most-upvoted ask.")
ext("C082", " Report 64 (Critique AI): with no free tier, 12 (2.86%, mean 1.58) propose an ad-supported way in, one proposes an ad-supported base of a three-tier ladder; a 2★ defends the price as the alternative to 'annoying ads'.")
ext("C127", " Report 64 (Critique AI): a subscriber reports seeing ads while paying £40/yr (4★) — 'the worst of both models'; F6, verify before acting.")
ext("C092", " Report 64 (Critique AI): M6 — price for the actual audience: an age- or region-tiered price as an experiment on a teen-heavy creator audience; volume markets ask for free rather than cheaper (20.0% vs 14.3%).")
ext("C056", " Report 64 (Critique AI): the AI is the brand ('AI Coach' in the name) and 'among people who used it, the weakest part' — 19 AI reviews at mean 2.21 vs outcomes 4.92 and gamification 4.00; a paying 5★ splits the product: 'for the AI plan? No. For speaking coaching and challenges to improve overall? Yes'; the substitute named for the AI half is ChatGPT / Grok / Gemini.")
ext("C267", " Report 64 (Critique AI): TRUST_AISLOP 4 (0.95%, mean 1.50) accuse the app itself of being AI-generated, one from inside after paying; the community page read as 'probably fake'.")
ext("C148", " Report 64 (Critique AI): '$50… expecting actual coaching' — 'all it does is organize workouts I had already organized myself'; 'Temu quality'; an AI that 'points out what's supposedly wrong with you without offering any solutions' (R3: give the AI something to say after the critique).")
ext("C085", " Report 64 (Critique AI): 'don't put your email in this app' — two German reviewers independently, three months apart; refusal to give card or personal details before seeing the product; a photo demanded before the price; German reviews 28.6% scam and 14.3% privacy (n=14) vs 5.01% / 1.19% globally.")
ext("C005", " Report 64 (Critique AI): ALT_TOOL 13 (3.10%, mean 1.92) — ChatGPT, Grok, Gemini for the AI half; Apple Notes, Google Sheets, Google Calendar for the tracker; Clearspace for focus mode; Duolingo as the freemium model to copy — 'Nobody names a competing self-improvement app'.")
ext("C214", " Report 64 (Critique AI): 'I don't think any one is gonna pay 40$ just to check off a list'; 'I lost 40 dollars on something I could've just done on the notes app'.")
ext("C024", " Report 64 (Critique AI): XP, quests and leaderboards are 'unambiguously liked' (8, 1.91%, mean 4.00) and proposed as the free hook ('keep the workout and XP/leaderboard free'), with one sharp dissent that generated tasks 'seem more like XP grabs than anything else'.")
ext("C134", " Report 64 (Critique AI): R4 — lead with what works: reported physical outcomes are the highest-rated theme (12, mean 4.92: 'It helped me lost 50 pound'; 'i'm in shape now because of this app') and social / confidence outcomes 4.75 ('you go from not talking to anyone to talking to everyone'), against 2.17 for the AI layer the name sells.")
ext("C067", " Report 64 (Critique AI): fitness outcomes carry the corpus's highest mean (12, 4.92); requests for a calorie tracker beside the food scanner, Apple Health and Hevy sync, exercise animations and bodyweight / muscle-group tracking; outcomes run 5× higher in volume markets (11.4% vs 2.2%).")
ext("C021", " Report 64 (Critique AI): Apple Health and Hevy sync requested with exercise animations (us, 3★).")
ext("C185", " Report 64 (Critique AI): the onboarding analysis works as a hook — a reviewer praises the personalised analysis then refuses to pay (PERSONALIZE 5, mean 4.40); a physique scan and a projected score are the free teaser before the wall.")
ext("C094", " Report 64 (Critique AI): 11 contradicting reviews, ten at 5★, three explicitly using the star as a message about price ('im only doing 5 star just for you to take the payment subscription away'; 'I only gave 5 stars so you can see this'; 'i'm rating this 5 stars because i support your content bro but just please, please lower that price') — 39.8% of the 5★ band is not a product endorsement.")
ext("C231", " Report 64 (Critique AI): written vs public gap −1.84 to −2.92 in every storefront with ≥ 5 reviews (US 180 @ 2.66 vs 9,557 @ 4.73); high-spend ('rich') markets carry the friction (2.53, 47.9% 1★) against volume markets (2.91, 34.3%) — the paywall binds where the creator's audience is; the US argues the amount (price 30.0% > hardwall 29.4%) and is where people get in (22.2% vs 11.5%), while GB argues the wall's existence (40.0% vs 20.0%); the app ranks worst in the US (48th) where 43% of written reviews come from.")
ext("C062", " Report 64 (Critique AI): the visible real user base is overwhelmingly American — all but two price defenders and 9 of 11 focus-mode mentions are US.")
ext("C184", " Report 64 (Critique AI): 'the quiz questions are clearly directed toward men, and didn't have a nothing option' (au, 3★, one review) — consistent with the male-coded framing throughout ('looksmax', physique, 'made me more into a man').")
ext("C145", " Report 64 (Critique AI): 'Doesnt work on smaller phones' and 'I can't scroll in the app, which means I can't choose the correct options' — defects that exclude rather than annoy (R7).")
ext("C031", " Report 64 (Critique AI): the one repeated defect is a freeze during AI plan generation (May 2025 and Apr 2026, independently), then on every launch for one reviewer; crashes on every AI review and on the coach tab 'after the update' ('I expect better from an app which costs like 30 dollars').")
ext("C141", " Report 64 (Critique AI): the app 'refuses to work on iPad' for a payer who also could not log in on a second device.")
ext("C202", " Report 64 (Critique AI): a community feed is 'priceless' to one payer, 'a probably fake community page' to another, and over-moderated to a third (R5: loosen comment moderation); only paying reviewers describe it.")
ext("C172", " Report 64 (Critique AI): a notes space requested (ch, 5★).")
ext("C064", " Report 64 (Critique AI): PAY_PRICE 105 (25.06%, mean 1.94) against 11 defenders (2.63%, mean 4.55: '$40 bucks a year is a steal. A human trainer could cost as much as $40 a week!'; 'way cheaper than others'); PAY_PRICE jumped 19.2% → 34.0% in the latest quarter while defect themes stayed flat and defenders rose 0.8% → 8.7% — 'Contested pricing became a topic on the listing itself'; a price rise, a trial withdrawal or an audience widening past willingness-to-pay cannot be separated without pricing history.")
ext("C212", " Report 64 (Critique AI): a parent bought for a 12-year-old found it too advanced and asked for a refund in a review; 'would not let me have my money back' after a 'cancel anytime' promise.")
ext("C166", " Report 64 (Critique AI): a paying reviewer's verdict splits the product — the AI plan is not worth it, the coaching and challenges are.")

M = {
 "R64-001":["C281"], "R64-002":["C231"], "R64-003":["C150","C231","C094"], "R64-004":["C147","C065","C002"], "R64-005":["C147","C182","C002"],
 "R64-006":["C145","C110"], "R64-007":["C281","C218","C058"], "R64-008":["C111","C085"], "R64-009":["C147","C238","C082","C024"], "R64-010":["C082","C127","C238"],
 "R64-011":["C103","C092","C238"], "R64-012":["C279","C056","C148"], "R64-013":["C148","C279"], "R64-014":["C280","C066"], "R64-015":["C024","C134"],
 "R64-016":["C134","C067"], "R64-017":["C185"], "R64-018":["C282","C203","C266","C073"], "R64-019":["C056","C166","C282"], "R64-020":["C147","C063"],
 "R64-021":["C113","C177","C109"], "R64-022":["C064","C147"], "R64-023":["C109","C063"], "R64-024":["C113","C085"], "R64-025":["C283","C103"],
 "R64-026":["C085","C111"], "R64-027":["C267","C202"], "R64-028":["C005","C214","C056","C280"], "R64-029":["C031","C145","C171","C141"], "R64-030":["C036"],
 "R64-031":["C002","C147"], "R64-032":["C094","C127","C282","C021"], "R64-033":["C094","C231"], "R64-034":["C180","C113"], "R64-035":["C033","C065","C141"],
 "R64-036":["C033","C029","C163","C212","C148","C036"], "R64-037":["C182","C180"], "R64-038":["C003","C163","C085","C005"], "R64-039":["C064","C147"],
 "R64-040":["C067","C021","C172","C202","C282","C279","C280"], "R64-041":["C231","C062","C103"], "R64-042":["C231","C062"], "R64-043":["C231","C150"], "R64-044":["C184"],
 "R64-045":["C064","C145","C063","C231"], "R64-046":["C281","C279","C280"], "R64-047":["C281","C111","C145","C279","C147"], "R64-048":["C280"],
 "R64-049":["C094"], "R64-050":["C033","C036","C035"], "R64-051":["C281","C111","C218"], "R64-052":["C231","C180"], "R64-053":["C094","C150"],
}
cards = [json.loads(l) for l in open("Tools/prd_ledger/64/cards.jsonl") if l.strip()]
ids = {c["id"] for c in cards}
for k, v in M.items():
    assert k in ids, k
    for cid in v: assert cid in C and not C[cid].get("merged_into"), (k, cid)
for c in cards:
    c["canonical"] = M.get(c["id"], [])
    for cid in c["canonical"]:
        if c["id"] not in C[cid]["cards"]: C[cid]["cards"].append(c["id"])
        if c["report"] not in C[cid]["reports"]: C[cid]["reports"].append(c["report"])
with open("Tools/prd_ledger/64/cards.jsonl", "w") as f:
    for c in cards: f.write(json.dumps(c, ensure_ascii=False) + "\n")
json.dump(list(C.values()), open("Tools/prd_ledger/canonical.json", "w"), indent=1, ensure_ascii=False)
null = [c["id"] for c in cards if not c["canonical"]]
print(f"{len(C)} canonical; {len(cards)-len(null)} attached; {len(null)} unattached: {null}")
print("unbacked:", [x["id"] for x in C.values() if "Report 64" in x["statement"] and not any(k.startswith("R64-") for k in x["cards"])])
