# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/84")
from _lib import c, table, save

c(1, "header lines 1-6; §2.1; §2.1 table (verbatim); §2.2 table (verbatim); §2.2", "positioning", "Habit Tracker - HabitGrid (App Store ID 6746483721, com.edvarderos.habitGrid) by Edvard Adam Eros (copyright THE GREAT DIGITAL ADVENTURE SRL, Romania), released 2025-06-04, current 1.0.19 (2026-09-02, 'Custom week start'), Free with hasInAppPurchases: false, iPhone / Mac / Vision, no Watch, listing says English only — a free single-purpose tracker whose main surface is a coloured tile grid of completions ('remind me of github'), statistics by week / month / year, home-screen interactive widgets, reminders, notes, marking past days, categories (1.0.14), archiving (1.0.13), goals (1.0.15), weekly/monthly streaks (1.0.16); the developer links Google Play, Discord, a subreddit and socials; one other app (Teleprompter Kit). Feature inventory (verbatim): " + table("## 2.1 What the product is", 0) + " || listing (verbatim): " + table("## 2.2 What the store listing says", 0), "entirely free, no ads, no IAP", "praise", "86 reviews, 28 storefronts, 9 languages, 2025-06-08 → 2026-09-02 (451 days), mean 4.930★; 81 5★ (94.19%), 0 1–2★; 55 codes; 405 assignments", "none", "header", "app-specific", ["13733717410", "13546859530", "12749498855"], "", "")

c(2, "How to read this; Nine warnings 1, 2, 6, 7, 8; §1.1 table (verbatim); §1.2 table (verbatim); §1.3 table (verbatim); §1.4; §1.5 table (verbatim); §1.6", "data-caveat", "Method and limits: every one of 86 reviews read in date order in the original language (ru 39, es 6, fr 4, pt/de/zh/ar/vi 1), 55 codes in 9 families (52 hand, 3 mechanical), 17 unions, 405 assignments, 35 checks (three real errors caught), 18 absence tests; no duplicates, no repeat authors, 1 edited; no storefront reaches 50 (Russia 37) — no standalone country claim; one review is 1.16% (already 'Meaningful'), five reach 'High-priority' — read counts and CIs, not labels; 28 reviews (32.56%) under 60 characters, all 5★; no version field but an 18-release history exists so eras use release dates (timing, not cause). Bands (verbatim): " + table("## 1.5 Signal thresholds", 0), "n/a", "mixed", "86/86 read; 55 codes; 35 checks; 18 absence tests", "none", "method", "generalisable", ["12749498855"], "", "")

c(3, "Warning 9; §1.3 selection bias table (verbatim)", "data-caveat", "The text corpus matches the public rating: ratings-weighted public mean 4.939★ over 311 ratings vs corpus 4.930★ — gap +0.009★; the corpus is 27.65% of the rating base; the US histogram's single 1★ (43 ratings) has no text anywhere; 'the corpus is a complete census of text reviews and, on rating, is not distinguishable from the silent majority' (verbatim): " + table("### Selection bias, quantified", 0), "n/a", "mixed", "gap +0.009★; 311 ratings; 86 text (27.65%)", "none", "High-priority", "generalisable", ["12749498855"], "", "the smallest corpus-to-public gap in the series")

c(4, "Warning 4; §7.3", "data-caveat", "Reviews were solicited in-app: release 1.0.1 (2025-07-03) added 'in-app review' and 1.0.6 (2025-08-21) 'Love the app? Now it's easier to leave a review'; 83 of 86 reviews postdate the first prompt; prompted and unprompted cannot be separated; §7.3 shows the review rate did not rise after either prompt release — it rose after localisation.", "in-app review prompt from month one", "5★-burst", "83 of 86 post-prompt; rate 3.04/30 days after 1.0.6", "none", "High-priority", "generalisable", ["12749498855"], "", "")

c(5, "Warning 5; §2.6; §7.6", "data-caveat", "Early reviews cluster on the developer's home region: six of the 13 reviews in the first five months come from the Romanian and Hungarian storefronts, the copyright holder is a Romanian SRL, and two Romanian-storefront authors carry the developer's surname ('Öcsi Erős', 'Mihaela Eros') — disclosed, not adjudicated; all six retained; removing them moves the mean 4.930 → 4.925★; 'a shared surname is not evidence of a relationship'.", "n/a", "mixed", "6 of first 13 from ro/hu; 2 surname matches; mean −0.005★ without them", "none", "limited evidence", "app-specific", ["12886063451", "13282170850"], "", "")

c(6, "§0.1; §0.1 table (verbatim); §3.2", "monetization", "People chose this app because it is free, has no ads and does not paywall habits: U:free_model_any 39 of 86 (45.35%, CI 35.3–55.8%, 4.97★) (verbatim): " + table("## 0.1 People chose this app", 0) + " — reviewers had already met paywalls elsewhere: 'most of them only let you make around 4 habits before tealling you to pay. This one let me make as many as I wanted (10 so far)!'; 'almost all of them need some sort of payment… rivalling paid habit trackers'; 'Why anyone would be pay a monthly sub for an app like habitkit, which offers no benefit over this app, I haven't a clue'; 'I sat down to write a similar app because the alternatives have paid subscriptions. GPT suggested I look at this app; I downloaded it and immediately closed Xcode' (ru); U:paywall_contrast 16 (18.60%), all 5★.", "free, no ads, unlimited habits, no IAP", "purchase-driver", "free_model_any 39 / 45.35% / 4.97★; MODEL_FREE 30; NO_ADS 12; NO_PAYWALL 7; VS_PAID 7; UNLIMITED 3; paywall_contrast 16 / 18.60%", "build-free", "High-priority", "generalisable", ["13903380759", "13469159788", "13546859530", "14227392787", "14458611566"], "'free with no habit cap' is itself the positioning against the category", "")

c(7, "§0.2; §3.3; §3.4", "insight", "What they value in the product: simplicity, then the grid — U:simplicity 40 (46.51%, CI 36.3–57.0%; PRAISE_EASE 27, PRAISE_SIMPLE 20): 'Everything you need, and nothing more… no fancy or overly complicated features'; 'Nothing superfluous, aesthetic, beautiful, intuitive' (ru); 'without extra noise'; U:visual_progress 16 (18.60%; PRAISE_VISUAL 10, PRAISE_STATS_VIEWS 9): 'remind me of github, very beautiful'; 'progress by day, week, for the year, clear statistics, beautiful visualisation. You can mark progress for past days and add a note. Ideal'; 'It is very motivating when you see your progress for the year'; widgets the third strength (PRAISE_WIDGETS 8: 'keep a widget on my home screen, and tick the specific habit… and that's it!').", "grid + stats + widgets, minimal", "praise", "simplicity 40 / 46.51%; visual_progress 16 / 18.60%; WIDGETS 8 / 9.30%", "build-free", "High-priority", "generalisable", ["13682234945", "13766824285", "13888489114", "13733717410", "13958506607", "14170605260", "13787454014"], "", "")

c(8, "§0.3; §2.3 (future charging); §5.4; §8.4", "product-rule", "The main risk in this corpus is a change to the free model: the developer's terms reserve the right to 'charge for their services at any time'; two reviewers attach their loyalty to the price (U:future_pricing 2, 2.33%): 'I really hope it stays free, otherwise I will have to find a different habit tracker'; 'I hope it won't become a subscription, or at least that there will be an option to buy it once!' (ru) — the only statements in the corpus that make continued use conditional on anything, and the condition is price; the free model is the reason 45.35% give, and three name habit limits or subscriptions as what they avoid elsewhere.", "free now; terms reserve charging", "mixed", "future_pricing 2 / 2.33%; free_model_any 45.35%", "product-rule", "Meaningful (n=2)", "generalisable", ["13682234945", "13936987753", "13903380759", "13546859530", "14227392787"], "", "")

c(9, "§0.4; §0.4 table (verbatim); §2.5; §8.1", "must-have", "The developer's public statements about data and languages disagree with each other (verbatim): " + table("## 0.4 The developer", 0) + " — the description says 'No sign-in. No servers. No cloud.' while the privacy label lists analytics identifiers/usage/diagnostics and the policy (generic template text) names IP, approximate location, Amplitude, marketing promotions and 'servers'; the website offers opt-in authentication and cloud backups that appear nowhere else; privacy is something reviewers credit (PRIV_PRAISE 2: 'only anonymized data collection'); the listing says English only while 1.0.9 'Added languages', 54 reviews (62.79%) are non-English and one names a Vietnamese UI — 'the store metadata is out of date'.", "local-only claim vs analytics SDK; stale language list", "mixed", "PRIV_PRAISE 2; non-English 54 / 62.79%; 4 contradicting sources", "must-have", "external", "generalisable", ["13274273193", "13726727720", "14458611566"], "", "")

c(10, "§0.5; §0.5 table (verbatim); §3.9; §8.2; §8.3", "must-never-break", "Problems are few, specific and fixable — U:negative_any 7 (8.14%, CI 4.0–15.9%), every review below five stars contains one (verbatim): " + table("## 0.5 Problems are few", 0) + " — date logic is the only defect reported twice (DEF_DATE_LOGIC 2: a weekend tick fills both days; a widget counter increments the following day, 'possibly a time zone mismatch'); one launch failure after 7 days (3★); a yearly percentage counted from the habit's start rather than the year; icons in transparency mode; one widget per habit only; two ask for something the listing says exists (MISUNDERSTAND_EXISTING 2: data cannot survive a phone change vs 'IMPORT AND EXPORT… restore it at any time'; widgets) — 'discoverability problems, not missing features'.", "few defects; date boundary; export undiscovered", "complaint", "negative_any 7 / 8.14%; DEF_DATE_LOGIC 2; DEF_WIDGET 1; DEF_WONT_OPEN 1; RISK_DATA_LOSS 1; DEF_STATS_CALC 1; MISUNDERSTAND_EXISTING 2", "must-never-break", "High-priority", "generalisable", ["12782107949", "13318616929", "13682367544", "13761082816", "13852112119", "13985196266", "14499109087", "13426911405"], "", "")

c(11, "§0.6; §3.10; §7.5; §8.5; §8.6", "feature", "What reviewers ask for — U:request_any 11 (12.79%), all 5★: habit-frequency modes REQ_FREQUENCY 5 (5.81%: N times a week without fixed days, specific weekdays, every N days, monthly) — all five dated before 1.0.15 'Smarter habit goals' (2026-05-09) and none of the 27 reviews after it repeats the request; Apple Watch 2 (no watch app); one each: an optional account for backup, widgets (already shipped), shared habits with friends, a printable sheet, calendar highlighting of planned days.", "daily-only frequency until 1.0.15; no Watch", "complaint", "request_any 11 / 12.79%; REQ_FREQUENCY 5 (0 after 1.0.15); REQ_WATCH 2", "must-have", "High-priority", "generalisable", ["14005146777", "14196935443", "13868640698", "13426911405", "14074933658", "14048929482"], "", "a request that stops after a release is the corpus's only evidence the release worked")

c(12, "§0.7; §6.3; §7.2", "market", "Russia is 43% of the corpus and arrived after localisation: 37 of 86 (43.02%) from the Russian storefront, all 5★, 34 in Russian; Russia is 137 of 311 public ratings (44.05%); zero Russian-language reviews before 1.0.9 'Added languages' (0 of 13), the first 25 days after it; of the 73 reviews after 1.0.9, 39 are Russian (53.42%) — limited evidence under the 50 threshold.", "localised in 1.0.9", "praise", "ru 37 / 43.02% / 5.00★; 0 of 13 pre-1.0.9 → 39 of 73 post", "do", "limited evidence", "generalisable", ["13432837735", "13766824285"], "", "localisation opened the market that now dominates the ratings")

c(13, "§0.8; §9.F reference", "data-caveat", "Absent (18 of 18 claims): no complaint about price, subscriptions or ads (all 23 price and 9 ad hits are praise); no crash or freeze vocabulary (one 'stopped opening'); no support failure (four fast replies, none ignored); no actual data loss (one warning it could happen); no mention of import/export, iPad, Mac, dark mode, Android, Siri, Apple Health, battery, accessibility or in-app AI.", "n/a", "mixed", "18 absence tests, 18 absent", "none", "absence test", "generalisable", ["12749498855"], "", "")

c(14, "§2.3 table (verbatim); §2.4 table (verbatim); §2.4; §2.6", "monetization", "Free / paid classification (verbatim): " + table("## 2.3 Free / paid / trial", 0) + " — no IAP, no ads (12 reviewers say so), no subscription, trial or one-time purchase; future charging reserved; cloud backup contradictory. What shipped and when reviewers noticed (verbatim): " + table("## 2.4 What shipped", 0) + " — widgets have no release note yet the first review praises them; notes praised eight months after shipping; categories 21 days after; frequency requests 5 before 1.0.15, 0 after; not establishable: downloads, whether 1.0.15 provides the requested modes, whether cloud backup exists, competitor pricing (a near-identical 'HabitGrid - Goal tracker' by another developer exists).", "free everything", "mixed", "18 releases; requests → releases matched by timing", "none", "table", "app-specific", ["13958506607", "14048929482", "13682234945"], "", "")

save("w")
