# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/84")
from _lib import c, table, save

c(26, "§4.1 table (verbatim); §4.1; §4.2 table (verbatim); §4.2; §4.3 table (verbatim); §4.3", "data-caveat", "Distribution (verbatim): " + table("## 4.1 The distribution", 0) + " — 94.19% five-star, 98.84% four-or-five, zero below 3★; themes by band (verbatim): " + table("## 4.2 Themes by star band", 0) + " — five-star reviews praise; each of the five below five reports a problem; every request comes from a five-star reviewer. Five-star anatomy (verbatim): " + table("## 4.3 Five-star reviews", 0) + " — two-thirds name a specific quality, a third are one-line approvals often in Russian thanking the developer; all 28 low-information reviews are five-star; two 5★ report a problem as a request for help ('лучший трекер! (помогите с виджетами pls)').", "n/a", "mixed", "5★ 81 (94.19%); praise_specific 52 / 64.2% of 5★; LOW_INFO 28 / 34.6%", "none", "table", "generalisable", ["13761082816", "14499109087"], "", "")

c(27, "§4.4 table (verbatim); §4.4; §4.5; §4.6; §4.7; §4.8", "insight", "Every four-star review (verbatim): " + table("## 4.4 Four-star reviews", 0) + " — three of four name a defect, one a data-safety fear (a misunderstanding; export exists); none names price, ads, design or missing features; the one 3★ is a launch failure in the app's second week; zero text reviews below 3★ in 451 days (Wilson upper 4.3% per band) — the only trace of a very dissatisfied user is one textless 1★ US rating; no substantive contradictions; no churn statements, no rating revisions, limited elasticity (one ties opinion to frequency, one continued use to price).", "n/a", "complaint", "4★ 4; 3★ 1; 1–2★ 0; churn 0", "none", "table", "generalisable", ["13318616929", "13682367544", "13852112119", "13985196266", "12782107949", "13766824285", "13682234945"], "", "")

c(28, "§5.1 table (verbatim); §5.1; §5.5", "data-caveat", "There is no paid segment (verbatim): " + table("## 5.1 There is no paid segment", 0) + " — hasInAppPurchases false, terms 'created as a Free service', 0 of 86 paid / trialled / refunded, 0 of 86 object to a price, paywall, subscription or ad; no purchase trigger or post-purchase problem can be analysed; no conversion, retention, churn rate, price point or estimate of how many would leave if charged.", "no monetisation at all", "mixed", "purchase evidence 0; price objections 0", "none", "High-priority", "app-specific", ["12749498855"], "", "")

c(29, "§5.2 table (verbatim); §5.2", "insight", "What drives adoption instead of purchase (verbatim): " + table("## 5.2 What drives adoption", 0) + " — the competitor behaviour that pushed reviewers here is named precisely: a habit cap before payment ('around 4 habits before tealling you to pay'), monthly subscriptions ('a monthly sub for an app like habitkit'; 'the alternatives have paid subscriptions'), generic payment walls ('almost all of them need some sort of payment').", "n/a", "purchase-driver", "paywall_contrast 16; free_model 39; simplicity 40; switching 28; visual 16; widgets 8", "build-free", "High-priority", "generalisable", ["13903380759", "13546859530", "14227392787", "13469159788"], "", "")

c(30, "§5.3 table (verbatim); §5.3", "monetization", "Willingness to pay — what the corpus actually says (verbatim): " + table("## 5.3 Willingness to pay", 0) + " — one review (1.16%) volunteers an acceptable model, a one-time purchase; zero volunteer a subscription; one would leave if charged at all; one ranks the app because it is free — four stated attitudes, not an estimate.", "free; one-time purchase acceptable to one", "mixed", "one-time accepted 1; subscription rejected 2; leave-if-charged 1", "build-paid", "Meaningful (n=4)", "generalisable", ["13936987753", "13682234945", "13546859530", "14499109087"], "", "")

c(31, "§5.4 table (verbatim); §5.4; §8.4", "product-rule", "What the corpus implies for any monetisation decision (verbatim): " + table("## 5.4 What the corpus implies", 0) + " — 'the distinction the corpus supports is between charging for what users already have (which is what they chose the app for) and charging for things they have asked for and do not yet have' (watch app, cloud backup, frequency modes); it cannot say whether anyone would pay for the latter; capping habits, adding a subscription or adding ads each contradict a stated reason for choosing the app.", "free core; extras unbuilt", "mixed", "cap named as reason to leave others 3; subscription rejected 2; NO_ADS 12; one-time proposed 1", "product-rule", "High-priority", "generalisable", ["13903380759", "14170605260", "14500697857", "13936987753", "13682234945"], "", "")

c(32, "§6.1 table (verbatim); §6.2; §6.7", "market", "Full storefront table (verbatim): " + table("## 6.1 The full storefront table", 0) + " — no storefront reaches 50 (Russia 37, US 8, France 5; 17 with exactly one); the public rating is a fair summary of the written reviews — the largest public bases (Russia 137 at 4.99, US 43 at 4.86, Spain 20, France 17) sit within 0.12★ of their corpus means.", "n/a", "mixed", "28 storefronts; 0 eligible; public 311 / 4.939★", "none", "table", "generalisable", ["12749498855"], "", "")

c(33, "§6.3 table (verbatim); §6.3; §6.4", "market", "Russia n=37 (limited evidence) (verbatim): " + table("## 6.3 Russia", 0) + " — all 37 five-star (34 in Russian); gratitude to the developer 17 of 37 (45.9%, CI 31.0–61.6%) vs 6 of 49 elsewhere (non-overlapping intervals) yet none reports a developer reply (0 of 37 vs 4 of 49); paywall contrast 3 of 37 vs 13 of 49 — Russians say 'free' and 'no ads' but rarely frame it against paid rivals; requests 7 of 37 incl. 4 of 5 frequency; low-info 40.5%; 'the best tracker in Russia'; the corpus cannot show why Russian users arrived. US n=8: 4.75★, two of the four 4★, the longest explanations of why (habit cap, HabitKit, 'stays free').", "n/a", "mixed", "ru 37 / 5.00★ / thanks 45.9% / replies 0; us 8 / 4.75★", "none", "limited evidence", "app-specific", ["14126698100", "14227392787", "13903380759", "13546859530"], "", "")

c(34, "§6.5 table (verbatim); §6.5", "market", "High-spend (defined list, 11 present) vs others vs high-volume (ru, us, fr) (verbatim): " + table("## 6.5 High-spend markets", 0) + " — the high-spend group mentions the free model and paywall contrast far more (64.0% vs 37.7%; 32.0% vs 13.1%), writes fewer very short reviews (20.0% vs 37.7%), reports proportionally more problems and widget issues; the high-volume group is Russia's profile; no price differentiation possible — nothing is sold.", "n/a", "mixed", "high-spend 25 / 4.880★ / free_model 64.0%; others 61 / 4.951★ / 37.7%", "research", "limited evidence", "generalisable", ["13903380759"], "", "the paywall-contrast argument is a high-spend-market argument")

c(35, "§6.6 table (verbatim); §6.6 observations table (verbatim); §6.6", "market", "Storefront is not language (verbatim): " + table("## 6.6 Storefront is not language", 0) + " || " + table("## 6.6 Storefront is not language", 1) + " — Russian on five storefronts incl. us and ca; the Russian storefront has three English reviews ('Thanks from Russia!'); all six Romanian/Hungarian reviews are in English; a Vietnamese UI on a storefront the listing does not advertise; 'the listing says English only; 62.79% of the reviews are not in English'.", "listing English-only; app localised", "mixed", "ru 39 (45.35%); en 32; es 6; fr 4; 5 singletons", "do", "table", "generalisable", ["13985196266", "14029898629", "14431846669", "14458611566"], "", "")

save("a")
