# -*- coding: utf-8 -*-
import sys; sys.path.insert(0, "Tools/prd_ledger/84")
from _lib import c, table, save

c(36, "§7.1 table (verbatim); §7.1; §7.2 table (verbatim); §7.2; §7.3 table (verbatim); §7.3", "timeline", "Eras are release dates (verbatim): " + table("## 7.1 Method", 0) + " || by month (verbatim): " + table("## 7.2 Volume and language", 0) + " — volume rises after 1.0.9 'Added languages' (2.65 → 7.09 per 30 days; peak 10.24 in 2026-01-24 → 04-18, 18 of 29 Russian); non-English 23.1% before → 69.9% after; ratings do not move (4.77 → 4.95 → 4.97) — 'the largest change in the corpus is about who writes, not what they think'. The review prompts did not produce the rise (verbatim): " + table("## 7.3 The review prompts", 0) + " — neither prompt release is followed by a rise; the prompt alone does not explain the volume.", "localisation 1.0.9; review prompt 1.0.1/1.0.6", "praise", "E1 13 / 4.77★; E2 43 / 4.95★; E3 30 / 4.97★; post-1.0.9 rate ×2.7", "none", "table", "app-specific", ["13432837735", "12749498855"], "", "localisation, not the review prompt, moved the review rate")

c(37, "§7.4 table (verbatim); §7.4 movement table (verbatim); §7.4; §7.7 table (verbatim); §7.7", "timeline", "Theme movement across eras (verbatim): " + table("## 7.4 Theme movement", 0) + " || movements (verbatim): " + table("## 7.4 Theme movement", 1) + " — developer gratitude appears with the Russian-language share (0 → 32.6% → 36.7%); short reviews grow (23.1% → 43.3%); widget praise disappears (3 → 5 → 0, observation only); paywall contrast falls E1 → E2 only; the free model holds at 44–47% in every era through a language mix change from 23% to 77% non-English — 'the one reason that does not depend on who is writing'. Persisted (verbatim): " + table("## 7.7 What persisted", 0) + " — 'nothing in the corpus deteriorates'.", "n/a", "mixed", "free_model 46.2 → 44.2 → 46.7%; dev_relationship 0 → 36.7%; LOW_INFO 23.1 → 43.3%; WIDGETS 3 → 5 → 0", "none", "table", "app-specific", ["14499109087", "13682234945"], "", "")

c(38, "§7.5; §7.6", "timeline", "Requests and releases: frequency requests stop after 'Smarter habit goals' (5 of 59 before 1.0.15, 0 of 27 after — consistent with the release addressing the need, nothing stronger); categories praised 21 days after 1.0.14; both Watch requests are recent (E3) and unaddressed; both date-boundary defects predate 1.0.19 'Custom week start'. The launch-period storefront cluster: six of E1's 13 reviews (46.2%) from Romania and Hungary, none after 2025-10-18, all 5★ in English, two carrying the developer's surname; consistent with a launch audience in the developer's network — 'the earliest ratings are the least independent'; excluding them E1 falls 4.77 → 4.57★ (7 reviews), corpus 4.930 → 4.925★, no share moves more than 3.8 points.", "n/a", "mixed", "REQ_FREQUENCY 5 → 0 after 1.0.15; ro/hu 6 of 13 E1; E1 ex-cluster 4.57★", "none", "limited evidence", "app-specific", ["13284638193", "13704639248", "13915639119", "13951819028", "14048929482", "12886063451", "13282170850"], "", "")

c(39, "§8.1 table (verbatim); §8.1; part 8 #1", "must-have", "§8.1 immediate fix — make the listing and privacy documents agree with the app (verbatim): " + table("## 8.1 Immediate fix", 0) + " — update the Languages field to what 1.0.9 shipped; replace 'No servers. No cloud.' with a statement matching the label (a reviewer already describes it accurately: 'only anonymized data collection'); replace the template privacy policy (location, marketing, servers) with one that describes the app; reconcile the website's opt-in cloud backup with the listing — 'privacy and free are the positioning reviewers credit, and all four fixes are text changes'.", "listing/policy/label/website disagree", "mixed", "4 text fixes; PRIV_PRAISE 2; non-English 62.79%", "must-have", "external", "generalisable", ["14458611566", "13726727720", "13274273193"], "", "")

c(40, "§8.2; part 8 #2", "must-never-break", "§8.2 immediate fix — the date-boundary and widget defects: test completion writes across the week boundary (including the new custom week start), across time zones, and from widgets specifically; confirm several widgets can each show a different habit and show how; 'the only defects that recur in type, and widgets are the most praised feature that also fails'; also the transparent-icon display and the yearly-percentage basis (one each; the second may be an option rather than a fix).", "date/time-zone boundary; widget config", "complaint", "DEF_DATE_LOGIC 2; DEF_WIDGET 1; FRICTION_WIDGET_CONFIG 1; 3 of 4 4★ name a defect", "must-never-break", "High-priority", "generalisable", ["13318616929", "13682367544", "14499109087", "13761082816", "13985196266"], "", "")

c(41, "§8.3; part 8 #3", "must-have", "§8.3 immediate fix — make export/backup visible where users worry about data: one 4★ warns all data is lost on a phone change, one asks for an account for the same reason, and zero reviews mention the import/export the listing advertises; surface export in onboarding and settings (and a reminder after a period of use) before building accounts — 'the cheapest change that answers both reviews, and it corrects a misunderstanding that cost one star'.", "export exists, undiscovered", "complaint", "data_safety 2; export mentions 0", "must-have", "Meaningful", "generalisable", ["13852112119", "13868640698"], "", "")

c(42, "§8.4; part 8 #4", "product-rule", "§8.4 experiment — if monetisation is introduced, charge for new capability, never for the free core: free_model_any stable at 44–47% in every era; a habit cap and subscriptions are what reviewers avoid in competitors; one will leave if charged; the only proposed model is a one-time purchase; the terms already reserve charging; do not cap habits, move widgets or statistics behind payment, or add ads — each contradicts a stated reason; if revenue is needed test an optional one-time purchase or tip for capabilities not yet shipped (watch, cloud backup, advanced frequency), announced in advance; measure the review stream for the first price complaints — 'the baseline is zero'.", "free core; charge only for unbuilt extras", "mixed", "free_model 45.35%; paywall_contrast 18.60%; one-time proposed 1; leave-if-charged 1", "product-rule", "High-priority", "generalisable", ["13903380759", "13546859530", "14227392787", "13682234945", "13936987753"], "", "")

c(43, "§8.5; §8.6; §8.7; part 8 #5; part 8 #6; part 8 #7", "insight", "§8.5 research — do the 1.0.15 goals cover the five frequency variants (N per week without fixed days; specific weekdays; every N days; monthly; custom interval)? where missing, the best-evidenced gap; where present, discoverability (one reviewer already credits 'a wide range of habit frequencies'). §8.6 Apple Watch — two E3 requests do not justify building one; check the developer's Discord/Reddit where requests are cheaper. §8.7 how independent are the ratings? — a prompt in every version, a launch cluster with the developer's surname, 28 one-line 5★, and website testimonials with generic names ('John Harris', 'Maria Smith') matching no reviewer — 'none of this indicates a problem with the product', but the rating is the main acquisition asset and its organic share is unknowable here; store rules on reviews from the developer's circle should be checked and the testimonials real or removed.", "n/a", "mixed", "REQ_FREQUENCY 5 variants; REQ_WATCH 2; ro/hu cluster 6; testimonials generic", "research", "limited evidence", "generalisable", ["13766824285", "13682367544", "14005146777", "14196935443", "12886063451"], "", "")

c(44, "§8.8 table (verbatim); §8.8; part 8 #8", "dont", "§8.8 what not to prioritise (verbatim): " + table("## 8.8 What this corpus", 0) + " — no stability overhaul (one launch failure, zero crashes since); no social features (one request); no features for their own sake ('nothing superfluous' is credited and bloat is why they left rivals); no price/ads/trial friction work (none exists); no country work; no support-process change (four praise response speed).", "n/a", "mixed", "crash 0; social 1; support failures 0", "dont", "High-priority", "generalisable", ["14074933658", "13682234945"], "", "")

c(45, "§3.6; §7.4 (dev gratitude tracks Russian share); §6.3", "contradiction", "Gratitude without contact: Russian-storefront reviewers thank the developer at 45.9% (17 of 37) yet none of them reports a developer reply (0 of 37 vs 4 of 49 elsewhere) — the thanks is for the free product and the localisation, not for support; the intervals on gratitude do not overlap with the rest of the corpus.", "n/a", "praise", "ru THANKS 17/37 vs 6/49; ru RESPONSIVE 0/37 vs 4/49", "none", "limited evidence", "generalisable", ["14481206696", "14126698100", "13546859530"], "", "")

c(46, "§0.1; §5.2 (competitor cap); §3.7", "anti-pattern", "The competitor pattern this app's users fled, in their own words: 'most of them only let you make around 4 habits before tealling you to pay'; 'a monthly sub for an app like habitkit, which offers no benefit over this app'; 'the alternatives have paid subscriptions' — so a developer nearly wrote their own tracker; 'almost all of them need some sort of payment'; 'too many features for my liking' — a small-cap freemium with a monthly subscription and feature bloat is the category default reviewers are escaping.", "category default: ~4-habit cap + monthly subscription", "churn", "paywall_contrast 16 / 18.60%; TRIED_MANY 16", "dont", "High-priority", "generalisable", ["13903380759", "13546859530", "14227392787", "13469159788", "13682234945"], "", "")

save("a")
